Repository greenplum-db/gpdb, pull requests merged in 2018-08, with the labels that each got.

#5344 Backport to 5X: Fix gpconfig read from file
  gpMgmt/bin/gpconfig
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gp.py
Labels: 5X_STABLE

#5422 pg_dump: disable unused pre-7.3 dump code
  src/bin/pg_dump/pg_dump.h
  src/bin/pg_dump/pg_dump_sort.c
Labels: Upgrade

#5499 Backport a PG upstream patch to fix a panic related to that.
  src/backend/executor/spi.c
  src/backend/parser/analyze.c
  src/backend/tcop/postgres.c
  src/backend/tcop/utility.c
  src/backend/utils/cache/plancache.c
  src/include/utils/plancache.h
Labels: 5X_STABLE

#5516 resgroup: treat cpuset as -1 when it is missing in catalog.
  concourse/scripts/ic_gpdb_resgroup.bash
  src/backend/commands/resgroupcmds.c
Labels: Resource Groups

#5527 resgroup: gpconfig should check for cpuset cgroup dir on master.
  gpMgmt/bin/gpcheckresgroupimpl
  gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckresgroupimpl.py
Labels: Resource Groups

#5532 Prevent concurrent DROP SCHEMA when objects are being created
  src/backend/commands/functioncmds.c
  src/backend/commands/schemacmds.c
  src/backend/commands/tablecmds.c
  src/backend/commands/typecmds.c
  src/test/isolation2/expected/concurrent_schema_drop.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/concurrent_schema_drop.sql
Labels: 5X_STABLE

#5548 Copy tuple from shared buffer during persistent table rebuild
  gpMgmt/test/behave/mgmt_utils/gppersistent_rebuild.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  src/backend/cdb/cdbdatabaseinfo.c
Labels: 5X_STABLE

#5562 Raise the max value of MAX_GP_MAX_CSV_LINE_LENGTH GUC from 4MB to 1GB
  gpdb-doc/dita/ref_guide/config_params/guc-list.xml
  src/include/cdb/cdbcsv.h
Labels: 5X_STABLE

#5515 Fix gpperfmon bug that ATExecSetDistributedBy statement produce wrong tsubmit
  gpMgmt/test/behave/mgmt_utils/gpperfmon.feature
  src/backend/commands/tablecmds.c
Labels: 5X_STABLE

#5603 pg_upgrade: fix GPDB-specific long options
  contrib/pg_upgrade/option.c
Labels: Upgrade

#5617 Fix COPY <table> FROM <file> WITH OIDS.
  src/backend/commands/copy.c
  src/test/regress/input/gpcopy.source
  src/test/regress/output/gpcopy.source
Labels: 5X_STABLE
