Repository greenplum-db/gpdb, pull requests merged in 2018-06, with the labels that each got.

#5023 Implement CPUSET
  concourse/pipelines/gpdb_master-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
  concourse/scripts/ic_gpdb_resgroup.bash
  src/backend/catalog/gp_toolkit.sql
  src/backend/commands/resgroupcmds.c
  src/backend/parser/gram.y
  src/backend/utils/resgroup/resgroup-ops-dummy.c
  src/backend/utils/resgroup/resgroup-ops-linux.c
  src/backend/utils/resgroup/resgroup.c
  src/backend/utils/resgroup/resgroup_helper.c
  src/backend/utils/resgroup/test/resgroup_test.c
  src/bin/pg_dump/pg_dumpall.c
  src/include/catalog/pg_resgroup.h
  src/include/catalog/pg_resgroupcapability.h
  src/include/parser/kwlist.h
  src/include/utils/faultinjector_lists.h
  src/include/utils/resgroup-ops.h
  src/include/utils/resgroup.h
  src/test/isolation2/expected/.gitignore
  src/test/isolation2/expected/resgroup/resgroup_syntax.out
  src/test/isolation2/input/resgroup/enable_resgroup.source
  src/test/isolation2/input/resgroup/enable_resgroup_validate.source
  src/test/isolation2/input/resgroup/resgroup_cpuset.source
  src/test/isolation2/isolation2_resgroup_schedule
  src/test/isolation2/output/resgroup/enable_resgroup.source
  src/test/isolation2/output/resgroup/enable_resgroup_validate.source
  src/test/isolation2/output/resgroup/resgroup_cpuset.source
  src/test/isolation2/sql/.gitignore
  src/test/isolation2/sql/resgroup/resgroup_syntax.sql
  src/test/regress/expected/resource_group_cpuset.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/resource_group_cpuset.sql
Labels: Resource Groups

#5096 COPY: don't pfree() part_distData explicitly
  src/backend/commands/copy.c
Labels: 5X_STABLE

#4154 First shot at merging SPI 64 bit changes for pl/Python
  src/pl/plpython/plpython.c
  src/test/regress/expected/python_processed64bit.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/python_processed64bit.sql
Labels: ToDo

#5108 CREATE DATABASE using a template db copies relation extensions
  src/backend/commands/dbcommands.c
  src/test/regress/expected/createdb_large_table.out
  src/test/regress/expected/qp_misc_jiras.out
  src/test/regress/expected/qp_misc_jiras_optimizer.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/createdb_large_table.sql
  src/test/regress/sql/qp_misc_jiras.sql
Labels: 5X_STABLE

#5154 Fixed EXTERNAL WEB TABLE crashed when ON MASTER without LOG ERRORS
  src/backend/access/external/fileam.c
  src/backend/commands/exttablecmds.c
  src/test/regress/input/external_table.source
  src/test/regress/output/external_table.source
Labels: 5X_STABLE

#5158 docs - cpuset content for 5x
  doc/src/sgml/ref/alter_resource_group.sgml
  doc/src/sgml/ref/create_resource_group.sgml
  gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml
  gpdb-doc/dita/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.xml
  gpdb-doc/dita/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.xml
  gpdb-doc/dita/ref_guide/sql_commands/DROP_RESOURCE_GROUP.xml
  gpdb-doc/dita/ref_guide/system_catalogs/gp_resgroup_config.xml
  gpdb-doc/dita/ref_guide/system_catalogs/pg_resgroupcapability.xml
Labels: 5X_STABLE

#5121 resgroup: fallback to insert when updating caps.
  src/backend/commands/resgroupcmds.c
Labels: Resource Groups
