Repository greenplum-db/gpdb, pull requests merged in 2018-05, with the labels that each got.

#4892 Fix crash while generating planning percentile func on partition tables
  src/backend/cdb/cdbgroup.c
  src/test/regress/expected/percentile.out
  src/test/regress/sql/percentile.sql
Labels: 5X_STABLE

#4926 docs: clarify GPORCA index support -backport from master
  gpdb-doc/dita/admin_guide/query/topics/query-piv-opt-limitations.xml
  gpdb-doc/dita/ref_guide/sql_commands/CREATE_INDEX.xml
Labels: 5X_STABLE

#4906 docs - using page updates for resgroup global shmem for 5x
  gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml
  gpdb-doc/dita/ref_guide/config_params/guc-list.xml
  gpdb-doc/dita/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.xml
Labels: 5X_STABLE

#5034 Use proiswin instead proiswindow when pg_dump run on gpdb4.3
  src/bin/pg_dump/pg_dump.c
Labels: Upgrade

#5009 docs: integrate cast information with install guide.
  gpdb-doc/dita/admin_guide/query/topics/defining-queries.xml
Labels: 5X_STABLE

#5035 docs - identify query to view RG memory auditor (5x)
  gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml
Labels: 5X_STABLE

#5033 Test COPY processed overflow
  gpMgmt/bin/gppylib/programs/clsInjectFault.py
  src/backend/commands/copy.c
  src/backend/utils/misc/faultinjector.c
  src/include/utils/faultinjector.h
  src/test/regress/input/gpcopy.source
  src/test/regress/output/gpcopy.source
Labels: 5X_STABLE

#4966 Fix crash issues in global deadlock detector.
  src/backend/utils/gdd/gddbackend.c
Labels: Global Deadlock Detector

#5045 Fix memory leak when copy into a partition table
  src/backend/commands/copy.c
Labels: 5X_STABLE
