Repository greenplum-db/gpdb, pull requests merged in 2018-07, with the labels that each got.

#5223 Implement resource group bypass mode (5X)
  src/backend/utils/misc/guc_gp.c
  src/backend/utils/resgroup/resgroup.c
  src/include/utils/resgroup.h
  src/test/isolation2/expected/resgroup/resgroup_concurrency.out
  src/test/isolation2/init_file_resgroup
  src/test/isolation2/sql/resgroup/resgroup_concurrency.sql
Labels: 5X_STABLE

#5250 Don't attempt to truncate external tables in gpdbrestore
  gpMgmt/bin/gppylib/operations/restore.py
  gpMgmt/test/behave/mgmt_utils/backup_and_restore_backups.feature
  gpMgmt/test/behave/mgmt_utils/backup_and_restore_restores.feature
Labels: 5X_STABLE

#5256 Removed extraneous calls to CheckTableExists in gpcrondump
  gpMgmt/bin/gppylib/operations/dump.py
Labels: 5X_STABLE

#5262 Fix resgroup bypass quota
  src/backend/utils/resgroup/resgroup.c
  src/test/isolation2/expected/.gitignore
  src/test/isolation2/expected/resgroup/resgroup_concurrency.out
  src/test/isolation2/input/resgroup/resgroup_bypass.source
  src/test/isolation2/input/resgroup/resgroup_memory_statistic.source
  src/test/isolation2/isolation2_resgroup_schedule
  src/test/isolation2/output/resgroup/resgroup_bypass.source
  src/test/isolation2/output/resgroup/resgroup_bypass_optimizer.source
  src/test/isolation2/output/resgroup/resgroup_memory_statistic.source
  src/test/isolation2/sql/.gitignore
  src/test/isolation2/sql/resgroup/resgroup_concurrency.sql
Labels: Resource Groups

#5265 Do not automatically create an array type for child partitions
  src/backend/access/bitmap/bitmapattutil.c
  src/backend/bootstrap/bootparse.y
  src/backend/catalog/aocatalog.c
  src/backend/catalog/heap.c
  src/backend/catalog/toasting.c
  src/backend/commands/cluster.c
  src/backend/commands/tablecmds.c
  src/backend/executor/execMain.c
  src/include/catalog/heap.h
  src/test/regress/expected/partition.out
  src/test/regress/expected/partition_optimizer.out
  src/test/regress/sql/partition.sql
Labels: 5X_STABLE

#5046 tuptoaster: gracefully handle changes to TOAST_MAX_CHUNK_SIZE
  src/backend/access/heap/tuptoaster.c
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/test/regress/expected/toast.out
  src/test/regress/sql/toast.sql
Labels: Upgrade

#5284 Fix gp_max_csv_line_length does not work in INSERT INTO ... SELECT ...
  src/backend/utils/misc/guc_gp.c
  src/test/regress/input/external_table.source
  src/test/regress/output/external_table.source
Labels: 5X_STABLE

#5050 Narrow race condition between pg_partitions view and altering partiti…
  src/backend/utils/adt/ruleutils.c
Labels: 5X_STABLE

#4795 pg_upgrade: dump REINDEX instructions after upgrade from GPDB4
  contrib/pg_upgrade/version.c
Labels: Upgrade

#5301 Remove MyProc inDropTransaction flag
  src/backend/access/transam/twophase.c
  src/backend/commands/vacuum.c
  src/backend/storage/ipc/procarray.c
  src/backend/storage/lmgr/proc.c
  src/include/storage/proc.h
  src/include/storage/procarray.h
  src/test/isolation2/input/uao/vacuum_cleanup.source
  src/test/isolation2/output/uao/vacuum_cleanup.source
Labels: 5X_STABLE

#5303 gpperfmon: fix long query text cannot load into queries_history
  gpAux/gpperfmon/src/gpmon/gpmon_agg.c
  gpAux/gpperfmon/src/gpmon/gpmondb.c
  gpAux/gpperfmon/src/gpmon/gpmondb.h
  src/backend/utils/misc/guc_gp.c
  src/include/cdb/cdbcsv.h
Labels: 5X_STABLE

#5143 Remove reference to ability to use port/username
  gpdb-doc/dita/utility_guide/admin_utilities/gpssh.xml
Labels: ClusterMgmt
