Repository greenplum-db/gpdb, pull requests merged in 2018-04, with the labels that each got.

#4794 pg_dump: remove version-specific EXTERNAL TABLE differences
  src/bin/pg_dump/pg_dump.c
Labels: Upgrade

#4776 Fix bug for dropped columns in partition table in pg_dump.
  src/bin/pg_dump/pg_dump.c
Labels: Upgrade

#4829 Remove GPDB_84_MERGE_FIXME in parse_clause.c
  src/backend/parser/parse_clause.c
Labels: 8.4 Merge

#4805 When dumping function, append callback function attribute if needed.
  src/bin/pg_dump/pg_dump.c
Labels: Upgrade

#4811 Fix setting relfrozenxid during upgrade.
  contrib/pg_upgrade/pg_upgrade.c
  src/backend/catalog/heap.c
Labels: Upgrade

#4809 Address GPDB_84_MERGE_FIXME in `simplify_EXISTS_query()`
  src/backend/optimizer/plan/subselect.c
  src/test/regress/expected/qp_correlated_query.out
  src/test/regress/expected/qp_correlated_query_optimizer.out
  src/test/regress/sql/qp_correlated_query.sql
Labels: 8.4 Merge

#4837 Implement NUMERIC upgrade for AOCO versions < 8.3
  src/backend/access/aocs/aocsam.c
  src/backend/access/appendonly/appendonlyam.c
  src/backend/utils/datumstream/datumstream.c
  src/include/utils/datumstream.h
  src/test/isolation2/.gitignore
  src/test/isolation2/input/ao_upgrade.source
  src/test/isolation2/isolation2_regress.c
  src/test/isolation2/output/ao_upgrade.source
  src/test/isolation2/output/ao_upgrade_optimizer.source
Labels: Upgrade

#4876 resgroup: fix an access to uninitialized address.
  src/backend/utils/resgroup/resgroup-ops-linux.c
  src/backend/utils/resgroup/resgroup.c
Labels: Resource Groups

#4874 resgroup: dump cgroup memory limit with _granted suffix.
  src/backend/utils/resgroup/resgroup.c
Labels: Resource Groups

#4903 resgroup: dump memory_auditor in pg_dumpall for 5X branch.
  src/bin/pg_dump/pg_dumpall.c
Labels: Resource Groups
