Repository greenplum-db/gpdb, pull requests merged in 2018-03, with the labels that each got.

#4684 Fix double-free during AO tuple upgrade from GPDB 4
  src/backend/access/appendonly/appendonlyam.c
Labels: Upgrade

#4682 Fix pg_dump for 4.x EXTERNAL tables with ON clauses
  src/bin/pg_dump/pg_dump.c
Labels: Upgrade

#4710 Fix storing of nextLocalTransactionId into shared memory
  src/backend/storage/ipc/sinvaladt.c
Labels: 5X_STABLE

#4713 Fix wrong results for queries of type NOT (EXPR sublink)
  src/backend/optimizer/prep/prepjointree.c
  src/test/regress/expected/qp_correlated_query.out
  src/test/regress/expected/qp_correlated_query_optimizer.out
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/sql/qp_correlated_query.sql
  src/test/regress/sql/subselect_gp.sql
Labels: Planner
