Repository greenplum-db/gpdb, pull requests merged in 2018-09, with the labels that each got.

#5612 gppersistentrebuild: Fix directory for transaction file space
  gpMgmt/bin/gppylib/operations/persistent_rebuild.py
  gpMgmt/test/behave/mgmt_utils/gppersistent_rebuild.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  gpMgmt/test/behave_utils/utils.py
Labels: 5X_STABLE

#5651 Relax filerep resync logic to send change tracking entries
  src/backend/cdb/cdbfilerepresyncworker.c
  src/backend/cdb/cdbresynchronizechangetracking.c
  src/backend/utils/misc/faultinjector.c
  src/include/utils/faultinjector.h
  src/test/isolation2/expected/resync_xlog_hints.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/resync_xlog_hints.sql
Labels: 5X_STABLE

#5710 5X: improve pg_dump performance
  src/bin/pg_dump/pg_dump.c
Labels: 5X_STABLE, Upgrade

#5716 5X: dump REINDEX instructions after upgrade from GPDB4
  contrib/pg_upgrade/version.c
Labels: 5X_STABLE, Upgrade

#5721 docs - ANALYZE - HLL statistics, incremental analyze
  gpdb-doc/dita/admin_guide/intro/about_statistics.xml
  gpdb-doc/dita/admin_guide/query/topics/query-piv-opt-root-partition.xml
  gpdb-doc/dita/ref_guide/config_params/guc-list.xml
  gpdb-doc/dita/ref_guide/sql_commands/ANALYZE.xml
Labels: 5X_STABLE

#5722 Support for HBA_HOSTNAMES flag in gpinitsystem config file
  gpMgmt/bin/gpinitstandby
  gpMgmt/bin/gpinitsystem
  gpMgmt/bin/gppylib/operations/initstandby.py
  gpMgmt/bin/lib/gp_bash_functions.sh
  gpMgmt/bin/lib/gpcreateseg.sh
  gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: 5X_STABLE

#5539 Make planner generate redistribute-motion.
  src/backend/cdb/cdbpath.c
  src/test/regress/expected/bfv_partition_plans.out
  src/test/regress/expected/dpe.out
  src/test/regress/expected/gpdiffcheck.out
  src/test/regress/expected/join.out
  src/test/regress/expected/join_optimizer.out
  src/test/regress/expected/qp_correlated_query.out
  src/test/regress/expected/qp_misc_jiras.out
  src/test/regress/expected/rangefuncs.out
  src/test/regress/sql/join.sql
Labels: Planner, bug

#5749 gdd: disable flaky test case non-lock-107.
  src/test/isolation2/isolation2_schedule
Labels: Global Deadlock Detector

#5717 Fix race condition in gptransfer ccp multi-cluster tests
  concourse/pipelines/5X_STABLE-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: 5X_STABLE

#5737 resgroup: detect gpdb cgroup comp dirs automatically.
  gpMgmt/bin/gpcheckresgroupimpl
  gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckresgroupimpl.py
  src/backend/utils/resgroup/resgroup-ops-dummy.c
  src/backend/utils/resgroup/resgroup-ops-linux.c
  src/backend/utils/resgroup/resgroup.c
  src/include/utils/resgroup-ops.h
Labels: Resource Groups

#5768 Fix ao_upgrade tests and add them to the schedule
  src/backend/utils/adt/numeric.c
  src/include/utils/numeric.h
  src/test/isolation2/input/ao_upgrade.source
  src/test/isolation2/isolation2_regress.c
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/output/ao_upgrade.source
  src/test/isolation2/output/ao_upgrade_optimizer.source
Labels: Upgrade

#5873 Upgrade APR to 1.6.5 because 1.6.3 is no longer available.
  .travis.yml
Labels: 5X_STABLE

#5853 Add more checks when deduce quals from non-equivalence clauses.
  src/backend/optimizer/path/pathkeys.c
  src/backend/optimizer/util/clauses.c
  src/include/optimizer/clauses.h
  src/test/regress/expected/qp_correlated_query.out
  src/test/regress/expected/qp_correlated_query_optimizer.out
  src/test/regress/sql/qp_correlated_query.sql
Labels: 5X_STABLE
