Repository greenplum-db/gpdb, pull requests merged in 2019-09, with the labels that each got.

#8518 Remove lockmode ExclusiveLock upgrade for non-partitioned tables
  src/backend/executor/execMain.c
  src/test/isolation2/expected/dml_on_root_locks_all_parts.out
  src/test/isolation2/sql/dml_on_root_locks_all_parts.sql
Labels: version: 5X_STABLE

#8277 6X: Fix tcp interconnect hang
  src/backend/cdb/motion/ic_tcp.c
  src/backend/cdb/motion/ic_udpifc.c
  src/test/isolation2/.gitignore
  src/test/isolation2/Makefile
  src/test/isolation2/input/external_table.source
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/output/external_table.source
  src/test/regress/expected/ic.out
  src/test/regress/greenplum_schedule
  src/test/regress/input/external_table.source
  src/test/regress/output/external_table.source
  src/test/regress/sql/ic.sql
Labels: version: 6X_STABLE

#8588 6X: ci: fix ic and external_table
  src/test/isolation2/output/external_table.source
  src/test/regress/expected/ic.out
Labels: version: 6X_STABLE

#8531 6X: Avoid duplicated repeat node.
  src/backend/cdb/cdbgroup.c
  src/backend/optimizer/plan/planner.c
  src/test/regress/expected/olap_group.out
  src/test/regress/sql/olap_group.sql
Labels: version: 6X_STABLE

#8592 Limit bypass memory usage per query instead of per session
  src/backend/utils/resgroup/resgroup.c
  src/test/isolation2/expected/resgroup/resgroup_bypass_memory_limit.out
  src/test/isolation2/isolation2_resgroup_schedule
  src/test/isolation2/sql/resgroup/resgroup_bypass_memory_limit.sql
Labels: topic: resource group

#8589 Fix flaky partition deadlock tests
  src/test/isolation2/expected/gdd/delete-deadlock-root-leaf-concurrent-op.out
  src/test/isolation2/expected/gdd/update-deadlock-root-leaf-concurrent-op.out
  src/test/isolation2/sql/gdd/delete-deadlock-root-leaf-concurrent-op.sql
  src/test/isolation2/sql/gdd/update-deadlock-root-leaf-concurrent-op.sql
Labels: topic: continuous integration, topic: global deadlock detector, topic: partitions

#8610 5X Backport: Limit bypass memory usage per query instead of per session
  src/backend/utils/resgroup/resgroup.c
  src/test/isolation2/expected/resgroup/resgroup_bypass_memory_limit.out
  src/test/isolation2/isolation2_resgroup_schedule
  src/test/isolation2/sql/resgroup/resgroup_bypass_memory_limit.sql
Labels: version: 5X_STABLE

#8608 6X Backport: Limit bypass memory usage per query instead of per session
  src/backend/utils/resgroup/resgroup.c
  src/test/isolation2/expected/resgroup/resgroup_bypass_memory_limit.out
  src/test/isolation2/isolation2_resgroup_schedule
  src/test/isolation2/sql/resgroup/resgroup_bypass_memory_limit.sql
Labels: version: 6X_STABLE

#8611 6X: Fix flaky partition deadlock tests
  src/test/isolation2/expected/gdd/delete-deadlock-root-leaf-concurrent-op.out
  src/test/isolation2/expected/gdd/update-deadlock-root-leaf-concurrent-op.out
  src/test/isolation2/sql/gdd/delete-deadlock-root-leaf-concurrent-op.sql
  src/test/isolation2/sql/gdd/update-deadlock-root-leaf-concurrent-op.sql
Labels: topic: continuous integration, topic: global deadlock detector, topic: partitions, version: 6X_STABLE

#8613 Default wire_format to CSV
  contrib/pxf_fdw/expected/pxf_fdw_foreign_table.out
  contrib/pxf_fdw/pxf_option.c
  contrib/pxf_fdw/sql/pxf_fdw_foreign_table.sql
Labels: topic: FDW, topic: pxf

#8617 Fix gpexpand entries in hba.conf
  gpMgmt/bin/gpexpand
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/doc/gpexpand_help
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: type: feature

#8634 Update pg_hba.conf with mirror information with gpmovemirrors
  gpMgmt/bin/gpmovemirrors
  gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
  gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
Labels: type: feature

#8600 6X Backport:Remove duplicate code block in parse_utilcmd.c
  src/backend/parser/parse_utilcmd.c
Labels: type: maintenance

#8650 Fix gpexpand entries in hba.conf (#8617)
  gpMgmt/bin/gpexpand
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/doc/gpexpand_help
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: version: 6X_STABLE

#8606 ICG tests for ORCA change: "Wrong preprocessed query for nullable contraints"
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, topic: gporca, type: bug

#8655 Bump ORCA version to 3.71, Add ICG tests for ORCA PR527
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, topic: gporca, type: bug, version: 5X_STABLE

#8629 Backports to improve spinlock performance.
  src/backend/storage/lmgr/s_lock.c
  src/include/storage/s_lock.h
Labels: type: feature, version: 5X_STABLE

#8519 Fix the panic when rollup() meets subplan.
  src/backend/optimizer/plan/plangroupext.c
  src/test/regress/expected/olap_group.out
  src/test/regress/sql/olap_group.sql
Labels: version: 6X_STABLE

#8416 Fix wrong results caused by NOT_EXISTS sublink elimination.
  src/backend/cdb/cdbsubselect.c
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/sql/subselect_gp.sql
Labels: version: 5X_STABLE

#8641 Fix miscellaneous warnings when building ORCA translator code
  src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
  src/backend/gpopt/utils/funcs.cpp
  src/include/gpopt/CGPOptimizer.h
  src/include/gpopt/translate/CContextQueryToDXL.h
  src/include/gpopt/translate/CTranslatorQueryToDXL.h
  src/include/gpopt/utils/funcs.h
Labels: area: gporca, topic: gporca, type: maintenance

#8625 Reduce Error logging for ORCA
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  src/backend/gpopt/utils/COptTasks.cpp
  src/backend/optimizer/plan/orca.c
  src/backend/utils/misc/guc_gp.c
  src/include/gpopt/utils/COptTasks.h
  src/test/regress/expected/gporca_optimizer.out
Labels: area: gporca, topic: gporca, type: bug

#8632 Don't Assert() in MemoryAccounting_ConvertIdToAccount()
  src/include/utils/memaccounting_private.h
Labels: type: bug

#8620 Backport #7533 Silece stringop-overflow warning and protect against invalid read to 6X
  src/bin/pg_dump/dumputils.c
Labels: type: bug, version: 6X_STABLE

#8619 Backport #8419 Silence pragma warnings to 6X
  gpMgmt/bin/stream/stream.c
Labels: type: bug, version: 6X_STABLE

#8623 Handle VALUES expressions in plan_tree_mutator()
  src/backend/cdb/cdbplan.c
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/sql/subselect_gp.sql
Labels: type: bug

#8647 Make estimate_hash_bucketsize MPP-correct.
  src/backend/cdb/cdbgroup.c
  src/backend/optimizer/path/costsize.c
  src/backend/utils/adt/selfuncs.c
  src/include/utils/selfuncs.h
  src/test/regress/expected/bfv_joins.out
  src/test/regress/expected/dpe.out
  src/test/regress/expected/join.out
Labels: type: bug

#8631 Omit slice information for SubPlans that are not dispatched separately.
  src/backend/commands/explain.c
  src/include/commands/explain.h
  src/test/regress/expected/aggregates.out
  src/test/regress/expected/aggregates_optimizer.out
  src/test/regress/expected/direct_dispatch_optimizer.out
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/insert_conflict.out
  src/test/regress/expected/join.out
  src/test/regress/expected/join_optimizer.out
  src/test/regress/expected/notin_optimizer.out
  src/test/regress/expected/partial_table.out
  src/test/regress/expected/qp_correlated_query.out
  src/test/regress/expected/qp_correlated_query_optimizer.out
  src/test/regress/expected/qp_misc_jiras.out
  src/test/regress/expected/qp_subquery.out
  src/test/regress/expected/qp_subquery_optimizer.out
  src/test/regress/expected/rangefuncs.out
  src/test/regress/expected/rangefuncs_optimizer.out
  src/test/regress/expected/rowsecurity.out
  src/test/regress/expected/subselect.out
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_indexes.out
  src/test/regress/expected/subselect_gp_indexes_optimizer.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/expected/subselect_optimizer.out
  src/test/regress/expected/updatable_views.out
  src/test/regress/expected/updatable_views_optimizer.out
Labels: type: feature

#8605 Use root's stat info instead of largest child's.
  src/backend/utils/adt/selfuncs.c
  src/backend/utils/misc/guc_gp.c
  src/test/regress/expected/dpe.out
  src/test/regress/expected/join_gp.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/expected/qp_subquery.out
  src/test/regress/expected/qp_subquery_optimizer.out
  src/test/regress/sql/join_gp.sql
Labels: type: feature

#8627 Only build pxf_fdw when --enable_pxf is present
  contrib/Makefile
Labels: topic: FDW, type: maintenance

#8669 Print pg_aocsseg and gp_relation_node entries in case of mismatch
  src/backend/access/aocs/aocssegfiles.c
Labels: type: maintenance, version: 5X_STABLE

#8708 gpload.py supports both gpdb5 and gpdb6.
  gpMgmt/bin/gpload.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gpload.py
Labels: version: 5X_STABLE

#8704 5X Backport: Introduce GUC optimizer_enable_dml
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/test/regress/expected/qp_orca_fallback.out
  src/test/regress/expected/qp_orca_fallback_optimizer.out
  src/test/regress/sql/qp_orca_fallback.sql
Labels: area: gporca, version: 5X_STABLE

#8739 Bump ORCA version to 3.73.0
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
Labels: area: gporca, topic: gporca
