Repository greenplum-db/gpdb, pull requests merged in 2019-01, with the labels that each got.

#6543 Fix SIGSEGV causes by double cleanup of gang.
  concourse/pipelines/5X_STABLE-generated.yml
  src/backend/cdb/dispatcher/cdbgang_async.c
  src/backend/cdb/dispatcher/cdbgang_thread.c
  src/backend/utils/misc/faultinjector.c
  src/test/regress/input/dispatch.source
  src/test/regress/output/dispatch.source
Labels: 5X_STABLE

#6573 Fix gpperfmon bug that Gpmon return "WARNING: gpmon - bad magic 0" with explain plan
  gpMgmt/test/behave/mgmt_utils/gpperfmon.feature
  gpMgmt/test/behave/mgmt_utils/steps/data/gpperfmon/bitmap_index_scan.sql
  gpMgmt/test/behave/mgmt_utils/steps/data/gpperfmon/index_scan.sql
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  gpMgmt/test/behave_utils/utils.py
  src/backend/executor/nodeBitmapIndexscan.c
  src/backend/executor/nodeIndexscan.c
Labels: 5X_STABLE

#6613 Fix misuse pointer of pointer in IndexScan_OpenIndexRelation
  src/backend/executor/execDynamicIndexScan.c
Labels: 5X_STABLE

#6628 Skip numsegments sanity check in UTILITY mode
  src/backend/cdb/cdbcat.c
Labels: feature branch, gpdb6 expand

#6630 Add a GUC to specify the method to expand a table
  src/backend/cdb/cdbvars.c
  src/backend/commands/tablecmds.c
  src/backend/nodes/copyfuncs.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfast.c
  src/backend/utils/misc/guc_gp.c
  src/include/cdb/cdbvars.h
  src/include/nodes/parsenodes.h
  src/test/regress/expected/reshuffle.out
  src/test/regress/expected/reshuffle_ao.out
  src/test/regress/expected/reshuffle_aoco.out
  src/test/regress/sql/reshuffle.sql
  src/test/regress/sql/reshuffle_ao.sql
  src/test/regress/sql/reshuffle_aoco.sql
Labels: feature branch

#6583 Add snapshot details and role to logging
  src/backend/access/appendonly/aosegfiles.c
Labels: 5X_STABLE

#6555 Make SendTuple do de-toasting for heap as well as memtuples
  src/backend/cdb/motion/cdbmotion.c
  src/backend/cdb/motion/tupser.c
  src/backend/commands/copy.c
  src/backend/commands/tablecmds.c
  src/backend/executor/execMain.c
  src/backend/executor/execTuples.c
  src/backend/executor/nodeHash.c
  src/backend/executor/nodeHashjoin.c
  src/backend/executor/nodeMotion.c
  src/backend/executor/nodeRowTrigger.c
  src/include/cdb/cdbmotion.h
  src/include/cdb/tupser.h
  src/include/executor/tuptable.h
  src/test/regress/expected/toast.out
  src/test/regress/sql/toast.sql
Labels: 5X_STABLE

#6701 Adjust cdb_restore_agent to use bash as default shell
  src/bin/pg_dump/cdb/cdb_restore_agent.c
Labels: 5X_STABLE

#6696 Add a mock for gpexpandcheck to fix unittest of gpconfig.
  gpMgmt/bin/gpcheckcat
  gpMgmt/bin/gpconfig
  gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckcat.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gpconfig.py
Labels: feature branch, gpdb6 expand

#6681 resgroup: provide an API to get resgroup id of my proc.
  src/backend/utils/resgroup/resgroup.c
  src/include/utils/resgroup.h
Labels: Resource Groups

#6697 resgroup: add new flatten views on the status.
  src/backend/catalog/gp_toolkit.sql
  src/test/isolation2/expected/resgroup/resgroup_views.out
  src/test/isolation2/isolation2_resgroup_schedule
  src/test/isolation2/sql/resgroup/resgroup_views.sql
Labels: Resource Groups

#6730 Fix output of utility while gpexpand.
  gpMgmt/bin/gpcheckcat
  gpMgmt/bin/gppylib/utils.py
  src/test/regress/expected/run_utility_gpexpand_phase1.out
Labels: feature branch

#6742 resgroup: add new flatten views on the status. (v2)
  src/backend/catalog/gp_toolkit.sql
  src/test/isolation2/expected/resgroup/resgroup_views.out
  src/test/isolation2/isolation2_resgroup_schedule
  src/test/isolation2/sql/resgroup/resgroup_views.sql
Labels: Resource Groups

#6674 Fix configure call in test_gpdb.py
  concourse/scripts/test_gpdb.py
  concourse/tasks/test_with_planner_conan.yml
Labels: 5X_STABLE
