Repository greenplum-db/gpdb, pull requests merged in 2019-04, with the labels that each got.

#7263 6X Backport: Lock child partition tables at INSERT InitPlan() on QD
  src/backend/commands/vacuum.c
  src/backend/executor/execMain.c
  src/test/isolation2/input/uao/insert_while_vacuum_drop.source
  src/test/isolation2/output/uao/insert_while_vacuum_drop.source
  src/test/regress/expected/partition_locking.out
  src/test/regress/expected/partition_locking_optimizer.out
Labels: version: 6X_STABLE

#7302 [6X backport] Fix two fts bugs related to promoting mirror. (#7246)
  src/backend/access/transam/xlog.c
  src/backend/cdb/cdbfts.c
  src/backend/postmaster/postmaster.c
  src/include/cdb/cdbfts.h
Labels: version: 6X_STABLE

#7301 [6X backport] Set default value of guc log_rotation_size so that log file would be …
  src/backend/utils/misc/guc.c
Labels: version: 6X_STABLE

#7300 [6X backport] Improve timeout mechanism for pg_rewind tests (#7281)
  src/bin/pg_rewind/sql/config_test.sh
Labels: version: 6X_STABLE

#7313 5X: Make sure gpfdist is ready in test cases
  src/bin/gpfdist/regress/input/custom_format.source
  src/bin/gpfdist/regress/input/exttab1.source
  src/bin/gpfdist/regress/input/gpfdist2.source
  src/bin/gpfdist/regress/input/gpfdist_ssl.source
  src/bin/gpfdist/regress/output/custom_format.source
  src/bin/gpfdist/regress/output/exttab1.source
  src/bin/gpfdist/regress/output/gpfdist2.source
  src/bin/gpfdist/regress/output/gpfdist_ssl.source
  src/test/regress/input/sreh.source
  src/test/regress/output/sreh.source
Labels: version: 5X_STABLE

#7312 6X: Make sure gpfdist is ready in test cases
  src/bin/gpfdist/regress/input/custom_format.source
  src/bin/gpfdist/regress/input/exttab1.source
  src/bin/gpfdist/regress/input/gpfdist2.source
  src/bin/gpfdist/regress/input/gpfdist_ssl.source
  src/bin/gpfdist/regress/output/custom_format.source
  src/bin/gpfdist/regress/output/exttab1.source
  src/bin/gpfdist/regress/output/gpfdist2.source
  src/bin/gpfdist/regress/output/gpfdist_ssl.source
  src/test/regress/input/sreh.source
  src/test/regress/output/sreh.source
Labels: version: 6X_STABLE

#7316 5X: Fix missing pipeline file of 5X_STABLE
  concourse/tasks/test_with_planner_conan.yml
Labels: version: 5X_STABLE

#7334 6X backport: Fix gpexpand flaky test cases
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
Labels: version: 6X_STABLE

#7328 Backport 6X - Enable OpenSSL on the PR pipeline.
  concourse/scripts/compile_gpdb_open_source_ubuntu.bash
  concourse/scripts/test_gpdb.py
Labels: version: 6X_STABLE

#7293 6X_STABLE Backport: "Allow large Append-only table to have GIN index."
  src/backend/access/gin/ginpostinglist.c
  src/backend/access/gin/test/Makefile
  src/backend/access/gin/test/debugger.c
  src/backend/access/gin/test/debugger.h
  src/backend/access/gin/test/ginpostinglist_fakes.c
  src/backend/access/gin/test/ginpostinglist_test.c
  src/test/regress/expected/appendonly_with_gin_index.out
  src/test/regress/sql/appendonly_with_gin_index.sql
Labels: version: 6X_STABLE

#7292 Allow PXF to talk to custom host and port
  gpcontrib/pxf/src/libchurl.c
  gpcontrib/pxf/src/pxfuriparser.c
  gpcontrib/pxf/src/pxfutils.c
  gpcontrib/pxf/src/pxfutils.h
  gpcontrib/pxf/test/libchurl_test.c
  gpcontrib/pxf/test/pxfuriparser_test.c
  gpcontrib/pxf/test/pxfutils_test.c
Labels: version: 5X_STABLE, version: 6X_STABLE

#7239 6_Backport: show gprecoverseg progress
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/bin/gppylib/mainUtils.py
  gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
  gpMgmt/bin/gppylib/operations/test/unit/test_unit_buildMirrorSegments.py
  gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py
  gpMgmt/bin/lib/gpconfigurenewsegment
  gpMgmt/doc/gprecoverseg_help
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
  src/test/isolation2/expected/fts_dns_error.out
  src/test/isolation2/expected/fts_errors.out
  src/test/isolation2/expected/segwalrep/mirror_promotion.out
  src/test/isolation2/expected/segwalrep/twophase_tolerance_with_mirror_promotion.out
  src/test/isolation2/sql/fts_dns_error.sql
  src/test/isolation2/sql/fts_errors.sql
  src/test/isolation2/sql/segwalrep/mirror_promotion.sql
  src/test/isolation2/sql/segwalrep/twophase_tolerance_with_mirror_promotion.sql
  src/test/regress/sql/fts_recovery_in_progress.sql
  src/test/regress/sql/mirror_replay.sql
Labels: version: 6X_STABLE

#7252 add hook in MultiExecProcNode
  src/backend/executor/execProcnode.c
  src/test/regress/input/query_info_hook_test.source
  src/test/regress/output/query_info_hook_test.source
  src/test/regress/query_info_hook_test/query_info_hook_test.c
Labels: version: 5X_STABLE

#7231 Disallow joins between nested RECURSIVE clauses
  src/backend/optimizer/path/joinpath.c
  src/test/regress/expected/with_clause.out
  src/test/regress/expected/with_clause_optimizer.out
  src/test/regress/sql/with_clause.sql
Labels: version: 6X_STABLE

#7326 6X: gppylib: remove race in WorkerPool progress test
  gpMgmt/bin/gppylib/test/unit/test_unit_workerpool.py
Labels: version: 6X_STABLE

#7371 Backport 6X - Backport silence fts logging
  src/backend/fts/ftsprobe.c
Labels: version: 6X_STABLE

#7370 Backport 6X - Disable sanity assertion for itempointer offsetnumber
  src/backend/access/gin/ginpostinglist.c
Labels: version: 6X_STABLE

#7330 Create a public dockerfile for compiling greenplum on ubuntu
  src/tools/docker/README.md
  src/tools/docker/ubuntu16/Dockerfile
  src/tools/docker/ubuntu16_ppa-persistent/Dockerfile
  src/tools/docker/ubuntu16_ppa-persistent/README.md
  src/tools/docker/ubuntu16_ppa-persistent/container_init.sh
  src/tools/docker/ubuntu16_ppa-persistent/gpdb_start.sh
  src/tools/docker/ubuntu16_ppa/Dockerfile
  src/tools/docker/ubuntu16_ppa/README.md
  src/tools/docker/ubuntu16_ppa/install_and_start_gpdb.sh
Labels: version: 6X_STABLE

#7262 5X backport: Lock child partition tables at INSERT InitPlan() on QD
  src/backend/executor/execMain.c
  src/test/isolation2/input/uao/insert_while_vacuum_drop.source
  src/test/isolation2/output/uao/insert_while_vacuum_drop.source
  src/test/regress/expected/partition_locking.out
  src/test/regress/expected/partition_locking_optimizer.out
Labels: version: 5X_STABLE

#7382 Backport 6X - Do not modify a cached plan statement during ExecuteTruncate.
  src/backend/commands/tablecmds.c
  src/test/regress/expected/partition_with_user_defined_function_that_truncates.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/partition_with_user_defined_function_that_truncates.sql
Labels: version: 6X_STABLE

#7358 [6X Backport] Fix assert failure when truncating a simple toast unlogged table. (#7…
  src/backend/commands/tablecmds.c
  src/test/regress/expected/create_table.out
  src/test/regress/sql/create_table.sql
Labels: version: 6X_STABLE

#7390 6X backport: Exit earlier in test gp_replica_check if the cluster is not healthy. …
  gpcontrib/gp_replica_check/gp_replica_check.py
Labels: version: 6X_STABLE

#7336 Re-enable SRF-in-targetlist support for WindowAgg nodes.
  src/backend/executor/nodeAgg.c
  src/backend/executor/nodeWindowAgg.c
  src/include/nodes/execnodes.h
  src/test/regress/expected/olap_window.out
  src/test/regress/expected/olap_window_optimizer.out
  src/test/regress/sql/olap_window.sql
Labels: version: 6X_STABLE

#7253 Add node hook in MultiExecProcNode
  src/backend/executor/execProcnode.c
  src/test/regress/input/query_info_hook_test.source
  src/test/regress/output/query_info_hook_test.source
  src/test/regress/query_info_hook_test/query_info_hook_test.c
Labels: version: 6X_STABLE

#7389 6X Backport: Fix flaky test fts_recovery_in_progress by increasing gang creation t…
  src/test/regress/expected/fts_recovery_in_progress.out
  src/test/regress/sql/fts_recovery_in_progress.sql
Labels: version: 6X_STABLE

#7359 [6X Backport] Fix flakey test isolation2/unlogged_heap_tables due to primary/mirror…
  src/test/isolation2/expected/unlogged_appendonly_tables.out
  src/test/isolation2/expected/unlogged_heap_tables.out
  src/test/isolation2/sql/unlogged_appendonly_tables.sql
  src/test/isolation2/sql/unlogged_heap_tables.sql
Labels: version: 6X_STABLE

#7391 6X backport: Fix missing_xlog test failure due to bad function argument. (#7366)
  src/test/walrep/expected/missing_xlog.out
  src/test/walrep/sql/missing_xlog.sql
Labels: version: 6X_STABLE

#7406 6X backport: Disallow joins between nested RECURSIVE clauses
  src/backend/optimizer/path/joinpath.c
  src/test/regress/expected/with_clause.out
  src/test/regress/expected/with_clause_optimizer.out
  src/test/regress/sql/with_clause.sql
Labels: version: 6X_STABLE

#7297 SET DISTRIBUTED BY: distribution keys must be prefix of unique indexes
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_distribution_policy.out
  src/test/regress/sql/alter_distribution_policy.sql
Labels: version: 5X_STABLE

#7385 Backport 5X - Do not modify a cached plan statement during ExecuteTruncate.
  src/backend/commands/tablecmds.c
  src/test/regress/expected/partition_with_user_defined_function_that_truncates.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/partition_with_user_defined_function_that_truncates.sql
Labels: version: 5X_STABLE

#7423 Bumping ORCA version to 3.33.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: version: 5X_STABLE

#7298 Add unique index: distribution keys must be prefix of unique indexes
  src/backend/cdb/cdbcat.c
  src/test/regress/expected/alter_table.out
  src/test/regress/expected/alter_table_gp.out
  src/test/regress/expected/create_index.out
  src/test/regress/expected/gp_create_table.out
  src/test/regress/expected/partition_indexing.out
  src/test/regress/sql/alter_table_gp.sql
  src/test/regress/sql/create_index.sql
Labels: version: 5X_STABLE

#7343 Re-enable SRF-in-targetlist support for Window nodes.
  src/backend/executor/nodeWindow.c
  src/include/nodes/execnodes.h
  src/test/regress/expected/olap_window.out
  src/test/regress/expected/olap_window_optimizer.out
  src/test/regress/sql/olap_window.sql
Labels: version: 5X_STABLE

#7392 Fix gpperfmon flaky tests.
  gpAux/gpperfmon/src/gpmon/gpmondb.c
  gpMgmt/test/behave/mgmt_utils/gpperfmon.feature
Labels: version: 6X_STABLE

#7432 Bump ORCA version to 3.34.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: version: 5X_STABLE

#7387 6X: UtilsTestCase: improve test reporting for flake
  gpMgmt/bin/gppylib/operations/test/unit/test_unit_utils.py
Labels: version: 6X_STABLE

#7461 Backport 6X - Enable recursive CTEs by default.
  src/backend/utils/misc/guc_gp.c
  src/test/regress/expected/index_constraint_naming_partition.out
  src/test/regress/expected/join_gp.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/expected/with_clause.out
  src/test/regress/expected/with_clause_optimizer.out
  src/test/regress/sql/collate.linux.utf8.sql
  src/test/regress/sql/collate.sql
  src/test/regress/sql/ic.sql
  src/test/regress/sql/index_constraint_naming_partition.sql
  src/test/regress/sql/inherit.sql
  src/test/regress/sql/join_gp.sql
  src/test/regress/sql/with.sql
  src/test/regress/sql/with_clause.sql
Labels: version: 6X_STABLE

#7434 Fix gpperfmon partition flaky test.
  gpMgmt/test/behave/mgmt_utils/gpperfmon.feature
Labels: version: 6X_STABLE

#6921 Fix the math in AllocSizeIsValid. (5X_STABLE)
  src/backend/lib/stringinfo.c
  src/include/utils/memutils.h
Labels: version: 5X_STABLE

#7482 Fix gprecoverseg crash
  src/backend/access/transam/xlog.c
  src/include/utils/faultinjector_lists.h
  src/test/isolation2/expected/segwalrep/failover_with_many_records.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/segwalrep/failover_with_many_records.sql
Labels: version: 6X_STABLE

#7472 Remove references to replication ports
  gpMgmt/bin/gppylib/programs/clsAddMirrors.py
  gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
  gpMgmt/bin/gppylib/system/ComputeCatalogUpdate.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gpaddmirrors.py
  gpMgmt/doc/gpaddmirrors_help
  gpMgmt/doc/gpconfigs/gpinitsystem_config
  gpMgmt/doc/gpconfigs/gpinitsystem_test
  gpMgmt/doc/gpinitsystem_help
Labels: version: 6X_STABLE

#7464 Compile ORCA and Xerces using the same toolchain as GPDB on CentOS.
  concourse/scripts/compile_gpdb.bash
  concourse/scripts/sync_tools.bash
  concourse/tasks/compile_gpdb.yml
  concourse/tasks/sync_tools.yml
  gpAux/releng/releng.mk
Labels: version: 6X_STABLE

#7457 5X: Improve monitability of query_info_hook to SPI queries
  src/backend/executor/execMain.c
  src/backend/executor/functions.c
  src/backend/executor/spi.c
  src/backend/nodes/copyfuncs.c
  src/backend/nodes/outfast.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfast.c
  src/include/nodes/plannodes.h
  src/include/utils/metrics_utils.h
  src/test/regress/input/query_info_hook_test.source
  src/test/regress/output/query_info_hook_test.source
  src/test/regress/query_info_hook_test/query_info_hook_test.c
Labels: version: 5X_STABLE

#7515 Compile pygresql on windows with CMake
  gpMgmt/bin/pythonSrc/PyGreSQL-4.0/CMakeLists.txt
Labels: area: clients

#7523 Add README for building client tools on Windows
  README.md
  README.windows.md
Labels: area: clients

#7519 6X: CI improvements for gpexpand and gppkg
  concourse/pipelines/gpdb_6X_STABLE-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
  concourse/scripts/gppkg_behave.sh
  concourse/tasks/gppkg_behave.yml
  gpMgmt/test/behave/mgmt_utils/gppkg.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: version: 6X_STABLE

#7527 6X backport: Fix bug missing initializing timeout
  src/backend/fts/fts.c
  src/backend/utils/gdd/gddbackend.c
Labels: version: 6X_STABLE
