Repository greenplum-db/gpdb, pull requests merged in 2019-06, with the labels that each got.

#7614 Dump PgLocks when GDD detect global deadlock happens
  src/backend/utils/gdd/README.md
  src/backend/utils/gdd/gddbackend.c
  src/backend/utils/gdd/gdddetectorpriv.h
  src/backend/utils/gdd/gddfuncs.c
  src/include/catalog/catversion.h
  src/include/catalog/pg_proc.sql
  src/include/catalog/pg_proc_gp.h
  src/include/utils/builtins.h
Labels: topic: global deadlock detector

#7843 6X: Improve GDD logs to help debug
  src/backend/utils/gdd/README.md
  src/backend/utils/gdd/gddbackend.c
  src/backend/utils/gdd/gdddetectorpriv.h
  src/backend/utils/gdd/gddfuncs.c
  src/include/catalog/catversion.h
  src/include/catalog/pg_proc.sql
  src/include/catalog/pg_proc_gp.h
  src/include/utils/builtins.h
Labels: topic: global deadlock detector, version: 6X_STABLE

#7726 Support 'copy (select statement) to file on segment'
  src/backend/cdb/cdbllize.c
  src/backend/cdb/cdbmutate.c
  src/backend/commands/copy.c
  src/backend/executor/execMain.c
  src/backend/executor/execUtils.c
  src/backend/gpopt/translate/CQueryMutators.cpp
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/backend/nodes/copyfuncs.c
  src/backend/nodes/equalfuncs.c
  src/backend/nodes/outfast.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfast.c
  src/backend/nodes/readfuncs.c
  src/backend/optimizer/plan/planner.c
  src/backend/postmaster/autostats.c
  src/backend/tcop/pquery.c
  src/include/commands/copy.h
  src/include/nodes/nodes.h
  src/include/nodes/parsenodes.h
  src/include/nodes/plannodes.h
  src/include/nodes/primnodes.h
  src/test/regress/input/gpcopy.source
  src/test/regress/output/gpcopy.source
Labels: version: 5X_STABLE

#7802 Remove redundant environment variable for max connections
  concourse/scripts/common.bash
Labels: version: 6X_STABLE

#7840 Create an ArrayExpr from an array of constants
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/backend/optimizer/util/clauses.c
Labels: area: gporca, topic: gporca

#7852 Port to 5X: Create an ArrayExpr from an array of constants
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/backend/optimizer/util/clauses.c
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#7855 6X: Fix crash in transformSetOperationTree_internal()
  src/backend/parser/analyze.c
  src/test/regress/expected/union_gp.out
  src/test/regress/sql/union_gp.sql
Labels: version: 6X_STABLE

#7858 5X: resgroup: retire the memory_spill_ratio absolute value format
  src/backend/commands/resgroupcmds.c
  src/backend/parser/gram.y
  src/backend/utils/misc/guc_gp.c
  src/backend/utils/resgroup/resgroup.c
  src/include/utils/resgroup.h
  src/test/isolation2/expected/resgroup/resgroup_alter_memory_spill_ratio.out
  src/test/isolation2/expected/resgroup/resgroup_operator_memory.out
  src/test/isolation2/expected/resgroup/resgroup_set_memory_spill_ratio.out
  src/test/isolation2/expected/resgroup/resgroup_syntax.out
  src/test/isolation2/expected/resgroup/resgroup_unlimit_memory_spill_ratio.out
  src/test/isolation2/input/resgroup/enable_resgroup.source
  src/test/isolation2/output/resgroup/enable_resgroup.source
  src/test/isolation2/sql/resgroup/resgroup_operator_memory.sql
  src/test/isolation2/sql/resgroup/resgroup_set_memory_spill_ratio.sql
  src/test/isolation2/sql/resgroup/resgroup_syntax.sql
Labels: topic: resource group, version: 5X_STABLE

#7847 Change separator to '|' for gpexpand tablespace input file
  gpMgmt/bin/gpexpand
Labels: topic: gpexpand

#7868 6x backport: Change separator to '|' for gpexpand tablespace input file
  gpMgmt/bin/gpexpand
Labels: topic: gpexpand, version: 6X_STABLE

#7860 Remove plain password from logs when run gpperfmon_install.
  gpAux/gpperfmon/src/gpmon/gpperfmon_install
  gpMgmt/test/behave/mgmt_utils/gpperfmon.feature
Labels: version: 5X_STABLE

#7863 5X: Fix integer overflow in compute_scalar_stats
  src/backend/commands/analyze.c
  src/test/regress/expected/analyze.out
  src/test/regress/sql/analyze.sql
Labels: version: 5X_STABLE

#7634 Backport: Add test cases for auto_explain and enable it
  GNUmakefile.in
  contrib/auto_explain/Makefile
  contrib/auto_explain/expected/auto_explain.out
  contrib/auto_explain/expected/auto_explain_optimizer.out
  contrib/auto_explain/init_file
  contrib/auto_explain/sql/auto_explain.sql
Labels: version: 6X_STABLE

#7891 Bump ORCA version to 3.48
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#7820 Update gen_pipeline to work with python3
  concourse/pipelines/gen_pipeline.py
Labels: version: 6X_STABLE

#7889 Backport: Fix read pg_distributedlog bug (#7764)
  src/backend/access/transam/distributedlog.c
  src/backend/access/transam/test/distributedlog_test.c
  src/backend/access/transam/varsup.c
  src/include/access/distributedlog.h
  src/include/access/transam.h
  src/include/storage/lwlock.h
Labels: version: 6X_STABLE

#7865 5X_STABLE: Dump persistent tables before and after resync transition
  src/backend/cdb/cdbfilerepresyncmanager.c
  src/backend/cdb/cdbpersistentfilesysobj.c
  src/include/cdb/cdbpersistentfilesysobj.h
Labels: version: 5X_STABLE

#7914 gpcloud: try more times if AWS returns "NoSuchKey" error
  gpcontrib/gpcloud/include/s3interface.h
  gpcontrib/gpcloud/test/s3interface_test.cpp
Labels: version: 6X_STABLE

#7919 gpMgmt: add Python code coverage instructions
  gpMgmt/test/README.coverage.md
  gpMgmt/test/coveragerc
Labels: version: 6X_STABLE

#7898 Changes for ORCA commit: Skip CXformPushGbBelowSetOp when arity > threshold
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  src/backend/gpopt/utils/COptTasks.cpp
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
Labels: area: gporca, version: 6X_STABLE

#7897 Skip CXformPushGbBelowSetOp when arity > threshold
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/backend/gpopt/utils/COptTasks.cpp
Labels: area: gporca, version: 5X_STABLE

#7875 5X_STABLE: Error if about to store an invalid segment number.
  src/backend/access/aocs/aocssegfiles.c
  src/backend/access/appendonly/aosegfiles.c
  src/backend/access/appendonly/appendonlywriter.c
  src/backend/access/appendonly/test/Makefile
  src/backend/access/appendonly/test/aosegfiles_test.c
  src/include/access/aosegfiles.h
Labels: version: 5X_STABLE

#7951 Bump ORCA version to 3.50.0, ICG result file changes
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  src/test/regress/expected/qp_gist_indexes3_optimizer.out
  src/test/regress/expected/qp_gist_indexes4_optimizer.out
  src/test/regress/expected/qp_targeted_dispatch_optimizer.out
Labels: area: gporca, topic: gporca, version: 7X_ALPHA

#7952 5X: Bump ORCA version to 3.50, ICG expected file changes
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/test/regress/expected/qp_gist_indexes3_optimizer.out
  src/test/regress/expected/qp_gist_indexes4_optimizer.out
  src/test/regress/expected/qp_targeted_dispatch_optimizer.out
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#7915 gpcloud: try more times if AWS returns "NoSuchKey" error
  gpAux/extensions/gpcloud/include/s3interface.h
  gpAux/extensions/gpcloud/test/s3interface_test.cpp
Labels: version: 5X_STABLE

#7933 6X: Skip vacuuming external and foreign tables at the first place
  src/backend/commands/vacuum.c
  src/test/regress/expected/vacuum_gp.out
  src/test/regress/sql/vacuum_gp.sql
Labels: version: 6X_STABLE

#7941 Ensure temp relation files are removed from the file-system on a DROP.
  src/backend/access/rmgrdesc/xactdesc.c
  src/backend/access/transam/twophase.c
  src/backend/access/transam/xact.c
  src/backend/catalog/storage.c
  src/backend/storage/smgr/md.c
  src/include/access/xact.h
  src/include/catalog/catversion.h
  src/include/catalog/storage.h
  src/include/storage/relfilenode.h
  src/include/storage/smgr.h
  src/test/regress/greenplum_schedule
  src/test/regress/input/temp_relation.source
  src/test/regress/output/temp_relation.source
Labels: warning: on-disk change

#7962 6X Backport: Ensure temp relation files are removed from the file-system on a DROP.
  src/backend/access/rmgrdesc/xactdesc.c
  src/backend/access/transam/twophase.c
  src/backend/access/transam/xact.c
  src/backend/catalog/storage.c
  src/backend/storage/smgr/md.c
  src/include/access/xact.h
  src/include/catalog/catversion.h
  src/include/catalog/storage.h
  src/include/storage/relfilenode.h
  src/include/storage/smgr.h
  src/test/regress/greenplum_schedule
  src/test/regress/input/temp_relation.source
  src/test/regress/output/temp_relation.source
Labels: warning: on-disk change

#7997 Bump ORCA version to 3.51.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: area: gporca, version: 5X_STABLE

#7884 Default tablespace for index creation and temporary table tests.
  src/test/regress/GNUmakefile
  src/test/regress/greenplum_schedule
  src/test/regress/input/default_tablespace.source
  src/test/regress/output/default_tablespace.source
Labels: version: 6X_STABLE, version: 7X_ALPHA

#7991 6X: basebackup: correctly terminate readlink() buffer
  src/backend/replication/basebackup.c
Labels: version: 6X_STABLE

#8018 Bump ORCA version to 3.52.0
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
Labels: area: gporca

#8017 Bump ORCA version to 3.52.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: area: gporca, version: 5X_STABLE

#8013 Move Greenplum-db open source release pipeline to new repo
  concourse/pipelines/gpdb_opensource_release.yml
  concourse/scripts/compile_gpdb_oss.bash
  concourse/tasks/compile_gpdb_oss.yml
Labels: version: 6X_STABLE

#8006 6X_STABLE: Behave: Correctly kill processes during gprecoverseg tests
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
Labels: version: 6X_STABLE

#8007 6X_STABLE: Behave: Unset `TZ` rather than setting to empty string
  gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: version: 6X_STABLE

#7978 Fix wrong results for aggs containing a correlated subquery
  src/backend/gpopt/translate/CQueryMutators.cpp
  src/test/regress/expected/aggregates_optimizer.out
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca

#8021 6X_STABLE: gen_pipeline: Do not call suggested_*() functions in gen_pipeline().
  concourse/pipelines/gen_pipeline.py
Labels: version: 6X_STABLE

#8029 Behave: enable tablespace test on gpactivatestandby
  gpMgmt/test/behave/mgmt_utils/gpactivatestandby.feature
Labels: version: 6X_STABLE

#8012 5X_STABLE: Fix deadlock between gprecoverseg and FTS probe
  src/backend/utils/gp/segadmin.c
  src/test/regress/greenplum_schedule
  src/test/regress/input/fts_deadlock.source
  src/test/regress/output/fts_deadlock.source
Labels: version: 5X_STABLE
