Repository greenplum-db/gpdb, pull requests merged in 2019-02, with the labels that each got.

#6895 Remove standby master during PT rebuild Behave test
  gpMgmt/test/behave/mgmt_utils/gppersistent_rebuild.feature
Labels: 5X_STABLE

#6655 Remove dependency of test AIX to release Candidate
  concourse/pipelines/5X_STABLE-generated.yml
  concourse/pipelines/gen_pipeline.py
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: 5X_STABLE

#6866 5X: Fix OOM after cluster reset when gp_vmem_protect_limit > 16GB
  src/backend/utils/mmgr/vmem_tracker.c
Labels: 5X_STABLE

#6970 udpifc: discard out-of-date rx-thread error
  src/backend/cdb/motion/ic_udpifc.c
  src/test/regress/expected/icudp/icudp_regression.out
  src/test/regress/icudp_schedule
  src/test/regress/sql/icudp/icudp_regression.sql
Labels: interconnect, udpifc

#6772 Fix qual pushdown through Set Operation with window functions.
  src/backend/optimizer/path/allpaths.c
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/olap_window_seq.out
  src/test/regress/sql/gporca.sql
Labels: 5X_STABLE

#7007 Use unique tablename for selectinsert_while_vacuum test
  src/test/isolation2/input/uao/selectinsert_while_vacuum.source
  src/test/isolation2/output/uao/selectinsert_while_vacuum.source
Labels: type: dev environment improvement

#6997 Move test partial_table to another test group to avoid deadlock
  src/test/regress/greenplum_schedule
Labels: type: dev environment improvement, wip: feature branch

#7015 Set last segment's fragment header for PXF fragments (#5279)
  gpAux/extensions/pxf/src/pxfbridge.c
  gpAux/extensions/pxf/src/pxffragment.c
  gpAux/extensions/pxf/src/pxffragment.h
  gpAux/extensions/pxf/test/pxfbridge_test.c
  gpAux/extensions/pxf/test/pxffragment_test.c
Labels: version: 5X_STABLE

#7035 Review a PR when create a PR
  PULL_REQUEST_TEMPLATE.md
Labels: type: dev environment improvement

#6931 Rename all HLL functions (and structs) in GPDB
  src/backend/commands/analyze.c
  src/backend/utils/hyperloglog/Makefile
  src/backend/utils/hyperloglog/gp_hyperloglog.c
  src/include/utils/hyperloglog/gp_hyperloglog.h
Labels: version: 5X_STABLE

#6764 Make Vagrant builds functional
  src/tools/vagrant/.gitignore
  src/tools/vagrant/centos/Vagrantfile
  src/tools/vagrant/centos/vagrant-build-gpdb.sh
  src/tools/vagrant/centos/vagrant-configure-os.sh
  src/tools/vagrant/centos/vagrant-setup.sh
  src/tools/vagrant/common/vagrant-build-gpdb.sh
  src/tools/vagrant/common/vagrant-build-gporca.sh
  src/tools/vagrant/common/vagrant-common.rb
  src/tools/vagrant/common/vagrant-local-example.yml
  src/tools/vagrant/debian/Vagrantfile
  src/tools/vagrant/debian/vagrant-build.sh
  src/tools/vagrant/debian/vagrant-setup.sh
Labels: type: dev environment improvement

#7043 improve pg_upgrade checks for gphdfs in pre-6 clusters
  contrib/pg_upgrade/check_gp.c
Labels: topic: upgrade

#7016 allow binary_upgrade mode to create new tuples/relations of any type
  src/backend/catalog/oid_dispatch.c
Labels: topic: upgrade, version: 5X_STABLE

#6986 5X: Construct distributed snapshot after releasing LWLock
  src/backend/storage/ipc/procarray.c
Labels: version: 5X_STABLE, wip: feature branch
