Repository greenplum-db/gpdb, pull requests merged in 2019-07, with the labels that each got.

#7995 ICG changes for Create LAS Correlated Apply on in filter context
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  src/test/regress/expected/qp_subquery.out
  src/test/regress/expected/qp_subquery_optimizer.out
  src/test/regress/sql/qp_subquery.sql
Labels: area: gporca

#8037 5X: Bump ORCA version to 3.53.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/test/regress/expected/qp_subquery.out
  src/test/regress/expected/qp_subquery_optimizer.out
  src/test/regress/sql/qp_subquery.sql
Labels: area: gporca, version: 5X_STABLE

#8022 Fix check for empty array of failed_binaries
  concourse/scripts/compare_abi_ubuntu.bash
Labels: version: 5X_STABLE

#8071 Backport to 6X Fix COPY WITH OIDS
  src/backend/commands/copy.c
  src/test/regress/expected/copy2.out
  src/test/regress/sql/copy2.sql
Labels: version: 6X_STABLE

#8056 6X: Dispatch GUC setting commands with parameters quoted
  src/backend/utils/misc/guc.c
  src/test/regress/expected/guc.out
  src/test/regress/sql/guc.sql
Labels: version: 6X_STABLE

#8057 6X: Don't mark FDW or external table actions needing two phase commit
  src/backend/executor/execMain.c
Labels: version: 6X_STABLE

#8076 Remove dead command in Makefile
  gpcontrib/Makefile
Labels: version: 6X_STABLE

#7903 Schema qualify tables in create_table_distpol regress test
  src/test/regress/sql/create_table_distpol.sql
Labels: version: 6X_STABLE

#8086 Bump ORCA version to v3.54.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: area: gporca, topic: gporca

#8088 Bump ORCA version to v3.55.0
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
Labels: area: gporca

#8089 Bump ORCA version to v3.55.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: area: gporca, version: 5X_STABLE

#8101 Update AA jobs to pass along the OS version
  concourse/pipelines/5X_STABLE-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: version: 5X_STABLE

#8067 Backport 6X: Re-enable gppkg behave test for both centos and ubuntu
  gpMgmt/bin/gppylib/operations/package.py
  gpMgmt/demo/gppkg/README.md
  gpMgmt/demo/gppkg/build_gppkg.mk
  gpMgmt/demo/gppkg/data/sample-0.0-1.amd64.deb
  gpMgmt/demo/gppkg/data/sample-0.0.1-noop.x86_64.rpm
  gpMgmt/demo/gppkg/generate_sample_gppkg.sh
  gpMgmt/demo/gppkg/gppkg_deb.mk
  gpMgmt/demo/gppkg/gppkg_rpm.mk
  gpMgmt/demo/gppkg/gppkg_spec.yml.in
  gpMgmt/demo/gppkg/sample.control
  gpMgmt/test/behave/mgmt_utils/environment.py
  gpMgmt/test/behave/mgmt_utils/gpconfig.feature
  gpMgmt/test/behave/mgmt_utils/gppkg.feature
  gpMgmt/test/behave/mgmt_utils/steps/data/sample.gppkg
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: version: 6X_STABLE

#8112 Skip cdbcomponent_updateCdbComponents for FTS
  src/backend/cdb/cdbutil.c
Labels: version: 6X_STABLE

#8110 Auxiliary bgworkers should skip resource group assignment
  src/backend/utils/resource_manager/resource_manager.c
Labels: version: 6X_STABLE

#8108 Fix analyze table with more than 800 numeric columns
  src/backend/commands/analyze.c
  src/test/regress/expected/incremental_analyze.out
  src/test/regress/sql/incremental_analyze.sql
Labels: version: 5X_STABLE

#8129 Skip start the stats sender process when gpperfmon not enabled
  src/backend/postmaster/perfmon_segmentinfo.c
Labels: version: 6X_STABLE

#8144 gpexpand: improve timeout tests
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
Labels: topic: gpexpand

#8145 6X: gpexpand: improve timeout tests
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
Labels: topic: gpexpand, version: 6X_STABLE

#8103 Lock leaf partitions for all DML operations
  src/backend/executor/execMain.c
  src/test/isolation2/expected/dml_on_root_locks_all_parts.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/dml_on_root_locks_all_parts.sql
  src/test/regress/expected/partition_locking_optimizer.out
Labels: version: 5X_STABLE

#8149 Bump ORCA version from 3.55 to 3.57
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  src/include/gpopt/utils/COptServer.h
Labels: area: gporca, topic: gporca, version: 7X_ALPHA

#8150 Bump ORCA version from 3.55 to 3.57
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/include/gpopt/utils/COptServer.h
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#8152 Fix perfsummary.py script to recognize new optimizer name in EXPLAIN
  concourse/scripts/perfsummary.py
Labels: area: gporca, version: 7X_ALPHA

#8153 Backport 6X: Abort drop tablespace on error, delete files on commit.
  src/backend/access/transam/twophase.c
  src/backend/access/transam/xact.c
  src/backend/catalog/Makefile
  src/backend/catalog/storage_tablespace.c
  src/backend/catalog/storage_tablespace_twophase.c
  src/backend/catalog/storage_tablespace_xact.c
  src/backend/catalog/test/storage_tablespace_test.c
  src/backend/commands/tablespace.c
  src/backend/utils/init/postinit.c
  src/include/access/twophase_storage_tablespace.h
  src/include/access/xact.h
  src/include/access/xact_storage_tablespace.h
  src/include/catalog/storage_tablespace.h
  src/test/isolation2/expected/commit_transaction_block_checkpoint.out
  src/test/isolation2/sql/commit_transaction_block_checkpoint.sql
  src/test/regress/expected/.gitignore
  src/test/regress/input/gp_tablespace_with_faults.source
  src/test/regress/output/gp_tablespace_with_faults.source
  src/test/regress/sql/.gitignore
Labels: version: 6X_STABLE

#8131 6X_BACKPORT: Update sysctl settings to match new recommendations
  concourse/tasks/run_behave_on_ccp_cluster.yml
Labels: version: 6X_STABLE

#8170 Bump ORCA version from 3.57.0 to 3.58.1
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
Labels: area: gporca

#8164 Fix flaky in query_info_hook_test when interconnect in TCP mode
  src/test/regress/output/query_info_hook_test.source
  src/test/regress/query_info_hook_test/query_info_hook_test.c
Labels: version: 6X_STABLE

#8093 Change the size of interconnect connection hash table
  src/backend/cdb/dispatcher/cdbgang.c
  src/backend/cdb/dispatcher/cdbgang_async.c
  src/backend/cdb/motion/ic_udpifc.c
  src/include/cdb/cdbgang.h
Labels: version: 6X_STABLE

#8197 6X: Keep the order of reusing idle gangs
  src/backend/cdb/cdbutil.c
  src/backend/cdb/dispatcher/cdbdisp.c
  src/backend/cdb/dispatcher/cdbgang.c
  src/backend/commands/explain.c
  src/test/regress/expected/gang_reuse.out
  src/test/regress/expected/gang_reuse_optimizer.out
  src/test/regress/explain.pm
  src/test/regress/greenplum_schedule
  src/test/regress/sql/gang_reuse.sql
Labels: version: 6X_STABLE

#8198 5X: Add tests for idle gang reusing order
  src/backend/commands/explain.c
  src/test/regress/expected/gang_reuse.out
  src/test/regress/expected/gang_reuse_optimizer.out
  src/test/regress/explain.pm
  src/test/regress/greenplum_schedule
  src/test/regress/sql/gang_reuse.sql
Labels: version: 5X_STABLE

#8200 6X: Fix memory quota calculation of aggregation
  src/backend/executor/execUtils.c
Labels: version: 6X_STABLE

#8210 5X: Re-enable `COPY (query) TO` on utility mode
  src/backend/commands/copy.c
  src/test/regress/input/gpcopy.source
  src/test/regress/output/gpcopy.source
Labels: version: 5X_STABLE

#8209 6X: Re-enable `COPY (query) TO` on utility mode
  src/backend/commands/copy.c
  src/test/regress/input/gpcopy.source
  src/test/regress/output/gpcopy.source
Labels: version: 6X_STABLE

#8189 Behave CLI tests: use n1-standard-2 for ccp clusters
  concourse/pipelines/gpdb_6X_STABLE-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: version: 6X_STABLE

#7814 Support Equi- Full Merge Joins
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  src/backend/gpopt/config/CConfigParamMapping.cpp
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/utils/misc/guc_gp.c
  src/include/gpopt/gpdbwrappers.h
  src/include/utils/guc.h
  src/test/regress/expected/gpdist_optimizer.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/join_optimizer.out
Labels: area: gporca, topic: gporca

#8134 Disable Full Merge Join in 5X
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/backend/gpopt/config/CConfigParamMapping.cpp
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/include/gpopt/gpdbwrappers.h
Labels: area: gporca, version: 5X_STABLE

#8123 6X_BACKPORT: gparray: Add version check when connecting to cluster
  gpMgmt/bin/gppylib/gparray.py
  gpMgmt/bin/gppylib/gpversion.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gparray.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gpversion.py
Labels: version: 6X_STABLE

#8161 Fix flaky in query_info_hook_test when interconnect in TCP mode
  src/test/regress/output/query_info_hook_test.source
  src/test/regress/query_info_hook_test/query_info_hook_test.c
Labels: version: 5X_STABLE

#8203 Remove unused ORCA tasks in concourse/tasks
  concourse/pipelines/pr_pipeline.yml
  concourse/tasks/build_gpdb_with_orca_gen_by_conan.yml
  concourse/tasks/build_orca_using_conan.yml
  concourse/tasks/test_with_orca_conan.yml
  concourse/tasks/test_with_planner_conan.yml
Labels: version: 5X_STABLE

#8216 unset_search_path: backend fix
  gpAux/gpdemo/gpsegwalrep.py
  gpMgmt/bin/gpconfig
  gpMgmt/bin/gppylib/db/dbconn.py
  gpMgmt/bin/gppylib/db/test/regress/test_regress_catalog.py
  gpMgmt/bin/gppylib/db/test/test_catalog.py
  gpMgmt/bin/gppylib/db/test/unit/test_cluster_dbconn.py
  gpMgmt/bin/gppylib/test/regress/test_regress_gpexpand.py
  gpMgmt/test/behave/mgmt_utils/environment.py
  gpMgmt/test/behave/mgmt_utils/steps/analyzedb_mgmt_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/tablespace_mgmt_utils.py
  gpMgmt/test/behave_utils/cluster_expand.py
  gpMgmt/test/behave_utils/gpexpand_dml.py
  gpMgmt/test/behave_utils/utils.py
Labels: version: 6X_STABLE

#8224 Turn optimizer_dpe_stats to on.
  src/backend/utils/misc/guc_gp.c
  src/test/regress/expected/bfv_index_optimizer.out
  src/test/regress/expected/qp_targeted_dispatch_optimizer.out
Labels: version: 6X_STABLE

#8187 Propagate external table format options to PXF headers
  gpcontrib/pxf/src/pxfheaders.c
  gpcontrib/pxf/test/pxfheaders_test.c
  src/backend/access/external/fileam.c
  src/include/access/fileam.h
Labels: topic: FDW, topic: pxf, version: 7X_ALPHA

#8175 (5X)Fix bug: initplan may clean up gangs allocated to parent plan
  src/backend/access/transam/xact.c
  src/backend/cdb/cdbtm.c
  src/backend/cdb/dispatcher/cdbgang.c
  src/backend/cdb/dispatcher/test/cdbgang_test.c
  src/backend/commands/portalcmds.c
  src/backend/executor/execUtils.c
  src/backend/utils/misc/faultinjector.c
  src/include/cdb/cdbgang.h
  src/include/utils/faultinjector.h
  src/test/regress/expected/freegang_initplan.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/freegang_initplan.sql
Labels: version: 5X_STABLE

#8235 Backport 6X_STABLE: Add flag to pg_regress to display failure diffs on stdout.
  src/test/regress/pg_regress.c
Labels: version: 6X_STABLE

#8252 resgroup: hashagg: revert operator memory auto enlarging
  src/backend/executor/execHHashagg.c
  src/include/executor/execHHashagg.h
  src/test/isolation2/expected/resgroup/resgroup_agghash_memory.out
  src/test/isolation2/expected/resgroup/resgroup_operator_memory.out
  src/test/isolation2/isolation2_resgroup_schedule
  src/test/isolation2/sql/resgroup/resgroup_agghash_memory.sql
  src/test/isolation2/sql/resgroup/resgroup_operator_memory.sql
Labels: topic: resource group

#8242 Backport 6X_STABLE:CREATE DATABASE two-phase commit safe (#8078)
  src/backend/commands/dbcommands.c
  src/test/regress/expected/.gitignore
  src/test/regress/greenplum_schedule
  src/test/regress/input/createdb.source
  src/test/regress/output/createdb.source
  src/test/regress/serial_schedule
  src/test/regress/sql/.gitignore
Labels: version: 6X_STABLE

#8261 6X: resgroup: hashagg: revert operator memory auto enlarging
  src/backend/executor/execHHashagg.c
  src/include/executor/execHHashagg.h
  src/test/isolation2/expected/resgroup/resgroup_agghash_memory.out
  src/test/isolation2/expected/resgroup/resgroup_operator_memory.out
  src/test/isolation2/isolation2_resgroup_schedule
  src/test/isolation2/sql/resgroup/resgroup_agghash_memory.sql
  src/test/isolation2/sql/resgroup/resgroup_operator_memory.sql
Labels: topic: resource group, version: 6X_STABLE

#8213 [5X Backport] Propagate external table format options to PXF headers
  gpAux/extensions/pxf/src/pxfheaders.c
  gpAux/extensions/pxf/test/pxfheaders_test.c
  src/backend/access/external/fileam.c
  src/include/access/fileam.h
Labels: topic: FDW, topic: pxf
