Repository greenplum-db/gpdb, pull requests merged in 2019-08, with the labels that each got.

#8292 Fix aocs table block version mismatch (#8202)
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_table_aocs.out
  src/test/regress/sql/alter_table_aocs.sql
Labels: version: 6X_STABLE

#8295 Bump ORCA version to v3.62.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: area: gporca, version: 5X_STABLE

#8299 Bump ORCA to v3.63.0
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca

#8293 Fix aocs table block version mismatch (#8202)
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_table_aocs.out
  src/test/regress/sql/alter_table_aocs.sql
Labels: version: 5X_STABLE

#8096 Add test cases, certificates and keys for contrib/sslinfo
  GNUmakefile.in
  contrib/sslinfo/Makefile
  contrib/sslinfo/config.bash
  contrib/sslinfo/data/postgresql.crt
  contrib/sslinfo/data/postgresql.key
  contrib/sslinfo/data/root.crt
  contrib/sslinfo/data/server.crt
  contrib/sslinfo/data/server.key
  contrib/sslinfo/expected/sslinfo.out
  contrib/sslinfo/sql/sslinfo.sql
Labels: version: 6X_STABLE

#8306 [6X Backport] Fix `Explain Analyze` crash
  src/backend/commands/explain_gp.c
  src/test/regress/expected/gp_explain.out
  src/test/regress/expected/gp_explain_optimizer.out
  src/test/regress/sql/gp_explain.sql
Labels: version: 6X_STABLE

#8317 FTS: Ensure fresh results from a probe (6X_BACKPORT)
  src/backend/cdb/cdbfts.c
  src/backend/fts/README
  src/backend/fts/fts.c
  src/backend/fts/ftsprobe.c
  src/include/cdb/cdbfts.h
  src/test/isolation2/helpers/server_helpers.sql
  src/test/isolation2/input/fts_manual_probe.source
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/output/fts_manual_probe.source
  src/test/regress/regress_gp.c
Labels: version: 6X_STABLE

#8345 6X_BACKPORT: Behave stop segments: Add -w flag to pg_ctl stop
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: version: 6X_STABLE

#8329 docs - pxf updates due to changes in passing format options
  gpdb-doc/markdown/pxf/hive_pxf.html.md.erb
  gpdb-doc/markdown/pxf/upgrade_pxf.html.md.erb
Labels: version: 5X_STABLE

#7185 Fix assert failure for copy to partition table (#7132)
  src/backend/commands/copy.c
  src/test/regress/expected/partition.out
  src/test/regress/expected/partition_optimizer.out
  src/test/regress/sql/partition.sql
Labels: version: 5X_STABLE

#8348 6X: Init plan with input param follow upstream execution flow
  src/backend/optimizer/plan/subselect.c
  src/test/regress/expected/rangefuncs.out
  src/test/regress/expected/rangefuncs_optimizer.out
  src/test/regress/sql/rangefuncs.sql
Labels: version: 6X_STABLE

#8378 6X Backport: Tear out movedb_failure_callback
  src/backend/commands/dbcommands.c
Labels: version: 6X_STABLE

#8358 Fix COPY FROM SEGMENT segment rows completed count
  src/backend/cdb/cdbcopy.c
  src/backend/cdb/test/Makefile
  src/backend/cdb/test/cdbcopy_test.c
Labels: version: 5X_STABLE

#8392 6X_BACKPORT: set_config_by_name(): dispatch all values correctly
  src/backend/utils/misc/guc.c
  src/test/regress/input/dispatch.source
  src/test/regress/output/dispatch.source
Labels: version: 6X_STABLE

#8312 docs - Update of locking on partitioned tables for DELETE/INSERT/UPDA…
  gpdb-doc/dita/ref_guide/sql_commands/DELETE.xml
  gpdb-doc/dita/ref_guide/sql_commands/INSERT.xml
  gpdb-doc/dita/ref_guide/sql_commands/UPDATE.xml
Labels: version: 5X_STABLE

#8400 6X BackPort: Fix interconnect retransmission period
  src/backend/cdb/motion/ic_udpifc.c
Labels: version: 6X_STABLE

#8414 6X BackPort Error out when locallock and proclock are not consistent.
  src/backend/storage/lmgr/lock.c
Labels: version: 6X_STABLE

#8415 5X BackPort Error out when locallock and proclock are not consistent.
  src/backend/storage/lmgr/lock.c
Labels: version: 5X_STABLE

#8404 Use updated pyOpenSSL for travis pipeline
  .travis.yml
Labels: version: 5X_STABLE

#8381 Set Plan::allParam correctly in CTranslatorDXLToPlStmt
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/optimizer/util/walkers.c
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, topic: gporca

#8412 5X BackPort: Fix interconnect retransmission period
  src/backend/cdb/motion/ic_udpifc.c
Labels: version: 5X_STABLE

#8447 Set Plan::allParam correctly in CTranslatorDXLToPlStmt
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/optimizer/util/walkers.c
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, topic: gporca

#8444 5X: Add stats warning to gpsd and minirepro
  gpMgmt/bin/gpsd
  gpMgmt/bin/minirepro
Labels: version: 5X_STABLE

#8464 6X: Restore default net.ipv4.ip_local_port_range
  concourse/tasks/run_behave_on_ccp_cluster.yml
Labels: version: 6X_STABLE

#8331 Handle jumps from sigusr1 handler to sigterm handler
  src/backend/replication/syncrep.c
  src/backend/storage/ipc/procsignal.c
Labels: version: 5X_STABLE

#8456 Unset optimizer_force_multistage_agg by default.
  src/backend/utils/misc/guc_gp.c
  src/test/regress/expected/bfv_aggregate.out
  src/test/regress/expected/bfv_aggregate_optimizer.out
  src/test/regress/expected/bfv_dd_multicolumn.out
  src/test/regress/expected/bfv_dd_multicolumn_optimizer.out
  src/test/regress/expected/bfv_index_optimizer.out
  src/test/regress/expected/bitmapops_optimizer.out
  src/test/regress/expected/create_index_optimizer.out
  src/test/regress/expected/dpe_optimizer.out
  src/test/regress/expected/eagerfree_optimizer.out
  src/test/regress/expected/gang_reuse.out
  src/test/regress/expected/gang_reuse_optimizer.out
  src/test/regress/expected/gp_aggregates.out
  src/test/regress/expected/gp_dqa_optimizer.out
  src/test/regress/expected/gpdiffcheck_optimizer.out
  src/test/regress/expected/gpdist_optimizer.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/notin_optimizer.out
  src/test/regress/expected/olap_window_seq_optimizer.out
  src/test/regress/expected/pg_lsn_optimizer.out
  src/test/regress/expected/qp_correlated_query_optimizer.out
  src/test/regress/expected/qp_misc_jiras_optimizer.out
  src/test/regress/expected/qp_targeted_dispatch_optimizer.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/expected/union_optimizer.out
  src/test/regress/expected/update_gp_optimizer.out
  src/test/regress/expected/workfile/hashagg_spill.out
  src/test/regress/sql/bfv_aggregate.sql
  src/test/regress/sql/bfv_dd_multicolumn.sql
  src/test/regress/sql/gang_reuse.sql
  src/test/regress/sql/gp_aggregates.sql
  src/test/regress/sql/workfile/hashagg_spill.sql
Labels: area: gporca, topic: gporca

#8476 6X: icw: run namespace_gp separately
  src/test/regress/greenplum_schedule
Labels: version: 6X_STABLE

#8473 Update gen_pipeline secrets help
  concourse/pipelines/gen_pipeline.py
Labels: version: 5X_STABLE

#8461 Fix unit test sharedsnapshot_test.c
  src/backend/utils/time/sharedsnapshot.c
  src/backend/utils/time/test/sharedsnapshot_test.c
Labels: version: 6X_STABLE

#8490 Remove dead test files for ALTER DATABASE SET TABLESPACE
  src/test/regress/input/alter_db_set_tablespace_with_fault.source
  src/test/regress/output/alter_db_set_tablespace_with_fault.source
Labels: version: 6X_STABLE

#8497 Remove unused faulinject facility
  src/backend/cdb/cdbfts.c
  src/backend/utils/error/Makefile
  src/backend/utils/error/faultinject.c
  src/backend/utils/mmgr/vmem_tracker.c
  src/include/catalog/catversion.h
  src/include/catalog/pg_proc_gp.h
  src/include/utils/faultinjection.h
  src/include/utils/vmem_tracker.h
Labels: warning: catalog change

#8428 Fix crash when the qual under DynamicTableScan has a subplan
  src/backend/executor/execScan.c
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: version: 5X_STABLE

#8523 Bump ORCA version to v3.66.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: version: 5X_STABLE

#8489 Consider predicate of type <cast(ident)> array cmp <const array>
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, topic: gporca

#8534 Avoid I/U failure due to out-of-sync AO segfile state between QD & QE
  src/backend/access/aocs/aocs_compaction.c
  src/backend/commands/vacuum.c
  src/test/isolation2/expected/vacuum_drop_phase_ao.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/vacuum_drop_phase_ao.sql
Labels: version: 5X_STABLE
