Repository greenplum-db/gpdb, pull requests merged in 2019-05, with the labels that each got.

#7583 Disable SSL renegotiation by default.
  src/backend/utils/misc/guc.c
Labels: version: 5X_STABLE

#7604 5X: Bump ORCA version to 3.37 (from 3.35)
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/union_gp.out
  src/test/regress/sql/union_gp.sql
Labels: version: 5X_STABLE

#7597 Port to 5X ICG changes for 'Convert FULL OUTER JOIN to LEFT JOIN when possible'
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: version: 5X_STABLE

#7565 6X: gpcloud: sleep and retry if AWS returns "NoSuchKey" error
  gpcontrib/gpcloud/include/s3exception.h
  gpcontrib/gpcloud/src/s3interface.cpp
Labels: version: 6X_STABLE

#7566 5X: gpcloud: sleep and retry if AWS returns "NoSuchKey" error
  gpAux/extensions/gpcloud/include/s3exception.h
  gpAux/extensions/gpcloud/src/s3interface.cpp
Labels: version: 5X_STABLE

#7622 [6X backport] Recursively create tablespace directories if they do not exist but we…
  src/backend/commands/dbcommands.c
  src/backend/commands/tablespace.c
Labels: version: 6X_STABLE

#7621 6X: Fix motion hazard between outer and joinqual
  src/backend/executor/execUtils.c
  src/backend/executor/nodeHashjoin.c
  src/backend/executor/nodeMergejoin.c
  src/backend/executor/nodeNestloop.c
  src/backend/nodes/copyfuncs.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfast.c
  src/backend/optimizer/plan/createplan.c
  src/include/executor/executor.h
  src/include/nodes/execnodes.h
  src/include/nodes/plannodes.h
  src/test/regress/expected/deadlock2.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/deadlock2.sql
Labels: version: 6X_STABLE

#7620 5X: Fix motion hazard between outer and joinqual
  src/backend/executor/execUtils.c
  src/backend/executor/nodeHashjoin.c
  src/backend/executor/nodeMergejoin.c
  src/backend/executor/nodeNestloop.c
  src/backend/nodes/copyfuncs.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfast.c
  src/backend/optimizer/plan/createplan.c
  src/include/executor/executor.h
  src/include/nodes/execnodes.h
  src/include/nodes/plannodes.h
  src/test/regress/expected/deadlock2.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/deadlock2.sql
Labels: version: 5X_STABLE

#7629 Add notice if analyze finds only empty pages for table
  src/backend/commands/analyze.c
  src/test/regress/expected/gp_toolkit.out
  src/test/regress/expected/metadata_track.out
  src/test/regress/expected/workfile/spilltodisk.out
  src/test/regress/init_file
Labels: version: 5X_STABLE

#7654 Allow user to enable and disable hash/group aggregates with GPORCA
  src/backend/gpopt/config/CConfigParamMapping.cpp
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/test/regress/expected/qp_orca_fallback.out
  src/test/regress/expected/qp_orca_fallback_optimizer.out
  src/test/regress/sql/qp_orca_fallback.sql
Labels: area: gporca, version: 6X_STABLE

#7652 Bump ORCA to v3.41.0 and update test cases
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/expected/notin_optimizer.out
  src/test/regress/expected/update_gp_optimizer.out
Labels: area: gporca

#7624 Waiting relation in GDD should consider lock conflict map.
  src/backend/storage/lmgr/lock.c
  src/backend/utils/gdd/gddfuncs.c
  src/include/storage/lock.h
  src/test/isolation2/expected/gdd/non-lock-108.out
  src/test/isolation2/sql/gdd/non-lock-108.sql
Labels: topic: global deadlock detector

#7668 [6X backport] Waiting relation in GDD should consider lock conflict map. (#7624)
  src/backend/storage/lmgr/lock.c
  src/backend/utils/gdd/gddfuncs.c
  src/include/storage/lock.h
  src/test/isolation2/expected/gdd/non-lock-108.out
  src/test/isolation2/sql/gdd/non-lock-108.sql
Labels: version: 6X_STABLE

#7667 Dump gp_segment_configuration in gpexpand behave test
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: topic: gpexpand

#7664 [5X Backport] Various PXF libchurl cleanups
  gpAux/extensions/pxf/src/libchurl.c
Labels: topic: pxf, version: 5X_STABLE

#7485 Fix algebrization of subqueries in queries with complex GROUP BYs (5x)
  src/backend/gpopt/translate/CQueryMutators.cpp
  src/include/gpopt/translate/CQueryMutators.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 5X_STABLE

#7602 gpconfig: Add support for empty-string values
  gpMgmt/bin/gpconfig
  gpMgmt/bin/gppylib/test/unit/test_unit_gpconfig.py
  gpMgmt/test/behave/mgmt_utils/gpconfig.feature
Labels: version: 6X_STABLE

#7655 Optimize hash table lookups in ORCA algebrization
  src/backend/gpopt/translate/CMappingVarColId.cpp
Labels: area: gporca, version: 5X_STABLE, version: 6X_STABLE

#7193 Fix algebrization of subqueries in queries with complex GROUP BYs
  src/backend/gpopt/translate/CQueryMutators.cpp
  src/include/gpopt/translate/CQueryMutators.h
  src/test/regress/expected/aggregates_optimizer.out
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 6X_STABLE

#7710 Bump ORCA version to 3.43.1
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/test/regress/expected/gp_dqa_optimizer.out
Labels: area: gporca

#7717 Bump ORCA version to 3.43.1
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: area: gporca

#7697 Support internal communications when re-initialize connection.
  src/backend/libpq/auth.c
  src/include/libpq/pqcomm.h
  src/interfaces/libpq/fe-connect.c
  src/test/regress/expected/internal_connection.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/internal_connection.sql
Labels: topic: fe

#7730 6X BACKPORT: remove paramiko
  .travis.yml
  README.amazon_linux
  README.ubuntu.bash
  gpMgmt/Makefile
  gpMgmt/bin/Makefile
  gpMgmt/bin/ext/.gitignore
  gpMgmt/bin/ext/Crypto/.gitignore
  gpMgmt/bin/lib/.gitignore
  python-dependencies.txt
  src/tools/docker/centos6/Dockerfile
  src/tools/docker/centos7/Dockerfile
  src/tools/docker/ubuntu16/Dockerfile
  src/tools/vagrant/centos/vagrant-setup.sh
  src/tools/vagrant/debian/vagrant-setup.sh
Labels: version: 6X_STABLE

#7718 PXF: Validation for wrapper options
  contrib/pxf_fdw/Makefile
  contrib/pxf_fdw/expected/pxf_fdw.out
  contrib/pxf_fdw/pxf_fdw--1.0.sql
  contrib/pxf_fdw/pxf_fdw.c
  contrib/pxf_fdw/pxf_option.c
  contrib/pxf_fdw/sql/pxf_fdw.sql
Labels: topic: pxf

#7713 6X Backport: Declare a whitelist in gpstop for bgworker
  gpMgmt/bin/gppylib/db/catalog.py
  gpMgmt/bin/gpstop
Labels: version: 6X_STABLE

#7745 Backport 6X: pg_basebackup: WARN when running in TAR mode.
  src/bin/pg_basebackup/pg_basebackup.c
Labels: version: 6X_STABLE

#7704 Backport 6X: Modify pg_rewind to handle new tablespace layout.
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  src/bin/pg_rewind/Makefile
  src/bin/pg_rewind/copy_fetch.c
  src/bin/pg_rewind/expected/tablespaces_objects_created_after_promotion.out
  src/bin/pg_rewind/expected/tablespaces_objects_created_before_promotion.out
  src/bin/pg_rewind/expected/tablespaces_objects_removed_after_promotion.out
  src/bin/pg_rewind/file_ops.c
  src/bin/pg_rewind/filemap.c
  src/bin/pg_rewind/filemap.h
  src/bin/pg_rewind/pg_rewind.c
  src/bin/pg_rewind/pg_rewind.h
  src/bin/pg_rewind/sql/config_test.sh
  src/bin/pg_rewind/sql/run_test.sh
  src/bin/pg_rewind/sql/tablespaces_objects_created_after_promotion.sql
  src/bin/pg_rewind/sql/tablespaces_objects_created_before_promotion.sql
  src/bin/pg_rewind/sql/tablespaces_objects_removed_after_promotion.sql
Labels: version: 6X_STABLE

#7743 Control operator memory by absolute values in resource group mode
  src/backend/catalog/gp_toolkit.sql
  src/backend/cdb/cdbvars.c
  src/backend/commands/resgroupcmds.c
  src/backend/parser/gram.y
  src/backend/utils/misc/guc_gp.c
  src/backend/utils/resgroup/resgroup.c
  src/include/catalog/catversion.h
  src/include/catalog/pg_resgroupcapability.h
  src/include/utils/guc.h
  src/include/utils/resgroup.h
  src/test/isolation2/expected/resgroup/resgroup_alter_memory_spill_ratio.out
  src/test/isolation2/expected/resgroup/resgroup_concurrency.out
  src/test/isolation2/expected/resgroup/resgroup_dumpinfo.out
  src/test/isolation2/expected/resgroup/resgroup_operator_memory.out
  src/test/isolation2/expected/resgroup/resgroup_set_memory_spill_ratio.out
  src/test/isolation2/expected/resgroup/resgroup_syntax.out
  src/test/isolation2/expected/resgroup/resgroup_transaction.out
  src/test/isolation2/expected/resgroup/resgroup_unlimit_memory_spill_ratio.out
  src/test/isolation2/expected/resgroup/resgroup_views.out
  src/test/isolation2/input/resgroup/disable_resgroup.source
  src/test/isolation2/input/resgroup/enable_resgroup.source
  src/test/isolation2/input/resgroup/resgroup_alter_memory.source
  src/test/isolation2/input/resgroup/resgroup_memory_limit.source
  src/test/isolation2/output/resgroup/disable_resgroup.source
  src/test/isolation2/output/resgroup/enable_resgroup.source
  src/test/isolation2/output/resgroup/resgroup_alter_memory.source
  src/test/isolation2/output/resgroup/resgroup_memory_limit.source
  src/test/isolation2/sql/resgroup/resgroup_alter_memory_spill_ratio.sql
  src/test/isolation2/sql/resgroup/resgroup_concurrency.sql
  src/test/isolation2/sql/resgroup/resgroup_dumpinfo.sql
  src/test/isolation2/sql/resgroup/resgroup_set_memory_spill_ratio.sql
  src/test/isolation2/sql/resgroup/resgroup_syntax.sql
  src/test/isolation2/sql/resgroup/resgroup_transaction.sql
  src/test/isolation2/sql/resgroup/resgroup_unlimit_memory_spill_ratio.sql
  src/test/isolation2/sql/resgroup/resgroup_views.sql
Labels: topic: resource group

#7762 BACKPORT 6X: GUC with PGC_BACKEND context should also be dispatched to QE (#7741)
  src/backend/cdb/dispatcher/cdbgang.c
Labels: version: 6X_STABLE

#7766 5X: Control operator memory by absolute values in resource group mode
  src/backend/commands/resgroupcmds.c
  src/backend/parser/gram.y
  src/backend/utils/misc/guc_gp.c
  src/backend/utils/resgroup/resgroup.c
  src/include/utils/resgroup.h
  src/test/isolation2/expected/resgroup/resgroup_alter_memory_spill_ratio.out
  src/test/isolation2/expected/resgroup/resgroup_dumpinfo.out
  src/test/isolation2/expected/resgroup/resgroup_operator_memory.out
  src/test/isolation2/expected/resgroup/resgroup_set_memory_spill_ratio.out
  src/test/isolation2/expected/resgroup/resgroup_syntax.out
  src/test/isolation2/expected/resgroup/resgroup_unlimit_memory_spill_ratio.out
  src/test/isolation2/input/resgroup/disable_resgroup.source
  src/test/isolation2/input/resgroup/enable_resgroup.source
  src/test/isolation2/input/resgroup/resgroup_memory_limit.source
  src/test/isolation2/output/resgroup/disable_resgroup.source
  src/test/isolation2/output/resgroup/enable_resgroup.source
  src/test/isolation2/output/resgroup/resgroup_memory_limit.source
  src/test/isolation2/sql/resgroup/resgroup_dumpinfo.sql
  src/test/isolation2/sql/resgroup/resgroup_set_memory_spill_ratio.sql
  src/test/isolation2/sql/resgroup/resgroup_syntax.sql
  src/test/isolation2/sql/resgroup/resgroup_unlimit_memory_spill_ratio.sql
Labels: topic: resource group, version: 5X_STABLE

#7731 Report name of the index that conficts with proposed distribution key
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_distribution_policy.out
Labels: version: 5X_STABLE

#7767 Back Port 6X: Support internal communications when re-initialize connection. (#7697)
  src/backend/libpq/auth.c
  src/include/libpq/pqcomm.h
  src/interfaces/libpq/fe-connect.c
  src/test/regress/expected/internal_connection.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/internal_connection.sql
Labels: version: 6X_STABLE

#7794 5X: Avoid infinite loop in processCopyEndResults
  src/backend/cdb/cdbcopy.c
Labels: version: 5X_STABLE

#7804 Do not include zstd or quicklz for SLES
  concourse/scripts/compile_gpdb.bash
Labels: version: 6X_STABLE

#7798 PXF: Fix repository path
  README.md
  gpcontrib/pxf/test/Makefile
  gpdb-doc/markdown/pxf/sdk/dev_overview.html.md.erb
Labels: topic: pxf, version: 6X_STABLE

#7812 Check presence of commit SHA in executables with readelf
  concourse/scripts/verify_gpdb_versions.bash
Labels: version: 6X_STABLE

#7818 6X_BACKPORT: parseutils: cluster management input file refactoring
  gpMgmt/bin/gpexpand
  gpMgmt/bin/gpmovemirrors
  gpMgmt/bin/gppylib/parseutils.py
  gpMgmt/bin/gppylib/programs/clsAddMirrors.py
  gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
  gpMgmt/bin/gppylib/test/unit/test_unit_parseutils.py
  gpMgmt/bin/gppylib/utils.py
  gpMgmt/doc/gpaddmirrors_help
  gpMgmt/doc/gpexpand_help
  gpMgmt/doc/gprecoverseg_help
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/replication_slots_utils.py
Labels: version: 6X_STABLE

#7756 Revert "Skip analyzing root partitions by default in analyzedb (#7081)"
  gpMgmt/bin/analyzedb
  gpMgmt/test/behave/mgmt_utils/analyzedb.feature
  gpMgmt/test/behave/mgmt_utils/steps/analyzedb_mgmt_utils.py
Labels: version: 6X_STABLE

#7827 5X: Bump ORCA version to 3.45.0 and disable DPv2 transform
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/backend/gpopt/config/CConfigParamMapping.cpp
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#7826 Bump ORCA version to 3.45.0, added new value to guc
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/backend/gpopt/config/CConfigParamMapping.cpp
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/test/regress/expected/join_gp.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/sql/join_gp.sql
Labels: area: gporca, topic: gporca, version: 7X_ALPHA

#7778 Create a public dockerfile for compiling greenplum on ubuntu18
  src/tools/docker/README.md
  src/tools/docker/ubuntu/Dockerfile
Labels: version: 6X_STABLE

#7763 Remove windows support under gpAux.
  concourse/scripts/sync_tools.bash
  gpAux/Makefile
  gpAux/Makefile.global
  gpAux/Makefile.thirdparty
  gpAux/Makefile.windows
  gpAux/extensions/Makefile
  src/bin/gpfdist/Makefile
Labels: version: 6X_STABLE

#7836 resgroup: retire useless columns in views.
  src/backend/catalog/gp_toolkit.sql
Labels: topic: resource group

#7837 6X backport: Correctly handle tablespace for GPexpand
  gpMgmt/bin/gpexpand
  gpMgmt/bin/gppylib/gparray.py
  gpMgmt/bin/lib/gpconfigurenewsegment
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
  gpMgmt/test/behave/mgmt_utils/steps/tablespace_mgmt_utils.py
  gpMgmt/test/behave_utils/cluster_expand.py
Labels: topic: gpexpand, version: 6X_STABLE

#7828 Rename IMemoryPool to CMemoryPool
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/backend/gpopt/config/CConfigParamMapping.cpp
  src/backend/gpopt/relcache/CMDProviderRelcache.cpp
  src/backend/gpopt/translate/CCTEListEntry.cpp
  src/backend/gpopt/translate/CContextDXLToPlStmt.cpp
  src/backend/gpopt/translate/CContextQueryToDXL.cpp
  src/backend/gpopt/translate/CDXLTranslateContext.cpp
  src/backend/gpopt/translate/CDXLTranslateContextBaseTable.cpp
  src/backend/gpopt/translate/CMappingColIdVar.cpp
  src/backend/gpopt/translate/CMappingColIdVarPlStmt.cpp
  src/backend/gpopt/translate/CMappingVarColId.cpp
  src/backend/gpopt/translate/CQueryMutators.cpp
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
  src/backend/gpopt/translate/CTranslatorUtils.cpp
  src/backend/gpopt/utils/COptTasks.cpp
  src/include/gpopt/config/CConfigParamMapping.h
  src/include/gpopt/relcache/CMDProviderRelcache.h
  src/include/gpopt/translate/CCTEListEntry.h
  src/include/gpopt/translate/CContextDXLToPlStmt.h
  src/include/gpopt/translate/CContextQueryToDXL.h
  src/include/gpopt/translate/CDXLTranslateContext.h
  src/include/gpopt/translate/CDXLTranslateContextBaseTable.h
  src/include/gpopt/translate/CMappingColIdVar.h
  src/include/gpopt/translate/CMappingColIdVarPlStmt.h
  src/include/gpopt/translate/CMappingVarColId.h
  src/include/gpopt/translate/CQueryMutators.h
  src/include/gpopt/translate/CTranslatorDXLToPlStmt.h
  src/include/gpopt/translate/CTranslatorDXLToScalar.h
  src/include/gpopt/translate/CTranslatorQueryToDXL.h
  src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
  src/include/gpopt/translate/CTranslatorScalarToDXL.h
  src/include/gpopt/translate/CTranslatorUtils.h
  src/include/gpopt/utils/CConstExprEvaluatorProxy.h
  src/include/gpopt/utils/COptClient.h
  src/include/gpopt/utils/COptServer.h
  src/include/gpopt/utils/COptTasks.h
Labels: area: gporca, version: 6X_STABLE

#7829 5X: Rename IMemoryPool to CMemoryPool
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/backend/gpopt/config/CConfigParamMapping.cpp
  src/backend/gpopt/relcache/CMDProviderRelcache.cpp
  src/backend/gpopt/translate/CCTEListEntry.cpp
  src/backend/gpopt/translate/CContextDXLToPlStmt.cpp
  src/backend/gpopt/translate/CDXLTranslateContext.cpp
  src/backend/gpopt/translate/CDXLTranslateContextBaseTable.cpp
  src/backend/gpopt/translate/CMappingColIdVar.cpp
  src/backend/gpopt/translate/CMappingColIdVarPlStmt.cpp
  src/backend/gpopt/translate/CMappingVarColId.cpp
  src/backend/gpopt/translate/CQueryMutators.cpp
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
  src/backend/gpopt/translate/CTranslatorUtils.cpp
  src/backend/gpopt/utils/COptTasks.cpp
  src/include/gpopt/config/CConfigParamMapping.h
  src/include/gpopt/relcache/CMDProviderRelcache.h
  src/include/gpopt/translate/CCTEListEntry.h
  src/include/gpopt/translate/CContextDXLToPlStmt.h
  src/include/gpopt/translate/CDXLTranslateContext.h
  src/include/gpopt/translate/CDXLTranslateContextBaseTable.h
  src/include/gpopt/translate/CMappingColIdVar.h
  src/include/gpopt/translate/CMappingColIdVarPlStmt.h
  src/include/gpopt/translate/CMappingVarColId.h
  src/include/gpopt/translate/CQueryMutators.h
  src/include/gpopt/translate/CTranslatorDXLToPlStmt.h
  src/include/gpopt/translate/CTranslatorDXLToScalar.h
  src/include/gpopt/translate/CTranslatorQueryToDXL.h
  src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
  src/include/gpopt/translate/CTranslatorScalarToDXL.h
  src/include/gpopt/translate/CTranslatorUtils.h
  src/include/gpopt/utils/CConstExprEvaluatorProxy.h
  src/include/gpopt/utils/COptClient.h
  src/include/gpopt/utils/COptServer.h
  src/include/gpopt/utils/COptTasks.h
Labels: area: gporca, version: 5X_STABLE
