Repository greenplum-db/gpdb, pull requests merged in 2019-03, with the labels that each got.

#7102 Fix 5X storage test failure
  src/backend/access/appendonly/aosegfiles.c
Labels: version: 5X_STABLE

#7082 Skip analyzing root partitions by default in analyzedb (5X_STABLE)
  gpMgmt/bin/analyzedb
  gpMgmt/test/behave/mgmt_utils/analyzedb.feature
Labels: version: 5X_STABLE

#6963 ORCA: Updating subquery plans in ICG expected files
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/test/regress/expected/notin_optimizer.out
  src/test/regress/expected/subselect_gp_optimizer.out
Labels: area: gporca

#7144 Bump ORCA version to 3.29.0, updating ICG expected files
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/test/regress/expected/subselect_gp_optimizer.out
Labels: version: 5X_STABLE

#7156 gpaddmirrors increase error message clarity
  gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
  gpMgmt/bin/gppylib/operations/test/unit/test_unit_buildMirrorSegments.py
Labels: topic: cluster mgmt, type: enhancement

#7095 Fix dependencies issue in GPPKG utility (5X_STABLE)
  gpMgmt/bin/gppylib/operations/package.py
Labels: version: 5X_STABLE

#7213 Bump ORCA version to 3.30.0 (6X_STABLE)
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: version: 6X_STABLE

#7198 Remove gpaddmirrors from NON_PRODUCTION_FILES.txt
  gpAux/releng/NON_PRODUCTION_FILES.txt
Labels: topic: cluster mgmt, type: bug, version: 6X_STABLE

#7214 Bump ORCA version to 3.30.0 (5X_STABLE)
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: version: 5X_STABLE

#7215 6X_STABLE Backport: Remove gpaddmirrors from NON_PRODUCTION_FILES.txt
  gpAux/releng/NON_PRODUCTION_FILES.txt
Labels: version: 6X_STABLE

#7161 5x gpaddmirrors fix error message wording
  gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
  gpMgmt/bin/gppylib/operations/test/unit/test_unit_buildMirrorSegments.py
Labels: topic: cluster mgmt, type: bug, type: enhancement, version: 5X_STABLE

#7219 6X: Do not install gpMgmt/bin/README files
  gpMgmt/Makefile
Labels: version: 6X_STABLE

#7216 Backport to 6X: Fix two log-rotation bugs
  src/backend/postmaster/syslogger.c
Labels: version: 6X_STABLE

#7130 gpcheckcat: correctly display 'None' oids in summary
  gpMgmt/bin/gpcheckcat
  gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckcat.py
Labels: version: 5X_STABLE

#7236 5X_STABLE Backport: logfile_rotate(): correct multiple calls to set_next_rotation_time()
  src/backend/postmaster/syslogger.c
Labels: version: 5X_STABLE

#7233 Warn user replication slots will be created on current segment only.
  src/backend/replication/slotfuncs.c
  src/test/regress/expected/replication_slots.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/replication_slots.sql
Labels: version: 6X_STABLE

#7202 Add gpperfmon test for all supported platforms (#7174)
  concourse/pipelines/gen_pipeline.py
  concourse/pipelines/gpdb_master-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
  concourse/tasks/run_behave_on_ccp_cluster.yml
  gpMgmt/test/behave/mgmt_utils/gpperfmon.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: version: 6X_STABLE

#7221 6X:Remove useless FIXME in InitPlan
  src/backend/executor/execMain.c
Labels: version: 6X_STABLE

#7277 6X_STABLE: Bump ORCA version to 3.32.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: version: 6X_STABLE

#7278 5X_STABLE: Bump ORCA version to 3.32.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: version: 5X_STABLE
