Repository greenplum-db/gpdb, pull requests merged in 2019-12, with the labels that each got.

#9056 Fix dispatch of SET TIME ZONE INTERVAL statement.
  src/backend/utils/misc/guc.c
  src/test/regress/expected/guc_gp.out
  src/test/regress/sql/guc_gp.sql
Labels: needs: backport

#9149 6X Backport: Fix dispatch of SET TIME ZONE INTERVAL statement.
  src/backend/utils/misc/guc.c
  src/test/regress/expected/guc_gp.out
  src/test/regress/sql/guc_gp.sql
Labels: version: 6X_STABLE

#9135 Compile server against PR in 5X PR Pipeline
  concourse/pipelines/pr_pipeline.yml
Labels: version: 5X_STABLE

#9119 6X: COPY: remove redundant delimiter checking
  contrib/file_fdw/output/file_fdw.source
  src/backend/commands/copy.c
  src/bin/gpfdist/regress/output/exttab1.source
  src/bin/gpfdist/regress/output/gpfdist2.source
  src/bin/gpfdist/remote_regress/output/exttab1.source
  src/bin/gpfdist/remote_regress/output/gpfdist2.source
  src/test/regress/input/external_table.source
  src/test/regress/output/external_table.source
Labels: version: 6X_STABLE

#9163 Reinstate elog(ERROR,..) in pg_get_indexdef_worker()
  src/backend/utils/adt/ruleutils.c
Labels: type: fixme

#9047 Update the explain for Dynamic Bitmap Index Scans
  src/backend/commands/explain.c
  src/test/regress/expected/bfv_index_optimizer.out
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, topic: gporca, version: 7X_ALPHA

#9189 Bump ORCA version to 3.85, add ICG tests for ORCA with gpexpand
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#9188 Bump ORCA version to 3.85, add ICG tests for ORCA with gpexpand
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, topic: gporca, version: 7X_ALPHA

#9161 Call TransactionIdDidCommit after XidInMVCCSnapshot only if needed
  src/backend/utils/time/tqual.c
  src/include/utils/tqual.h
Labels: type: fixme

#9187 Allow quoted identifiers in gp_dist_random() input
  src/backend/parser/parse_clause.c
  src/test/regress/expected/gpdist.out
  src/test/regress/expected/gpdist_optimizer.out
  src/test/regress/sql/gpdist.sql
Labels: needs: backport

#9150 Remove redundant Result nodes from ORCA-generated plans.
  src/backend/cdb/cdbplan.c
  src/backend/optimizer/plan/createplan.c
  src/backend/optimizer/plan/orca.c
  src/test/regress/expected/DML_over_joins_optimizer.out
  src/test/regress/expected/aggregates_optimizer.out
  src/test/regress/expected/bfv_aggregate_optimizer.out
  src/test/regress/expected/bfv_catalog_optimizer.out
  src/test/regress/expected/bfv_dml_optimizer.out
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/expected/bfv_subquery_optimizer.out
  src/test/regress/expected/bitmapops_optimizer.out
  src/test/regress/expected/create_am_optimizer.out
  src/test/regress/expected/create_index_optimizer.out
  src/test/regress/expected/direct_dispatch_optimizer.out
  src/test/regress/expected/dpe_optimizer.out
  src/test/regress/expected/eagerfree_optimizer.out
  src/test/regress/expected/equivclass_optimizer.out
  src/test/regress/expected/gist_optimizer.out
  src/test/regress/expected/gp_dqa_optimizer.out
  src/test/regress/expected/gp_explain_optimizer.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/indexjoin_optimizer.out
  src/test/regress/expected/inherit_optimizer.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/expected/join_optimizer.out
  src/test/regress/expected/limit_optimizer.out
  src/test/regress/expected/matview_optimizer.out
  src/test/regress/expected/notin_optimizer.out
  src/test/regress/expected/olap_plans_optimizer.out
  src/test/regress/expected/olap_window_seq_optimizer.out
  src/test/regress/expected/pg_lsn_optimizer.out
  src/test/regress/expected/plpgsql_optimizer.out
  src/test/regress/expected/qp_correlated_query_optimizer.out
  src/test/regress/expected/qp_misc_jiras_optimizer.out
  src/test/regress/expected/qp_orca_fallback_optimizer.out
  src/test/regress/expected/qp_subquery_optimizer.out
  src/test/regress/expected/qp_union_intersect_optimizer.out
  src/test/regress/expected/select_distinct_optimizer.out
  src/test/regress/expected/select_parallel_optimizer.out
  src/test/regress/expected/subselect_gp_indexes_optimizer.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/expected/subselect_optimizer.out
  src/test/regress/expected/union_optimizer.out
  src/test/regress/expected/updatable_views_optimizer.out
  src/test/regress/expected/update_gp_optimizer.out
  src/test/regress/expected/update_optimizer.out
  src/test/regress/expected/window_optimizer.out
Labels: area: gporca, topic: gporca

#9190 Add check and test for upgrading table with unique/primary constraint
  contrib/pg_upgrade/check_gp.c
  contrib/pg_upgrade/test/integration/expected/upgraded_different_name_index_backed_constraint.out
  contrib/pg_upgrade/test/integration/gpdb5_schedule
  contrib/pg_upgrade/test/integration/gpdb6_schedule
  contrib/pg_upgrade/test/integration/input/different_name_index_backed_constraint.source
  contrib/pg_upgrade/test/integration/output/different_name_index_backed_constraint.source
  contrib/pg_upgrade/test/integration/sql/upgraded_different_name_index_backed_constraint.sql
Labels: topic: upgrade

#9215 packcore: be more verbose on test failures
  src/test/isolation2/expected/packcore.out
  src/test/isolation2/sql/packcore.sql
Labels: needs: backport, type: dev environment improvement

#9227 Add upgrade test for user defined aggregates
  contrib/pg_upgrade/test/integration/expected/upgraded_user_defined_aggregates.out
  contrib/pg_upgrade/test/integration/expected/user_defined_aggregates.out
  contrib/pg_upgrade/test/integration/gpdb5_schedule
  contrib/pg_upgrade/test/integration/gpdb6_schedule
  contrib/pg_upgrade/test/integration/sql/upgraded_user_defined_aggregates.sql
  contrib/pg_upgrade/test/integration/sql/user_defined_aggregates.sql
Labels: topic: upgrade

#9162 Add logic to pg_get_viewdef() to handle gp_dist_random
  src/backend/utils/adt/ruleutils.c
  src/test/regress/expected/gp_create_view.out
  src/test/regress/sql/gp_create_view.sql
Labels: needs: backport

#9213 Harden analyze rootpartition to merge stats if relpages is incorrect
  src/backend/commands/analyzeutils.c
  src/test/regress/expected/incremental_analyze.out
  src/test/regress/sql/incremental_analyze.sql
Labels: area: gporca, topic: gporca

#9228 5X: Harden analyze rootpartition to merge stats if relpages is incorrect
  src/backend/commands/analyzeutils.c
  src/test/regress/expected/incremental_analyze.out
  src/test/regress/sql/incremental_analyze.sql
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#9199 Deduplicate plan_node_id
  gpAux/gpperfmon/src/gpmon/gpsmon.c
  src/backend/cdb/cdbmutate.c
  src/backend/optimizer/plan/planner.c
  src/include/cdb/cdbmutate.h
  src/include/gpmon/gpmon.h
  src/include/nodes/plannodes.h
Labels: type: fixme

#9050 Fix normalization of queries with window functions
  src/backend/gpopt/translate/CQueryMutators.cpp
  src/include/gpopt/translate/CQueryMutators.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, topic: gporca, type: bug

#9205 Fix normalization of queries with window functions
  src/backend/gpopt/translate/CQueryMutators.cpp
  src/include/gpopt/translate/CQueryMutators.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#9235 Fix binary swap test for pg_get_viewdef() fix
  src/test/binary_swap/test_binary_swap.sh
  src/test/binary_swap/test_binary_swap_pre.sql
Labels: version: 6X_STABLE

#9248 6X backport: Rewrite test case xlog files
  src/backend/access/transam/test/Makefile
  src/backend/access/transam/test/xlog_test.c
  src/backend/access/transam/xlog.c
  src/backend/utils/misc/guc.c
  src/bin/pg_rewind/sql/run_test.sh
  src/test/walrep/Makefile
  src/test/walrep/expected/missing_xlog.out
  src/test/walrep/sql/missing_xlog.sql
Labels: backport, version: 6X_STABLE

#9259 Make plan_node_id assignments in ORCA 0-based
  src/backend/gpopt/utils/COptTasks.cpp
Labels: area: gporca, topic: gporca

#9276 Set the default value of wal_keep_segments to 5
  src/backend/utils/misc/guc.c
  src/test/walrep/sql/missing_xlog.sql
Labels: version: 6X_STABLE

#9295 6x: Fix add partition relops null pointer issue.
  src/backend/cdb/cdbpartition.c
  src/test/regress/expected/partition1.out
  src/test/regress/sql/partition1.sql
Labels: version: 6X_STABLE

#9296 5x: Fix add partition relops null pointer issue.
  src/backend/cdb/cdbpartition.c
  src/test/regress/expected/partition1.out
  src/test/regress/sql/partition1.sql
Labels: version: 5X_STABLE

#9300 6X: Fix `DELIMETER 'OFF'` validate error for external table.
  src/backend/commands/copy.c
  src/bin/gpfdist/regress/output/exttab1.source
  src/bin/gpfdist/regress/output/gpfdist2.source
  src/test/isolation2/input/external_table.source
  src/test/isolation2/output/external_table.source
Labels: version: 6X_STABLE

#9301 icw: fix flaky alter_db_set_tablespace
  src/test/regress/input/alter_db_set_tablespace.source
  src/test/regress/output/alter_db_set_tablespace.source
Labels: needs: backport, topic: continuous integration, type: dev environment improvement, version: 7X_ALPHA

#9309 6X: icw: fix flaky alter_db_set_tablespace
  src/test/regress/input/alter_db_set_tablespace.source
  src/test/regress/output/alter_db_set_tablespace.source
Labels: backport, topic: continuous integration, type: dev environment improvement, version: 6X_STABLE

#9310 zstd: check for OOM when creating {C,D}Ctx
  gpcontrib/zstd/zstd_compression.c
  src/backend/storage/file/buffile.c
  src/include/storage/gp_compress.h
Labels: needs: backport

#9315 6X: zstd: check for OOM when creating {C,D}Ctx
  gpcontrib/zstd/zstd_compression.c
  src/backend/storage/file/buffile.c
  src/include/storage/gp_compress.h
Labels: backport, version: 6X_STABLE

#9324 (5x)Sanity check update/delete to prevent potential data corruption
  src/backend/executor/execMain.c
  src/backend/executor/nodeDML.c
  src/include/nodes/execnodes.h
  src/test/isolation2/expected/modify_table_data_corrupt.out
  src/test/isolation2/expected/modify_table_data_corrupt_optimizer.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/modify_table_data_corrupt.sql
Labels: version: 5X_STABLE
