Repository greenplum-db/gpdb, pull requests merged in 2019-10, with the labels that each got.

#8741 Bump ORCA version to 3.73.0 (5X)
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#8643 Introduce PallocMemoryPool for use in GPORCA
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  src/backend/commands/explain_gp.c
  src/backend/gpopt/CGPOptimizer.cpp
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/utils/CMemoryPoolPalloc.cpp
  src/backend/gpopt/utils/CMemoryPoolPallocManager.cpp
  src/backend/gpopt/utils/COptTasks.cpp
  src/backend/gpopt/utils/Makefile
  src/backend/optimizer/plan/planner.c
  src/backend/utils/init/postinit.c
  src/backend/utils/mmgr/Makefile
  src/backend/utils/mmgr/ext_alloc.c
  src/backend/utils/mmgr/mcxt.c
  src/backend/utils/mmgr/memaccounting.c
  src/backend/utils/mmgr/test/memaccounting_test.c
  src/include/gpopt/gpdbwrappers.h
  src/include/gpopt/utils/CMemoryPoolPalloc.h
  src/include/gpopt/utils/CMemoryPoolPallocManager.h
  src/include/utils/ext_alloc.h
  src/include/utils/memaccounting.h
  src/include/utils/memutils.h
Labels: area: gporca, type: maintenance

#8747 5X: Introduce PallocMemoryPool for use in GPORCA
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/backend/cdb/cdbexplain.c
  src/backend/gpopt/CGPOptimizer.cpp
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/utils/CMemoryPoolPalloc.cpp
  src/backend/gpopt/utils/CMemoryPoolPallocManager.cpp
  src/backend/gpopt/utils/COptTasks.cpp
  src/backend/gpopt/utils/Makefile
  src/backend/optimizer/plan/planner.c
  src/backend/utils/init/postinit.c
  src/backend/utils/mmgr/Makefile
  src/backend/utils/mmgr/ext_alloc.c
  src/backend/utils/mmgr/mcxt.c
  src/backend/utils/mmgr/memaccounting.c
  src/backend/utils/mmgr/test/memaccounting_test.c
  src/include/gpopt/gpdbwrappers.h
  src/include/gpopt/utils/CMemoryPoolPalloc.h
  src/include/gpopt/utils/CMemoryPoolPallocManager.h
  src/include/utils/ext_alloc.h
  src/include/utils/memaccounting.h
  src/include/utils/memutils.h
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#8716 Add pg_upgrade integration test of partitioned heap tables
  contrib/pg_upgrade/test/integration/greenplum_five_to_greenplum_six_upgrade_test_suite.c
  contrib/pg_upgrade/test/integration/scenarios/partitioned_heap_table.c
  contrib/pg_upgrade/test/integration/scenarios/partitioned_heap_table.h
Labels: version: 6X_STABLE

#8779 Add pg_upgrade integration test for partitioned ao tables
  contrib/pg_upgrade/test/integration/greenplum_five_to_greenplum_six_upgrade_test_suite.c
  contrib/pg_upgrade/test/integration/scenarios/partitioned_ao_table.c
  contrib/pg_upgrade/test/integration/scenarios/partitioned_ao_table.h
Labels: topic: upgrade

#8738 Bump ORCA version to 3.76, send btree indexes on AO tables as type btree
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/test/regress/expected/bitmapops_optimizer.out
  src/test/regress/expected/co_nestloop_idxscan.out
  src/test/regress/expected/co_nestloop_idxscan_optimizer.out
  src/test/regress/sql/co_nestloop_idxscan.sql
Labels: area: gporca, topic: gporca

#8740 5X: Bump ORCA version to 3.76, send btree indexes on AO tables as type btree
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/test/regress/expected/co_nestloop_idxscan.out
  src/test/regress/expected/co_nestloop_idxscan_optimizer.out
  src/test/regress/sql/co_nestloop_idxscan.sql
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#8730 gdd: ensure the session orders on segments
  src/test/isolation2/expected/gdd/dist-deadlock-01.out
  src/test/isolation2/expected/gdd/dist-deadlock-04.out
  src/test/isolation2/expected/gdd/dist-deadlock-05.out
  src/test/isolation2/expected/gdd/dist-deadlock-06.out
  src/test/isolation2/expected/gdd/dist-deadlock-07.out
  src/test/isolation2/expected/gdd/dist-deadlock-102.out
  src/test/isolation2/expected/gdd/dist-deadlock-103.out
  src/test/isolation2/expected/gdd/dist-deadlock-104.out
  src/test/isolation2/expected/gdd/dist-deadlock-106.out
  src/test/isolation2/expected/gdd/local-deadlock-03.out
  src/test/isolation2/expected/gdd/non-lock-105.out
  src/test/isolation2/sql/gdd/dist-deadlock-01.sql
  src/test/isolation2/sql/gdd/dist-deadlock-04.sql
  src/test/isolation2/sql/gdd/dist-deadlock-05.sql
  src/test/isolation2/sql/gdd/dist-deadlock-06.sql
  src/test/isolation2/sql/gdd/dist-deadlock-07.sql
  src/test/isolation2/sql/gdd/dist-deadlock-102.sql
  src/test/isolation2/sql/gdd/dist-deadlock-103.sql
  src/test/isolation2/sql/gdd/dist-deadlock-104.sql
  src/test/isolation2/sql/gdd/dist-deadlock-106.sql
  src/test/isolation2/sql/gdd/local-deadlock-03.sql
  src/test/isolation2/sql/gdd/non-lock-105.sql
  src/test/isolation2/sql/gdd/non-lock-107.sql
  src/test/isolation2/sql/gdd/non-lock-108.sql
Labels: topic: global deadlock detector

#8796 6X: gdd: ensure the session orders on segments
  src/test/isolation2/expected/gdd/dist-deadlock-01.out
  src/test/isolation2/expected/gdd/dist-deadlock-04.out
  src/test/isolation2/expected/gdd/dist-deadlock-05.out
  src/test/isolation2/expected/gdd/dist-deadlock-06.out
  src/test/isolation2/expected/gdd/dist-deadlock-07.out
  src/test/isolation2/expected/gdd/dist-deadlock-102.out
  src/test/isolation2/expected/gdd/dist-deadlock-103.out
  src/test/isolation2/expected/gdd/dist-deadlock-104.out
  src/test/isolation2/expected/gdd/dist-deadlock-106.out
  src/test/isolation2/expected/gdd/local-deadlock-03.out
  src/test/isolation2/expected/gdd/non-lock-105.out
  src/test/isolation2/sql/gdd/dist-deadlock-01.sql
  src/test/isolation2/sql/gdd/dist-deadlock-04.sql
  src/test/isolation2/sql/gdd/dist-deadlock-05.sql
  src/test/isolation2/sql/gdd/dist-deadlock-06.sql
  src/test/isolation2/sql/gdd/dist-deadlock-07.sql
  src/test/isolation2/sql/gdd/dist-deadlock-102.sql
  src/test/isolation2/sql/gdd/dist-deadlock-103.sql
  src/test/isolation2/sql/gdd/dist-deadlock-104.sql
  src/test/isolation2/sql/gdd/dist-deadlock-106.sql
  src/test/isolation2/sql/gdd/local-deadlock-03.sql
  src/test/isolation2/sql/gdd/non-lock-105.sql
  src/test/isolation2/sql/gdd/non-lock-107.sql
  src/test/isolation2/sql/gdd/non-lock-108.sql
Labels: topic: global deadlock detector, version: 6X_STABLE

#8813 Bump ORCA version to 3.77.0
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
Labels: area: gporca, topic: gporca

#8814 5X: Bump ORCA version to 3.77.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#8836 (6X) Put checking dk_opfamily ahead when test equaility for locus.
  src/backend/cdb/cdbpathlocus.c
Labels: version: 6X_STABLE

#8849 5X: ic: tcp: init incoming conns before outgoing conns
  src/backend/cdb/motion/ic_tcp.c
Labels: version: 5X_STABLE

#8848 6X: ic: tcp: init incoming conns before outgoing conns
  src/backend/cdb/motion/ic_tcp.c
Labels: version: 6X_STABLE

#8752 Optimize CMemoryPoolPalloc for use with CMemoryPool in ORCA
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  src/backend/gpopt/utils/CMemoryPoolPalloc.cpp
  src/backend/gpopt/utils/CMemoryPoolPallocManager.cpp
  src/include/gpopt/utils/CMemoryPoolPalloc.h
  src/include/gpopt/utils/CMemoryPoolPallocManager.h
Labels: area: gporca, topic: gporca

#8867 Bump ORCA version to 3.78.0, Optimize CMemoryPoolPalloc in ORCA
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/backend/gpopt/utils/CMemoryPoolPalloc.cpp
  src/backend/gpopt/utils/CMemoryPoolPallocManager.cpp
  src/include/gpopt/utils/CMemoryPoolPalloc.h
  src/include/gpopt/utils/CMemoryPoolPallocManager.h
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#8802 Bump ORCA version to 3.79, update ICG answer file
  src/test/regress/expected/join_gp_optimizer.out
Labels: area: gporca, topic: gporca

#8803 5X: Bump ORCA version to 3.79, update ICG answer file
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/test/regress/expected/join_gp_optimizer.out
Labels: area: gporca, topic: gporca

#8846 Add upgrade happy-path test of partition tables with dropped columns
  contrib/pg_upgrade/test/integration/greenplum_five_to_greenplum_six_upgrade_test_suite.c
  contrib/pg_upgrade/test/integration/scenarios/partitioned_heap_table_with_a_dropped_column.c
  contrib/pg_upgrade/test/integration/scenarios/partitioned_heap_table_with_a_dropped_column.h
Labels: topic: upgrade, version: 6X_STABLE

#8874 [6X Backport] Consider non direct dispatch cost for cached plan.
  src/backend/utils/cache/plancache.c
  src/test/regress/expected/direct_dispatch.out
  src/test/regress/expected/direct_dispatch_optimizer.out
  src/test/regress/sql/direct_dispatch.sql
Labels: version: 6X_STABLE

#8890 [Backport]Fix direct dispatch answer file to use one-phase commit message.
  src/test/regress/expected/direct_dispatch.out
  src/test/regress/expected/direct_dispatch_optimizer.out
Labels: version: 6X_STABLE

#8888 Remove QP_memory-accounting job from 5X pipeline
  concourse/pipelines/5X_STABLE-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: version: 5X_STABLE

#8895 GPload: change metadata query SQL to improvement performance
  gpMgmt/bin/gpload.py
Labels: version: 5X_STABLE

#8897 6X backport: Fix heap-use-after-free in gp_inject_fault()
  gpcontrib/gp_inject_fault/gp_inject_fault.c
Labels: backport, version: 6X_STABLE

#8824 Add missing break and fallthrough comment within switch-case
  gpAux/extensions/gpcloud/lib/http_parser.cpp
  src/backend/access/hash/hashfunc.c
  src/backend/bootstrap/bootstrap.c
  src/backend/catalog/pg_compression.c
  src/backend/cdb/cdbexplain.c
  src/backend/cdb/cdbfilerepmirror.c
  src/backend/cdb/cdbfilerepprimary.c
  src/backend/cdb/cdbfilerepprimaryack.c
  src/backend/cdb/cdbfilerepservice.c
  src/backend/cdb/cdbgroup.c
  src/backend/cdb/cdbplan.c
  src/backend/cdb/cdbtm.c
  src/backend/cdb/dispatcher/cdbdisp_dtx.c
  src/backend/commands/tablecmds.c
  src/backend/commands/tablespace.c
  src/backend/executor/execAmi.c
  src/backend/executor/nodeAgg.c
  src/backend/regex/regc_lex.c
  src/backend/regex/regcomp.c
  src/backend/replication/walsender.c
  src/backend/storage/ipc/procarray.c
  src/backend/tcop/postgres.c
  src/backend/utils/adt/date.c
  src/backend/utils/adt/datetime.c
  src/backend/utils/adt/formatting.c
  src/backend/utils/adt/numeric.c
  src/backend/utils/adt/ruleutils.c
  src/backend/utils/adt/timestamp.c
  src/backend/utils/datumstream/datumstream.c
  src/backend/utils/error/faultinject.c
  src/backend/utils/hyperloglog/gp_hyperloglog.c
  src/backend/utils/misc/faultinjector.c
  src/backend/utils/misc/guc.c
  src/backend/utils/resscheduler/resqueue.c
  src/backend/utils/resscheduler/resscheduler.c
  src/backend/utils/sort/tuplestore.c
  src/bin/initdb/initdb.c
  src/bin/pg_basebackup/pg_basebackup.c
  src/interfaces/ecpg/pgtypeslib/interval.c
  src/interfaces/ecpg/preproc/ecpg.c
  src/interfaces/libpq/fe-secure.c
  src/pl/plpgsql/src/pl_exec.c
  src/test/regress/pg_regress.c
Labels: version: 5X_STABLE

#8876 Improve analyzedb performance on partitioned tables
  gpMgmt/bin/analyzedb
  src/backend/commands/vacuum.c
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/include/utils/unsync_guc_name.h
Labels: area: gporca, topic: analyze, topic: gporca, version: 7X_ALPHA

#8912 Improve analyzedb performance on partitioned tables
  gpMgmt/bin/analyzedb
  src/backend/commands/vacuum.c
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
Labels: area: gporca, topic: analyze, topic: gporca, version: 5X_STABLE

#8809 6X_STABLE: Enable -Wimplicit-fallthrough by default if GCC >=7
  configure
  configure.in
  gpcontrib/gpcloud/lib/http_parser.cpp
  gpcontrib/gpmapreduce/Makefile
  gpcontrib/orafce/Makefile
  src/backend/Makefile
  src/backend/access/hash/hashfunc.c
  src/backend/access/transam/xact.c
  src/backend/catalog/pg_compression.c
  src/backend/cdb/cdbgroup.c
  src/backend/cdb/cdbplan.c
  src/backend/cdb/cdbtm.c
  src/backend/cdb/dispatcher/cdbdisp_dtx.c
  src/backend/commands/tablecmds.c
  src/backend/executor/nodeAgg.c
  src/backend/fts/ftsprobe.c
  src/backend/nodes/outfast.c
  src/backend/nodes/readfast.c
  src/backend/optimizer/prep/prepsecurity.c
  src/backend/regex/regc_lex.c
  src/backend/regex/regcomp.c
  src/backend/storage/file/buffile.c
  src/backend/tcop/postgres.c
  src/backend/utils/adt/datetime.c
  src/backend/utils/adt/formatting.c
  src/backend/utils/adt/numeric.c
  src/backend/utils/adt/ruleutils.c
  src/backend/utils/adt/timestamp.c
  src/backend/utils/datumstream/datumstream.c
  src/backend/utils/error/faultinject.c
  src/backend/utils/hyperloglog/gp_hyperloglog.c
  src/backend/utils/misc/guc.c
  src/backend/utils/resscheduler/resscheduler.c
  src/backend/utils/sort/tuplestore.c
  src/bin/initdb/initdb.c
  src/bin/pg_basebackup/pg_basebackup.c
  src/bin/pg_rewind/parsexlog.c
  src/interfaces/ecpg/pgtypeslib/interval.c
  src/interfaces/ecpg/preproc/ecpg.c
  src/interfaces/libpq/fe-secure.c
  src/pl/plpgsql/src/pl_exec.c
Labels: version: 6X_STABLE

#8909 Add upgrade test for subpartitioned ao tables with multiple ao segments
  contrib/pg_upgrade/test/integration/greenplum_five_to_greenplum_six_upgrade_test_suite.c
  contrib/pg_upgrade/test/integration/scenarios/partitioned_ao_table.c
  contrib/pg_upgrade/test/integration/scenarios/partitioned_ao_table.h
  contrib/pg_upgrade/test/integration/utilities/query-helpers.c
  contrib/pg_upgrade/test/integration/utilities/query-helpers.h
Labels: topic: upgrade

#8931 Bump ORCA version to v3.80.0
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  src/test/regress/expected/qp_misc_jiras.out
  src/test/regress/expected/qp_misc_jiras_optimizer.out
  src/test/regress/sql/qp_misc_jiras.sql
Labels: area: gporca, topic: gporca

#8930 Bump ORCA version to v3.80.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/test/regress/expected/qp_misc_jiras.out
  src/test/regress/expected/qp_misc_jiras_optimizer.out
  src/test/regress/sql/qp_misc_jiras.sql
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#8908 Elevate force_mirrors_to_catch_up() to gp_inject_fault
  gpcontrib/gp_inject_fault/gp_inject_fault--1.0.sql
  gpcontrib/gp_inject_fault/gp_inject_fault.c
  src/test/regress/expected/psql_gp_commands.out
  src/test/regress/input/alter_db_set_tablespace.source
  src/test/regress/input/createdb.source
  src/test/regress/input/gp_tablespace.source
  src/test/regress/input/gp_tablespace_with_faults.source
  src/test/regress/output/alter_db_set_tablespace.source
  src/test/regress/output/createdb.source
  src/test/regress/output/gp_tablespace.source
  src/test/regress/output/gp_tablespace_with_faults.source
  src/test/regress/regress_gp.c
Labels: needs: backport

#8843 Change PORT_BASE semantics for demo cluster (6X_STABLE)
  README.md
  concourse/scripts/ic_gpdb_remote_windows.bat
  contrib/pg_upgrade/test_gpdb.sh
  gpAux/gpdemo/Makefile
  gpAux/gpdemo/README
  gpAux/gpdemo/demo_cluster.sh
  gpAux/gpdemo/probe_config.sh
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/replication_slots_utils.py
  src/test/regress/GNUmakefile
  src/tools/docker/README.md
Labels: version: 6X_STABLE

#8935 Fix ALTER EXTENSION ADD/DROP don't be executed on QE
  src/backend/commands/extension.c
Labels: needs: backport

#8899 Remove icw_gporca_centos6_gpos_memory job from pipeline
  concourse/pipelines/README.md
  concourse/pipelines/gen_pipeline.py
  concourse/pipelines/gpdb_master-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: area: gporca

#8936 Allow the cluster shutdown in some cases when dtx recovery hang happens
  src/backend/cdb/cdbutil.c
Labels: backport

#8940 6X Backport: Fix various issues in Gang management (#8893)
  src/backend/cdb/cdbutil.c
  src/backend/cdb/dispatcher/cdbdisp.c
  src/backend/cdb/dispatcher/cdbdisp_query.c
  src/backend/commands/copy.c
  src/backend/executor/execUtils.c
  src/include/cdb/cdbdisp.h
  src/test/regress/expected/guc_gp.out
  src/test/regress/input/dispatch.source
  src/test/regress/output/dispatch.source
  src/test/regress/sql/guc_gp.sql
Labels: backport, version: 6X_STABLE

#8948 Fix upgrade integration test ports
  contrib/pg_upgrade/test/integration/configuration/gpdb6-env.sh
  contrib/pg_upgrade/test/integration/utilities/gpdb6-cluster.c
Labels: topic: upgrade

#8959 Add a plpython test case for upgrade from 5X to 6X
  contrib/pg_upgrade/test/integration/greenplum_five_to_greenplum_six_upgrade_test_suite.c
  contrib/pg_upgrade/test/integration/scenarios/pl_function.c
  contrib/pg_upgrade/test/integration/scenarios/pl_function.h
  contrib/pg_upgrade/test/integration/scenarios/plpgsql_function.h
Labels: topic: upgrade

#8965 Enable python extensions on the upgrade CI
  contrib/pg_upgrade/ci/run-test-as-gpadmin.sh
Labels: topic: upgrade
