Repository greenplum-db/gpdb, pull requests merged in 2020-02, with the labels that each got.

#9491 6X: ci: dump icw dbs with the planner job
  concourse/pipelines/gpdb_6X_STABLE-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
  concourse/scripts/dumpdb.bash
  concourse/tasks/ic_gpdb_binary_swap.yml
Labels: topic: continuous integration, version: 6X_STABLE

#9527 (backport to 6X) Fix flaky test case gdd/end
  src/test/isolation2/expected/ao_same_trans_truncate_crash.out
  src/test/isolation2/expected/crash_recovery_dtm.out
  src/test/isolation2/expected/fts_errors.out
  src/test/isolation2/expected/gdd/end.out
  src/test/isolation2/expected/gdd/prepare.out
  src/test/isolation2/expected/segwalrep/commit_blocking.out
  src/test/isolation2/expected/segwalrep/dtm_recovery_on_standby.out
  src/test/isolation2/expected/segwalrep/failover_with_many_records.out
  src/test/isolation2/expected/segwalrep/fts_unblock_primary.out
  src/test/isolation2/expected/segwalrep/mirror_promotion.out
  src/test/isolation2/expected/uao_crash_compaction_column.out
  src/test/isolation2/helpers/server_helpers.sql
Labels: backport, version: 6X_STABLE

#9440 Better cardinality estimation for citext in ORCA
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
  src/backend/gpopt/translate/CTranslatorUtils.cpp
  src/include/gpopt/gpdbwrappers.h
  src/include/gpopt/translate/CTranslatorScalarToDXL.h
  src/include/utils/builtins.h
Labels: area: gporca, topic: gporca

#9541 BACKPORT 6X: Skip column acl check in gp_acquire_sample_rows
  src/backend/commands/analyze.c
  src/test/regress/expected/analyze.out
  src/test/regress/expected/incremental_analyze.out
  src/test/regress/sql/analyze.sql
Labels: version: 6X_STABLE

#9492 ci: do not generate ubuntu jobs if not specified
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: topic: continuous integration, type: dev environment improvement

#9547 Add experimental value for `optimizer_cost_model`
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  src/backend/gpopt/config/CConfigParamMapping.cpp
  src/backend/gpopt/utils/COptTasks.cpp
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/test/regress/expected/bfv_index.out
  src/test/regress/expected/bfv_index_optimizer.out
  src/test/regress/sql/bfv_index.sql
Labels: area: gporca, topic: gporca

#9548 5X: Add experimental value for `optimizer_cost_model`
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/backend/gpopt/config/CConfigParamMapping.cpp
  src/backend/gpopt/utils/COptTasks.cpp
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/test/regress/expected/bfv_index.out
  src/test/regress/expected/bfv_index_optimizer.out
  src/test/regress/sql/bfv_index.sql
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#9585 6X: Revert function name of getDtxStartTime()
  src/backend/cdb/cdbdtxcontextinfo.c
  src/backend/cdb/cdbtm.c
  src/backend/utils/gpmon/gpmon.c
  src/include/cdb/cdbtm.h
Labels: version: 6X_STABLE

#9614 BACKPORT 6X: Introduce execute on initplan option for function (#9542)
  src/backend/commands/functioncmds.c
  src/backend/executor/nodeFunctionscan.c
  src/backend/executor/nodeMaterial.c
  src/backend/executor/nodeShareInputScan.c
  src/backend/executor/nodeSubplan.c
  src/backend/nodes/copyfuncs.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfast.c
  src/backend/optimizer/plan/createplan.c
  src/backend/optimizer/plan/planagg.c
  src/backend/optimizer/plan/planmain.c
  src/backend/optimizer/plan/subselect.c
  src/backend/optimizer/util/pathnode.c
  src/backend/optimizer/util/walkers.c
  src/backend/parser/gram.y
  src/backend/parser/parse_target.c
  src/backend/storage/file/buffile.c
  src/backend/storage/file/fd.c
  src/backend/utils/sort/tuplestorenew.c
  src/bin/pg_dump/pg_dump.c
  src/include/catalog/pg_proc.h
  src/include/nodes/execnodes.h
  src/include/nodes/plannodes.h
  src/include/nodes/primnodes.h
  src/include/optimizer/subselect.h
  src/include/parser/kwlist.h
  src/include/storage/buffile.h
  src/include/storage/fd.h
  src/include/utils/tuplestorenew.h
  src/test/regress/expected/function_extensions.out
  src/test/regress/expected/function_extensions_optimizer.out
  src/test/regress/parallel_schedule
  src/test/regress/sql/function_extensions.sql
Labels: version: 6X_STABLE

#9570 tuplestore: support backward scanning of spill files
  src/backend/utils/sort/tuplestore.c
  src/test/regress/expected/misc_jiras.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/misc_jiras.sql
Labels: area: server, needs: backport, type: bug

#9571 Fix data reorganization when gp_use_legacy_hashops is true
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CContextDXLToPlStmt.cpp
  src/backend/parser/analyze.c
  src/include/gpopt/gpdbwrappers.h
  src/test/regress/expected/gpdist_legacy_opclasses.out
  src/test/regress/expected/gpdist_legacy_opclasses_optimizer.out
  src/test/regress/sql/gpdist_legacy_opclasses.sql
Labels: area: server, needs: backport, type: bug

#9645 6X: Fix data reorganization when gp_use_legacy_hashops is true
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CContextDXLToPlStmt.cpp
  src/backend/parser/analyze.c
  src/include/gpopt/gpdbwrappers.h
  src/test/regress/expected/gpdist_legacy_opclasses.out
  src/test/regress/expected/gpdist_legacy_opclasses_optimizer.out
  src/test/regress/sql/gpdist_legacy_opclasses.sql
Labels: area: server, backport, type: bug

#9644 6X: tuplestore: support backward scanning of spill files
  src/backend/utils/sort/tuplestore.c
  src/test/regress/expected/misc_jiras.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/misc_jiras.sql
Labels: area: server, backport, type: bug, version: 6X_STABLE
