Repository greenplum-db/gpdb, pull requests merged in 2020-03, with the labels that each got.

#9642 Change WARNING log to normal log on sending request to gpfdist
  src/backend/access/external/url_curl.c
Labels: backport, version: 5X_STABLE

#9648 (6x backport) Fix plan when join lateral inner plan contains limit clause.
  src/backend/cdb/cdbmutate.c
  src/backend/nodes/copyfuncs.c
  src/backend/nodes/outfuncs.c
  src/backend/optimizer/path/allpaths.c
  src/backend/optimizer/plan/createplan.c
  src/backend/optimizer/plan/initsplan.c
  src/backend/optimizer/plan/planmain.c
  src/backend/optimizer/util/pathnode.c
  src/include/cdb/cdbmutate.h
  src/include/nodes/nodes.h
  src/include/nodes/plannerconfig.h
  src/include/nodes/relation.h
  src/include/optimizer/pathnode.h
  src/include/optimizer/planmain.h
  src/test/regress/expected/join_gp.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/sql/join_gp.sql
Labels: backport, type: bug, version: 6X_STABLE

#9641 Don't report internal error if gpfdist session is closed
  src/bin/gpfdist/gpfdist.c
Labels: backport, version: 5X_STABLE

#9658 Fix pulling up EXPR sublinks.
  src/backend/cdb/cdbsubselect.c
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/sql/subselect_gp.sql
Labels: topic: planner

#9672 Add optimizer_enable_range_predicate_dpe guc
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  src/backend/gpopt/config/CConfigParamMapping.cpp
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/include/utils/unsync_guc_name.h
Labels: area: gporca, topic: gporca, version: 7X_ALPHA

#9673 Enable EopttraceAllowGeneralPredicatesforDPE in 5X
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/backend/gpopt/config/CConfigParamMapping.cpp
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#9717 5X: Fix analyzedb with config file to work with partitioned tables
  gpMgmt/bin/analyzedb
  gpMgmt/test/behave/mgmt_utils/analyzedb.feature
Labels: version: 5X_STABLE

#9718 5X: Harden analyzedb when a table is dropped
  gpMgmt/bin/analyzedb
  gpMgmt/bin/gppylib/operations/dump.py
Labels: version: 5X_STABLE

#9752 Bump ORCA version to v 3.95.0
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  src/test/regress/expected/bitmapops_optimizer.out
  src/test/regress/expected/direct_dispatch_optimizer.out
  src/test/regress/expected/plancache_optimizer.out
  src/test/regress/expected/qp_targeted_dispatch.out
  src/test/regress/expected/qp_targeted_dispatch_optimizer.out
  src/test/regress/sql/qp_targeted_dispatch.sql
Labels: area: gporca, topic: gporca

#9753 Bump ORCA version to v3.95.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/test/regress/expected/direct_dispatch_optimizer.out
  src/test/regress/expected/qp_targeted_dispatch.out
  src/test/regress/expected/qp_targeted_dispatch_optimizer.out
  src/test/regress/sql/direct_dispatch.sql
  src/test/regress/sql/qp_targeted_dispatch.sql
Labels: area: gporca, topic: gporca

#9765 Avoid ADD COLUMN full table rewrite for AOCO partitions
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_table_aocs2.out
  src/test/regress/sql/alter_table_aocs2.sql
Labels: version: 6X_STABLE

#9725 Update pg_aoseg entries for COPY FROM SEGMENT
  src/backend/commands/copy.c
  src/test/regress/input/gpcopy.source
  src/test/regress/output/gpcopy.source
Labels: version: 6X_STABLE

#9763 PXF: Encode header values for custom headers (Backport from 6X)
  gpAux/extensions/pxf/src/libchurl.c
  gpAux/extensions/pxf/src/pxfheaders.c
  gpAux/extensions/pxf/test/pxfheaders_test.c
Labels: version: 5X_STABLE

#9778 6X: syslogger: do not write to alert log file if fail to open it
  src/backend/postmaster/syslogger.c
Labels: needs: backport, type: bug, version: 6X_STABLE

#9782 5x: Only get necessary relids for partition table in InitPlan
  src/backend/executor/execMain.c
  src/test/isolation2/expected/ao_partition_lock.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/ao_partition_lock.sql
Labels: version: 5X_STABLE

#9788 5X: syslogger: do not write to alert log file if fail to open it
  src/backend/postmaster/syslogger.c
Labels: backport, type: bug, version: 5X_STABLE

#9777 (6X)Enable external table's error log to be persistent for ETL.
  contrib/extprotocol/expected/exttableext.out
  contrib/extprotocol/gpextprotocol.c
  gpcontrib/Makefile
  gpcontrib/gp_error_handling/.gitignore
  gpcontrib/gp_error_handling/Makefile
  gpcontrib/gp_error_handling/data/data.csv
  gpcontrib/gp_error_handling/gpexterrorhandle.c
  gpcontrib/gp_error_handling/gpexterrorhandle.sql.in
  gpcontrib/gp_error_handling/input/gpexterrorhandle.source
  gpcontrib/gp_error_handling/output/gpexterrorhandle.source
  gpcontrib/gp_error_handling/uninstall_gpexterrorhandle.sql
  src/backend/access/external/fileam.c
  src/backend/catalog/pg_exttable.c
  src/backend/cdb/cdbsreh.c
  src/backend/commands/dbcommands.c
  src/backend/commands/exttablecmds.c
  src/backend/commands/schemacmds.c
  src/backend/nodes/copyfuncs.c
  src/backend/nodes/equalfuncs.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfuncs.c
  src/backend/parser/gram.y
  src/bin/pg_dump/pg_dump.c
  src/include/catalog/pg_exttable.h
  src/include/cdb/cdbsreh.h
  src/include/nodes/parsenodes.h
  src/include/parser/kwlist.h
  src/test/regress/data/bytea.data
  src/test/regress/input/external_table_persistent_error_log.source
  src/test/regress/output/external_table_persistent_error_log.source
Labels: backport, version: 6X_STABLE

#9759 (5X)Enable external table's error log to be persistent for ETL.
  GNUmakefile.in
  contrib/Makefile
  contrib/extprotocol/expected/exttableext.out
  contrib/extprotocol/gpextprotocol.c
  contrib/gp_error_handling/.gitignore
  contrib/gp_error_handling/Makefile
  contrib/gp_error_handling/data/data.csv
  contrib/gp_error_handling/gpexterrorhandle.c
  contrib/gp_error_handling/gpexterrorhandle.sql.in
  contrib/gp_error_handling/input/gpexterrorhandle.source
  contrib/gp_error_handling/output/gpexterrorhandle.source
  contrib/gp_error_handling/uninstall_gpexterrorhandle.sql
  src/backend/access/external/fileam.c
  src/backend/catalog/pg_exttable.c
  src/backend/cdb/cdbsreh.c
  src/backend/commands/dbcommands.c
  src/backend/commands/exttablecmds.c
  src/backend/commands/schemacmds.c
  src/backend/nodes/copyfuncs.c
  src/backend/nodes/equalfuncs.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfuncs.c
  src/backend/parser/gram.y
  src/bin/pg_dump/pg_dump.c
  src/include/catalog/pg_exttable.h
  src/include/cdb/cdbsreh.h
  src/include/nodes/parsenodes.h
  src/include/parser/kwlist.h
  src/test/regress/data/bytea.data
  src/test/regress/input/external_table_persistent_error_log.source
  src/test/regress/output/external_table_persistent_error_log.source
Labels: backport, version: 5X_STABLE

#9793 [5X]Fix variable length arrays error in pg_dump.
  src/bin/pg_dump/pg_dump.c
Labels: type: bug

#9794 [6X]Fix variable length arrays error in pg_dump.
  src/bin/pg_dump/pg_dump.c
Labels: type: bug

#9769 5X: Make compile_gpdb_open_source_centos6 job private
  concourse/pipelines/5X_STABLE-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: version: 5X_STABLE

#9783 Rename BeginCopyToForExternalTable() to BeginCopyToForeignTable()
  src/backend/access/external/fileam.c
  src/backend/commands/copy.c
  src/include/commands/copy.h
Labels: version: 6X_STABLE

#9779 Set ps status when transaction is queuing on resource group
  src/backend/utils/resgroup/resgroup.c
Labels: topic: resource group
