Repository greenplum-db/gpdb, pull requests merged in 2020-01, with the labels that each got.

#9113 Fix invalid alloc size when invalidating caches
  src/backend/utils/cache/inval.c
Labels: type: bug

#9348 6X: Fix invalid alloc size when invalidating caches
  src/backend/utils/cache/inval.c
Labels: version: 6X_STABLE

#9112 5X: Use doubly-linked block lists in aset.c to reduce large-chunk overhead.
  src/backend/utils/cache/inval.c
  src/backend/utils/mmgr/aset.c
Labels: type: enhancement, version: 5X_STABLE

#9346 catch ImportError for gpversion (#8709)
  gpMgmt/bin/gpload.py
Labels: version: 6X_STABLE

#9349 6X: Use a different temp schema name pattern in utility mode
  src/backend/catalog/namespace.c
  src/test/isolation2/expected/misc.out
  src/test/isolation2/sql/misc.sql
Labels: version: 6X_STABLE

#9351 (6x backport) Subquery's locus should keep general
  src/backend/cdb/cdbpathlocus.c
  src/test/regress/expected/bfv_dd.out
  src/test/regress/expected/join.out
  src/test/regress/expected/join_gp.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/expected/join_optimizer.out
  src/test/regress/expected/qp_functions_in_subquery.out
  src/test/regress/expected/qp_functions_in_subquery_optimizer.out
  src/test/regress/expected/rangefuncs.out
  src/test/regress/expected/rangefuncs_optimizer.out
  src/test/regress/sql/join_gp.sql
Labels: backport, version: 6X_STABLE

#9362 Bump ORCA version to v3.87.0
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
Labels: area: gporca, topic: gporca

#9352 5x backport: Subquery's locus should keep general.
  src/backend/cdb/cdbpathlocus.c
  src/test/regress/expected/bfv_dd.out
  src/test/regress/expected/join_gp.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/expected/with_clause.out
  src/test/regress/sql/join_gp.sql
  src/test/regress/sql/with_clause.sql
Labels: backport, version: 5X_STABLE

#9363 Bump ORCA version to 3.87.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#9369 Fix crash with JSON/YAML format EXPLAIN.
  src/backend/commands/explain.c
  src/test/regress/expected/explain_format.out
  src/test/regress/expected/explain_format_optimizer.out
  src/test/regress/sql/explain_format.sql
Labels: version: 6X_STABLE

#9245 Support resource group runaway in global shared memory.
  src/backend/utils/mmgr/redzone_handler.c
  src/backend/utils/mmgr/runaway_cleaner.c
  src/backend/utils/resgroup/resgroup.c
  src/include/utils/resgroup.h
  src/test/isolation2/init_file_resgroup
  src/test/isolation2/input/resgroup/enable_resgroup.source
  src/test/isolation2/input/resgroup/resgroup_memory_runaway.source
  src/test/isolation2/isolation2_resgroup_schedule
  src/test/isolation2/output/resgroup/resgroup_memory_runaway.source
Labels: topic: resource group

#9364 BACKPORT 6X: Print warning message in checkNetworkTimeout.
  src/backend/cdb/motion/ic_tcp.c
  src/backend/cdb/motion/ic_udpifc.c
  src/include/cdb/cdbinterconnect.h
  src/test/regress/sql/icudp/gp_interconnect_min_retries_before_timeout.sql
Labels: version: 6X_STABLE

#9367 BACKPORT 5X: Print warning message in checkNetworkTimeout.
  src/backend/cdb/motion/ic_tcp.c
  src/backend/cdb/motion/ic_udpifc.c
  src/include/cdb/cdbinterconnect.h
Labels: version: 5X_STABLE

#9379 Teach mdnblocks() not to create zero-length files.
  src/backend/storage/smgr/md.c
Labels: backport, version: 5X_STABLE

#9375 Backport 6X: Optimize DistributedLogControlLock in DistributedLog_AdvanceOldestXmin
  src/backend/access/transam/distributedlog.c
Labels: version: 6X_STABLE

#9304 Dispatched once in one vacuum
  src/backend/commands/vacuum.c
  src/test/regress/expected/vacuum_gp.out
  src/test/regress/sql/vacuum_gp.sql
Labels: needs: backport

#9376 Backport 6X: Support resource group runaway in global shared memory.
  src/backend/utils/mmgr/redzone_handler.c
  src/backend/utils/mmgr/runaway_cleaner.c
  src/backend/utils/resgroup/resgroup.c
  src/include/utils/resgroup.h
  src/test/isolation2/init_file_resgroup
  src/test/isolation2/input/resgroup/enable_resgroup.source
  src/test/isolation2/input/resgroup/resgroup_memory_runaway.source
  src/test/isolation2/isolation2_resgroup_schedule
  src/test/isolation2/output/resgroup/resgroup_memory_runaway.source
Labels: version: 6X_STABLE

#9377 Backport 5X: Support resource group runaway in global shared memory.
  src/backend/utils/mmgr/redzone_handler.c
  src/backend/utils/mmgr/runaway_cleaner.c
  src/backend/utils/resgroup/resgroup.c
  src/include/utils/resgroup.h
  src/test/isolation2/init_file_resgroup
  src/test/isolation2/input/resgroup/enable_resgroup.source
  src/test/isolation2/input/resgroup/resgroup_memory_runaway.source
  src/test/isolation2/isolation2_resgroup_schedule
  src/test/isolation2/output/resgroup/resgroup_memory_runaway.source
Labels: version: 5X_STABLE

#9392 Backport missing hearder file into 5X.
  src/include/utils/session_state.h
Labels: version: 5X_STABLE

#9399 Bump ORCA version to v3.88.0
  concourse/tasks/compile_gpdb.yml
  config/orca.m4
  configure
  depends/conanfile_orca.txt
Labels: area: gporca, topic: gporca

#9400 Bump ORCA version to v3.88.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#9403 Fix format change in resgroup test case
  src/test/isolation2/input/resgroup/resgroup_memory_runaway.source
  src/test/isolation2/output/resgroup/resgroup_memory_runaway.source
Labels: version: 5X_STABLE

#9409 Fix another crash in JSON/YAML-format EXPLAIN, due to missing Flow.
  src/backend/commands/explain.c
  src/backend/optimizer/plan/createplan.c
  src/test/regress/expected/explain_format.out
  src/test/regress/expected/explain_format_optimizer.out
  src/test/regress/sql/explain_format.sql
Labels: version: 6X_STABLE

#9266 Consider different cdbhash value in EC.
  src/backend/cdb/cdbhash.c
  src/backend/cdb/cdbpath.c
  src/backend/cdb/cdbpullup.c
  src/include/cdb/cdbhash.h
  src/test/regress/expected/bfv_joins.out
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/sql/bfv_joins.sql
Labels: version: 5X_STABLE

#9447 6x: Avoid potential deadlock on QD
  src/backend/access/heap/heapam.c
  src/backend/storage/lmgr/lmgr.c
  src/backend/utils/cache/plancache.c
  src/include/storage/lmgr.h
  src/test/regress/expected/prepare_lockmode.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/prepare_lockmode.sql
Labels: area: server, type: bug, version: 6X_STABLE

#9448 6X: Fix gpperfmon tmid inconsistent across master and segments
  src/backend/utils/gpmon/gpmon.c
  src/test/isolation2/expected/instr_in_shmem_terminate.out
  src/test/isolation2/sql/instr_in_shmem_terminate.sql
Labels: version: 6X_STABLE

#9316 ci: remove server-build-* resources from non-prod pipelines
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: needs: backport, topic: continuous integration, type: dev environment improvement

#9470 ci: stick python modules to py2 compatible versions
  concourse/scripts/combine_cli_coverage.bash
  concourse/scripts/gsutil_sync
  gpMgmt/requirements-dev.txt
Labels: topic: continuous integration

#9474 Backport Correctly use atomic variable in ResGroupControl.freeChunks. (#8434)
  src/backend/commands/matview.c
  src/backend/utils/resgroup/resgroup.c
Labels: version: 6X_STABLE

#9453 Add sanity check for on conflict update to avoid wrong data distribut…
  src/backend/parser/analyze.c
  src/test/regress/expected/insert_conflict.out
  src/test/regress/expected/update.out
  src/test/regress/expected/update_gp.out
  src/test/regress/expected/update_gp_optimizer.out
  src/test/regress/expected/update_optimizer.out
  src/test/regress/expected/with.out
  src/test/regress/sql/update_gp.sql
Labels: area: server, type: bug, version: 7X_ALPHA

#9482 ci: dump icw dbs with the planner job
  concourse/pipelines/gpdb_master-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
  concourse/tasks/ic_gpdb_binary_swap.yml
Labels: topic: continuous integration

#9485 Backport: Single set command failed, rollback guc value
  src/backend/access/transam/xact.c
  src/backend/tcop/postgres.c
  src/backend/utils/misc/guc.c
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/test/regress/expected/guc_gp.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/guc_gp.sql
Labels: version: 6X_STABLE

#9495 Backport: GUC should be synchronized after change/restore.
  src/backend/utils/misc/guc.c
  src/test/regress/expected/guc.out
  src/test/regress/sql/guc.sql
Labels: version: 6X_STABLE
