Repository greenplum-db/gpdb, pull requests merged in 2020-04, with the labels that each got.

#9888 Bump ORCA version to 3.100, mark split point where 5X, 6X, master separate
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#9886 [6X BACKPORT]Avoid truncate error message in cdb_tidy_message (#9827)
  gpcontrib/gpmapreduce/output/mapred.source
  src/backend/utils/error/elog.c
  src/pl/plperl/expected/plperl.out
  src/pl/plperl/expected/plperl_elog.out
  src/pl/plperl/expected/plperl_elog_1.out
  src/pl/plperl/expected/plperl_plperlu.out
  src/test/isolation2/expected/crash_recovery_dtm.out
  src/test/isolation2/expected/fts_errors.out
  src/test/isolation2/expected/uao_crash_compaction_column.out
  src/test/isolation2/expected/uao_crash_compaction_row.out
  src/test/regress/expected/plpgsql.out
  src/test/regress/expected/plpgsql_optimizer.out
  src/test/regress/expected/xml.out
  src/test/regress/expected/xml_2.out
Labels: version: 6X_STABLE

#9881 6X: Fix the nowait issue(#8539)
  src/backend/access/heap/heapam.c
  src/backend/executor/execMain.c
  src/backend/parser/parse_clause.c
  src/backend/parser/parse_relation.c
  src/backend/rewrite/rewriteHandler.c
  src/backend/storage/lmgr/lmgr.c
  src/backend/utils/cache/plancache.c
  src/include/access/heapam.h
  src/include/parser/parse_relation.h
  src/include/storage/lmgr.h
  src/test/isolation2/expected/select_for_update.out
  src/test/isolation2/sql/select_for_update.sql
Labels: version: 6X_STABLE

#9882 5X: Fix the nowait issue(#8539)
  src/backend/access/heap/heapam.c
  src/backend/executor/execMain.c
  src/backend/parser/parse_clause.c
  src/backend/parser/parse_relation.c
  src/backend/rewrite/rewriteHandler.c
  src/include/access/heapam.h
  src/test/isolation2/expected/select_for_update.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/select_for_update.sql
Labels: version: 5X_STABLE

#9892 [Backport 6X] Truncate AO relation correctly (#9806)
  src/backend/access/appendonly/aomd.c
  src/backend/catalog/heap.c
  src/include/access/aomd.h
  src/test/regress/expected/sirv_functions.out
  src/test/regress/expected/truncate_gp.out
  src/test/regress/parallel_schedule
  src/test/regress/sql/sirv_functions.sql
  src/test/regress/sql/truncate_gp.sql
Labels: version: 6X_STABLE

#9905 (6x backport)Add check for indexpath when bring_to_singleQE.
  src/backend/optimizer/path/allpaths.c
  src/test/regress/expected/join_gp.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/sql/join_gp.sql
Labels: backport, version: 6X_STABLE

#9917 Speed up stats derivation for large number of disjunction in ORCA
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CHistogram.h
  src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp
Labels: area: gporca, topic: gporca, version: 7X_ALPHA

#9913 Speed up stats derivation for large number of disjunction in ORCA
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CHistogram.h
  src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp
Labels: area: gporca, topic: gporca, version: 6X_STABLE

#9730 Fix memory leak in checkpointer process.
  src/backend/access/transam/twophase.c
  src/backend/access/transam/xlog.c
  src/backend/access/transam/xlog_mm.c
  src/backend/cdb/cdbtm.c
  src/include/access/twophase.h
  src/include/access/xlogmm.h
  src/include/cdb/cdbtm.h
Labels: version: 5X_STABLE

#9950 (6x backport) Fix plan when segmentgeneral union all general locus.
  src/backend/cdb/cdbpath.c
  src/test/regress/expected/qp_union_intersect.out
  src/test/regress/expected/qp_union_intersect_optimizer.out
  src/test/regress/sql/qp_union_intersect.sql
Labels: backport, type: bug, version: 6X_STABLE

#9766 Fix memory leak in checkpointer process
  src/backend/access/transam/twophase.c
  src/backend/access/transam/xlog.c
  src/include/access/twophase.h
  src/test/isolation2/expected/crash_recovery_dtm.out
  src/test/isolation2/sql/crash_recovery_dtm.sql
Labels: version: 6X_STABLE

#9908 Do not push Volatile funcs below aggs
  src/backend/gporca/data/dxl/minidump/AggWithVolatileFunc.mdp
  src/backend/gporca/libgpopt/src/operators/CNormalizer.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CAggTest.cpp
  src/test/regress/expected/subselect_optimizer.out
Labels: area: gporca, topic: gporca

#9961 6x backport: Improve efficiency in pg_lock_status()
  src/backend/utils/adt/lockfuncs.c
Labels: backport, version: 6X_STABLE

#9918 Fix zero plan_node_id for BitmapOr/And in ORCA
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
Labels: area: gporca, topic: gporca

#9942 Fix getDtxCheckPointInfo to contain all committed transactions
  src/backend/storage/ipc/procarray.c
Labels: version: 6X_STABLE

#9970 Bump ORCA to v3.101.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: area: gporca, topic: gporca

#9945 5X: Fix poor performing query in analyzedb
  gpMgmt/bin/analyzedb
Labels: version: 5X_STABLE

#9976 (6x backport) Fix some potential bugs that not update size results.
  src/backend/storage/lmgr/lock.c
Labels: backport, version: 6X_STABLE

#9985 fix possible deadlocks between catalog update and FTS
  src/backend/utils/gp/segadmin.c
Labels: version: 5X_STABLE

#10025 6X only: gpexpand: clear gpinitsystem logs before every behave test
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
Labels: topic: gpexpand, version: 6X_STABLE

#9964 Reduce flakiness of orafce dbms_pipe test
  gpcontrib/orafce/expected/dbms_pipe_session_B.out
  gpcontrib/orafce/sql/dbms_pipe_session_B.sql
Labels: needs: backport, version: 7X_ALPHA

#9963 6X Backport: Fix zero plan_node_id for BitmapOr/And in ORCA
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
Labels: version: 6X_STABLE

#9929 Account for transvalue in combine function in the mpool
  src/backend/executor/nodeAgg.c
Labels: version: 7X_ALPHA
