Repository greenplum-db/gpdb, pull requests merged in 2020-08, with the labels that each got.

#10532 Coverity: Identical code for different branches
  src/backend/catalog/heap.c
  src/backend/commands/analyze.c
Labels: coverity, needs: backport

#10536 Coverity: Variable unused
  src/backend/access/external/external.c
  src/backend/commands/exttablecmds.c
  src/include/utils/tuplesort.h
Labels: coverity, needs: backport

#10534 Coverity: Logically dead code
  gpMgmt/bin/lib/pexpect/__init__.py
  src/backend/commands/vacuum_ao.c
Labels: coverity, needs: backport

#10539 Coverity: Sizeof not portable
  src/backend/commands/analyze.c
Labels: coverity, needs: backport

#10555 [5X Backport]Resolve high `CacheMemoryContext` usage for `ANALYZE` on large partition table.
  src/backend/commands/analyze.c
  src/backend/commands/analyzeutils.c
  src/include/commands/analyzeutils.h
  src/test/regress/expected/incremental_analyze.out
Labels: backport, version: 5X_STABLE

#10537 Coverity: Behave test misformat
  gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: coverity, needs: backport

#10535 Coverity: Check return value of strcmp
  src/bin/pg_dump/pg_backup_archiver.c
Labels: coverity, needs: backport

#10568 6X: ic-proxy: handle early coming BYE correctly
  src/backend/cdb/motion/ic_proxy_client.c
Labels: backport, version: 6X_STABLE

#10554 [6X Backport]Resolve high `CacheMemoryContext` usage for `ANALYZE` on large partition table.
  src/backend/commands/analyze.c
  src/backend/commands/analyzeutils.c
  src/include/commands/analyzeutils.h
Labels: backport, version: 6X_STABLE

#10572 ic-proxy: correct SIGHUP handler
  src/backend/cdb/motion/ic_proxy_main.c
Labels: needs: backport, type: bug

#10574 6X: ic-proxy: correct SIGHUP handler
  src/backend/cdb/motion/ic_proxy_main.c
Labels: backport, type: bug, version: 6X_STABLE

#10582 Print CTID when we detect data distribution wrong for UPDATE|DELETE.
  src/backend/executor/nodeModifyTable.c
  src/test/isolation2/expected/modify_table_data_corrupt.out
  src/test/isolation2/expected/modify_table_data_corrupt_optimizer.out
Labels: needs: backport

#10586 Fix crash when creating partitioned table in utility mode
  src/backend/parser/parse_utilcmd.c
  src/test/isolation2/expected/misc.out
  src/test/isolation2/sql/misc.sql
Labels: backport

#10567 [6X Backport]Coverity: dump_mt_bind should free FILE pointer.
  src/backend/utils/error/debugutils.c
Labels: backport, version: 6X_STABLE

#10570 [BACKPORT 6X] backport the fix to coverity issues
  gpMgmt/bin/lib/pexpect/__init__.py
  gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  src/backend/catalog/heap.c
  src/backend/cdb/cdbcopy.c
  src/backend/commands/analyze.c
  src/backend/commands/exttablecmds.c
  src/bin/pg_dump/pg_backup_archiver.c
  src/bin/pg_dump/pg_dump.c
  src/include/utils/tuplesort.h
Labels: version: 6X_STABLE

#10603 6X: Coverity: fix some coverity issues
  src/backend/access/external/url_curl.c
  src/backend/bootstrap/bootstrap.c
  src/backend/commands/functioncmds.c
  src/backend/fts/ftsmessagehandler.c
Labels: backport, version: 6X_STABLE

#10583 (6x backport) Print CTID when we detect data distribution wrong for UPDATE|DELETE.
  src/backend/executor/nodeModifyTable.c
  src/test/isolation2/expected/modify_table_data_corrupt.out
  src/test/isolation2/expected/modify_table_data_corrupt_optimizer.out
Labels: backport, version: 6X_STABLE

#10584 (5x backport) Print CTID when we detect data distribution wrong for UPDATE|DELETE.
  src/backend/executor/execMain.c
  src/backend/executor/nodeDML.c
  src/test/isolation2/expected/modify_table_data_corrupt_optimizer.out
Labels: backport, version: 5X_STABLE

#10494 Allow Partition selection for lossy casts in ORCA
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/gporca/data/dxl/minidump/ListPartLossyCastEq.mdp
  src/backend/gporca/data/dxl/minidump/ListPartLossyCastLT.mdp
  src/backend/gporca/data/dxl/minidump/RangePartLossyCastEqInPartitionRange.mdp
  src/backend/gporca/data/dxl/minidump/RangePartLossyCastEqOnEndPartitionRange.mdp
  src/backend/gporca/data/dxl/minidump/RangePartLossyCastLTEqInPartitionRange.mdp
  src/backend/gporca/data/dxl/minidump/RangePartLossyCastLTEqOnEndPartitionRange.mdp
  src/backend/gporca/data/dxl/minidump/RangePartLossyCastLTInPartitionRange.mdp
  src/backend/gporca/data/dxl/minidump/RangePartLossyCastLTOnEndPartitionRange.mdp
  src/backend/gporca/data/dxl/parse_tests/q26-Metadata.xml
  src/backend/gporca/libgpopt/include/gpopt/operators/CScalarCast.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CScalarIdent.h
  src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorExprToDXLUtils.h
  src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
  src/backend/gporca/libgpopt/src/operators/CScalarIdent.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXLUtils.cpp
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerMDGPDBFunc.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
  src/backend/gporca/libnaucrates/include/naucrates/md/CMDFunctionGPDB.h
  src/backend/gporca/libnaucrates/include/naucrates/md/IMDFunction.h
  src/backend/gporca/libnaucrates/src/md/CMDFunctionGPDB.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerMDGPDBFunc.cpp
  src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/include/catalog/pg_proc.h
  src/include/gpopt/gpdbwrappers.h
  src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca

#10624 Allow static partition selection for lossy casts in ORCA
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/gporca/data/dxl/minidump/ListPartLossyCastEq.mdp
  src/backend/gporca/data/dxl/minidump/ListPartLossyCastLT.mdp
  src/backend/gporca/data/dxl/minidump/RangePartLossyCastEqInPartitionRange.mdp
  src/backend/gporca/data/dxl/minidump/RangePartLossyCastEqOnEndPartitionRange.mdp
  src/backend/gporca/data/dxl/minidump/RangePartLossyCastLTEqInPartitionRange.mdp
  src/backend/gporca/data/dxl/minidump/RangePartLossyCastLTEqOnEndPartitionRange.mdp
  src/backend/gporca/data/dxl/minidump/RangePartLossyCastLTInPartitionRange.mdp
  src/backend/gporca/data/dxl/minidump/RangePartLossyCastLTOnEndPartitionRange.mdp
  src/backend/gporca/data/dxl/parse_tests/q26-Metadata.xml
  src/backend/gporca/libgpopt/include/gpopt/operators/CScalarCast.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CScalarIdent.h
  src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorExprToDXLUtils.h
  src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
  src/backend/gporca/libgpopt/src/operators/CScalarIdent.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXLUtils.cpp
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerMDGPDBFunc.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
  src/backend/gporca/libnaucrates/include/naucrates/md/CMDFunctionGPDB.h
  src/backend/gporca/libnaucrates/include/naucrates/md/IMDFunction.h
  src/backend/gporca/libnaucrates/src/md/CMDFunctionGPDB.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerMDGPDBFunc.cpp
  src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/include/catalog/pg_proc.h
  src/include/gpopt/gpdbwrappers.h
  src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: backport, version: 6X_STABLE

#10596 Modify error context callback functions to not assume that they can f…
  src/backend/catalog/pg_proc.c
  src/backend/executor/functions.c
  src/backend/optimizer/util/clauses.c
Labels: backport, version: 5X_STABLE

#10631 Correct modify_table_data_corrupt test output for orca.
  src/test/isolation2/expected/modify_table_data_corrupt_optimizer.out
Labels: version: 5X_STABLE

#10637 6X: ic-proxy: enable in release builds
  gpAux/Makefile
Labels: backport, version: 6X_STABLE

#10651 Enable external_table test case in ic-proxy mode
  concourse/pipelines/gpdb_master-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: needs: backport

#10553 6X: gp_replica_check: skip checking unlogged tables
  gpcontrib/gp_replica_check/gp_replica_check.c
  src/test/regress/expected/create_table.out
  src/test/regress/sql/create_table.sql
Labels: version: 6X_STABLE

#10653 [6X Backport]Fix CREATE EXTENSION gp_internal_tools changes search_path
  gpcontrib/gp_internal_tools/expected/gp_session_state_memory.out
  gpcontrib/gp_internal_tools/gp_internal_tools--1.0.0.sql
  gpcontrib/gp_internal_tools/uninstall_gp_session_state.sql
Labels: backport, version: 6X_STABLE

#10673 Remove GPORCA "error simulator" tests.
  src/backend/gporca/README.md
  src/backend/gporca/libgpopt/src/mdcache/CMDAccessorUtils.cpp
  src/backend/gporca/libgpopt/src/mdcache/CMDCache.cpp
  src/backend/gporca/libgpopt/src/minidump/CMinidumperUtils.cpp
  src/backend/gporca/libgpos/include/gpos/error/CException.h
  src/backend/gporca/libgpos/include/gpos/error/CFSimulator.h
  src/backend/gporca/libgpos/include/gpos/io/ioutils.h
  src/backend/gporca/libgpos/include/gpos/task/CWorker.h
  src/backend/gporca/libgpos/include/gpos/task/traceflags.h
  src/backend/gporca/libgpos/include/gpos/test/CFSimulatorTestExt.h
  src/backend/gporca/libgpos/include/gpos/test/CUnittest.h
  src/backend/gporca/libgpos/include/gpos/types.h
  src/backend/gporca/libgpos/server/CMakeLists.txt
  src/backend/gporca/libgpos/server/include/unittest/gpos/error/CFSimulatorTest.h
  src/backend/gporca/libgpos/server/src/startup/main.cpp
  src/backend/gporca/libgpos/server/src/unittest/gpos/common/CRefCountTest.cpp
  src/backend/gporca/libgpos/server/src/unittest/gpos/error/CFSimulatorTest.cpp
  src/backend/gporca/libgpos/server/src/unittest/gpos/error/CLoggerTest.cpp
  src/backend/gporca/libgpos/server/src/unittest/gpos/io/CFileTest.cpp
  src/backend/gporca/libgpos/server/src/unittest/gpos/io/COstreamFileTest.cpp
  src/backend/gporca/libgpos/src/_api.cpp
  src/backend/gporca/libgpos/src/error/CFSimulator.cpp
  src/backend/gporca/libgpos/src/error/CMessage.cpp
  src/backend/gporca/libgpos/src/error/Makefile
  src/backend/gporca/libgpos/src/io/CFileDescriptor.cpp
  src/backend/gporca/libgpos/src/io/CFileReader.cpp
  src/backend/gporca/libgpos/src/io/CFileWriter.cpp
  src/backend/gporca/libgpos/src/io/ioutils.cpp
  src/backend/gporca/libgpos/src/memory/CMemoryPool.cpp
  src/backend/gporca/libgpos/src/memory/CMemoryPoolManager.cpp
  src/backend/gporca/libgpos/src/task/CWorker.cpp
  src/backend/gporca/libgpos/src/test/CFSimulatorTestExt.cpp
  src/backend/gporca/libgpos/src/test/CUnittest.cpp
  src/backend/gporca/libnaucrates/src/CDXLUtils.cpp
  src/backend/gporca/libnaucrates/src/traceflags.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/backend/gporca/server/include/unittest/gpopt/CTestUtils.h
  src/backend/gporca/server/src/startup/main.cpp
  src/backend/gporca/server/src/unittest/CTestUtils.cpp
  src/backend/gporca/server/src/unittest/dxl/CParseHandlerManagerTest.cpp
  src/backend/gporca/server/src/unittest/dxl/CParseHandlerTest.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CMiniDumperDXLTest.cpp
Labels: area: gporca

#10650 6X: Fix flaky test: dbms_pipe_session_B
  gpcontrib/orafce/sql/dbms_pipe_session_B.sql
Labels: backport, version: 6X_STABLE

#10681 [6X Backport]Error out when changing datatype of column with constraint.
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_table.out
  src/test/regress/expected/alter_table_gp.out
  src/test/regress/sql/alter_table_gp.sql
Labels: backport, version: 6X_STABLE

#10646 Allow NEq predicates on lossy casts to do Partition Selection
  src/backend/gporca/data/dxl/minidump/BitmapIndexApply-InnerSelect-PartTable.mdp
  src/backend/gporca/data/dxl/minidump/BitmapIndexApply-PartTable.mdp
  src/backend/gporca/data/dxl/minidump/DynamicBitmapBoolOp.mdp
  src/backend/gporca/data/dxl/minidump/DynamicBitmapIndexScan.mdp
  src/backend/gporca/data/dxl/minidump/DynamicBitmapTableScan-Heterogeneous.mdp
  src/backend/gporca/data/dxl/minidump/DynamicIndexScan-Heterogenous-UnsupportedPredicate.mdp
  src/backend/gporca/data/dxl/minidump/DynamicIndexScan-Homogenous-EnabledDateConstraint.mdp
  src/backend/gporca/data/dxl/minidump/DynamicIndexScan-Homogenous-UnsupportedConstraint.mdp
  src/backend/gporca/data/dxl/minidump/EffectOfLocalPredOnJoin2.mdp
  src/backend/gporca/data/dxl/minidump/ExtractPredicateFromDisj.mdp
  src/backend/gporca/data/dxl/minidump/GroupingOnSameTblCol-2.mdp
  src/backend/gporca/data/dxl/minidump/IndexApply-PartKey-Is-IndexKey.mdp
  src/backend/gporca/data/dxl/minidump/ListPartLossyCastNEq.mdp
  src/backend/gporca/data/dxl/minidump/MS-UnionAll-1.mdp
  src/backend/gporca/data/dxl/minidump/MS-UnionAll-2.mdp
  src/backend/gporca/data/dxl/minidump/MS-UnionAll-4.mdp
  src/backend/gporca/data/dxl/minidump/MS-UnionAll-5.mdp
  src/backend/gporca/data/dxl/minidump/MS-UnionAll-6.mdp
  src/backend/gporca/data/dxl/minidump/MS-UnionAll-7.mdp
  src/backend/gporca/data/dxl/minidump/MultiLevelPartLossyCastNEq.mdp
  src/backend/gporca/data/dxl/minidump/QueryMismatchedDistribution-DynamicIndexScan.mdp
  src/backend/gporca/data/dxl/minidump/UpdateDroppedCols.mdp
  src/backend/gporca/data/dxl/minidump/UpdatePartTable.mdp
  src/backend/gporca/data/dxl/multilevel-partitioning/Multilevel-Casting-predicate-on-all-levels.mdp
  src/backend/gporca/libgpopt/include/gpopt/operators/CPredicateUtils.h
  src/backend/gporca/libgpopt/src/operators/CPhysicalFilter.cpp
  src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXLUtils.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 7X_ALPHA

#10625 Allow NEq predicates on lossy casts to do Partition Selection
  src/backend/gporca/data/dxl/minidump/BitmapIndexApply-InnerSelect-PartTable.mdp
  src/backend/gporca/data/dxl/minidump/BitmapIndexApply-PartTable.mdp
  src/backend/gporca/data/dxl/minidump/DynamicBitmapBoolOp.mdp
  src/backend/gporca/data/dxl/minidump/DynamicBitmapIndexScan.mdp
  src/backend/gporca/data/dxl/minidump/DynamicBitmapTableScan-Heterogeneous.mdp
  src/backend/gporca/data/dxl/minidump/DynamicIndexScan-Heterogenous-UnsupportedPredicate.mdp
  src/backend/gporca/data/dxl/minidump/DynamicIndexScan-Homogenous-EnabledDateConstraint.mdp
  src/backend/gporca/data/dxl/minidump/DynamicIndexScan-Homogenous-UnsupportedConstraint.mdp
  src/backend/gporca/data/dxl/minidump/EffectOfLocalPredOnJoin2.mdp
  src/backend/gporca/data/dxl/minidump/ExtractPredicateFromDisj.mdp
  src/backend/gporca/data/dxl/minidump/GroupingOnSameTblCol-2.mdp
  src/backend/gporca/data/dxl/minidump/IndexApply-PartKey-Is-IndexKey.mdp
  src/backend/gporca/data/dxl/minidump/ListPartLossyCastNEq.mdp
  src/backend/gporca/data/dxl/minidump/MS-UnionAll-1.mdp
  src/backend/gporca/data/dxl/minidump/MS-UnionAll-2.mdp
  src/backend/gporca/data/dxl/minidump/MS-UnionAll-4.mdp
  src/backend/gporca/data/dxl/minidump/MS-UnionAll-5.mdp
  src/backend/gporca/data/dxl/minidump/MS-UnionAll-6.mdp
  src/backend/gporca/data/dxl/minidump/MS-UnionAll-7.mdp
  src/backend/gporca/data/dxl/minidump/MultiLevelPartLossyCastNEq.mdp
  src/backend/gporca/data/dxl/minidump/QueryMismatchedDistribution-DynamicIndexScan.mdp
  src/backend/gporca/data/dxl/minidump/UpdateDroppedCols.mdp
  src/backend/gporca/data/dxl/minidump/UpdatePartTable.mdp
  src/backend/gporca/data/dxl/multilevel-partitioning/Multilevel-Casting-predicate-on-all-levels.mdp
  src/backend/gporca/libgpopt/include/gpopt/operators/CPredicateUtils.h
  src/backend/gporca/libgpopt/src/operators/CPhysicalFilter.cpp
  src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXLUtils.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 6X_STABLE

#10669 Harden analyzedb further against dropped/recreated tables
  gpMgmt/bin/analyzedb
Labels: area: gporca

#10699 [6X] Harden analyzedb further against dropped/recreated tables
  gpMgmt/bin/analyzedb
Labels: area: gporca, version: 6X_STABLE

#10697 Don't try to generate generic plans with GPORCA.
  src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
  src/backend/utils/cache/plancache.c
Labels: area: gporca

#10704 [5X] Harden analyzedb further against dropped/recreated tables
  gpMgmt/bin/analyzedb
  gpMgmt/bin/gppylib/operations/dump.py
Labels: area: gporca, version: 5X_STABLE

#10261 Fix url_curl on MacOS
  src/backend/access/external/url_curl.c
Labels: area: clients

#10703 Fix gp_error_handling makefile
  gpcontrib/gp_error_handling/Makefile
Labels: version: 6X_STABLE

#10702 Fix gp_error_handling makefile
  contrib/gp_error_handling/Makefile
Labels: version: 5X_STABLE

#10695 Fix dblink's libpq issue on gpdb 5X
  GNUmakefile.in
  contrib/dblink/Makefile
  contrib/dblink/dblink.c
Labels: area: extensions, version: 5X_STABLE

#10680 Fix postgres fdw on gpdb 6X
  contrib/postgres_fdw/Makefile
  contrib/postgres_fdw/postgres_fdw.h
Labels: topic: FDW, version: 6X_STABLE

#10656 Fix dblink's libpq issue on gpdb 6X
  GNUmakefile.in
  contrib/dblink/Makefile
  contrib/dblink/dblink.c
Labels: area: extensions, version: 6X_STABLE

#10684 [Backport 6X]Fix assertion failures in BackoffSweeper
  src/backend/postmaster/backoff.c
Labels: version: 6X_STABLE

#10712 [5X Backport]Error out when changing datatype of column with constraint.
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_table_gp.out
  src/test/regress/sql/alter_table_gp.sql
Labels: backport, version: 5X_STABLE

#10321 5X Backport PR#9946
  src/backend/executor/execHHashagg.c
Labels: version: 5X_STABLE
