Repository greenplum-db/gpdb, pull requests merged in 2020-07, with the labels that each got.

#10383 Fix Orca optimizer search stage couldn't measure elapsed time correctly
  src/backend/gporca/libgpopt/src/engine/CEngine.cpp
  src/backend/gporca/libgpopt/src/search/CSearchStage.cpp
Labels: area: gporca

#10392 [5X Backport] Improve statistics calculation for exprs like "var = ANY (ARRAY[...])"
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
Labels: area: gporca, backport, version: 5X_STABLE

#10408 (6x backport) Make QEs does not use the GUC gp_enable_global_deadlock_detector.
  src/backend/executor/execMain.c
  src/backend/executor/nodeModifyTable.c
  src/backend/storage/lmgr/lmgr.c
  src/test/isolation2/expected/gdd/concurrent_update.out
  src/test/isolation2/expected/lockmodes.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/concurrent_update.sql
  src/test/isolation2/sql/concurrent_update_distkeys.sql
  src/test/isolation2/sql/concurrent_update_epq.sql
  src/test/isolation2/sql/gdd/concurrent_update.sql
  src/test/isolation2/sql/lockmodes.sql
Labels: backport, version: 6X_STABLE

#10388 Check whether the directory exists when deleting the tablespace
  src/backend/commands/tablespace.c
  src/test/regress/input/gp_tablespace.source
  src/test/regress/output/gp_tablespace.source
Labels: backport, version: 6X_STABLE

#10411 [6X Backport]Let FTS mark mirror down if replication keeps crash.
  src/backend/cdb/cdbvars.c
  src/backend/replication/gp_replication.c
  src/backend/replication/test/gp_replication_test.c
  src/backend/replication/walsender.c
  src/backend/storage/ipc/ipci.c
  src/backend/utils/misc/guc_gp.c
  src/include/cdb/cdbvars.h
  src/include/replication/gp_replication.h
  src/include/replication/walsender_private.h
  src/include/storage/lwlock.h
  src/include/utils/unsync_guc_name.h
  src/test/isolation2/expected/segwalrep/replication_keeps_crash.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/segwalrep/replication_keeps_crash.sql
Labels: backport, version: 6X_STABLE

#10403 Remove PXF from the Greenplum repository
  GNUmakefile.in
  NOTICE
  README.md
  concourse/scripts/compile_gpdb.bash
  concourse/scripts/ic_gpdb_resgroup.bash
  concourse/scripts/ic_gpdb_ubuntu.bash
  concourse/scripts/run_fips_tests.sh
  configure
  configure.in
  gpAux/Makefile
  gpAux/extensions/Makefile
  gpAux/extensions/pxf/.gitignore
  gpAux/extensions/pxf/Makefile
  gpAux/extensions/pxf/README.md
  gpAux/extensions/pxf/expected/pxf.out
  gpAux/extensions/pxf/expected/pxfinvalid.out
  gpAux/extensions/pxf/expected/setup.out
  gpAux/extensions/pxf/pxf--1.0.sql
  gpAux/extensions/pxf/pxf.control
  gpAux/extensions/pxf/sql/pxf.sql
  gpAux/extensions/pxf/sql/pxfinvalid.sql
  gpAux/extensions/pxf/sql/setup.sql
  gpAux/extensions/pxf/src/gpdbwritableformatter.c
  gpAux/extensions/pxf/src/libchurl.c
  gpAux/extensions/pxf/src/libchurl.h
  gpAux/extensions/pxf/src/pxfbridge.c
  gpAux/extensions/pxf/src/pxfbridge.h
  gpAux/extensions/pxf/src/pxffilters.c
  gpAux/extensions/pxf/src/pxffilters.h
  gpAux/extensions/pxf/src/pxffragment.c
  gpAux/extensions/pxf/src/pxffragment.h
  gpAux/extensions/pxf/src/pxfheaders.c
  gpAux/extensions/pxf/src/pxfheaders.h
  gpAux/extensions/pxf/src/pxfprotocol.c
  gpAux/extensions/pxf/src/pxfuriparser.c
  gpAux/extensions/pxf/src/pxfuriparser.h
  gpAux/extensions/pxf/src/pxfutils.c
  gpAux/extensions/pxf/src/pxfutils.h
  gpAux/extensions/pxf/test/Makefile
  gpAux/extensions/pxf/test/libchurl_test.c
  gpAux/extensions/pxf/test/mock/curl_mock.c
  gpAux/extensions/pxf/test/mock/libchurl_mock.c
  gpAux/extensions/pxf/test/mock/pxfbridge_mock.c
  gpAux/extensions/pxf/test/mock/pxffilters_mock.c
  gpAux/extensions/pxf/test/mock/pxffragment_mock.c
  gpAux/extensions/pxf/test/mock/pxfheaders_mock.c
  gpAux/extensions/pxf/test/mock/pxfprotocol_mock.c
  gpAux/extensions/pxf/test/mock/pxfuriparser_mock.c
  gpAux/extensions/pxf/test/mock/pxfutils_mock.c
  gpAux/extensions/pxf/test/pxfbridge_test.c
  gpAux/extensions/pxf/test/pxffilters_test.c
  gpAux/extensions/pxf/test/pxffragment_test.c
  gpAux/extensions/pxf/test/pxfheaders_test.c
  gpAux/extensions/pxf/test/pxfprotocol_test.c
  gpAux/extensions/pxf/test/pxfuriparser_test.c
  gpAux/extensions/pxf/test/pxfutils_test.c
  src/Makefile.global.in
Labels: version: 5X_STABLE

#10424 Move slack command trigger repo
  src/backend/gporca/concourse/test_orca_pipeline.yml
Labels: area: gporca

#10425 Move slack command trigger repo
  src/backend/gporca/concourse/test_orca_pipeline.yml
Labels: area: gporca, version: 6X_STABLE

#10399 [5X Backport] gpMgmt: make additional utilities search_path-safe
  gpMgmt/bin/gpcheckcat
  gpMgmt/bin/gpsd
  gpMgmt/bin/minirepro
Labels: backport, version: 5X_STABLE

#10394 [6X Backport] gpMgmt: make additional utilities search_path-safe
  gpMgmt/bin/gpcheckcat
  gpMgmt/bin/gppylib/operations/segment_reconfigurer.py
  gpMgmt/bin/gpsd
  gpMgmt/bin/minirepro
Labels: backport, version: 6X_STABLE

#10422 [6X Backport] Fix bitmap scan crash issue for AO/AOCS table.
  src/backend/executor/nodeBitmapHeapscan.c
  src/test/regress/expected/co_nestloop_idxscan.out
  src/test/regress/expected/co_nestloop_idxscan_optimizer.out
  src/test/regress/sql/co_nestloop_idxscan.sql
Labels: backport, version: 6X_STABLE

#10434 Fix colrefs getting mangled when merging equivalent classes in Orca
  src/backend/gporca/data/dxl/minidump/UnionWithCTE.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca

#10436 [6X] Fix colrefs getting mangled when merging equivalent classes in Orca
  src/backend/gporca/data/dxl/minidump/UnionWithCTE.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, version: 6X_STABLE

#10428 Disallow the replicated table inherit or to be inherited
  src/backend/commands/tablecmds.c
  src/test/regress/expected/inherit.out
  src/test/regress/expected/inherit_optimizer.out
  src/test/regress/sql/inherit.sql
Labels: backport, version: 6X_STABLE

#10447 Bump Orca version to v3.107.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: area: gporca, version: 5X_STABLE

#10427 [6X Backport] Fix flaky test for replication_keeps_crash.
  src/backend/replication/gp_replication.c
  src/test/isolation2/expected/segwalrep/replication_keeps_crash.out
  src/test/isolation2/sql/segwalrep/replication_keeps_crash.sql
Labels: backport, version: 6X_STABLE

#10414 Fix the assert failure on pullup flow in within group
  src/backend/cdb/cdbgroup.c
  src/test/regress/expected/qp_functions_idf.out
  src/test/regress/sql/qp_functions_idf.sql
Labels: version: 5X_STABLE

#10465 Fix pulling up EXPR sublinks
  src/backend/cdb/cdbsubselect.c
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/sql/subselect_gp.sql
Labels: backport, version: 5X_STABLE

#10455 Fix pulling up EXPR sublinks
  src/backend/cdb/cdbsubselect.c
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/sql/subselect_gp.sql
Labels: backport, version: 6X_STABLE

#10440 Do not allocate MemoryPoolManager from a memory pool
  src/backend/gporca/libgpos/include/gpos/memory/CMemoryPoolManager.h
  src/backend/gporca/libgpos/src/memory/CMemoryPoolManager.cpp
Labels: area: gporca, version: 6X_STABLE, version: 7X_ALPHA

#10472 Change log level in ExecChooseHashTableSize
  src/backend/executor/nodeHash.c
Labels: needs: backport

#10467 Add ICW for oracle7 in pipeline
  concourse/pipelines/gen_pipeline.py
  concourse/pipelines/gpdb_6X_STABLE-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: topic: continuous integration, version: 6X_STABLE

#10498 [6X Backport]Fix flaky for test instr_in_shmem_terminate.
  src/test/isolation2/expected/instr_in_shmem_terminate.out
  src/test/isolation2/sql/instr_in_shmem_terminate.sql
Labels: backport, version: 6X_STABLE

#10483 (6X only) Fix cdbpath_dedup_fixup does not consider merge append path.
  src/backend/optimizer/util/pathnode.c
  src/backend/utils/adt/selfuncs.c
  src/test/regress/expected/bfv_joins.out
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/expected/join_gp.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/sql/bfv_joins.sql
Labels: topic: planner, type: bug, version: 6X_STABLE

#10495 (6x backport) Correct plan of general & segmentGeneral path with volatiole functions.
  src/backend/cdb/cdbpath.c
  src/backend/optimizer/path/allpaths.c
  src/backend/optimizer/plan/createplan.c
  src/backend/optimizer/plan/planner.c
  src/backend/optimizer/plan/subselect.c
  src/backend/optimizer/util/clauses.c
  src/backend/optimizer/util/pathnode.c
  src/include/cdb/cdbpath.h
  src/include/nodes/relation.h
  src/include/optimizer/pathnode.h
  src/test/regress/expected/bfv_planner.out
  src/test/regress/expected/qp_functions_in_subquery.out
  src/test/regress/expected/qp_functions_in_subquery_optimizer.out
  src/test/regress/expected/rpt.out
  src/test/regress/sql/bfv_planner.sql
  src/test/regress/sql/rpt.sql
Labels: backport, version: 6X_STABLE

#10484 [5X] Allow merging of statistics for domain types
  src/backend/commands/analyzeutils.c
  src/test/regress/expected/incremental_analyze.out
  src/test/regress/sql/incremental_analyze.sql
Labels: area: gporca, version: 5X_STABLE

#10486 [Backport 6X] Change log level in ExecChooseHashTableSize
  src/backend/executor/nodeHash.c
Labels: version: 6X_STABLE

#10516 Don't mock GPORCA functions unnecessarily.
  src/backend/mock.mk
Labels: area: gporca

#10517 docs - add GUC gp_add_column_inherits_table_setting 6.x only
  gpdb-doc/dita/ref_guide/config_params/guc-list.xml
  gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
  gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap
  gpdb-doc/dita/ref_guide/sql_commands/ALTER_TABLE.xml
Labels: version: 6X_STABLE

#10485 Add Orca support for index only scan
  src/backend/gpopt/config/CConfigParamMapping.cpp
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gporca/data/dxl/minidump/UnnestSQJoins.mdp
  src/backend/gporca/libgpdbcost/include/gpdbcost/CCostModelGPDB.h
  src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
  src/backend/gporca/libgpopt/include/gpopt/base/CColRef.h
  src/backend/gporca/libgpopt/include/gpopt/metadata/CIndexDescriptor.h
  src/backend/gporca/libgpopt/include/gpopt/operators/COperator.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalIndexOnlyScan.h
  src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorExprToDXL.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXform.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXformIndexGet2IndexOnlyScan.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/xforms.h
  src/backend/gporca/libgpopt/src/metadata/CIndexDescriptor.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalIndexGet.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalIndexOnlyScan.cpp
  src/backend/gporca/libgpopt/src/operators/Makefile
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformFactory.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformIndexGet2IndexOnlyScan.cpp
  src/backend/gporca/libgpopt/src/xforms/Makefile
  src/backend/utils/misc/guc_gp.c
  src/include/gpopt/translate/CTranslatorDXLToPlStmt.h
  src/include/utils/guc.h
  src/include/utils/unsync_guc_name.h
  src/test/regress/expected/bfv_index.out
  src/test/regress/expected/bfv_index_optimizer.out
  src/test/regress/sql/bfv_index.sql
Labels: area: gporca, version: 6X_STABLE, version: 7X_ALPHA

#10531 6X: Revert "ic-proxy: get libuv on pr pipeline"
  concourse/pipelines/pr_pipeline.yml
Labels: version: 6X_STABLE

#10524 6X backport: Add Orca support for index only scan
  src/backend/gpopt/config/CConfigParamMapping.cpp
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gporca/data/dxl/minidump/UnnestSQJoins.mdp
  src/backend/gporca/libgpdbcost/include/gpdbcost/CCostModelGPDB.h
  src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
  src/backend/gporca/libgpopt/include/gpopt/base/CColRef.h
  src/backend/gporca/libgpopt/include/gpopt/metadata/CIndexDescriptor.h
  src/backend/gporca/libgpopt/include/gpopt/operators/COperator.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalIndexOnlyScan.h
  src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorExprToDXL.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXform.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXformIndexGet2IndexOnlyScan.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/xforms.h
  src/backend/gporca/libgpopt/src/metadata/CIndexDescriptor.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalIndexGet.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalIndexOnlyScan.cpp
  src/backend/gporca/libgpopt/src/operators/Makefile
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformFactory.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformIndexGet2IndexOnlyScan.cpp
  src/backend/gporca/libgpopt/src/xforms/Makefile
  src/backend/utils/misc/guc_gp.c
  src/include/gpopt/translate/CTranslatorDXLToPlStmt.h
  src/include/utils/guc.h
  src/include/utils/unsync_guc_name.h
  src/test/regress/expected/bfv_index.out
  src/test/regress/expected/bfv_index_optimizer.out
  src/test/regress/sql/bfv_index.sql
Labels: area: gporca, version: 6X_STABLE

#10479 Improve cardinality for joins using distribution columns in ORCA
  src/backend/gporca/data/dxl/minidump/MultiDistKeyJoinCardinality.mdp
  src/backend/gporca/data/dxl/minidump/MultiDistKeyWithOtherPredsJoinCardinality.mdp
  src/backend/gporca/data/dxl/minidump/MultipleDampedPredJoinCardinality.mdp
  src/backend/gporca/data/dxl/minidump/NoDistKeyMultiPredJoinCardinality.mdp
  src/backend/gporca/data/dxl/minidump/OneDistKeyMultiPredJoinCardinality.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CColRef.h
  src/backend/gporca/libgpopt/include/gpopt/base/CColRefComputed.h
  src/backend/gporca/libgpopt/include/gpopt/base/CColRefTable.h
  src/backend/gporca/libgpopt/include/gpopt/base/CColumnFactory.h
  src/backend/gporca/libgpopt/include/gpopt/mdcache/CMDAccessor.h
  src/backend/gporca/libgpopt/include/gpopt/metadata/CColumnDescriptor.h
  src/backend/gporca/libgpopt/src/base/CColRefTable.cpp
  src/backend/gporca/libgpopt/src/base/CColumnFactory.cpp
  src/backend/gporca/libgpopt/src/base/CQueryContext.cpp
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libgpopt/src/mdcache/CMDAccessor.cpp
  src/backend/gporca/libgpopt/src/metadata/CColumnDescriptor.cpp
  src/backend/gporca/libgpopt/src/metadata/CTableDescriptor.cpp
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CScaleFactorUtils.h
  src/backend/gporca/libnaucrates/src/md/CMDRelationExternalGPDB.cpp
  src/backend/gporca/libnaucrates/src/statistics/CJoinStatsProcessor.cpp
  src/backend/gporca/libnaucrates/src/statistics/CScaleFactorUtils.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/backend/gporca/server/src/unittest/dxl/statistics/CJoinCardinalityTest.cpp
  src/backend/gporca/server/src/unittest/dxl/statistics/CStatisticsTest.cpp
Labels: area: gporca, version: 5X_STABLE, version: 6X_STABLE, version: 7X_ALPHA

#10263 Add knowledge of partition selectors to Orca's DPv2 algorithm
  src/backend/gporca/libgpopt/include/gpopt/base/CDrvdPropRelational.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpression.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionHandle.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogical.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalBitmapTableGet.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalCTEConsumer.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalCTEProducer.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDynamicGet.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDynamicGetBase.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalGet.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalSelect.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysical.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderDPv2.h
  src/backend/gporca/libgpopt/src/base/CDrvdPropRelational.cpp
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libgpopt/src/operators/CExpression.cpp
  src/backend/gporca/libgpopt/src/operators/CExpressionHandle.cpp
  src/backend/gporca/libgpopt/src/operators/CLogical.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalCTEConsumer.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalCTEProducer.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalSelect.cpp
  src/backend/gporca/libgpopt/src/xforms/CJoinOrderDPv2.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformExpandNAryJoinDPv2.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
  src/backend/gporca/libnaucrates/src/statistics/CStatisticsUtils.cpp
Labels: area: gporca

#10549 Improve cardinality for joins using distribution columns in ORCA
  src/backend/gporca/data/dxl/minidump/MultiDistKeyJoinCardinality.mdp
  src/backend/gporca/data/dxl/minidump/MultiDistKeyWithOtherPredsJoinCardinality.mdp
  src/backend/gporca/data/dxl/minidump/MultipleDampedPredJoinCardinality.mdp
  src/backend/gporca/data/dxl/minidump/NoDistKeyMultiPredJoinCardinality.mdp
  src/backend/gporca/data/dxl/minidump/OneDistKeyMultiPredJoinCardinality.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CColRef.h
  src/backend/gporca/libgpopt/include/gpopt/base/CColRefComputed.h
  src/backend/gporca/libgpopt/include/gpopt/base/CColRefTable.h
  src/backend/gporca/libgpopt/include/gpopt/base/CColumnFactory.h
  src/backend/gporca/libgpopt/include/gpopt/mdcache/CMDAccessor.h
  src/backend/gporca/libgpopt/include/gpopt/metadata/CColumnDescriptor.h
  src/backend/gporca/libgpopt/src/base/CColRefTable.cpp
  src/backend/gporca/libgpopt/src/base/CColumnFactory.cpp
  src/backend/gporca/libgpopt/src/base/CQueryContext.cpp
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libgpopt/src/mdcache/CMDAccessor.cpp
  src/backend/gporca/libgpopt/src/metadata/CColumnDescriptor.cpp
  src/backend/gporca/libgpopt/src/metadata/CTableDescriptor.cpp
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CScaleFactorUtils.h
  src/backend/gporca/libnaucrates/src/md/CMDRelationExternalGPDB.cpp
  src/backend/gporca/libnaucrates/src/statistics/CJoinStatsProcessor.cpp
  src/backend/gporca/libnaucrates/src/statistics/CScaleFactorUtils.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/backend/gporca/server/src/unittest/dxl/statistics/CJoinCardinalityTest.cpp
  src/backend/gporca/server/src/unittest/dxl/statistics/CStatisticsTest.cpp
Labels: area: gporca, backport, version: 6X_STABLE

#10558 [6X Backport] Add knowledge of partition selectors to Orca's DPv2 algorithm (#10263)
  src/backend/gporca/libgpopt/include/gpopt/base/CDrvdPropRelational.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpression.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionHandle.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogical.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalBitmapTableGet.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalCTEConsumer.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalCTEProducer.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDynamicGet.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDynamicGetBase.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalGet.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalSelect.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysical.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderDPv2.h
  src/backend/gporca/libgpopt/src/base/CDrvdPropRelational.cpp
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libgpopt/src/operators/CExpression.cpp
  src/backend/gporca/libgpopt/src/operators/CExpressionHandle.cpp
  src/backend/gporca/libgpopt/src/operators/CLogical.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalCTEConsumer.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalCTEProducer.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalSelect.cpp
  src/backend/gporca/libgpopt/src/xforms/CJoinOrderDPv2.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformExpandNAryJoinDPv2.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
  src/backend/gporca/libnaucrates/src/statistics/CStatisticsUtils.cpp
Labels: area: gporca, backport, version: 6X_STABLE

#10559 [5X] Bump Orca version to v3.108.0
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: area: gporca, version: 5X_STABLE

#10538 Coverity: Resource leak
  src/backend/cdb/cdbcopy.c
  src/bin/pg_dump/pg_dump.c
Labels: coverity, needs: backport

#10533 Coverity: Argument cannot be negative
  src/backend/cdb/cdbappendonlystorageread.c
  src/backend/utils/hyperloglog/gp_hyperloglog.c
Labels: coverity, needs: backport
