Repository greenplum-db/gpdb, pull requests merged in 2020-06, with the labels that each got.

#10185 [BACKPORT] Refactor the resource management in INITPLAN function
  src/backend/cdb/cdbsubplan.c
  src/backend/executor/execMain.c
  src/backend/executor/nodeFunctionscan.c
  src/backend/executor/nodeMaterial.c
  src/backend/executor/nodeShareInputScan.c
  src/backend/executor/nodeSubplan.c
  src/backend/utils/sort/tuplestorenew.c
  src/include/cdb/cdbsubplan.h
  src/include/utils/tuplestorenew.h
  src/test/regress/expected/function_extensions.out
  src/test/regress/expected/function_extensions_optimizer.out
  src/test/regress/sql/function_extensions.sql
Labels: version: 6X_STABLE

#10090 Support for an "NDV-preserving" function and op property
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/include/catalog/pg_operator.h
  src/include/catalog/pg_proc.h
  src/include/gpopt/gpdbwrappers.h
  src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
Labels: area: gporca, topic: gporca, type: bug, version: 5X_STABLE

#10215 Make concurrent refresh check early on matview
  src/backend/commands/matview.c
Labels: backport, version: 6X_STABLE

#10219 Add missing field skipData in RefreshClause serialization.
  src/backend/commands/matview.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfuncs.c
  src/test/regress/expected/matview_ao.out
  src/test/regress/sql/matview_ao.sql
Labels: backport, version: 6X_STABLE

#10208 Remove unnecessary projections from duplicate sensitive Distribute in ORCA
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, topic: gporca, version: 7X_ALPHA

#10207 [6x] Remove unnecessary projections from duplicate sensitive Distribute(s) in ORCA
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, topic: gporca, version: 6X_STABLE

#10236 Bump Orca version to 3.105
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#10225 Support "NDV-preserving" function and op property
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/gporca/data/dxl/minidump/EquiJoinOnExpr-Supported.mdp
  src/backend/gporca/data/dxl/minidump/EquiJoinOnExpr-Unsupported.mdp
  src/backend/gporca/data/dxl/minidump/InnerJoin-With-OuterRefs.mdp
  src/backend/gporca/data/dxl/minidump/OuterJoin-With-OuterRefs.mdp
  src/backend/gporca/data/dxl/parse_tests/q26-Metadata.xml
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalDifference.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalDifferenceAll.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalIntersectAll.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalLeftAntiSemiJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalLeftSemiJoin.cpp
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerMDGPDBFunc.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerMDGPDBScalarOp.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
  src/backend/gporca/libnaucrates/include/naucrates/md/CMDFunctionGPDB.h
  src/backend/gporca/libnaucrates/include/naucrates/md/CMDScalarOpGPDB.h
  src/backend/gporca/libnaucrates/include/naucrates/md/IMDFunction.h
  src/backend/gporca/libnaucrates/include/naucrates/md/IMDScalarOp.h
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatsPred.h
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatsPredJoin.h
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatsPredUtils.h
  src/backend/gporca/libnaucrates/src/md/CMDFunctionGPDB.cpp
  src/backend/gporca/libnaucrates/src/md/CMDScalarOpGPDB.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerMDGPDBFunc.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerMDGPDBScalarOp.cpp
  src/backend/gporca/libnaucrates/src/statistics/CJoinStatsProcessor.cpp
  src/backend/gporca/libnaucrates/src/statistics/CLeftOuterJoinStatsProcessor.cpp
  src/backend/gporca/libnaucrates/src/statistics/CLeftSemiJoinStatsProcessor.cpp
  src/backend/gporca/libnaucrates/src/statistics/CStatisticsUtils.cpp
  src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp
  src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/include/catalog/pg_operator.h
  src/include/catalog/pg_proc.h
  src/include/gpopt/gpdbwrappers.h
  src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
  src/test/regress/expected/join_optimizer.out
Labels: area: gporca, topic: gporca, version: 7X_ALPHA

#10244 [GP RELEASE]Recompile plperl to set the right RUNPATH
  gpAux/Makefile
Labels: topic: upgrade

#10247 NDV-preserving functions, take 2
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/gporca/data/dxl/minidump/EquiJoinOnExpr-Supported.mdp
  src/backend/gporca/data/dxl/minidump/EquiJoinOnExpr-Unsupported.mdp
  src/backend/gporca/data/dxl/minidump/InnerJoin-With-OuterRefs.mdp
  src/backend/gporca/data/dxl/minidump/OuterJoin-With-OuterRefs.mdp
  src/backend/gporca/data/dxl/parse_tests/q26-Metadata.xml
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalDifference.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalDifferenceAll.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalIntersectAll.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalLeftAntiSemiJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalLeftSemiJoin.cpp
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerMDGPDBFunc.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerMDGPDBScalarOp.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
  src/backend/gporca/libnaucrates/include/naucrates/md/CMDFunctionGPDB.h
  src/backend/gporca/libnaucrates/include/naucrates/md/CMDScalarOpGPDB.h
  src/backend/gporca/libnaucrates/include/naucrates/md/IMDFunction.h
  src/backend/gporca/libnaucrates/include/naucrates/md/IMDScalarOp.h
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatsPred.h
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatsPredJoin.h
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatsPredUtils.h
  src/backend/gporca/libnaucrates/src/md/CMDFunctionGPDB.cpp
  src/backend/gporca/libnaucrates/src/md/CMDScalarOpGPDB.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerMDGPDBFunc.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerMDGPDBScalarOp.cpp
  src/backend/gporca/libnaucrates/src/statistics/CJoinStatsProcessor.cpp
  src/backend/gporca/libnaucrates/src/statistics/CLeftOuterJoinStatsProcessor.cpp
  src/backend/gporca/libnaucrates/src/statistics/CLeftSemiJoinStatsProcessor.cpp
  src/backend/gporca/libnaucrates/src/statistics/CStatisticsUtils.cpp
  src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp
  src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/include/catalog/pg_operator.h
  src/include/catalog/pg_proc.h
  src/include/gpopt/gpdbwrappers.h
  src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/join_optimizer.out
Labels: area: gporca, topic: gporca, version: 7X_ALPHA

#10242 [BACKPORT] Support multiple INITPLAN functions in one query.
  src/backend/executor/nodeFunctionscan.c
  src/backend/executor/nodeSubplan.c
  src/backend/nodes/copyfuncs.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfast.c
  src/backend/optimizer/plan/createplan.c
  src/include/nodes/execnodes.h
  src/include/nodes/plannodes.h
  src/test/regress/expected/function_extensions.out
  src/test/regress/expected/function_extensions_optimizer.out
  src/test/regress/sql/function_extensions.sql
Labels: version: 6X_STABLE

#10209 Remove unnecessary projections from duplicate sensitive Distribute(s) in ORCA
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, topic: gporca, version: 5X_STABLE

#10203 [Backport 6X] Using gp_add_segment to register mirror in catalog. (#9974)
  gpMgmt/bin/gppylib/system/configurationImplGpdb.py
  src/test/isolation2/expected/segwalrep/recoverseg_from_file.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/segwalrep/recoverseg_from_file.sql
Labels: version: 6X_STABLE

#10265 Fall back with window function plus corr subquery in target list
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CQueryMutators.cpp
  src/include/gpopt/gpdbwrappers.h
  src/include/gpopt/translate/CQueryMutators.h
  src/test/regress/expected/gporca_optimizer.out
Labels: area: gporca, topic: gporca, version: 6X_STABLE

#10276 Fix test_gpdb slack command pipeline to work with new master changes
  src/backend/gporca/concourse/test_orca_pipeline.yml
Labels: area: gporca, topic: gporca

#10285 Fix flaky test exttab1
  src/backend/commands/copy.c
Labels: needs: backport

#10271 Fix flaky test terminate_in_gang_creation
  src/test/isolation2/expected/terminate_in_gang_creation.out
  src/test/isolation2/sql/terminate_in_gang_creation.sql
Labels: needs: backport

#10293 BACKPORT 6X: Fix flaky test terminate_in_gang_creation
  src/test/isolation2/expected/terminate_in_gang_creation.out
  src/test/isolation2/sql/terminate_in_gang_creation.sql
Labels: version: 6X_STABLE

#10294 [Backport 6X]Fix flaky test exttab1 and pxf_fdw
  src/backend/commands/copy.c
Labels: version: 6X_STABLE

#10291 (6x backport)Fix lateral PANIC issue when subquery contain limit or groupby.
  src/backend/optimizer/path/allpaths.c
  src/test/regress/expected/join_gp.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/sql/join_gp.sql
Labels: backport, version: 6X_STABLE

#10299 [Backport 6X]Increase retry count for pg_rewind tests' replication promotion and streaming.
  src/bin/pg_rewind/sql/config_test.sh
Labels: backport, version: 6X_STABLE

#10312 (6x backport) GetLatestSnapshot on QEs always return without distributed snapshot.
  src/backend/utils/time/snapmgr.c
  src/test/isolation2/expected/distributed_snapshot.out
  src/test/isolation2/sql/distributed_snapshot.sql
Labels: backport, version: 6X_STABLE

#10266 resgroup: fix the cpu value of the per host status view
  src/backend/catalog/gp_toolkit.sql
Labels: topic: resource group, type: bug

#10298 Fix CASE WHEN IS NOT DISTINCT FROM clause incorrect dump.
  src/backend/utils/adt/ruleutils.c
  src/test/regress/expected/case_gp.out
  src/test/regress/sql/case_gp.sql
Labels: type: bug

#10346 Make cdbpullup_missingVarWalker also consider PlaceHolderVar.
  src/backend/cdb/cdbpullup.c
  src/test/regress/expected/join_gp.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/sql/join_gp.sql
Labels: needs: backport

#10353 (6x backport) Make cdbpullup_missingVarWalker also consider PlaceHolderVar.
  src/backend/cdb/cdbpullup.c
  src/test/regress/expected/join_gp.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/sql/join_gp.sql
Labels: backport, version: 6X_STABLE

#10349 [6X backport]Fix flaky appendonly test.
  src/test/regress/input/appendonly.source
  src/test/regress/output/appendonly.source
Labels: backport, version: 6X_STABLE

#10309 Improve handling of target lists of window queries
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CQueryMutators.cpp
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/backend/gpopt/translate/CTranslatorUtils.cpp
  src/include/gpopt/gpdbwrappers.h
  src/include/gpopt/translate/CQueryMutators.h
  src/include/gpopt/translate/CTranslatorUtils.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, topic: gporca, version: 7X_ALPHA

#10345 Disallow to change the distribution policy to REPLICATED for partition table
  src/backend/commands/tablecmds.c
  src/test/regress/expected/rpt.out
  src/test/regress/sql/rpt.sql
Labels: backport, version: 6X_STABLE

#10356 Clean up the internal functions to merge partition stats a bit.
  src/backend/cdb/cdbpartition.c
  src/backend/commands/analyze.c
  src/backend/commands/analyzeutils.c
  src/include/cdb/cdbpartition.h
  src/include/commands/analyzeutils.h
Labels: area: gporca

#10319 6X: gpexpand: cleanup new segments in parallel
  gpMgmt/bin/gpexpand
Labels: backport, topic: gpexpand, version: 6X_STABLE

#10384 [6X Backport]Fix tupdesc dangling pointer segfault in HashAgg
  src/backend/executor/execHHashagg.c
  src/test/regress/expected/partition.out
  src/test/regress/expected/partition_optimizer.out
  src/test/regress/sql/partition.sql
Labels: backport, version: 6X_STABLE

#10110 Skip external tables during analyze
  src/backend/commands/analyze.c
  src/test/regress/expected/partition.out
  src/test/regress/expected/partition_optimizer.out
  src/test/regress/sql/partition.sql
Labels: version: 6X_STABLE

#10385 6X: resgroup: fix the cpu value of the per host status view
  src/backend/catalog/gp_toolkit.sql
Labels: backport, topic: resource group, version: 6X_STABLE

#10365 [6X Backport]Fix CASE WHEN IS NOT DISTINCT FROM clause incorrect dump.
  src/backend/utils/adt/ruleutils.c
  src/test/regress/expected/case_gp.out
  src/test/regress/sql/case_gp.sql
Labels: backport, version: 6X_STABLE

#10367 [5X Backport]Fix CASE WHEN IS NOT DISTINCT FROM clause incorrect dump.
  src/backend/utils/adt/ruleutils.c
  src/test/binary_swap/test_binary_swap_pre.sql
  src/test/regress/expected/case_gp.out
  src/test/regress/sql/case_gp.sql
Labels: backport, version: 5X_STABLE

#10395 [BACKPORT] Skip foreign table when gpexpand
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  src/backend/commands/tablecmds.c
Labels: version: 6X_STABLE

#10253 README: Fix documentation to install Greenplum with ORCA in Ubuntu
  README.md
  README.ubuntu.bash
Labels: area: gporca, version: 6X_STABLE
