Repository greenplum-db/gpdb, pull requests merged in 2021-05, with the labels that each got.

#11906 [5X_STABLE] Replace Conan ORCA package pull with Github release fetch
  concourse/pipelines/5X_STABLE-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
  concourse/scripts/compile_gpdb_open_source_ubuntu.bash
  concourse/scripts/deb_create_package.bash
  depends/conanfile_gpbackup.txt
  depends/conanfile_orca.txt
  src/tools/docker/ubuntu16/Dockerfile_dist
Labels: version: 5X_STABLE

#11911 6X: Pin clang-toolchain image to specific version
  concourse/pipelines/gpdb_6X_STABLE-generated.yml
  concourse/pipelines/pr_pipeline.yml
  concourse/pipelines/templates/gpdb-tpl.yml
  concourse/tasks/check_format.yml
  src/backend/gporca/concourse/test_orca_pipeline.yml
Labels: version: 6X_STABLE

#11912 5X: Pin clang-toolchain image to specific version
  concourse/pipelines/5X_STABLE-generated.yml
  concourse/pipelines/pr_pipeline.yml
  concourse/pipelines/templates/gpdb-tpl.yml
  concourse/tasks/check_format.yml
Labels: version: 5X_STABLE

#11930 6X: Bump clang-format version to 11
  .travis.yml
  concourse/tasks/check_format.yml
  src/backend/gporca/.clang-format
Labels: version: 6X_STABLE

#11919 Don't reuse AO block if the corresponding segment file was closed
  src/backend/access/appendonly/appendonlyam.c
  src/test/isolation2/input/uao/bitmapindex_rescan.source
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/output/uao/bitmapindex_rescan.source
Labels: version: 6X_STABLE

#11920 Don't reuse AO block if the corresponding segment file was closed
  src/backend/access/appendonly/appendonlyam.c
  src/test/isolation2/input/uao/bitmapindex_rescan.source
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/output/uao/bitmapindex_rescan.source
Labels: version: 5X_STABLE

#11807 (6x backport from master) Avoid dispatching OIDs for InitPlan.
  src/backend/executor/execMain.c
  src/test/regress/expected/gpctas.out
  src/test/regress/sql/gpctas.sql
Labels: version: 6X_STABLE

#11858 6X: Fix treat COPY FROM dtx as a read-only dtx
  src/backend/cdb/cdbcopy.c
  src/test/regress/expected/gp_copy_dtx.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/gp_copy_dtx.sql
Labels: version: 6X_STABLE

#11940 5X: Backport quote_all_identifiers GUC
  src/backend/utils/adt/ruleutils.c
  src/backend/utils/misc/guc.c
  src/backend/utils/misc/postgresql.conf.sample
  src/include/utils/builtins.h
  src/test/regress/expected/partition.out
  src/test/regress/sql/partition.sql
Labels: backport, topic: upgrade, version: 5X_STABLE

#11939 6X: pg_dump(all): Allow quote_all_identifiers for 8.3
  src/bin/pg_dump/pg_dump.c
  src/bin/pg_dump/pg_dumpall.c
Labels: topic: upgrade, version: 6X_STABLE

#11991 5X: Update partition_optimizer.out for quote_all_identifiers test
  src/test/regress/expected/partition_optimizer.out
Labels: topic: upgrade, version: 5X_STABLE

#11882 Correctly cast types for all SetOps during DXL->Expr translation
  src/backend/gporca/data/dxl/minidump/ExceptAllCompatibleDataType.mdp
  src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 6X_STABLE

#11450 [5X] Remove Ubuntu tests from CI
  concourse/pipelines/5X_STABLE-generated.yml
  concourse/pipelines/README.md
  concourse/pipelines/gen_pipeline.py
  concourse/pipelines/templates/gpdb-tpl.yml
  concourse/scripts/compare_abi_ubuntu.bash
  concourse/scripts/compile_gpdb_open_source_ubuntu.bash
  concourse/scripts/compile_gpdb_ubuntu16.bash
  concourse/scripts/deb_create_package.bash
  concourse/scripts/deb_init_cluster.bash
  concourse/scripts/deb_test_cluster.bash
  concourse/scripts/deb_test_package.bash
  concourse/scripts/ic_gpdb_ubuntu.bash
  concourse/scripts/regression_tests_gpcloud.bash
  concourse/tasks/compile_gpdb_open_source_ubuntu.yml
  concourse/tasks/compile_gpdb_ubuntu16.yml
  concourse/tasks/deb_create_package.yml
  concourse/tasks/deb_test_package.yml
  concourse/tasks/ic_gpdb_ubuntu.yml
Labels: version: 5X_STABLE

#11893 ORCA falls with segfault when trying to select from view:
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/test/regress/expected/alter_table_gp.out
  src/test/regress/sql/alter_table_gp.sql
Labels: area: gporca

#11736 Fix duplicated include
  contrib/dblink/dblink.c
Labels: version: 6X_STABLE

#11966 [6X backport] Fix the double-free issue of work_set
  src/backend/utils/workfile_manager/workfile_mgr.c
Labels: version: 6X_STABLE

#11973 Fix double free of TupleSort memory context (5X)
  src/backend/executor/nodeSort.c
  src/backend/utils/misc/faultinjector.c
  src/include/utils/faultinjector.h
  src/test/regress/expected/query_finish_pending.out
  src/test/regress/expected/query_finish_pending_optimizer.out
  src/test/regress/sql/query_finish_pending.sql
Labels: version: 5X_STABLE

#12014 Fix double free of TupleSort memory context (6X)
  src/backend/executor/nodeSort.c
Labels: version: 6X_STABLE

#11915 Fix exec location INITPLAN not showing up in \df+
  src/bin/psql/describe.c
  src/test/regress/expected/psql_gp_commands.out
  src/test/regress/sql/psql_gp_commands.sql
Labels: needs: backport

#12019 Dispatch collClause field for CreateDomainStmt.
  src/backend/nodes/outfast.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfuncs.c
  src/test/regress/expected/domain.out
  src/test/regress/expected/domain_optimizer.out
  src/test/regress/sql/domain.sql
Labels: needs: backport

#12018 Correct behavior of CTAS with no data
  src/backend/commands/createas.c
  src/backend/executor/execMain.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfast.c
  src/backend/tcop/utility.c
  src/include/nodes/parsenodes.h
  src/test/regress/expected/gpctas.out
  src/test/regress/sql/gpctas.sql
Labels: needs: backport, type: bug

#12017 Fix exec location INITPLAN not showing up in \df+
  src/bin/psql/describe.c
  src/test/regress/expected/psql_gp_commands.out
  src/test/regress/sql/psql_gp_commands.sql
Labels: version: 6X_STABLE

#12030 (6x backport) Dispatch collClause field for CreateDomainStmt.
  src/backend/nodes/outfast.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfuncs.c
  src/test/regress/expected/domain.out
  src/test/regress/expected/domain_optimizer.out
  src/test/regress/sql/domain.sql
Labels: version: 6X_STABLE

#12009 Fix logical difference derived constraint property
  src/backend/gporca/data/dxl/minidump/InnerJoinOverJoinExcept.mdp
  src/backend/gporca/data/dxl/minidump/InnerJoinOverJoinExceptAll.mdp
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDifference.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDifferenceAll.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalIntersect.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalIntersectAll.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalSetOp.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalUnion.h
  src/backend/gporca/libgpopt/src/operators/CLogicalSetOp.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/qp_dml_joins.out
  src/test/regress/expected/qp_dml_joins_optimizer.out
  src/test/regress/sql/qp_dml_joins.sql
Labels: area: gporca, needs: backport, version: 7X_ALPHA

#11970 Fix Distribution Spec for Union ALL where the outer child is External Scan
  src/backend/gporca/data/dxl/minidump/CTAS-with-randomly-distributed-external-table.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpec.h
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecExternal.h
  src/backend/gporca/libgpopt/src/base/CDistributionSpecExternal.cpp
  src/backend/gporca/libgpopt/src/base/Makefile
  src/backend/gporca/libgpopt/src/operators/CPhysicalExternalScan.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalSerialUnionAll.cpp
  src/test/regress/data/location1.csv
  src/test/regress/data/location2.csv
  src/test/regress/data/location3.csv
  src/test/regress/greenplum_schedule
  src/test/regress/input/external_table_union_all.source
  src/test/regress/output/external_table_union_all.source
  src/test/regress/output/external_table_union_all_optimizer.source
Labels: area: gporca, needs: backport, version: 7X_ALPHA
