Repository greenplum-db/gpdb, pull requests merged in 2021-07, with the labels that each got.

#12225 Use 'ss' command in absence of 'netstat' to find active tcp port
  gpMgmt/bin/gppylib/commands/unix.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gpstate.py
Labels: gpcm_in

#12201 Fix crash in ORCA if root and leaf dropped column layouts mismatch
  src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
  src/backend/gporca/libnaucrates/src/md/CMDRelationGPDB.cpp
  src/test/regress/expected/qp_dropped_cols.out
  src/test/regress/expected/qp_dropped_cols_optimizer.out
  src/test/regress/sql/qp_dropped_cols.sql
Labels: area: gporca, needs: backport, version: 6X_STABLE

#12224 Typo fix in logging message of UpperBoundNDVs module
  src/backend/gporca/libnaucrates/src/statistics/CUpperBoundNDVs.cpp
Labels: area: gporca, community

#12230 Add tests for partitioned table with dropped column mismatch between root & leaf
  src/test/regress/expected/qp_dropped_cols.out
  src/test/regress/expected/qp_dropped_cols_optimizer.out
  src/test/regress/sql/qp_dropped_cols.sql
Labels: area: gporca, version: 7X_ALPHA

#12252 (6x only) Fix unlock leaf partitions.
  src/backend/parser/parse_clause.c
  src/backend/utils/cache/plancache.c
  src/test/isolation2/expected/cached_plan.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/cached_plan.sql
Labels: type: bug, version: 6X_STABLE

#12197 Wrong snapshot for EOF corrupts data in AO/AOCO
  src/backend/access/aocs/aocs_compaction.c
  src/backend/access/aocs/aocsam.c
  src/backend/access/appendonly/appendonly_compaction.c
  src/backend/access/appendonly/appendonlyam.c
  src/backend/access/appendonly/appendonlywriter.c
  src/test/isolation2/input/uao/snapshot_eof.source
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/output/uao/snapshot_eof.source
Labels: community

#12238 Check if subpath can do motion.
  src/backend/cdb/cdbpath.c
  src/test/regress/expected/rpt_joins.out
  src/test/regress/sql/rpt_joins.sql
Labels: community

#11850 Fix a typo in md.c
  src/backend/storage/smgr/md.c
Labels: community

#11767 [6X] Fix TypeError for sig_handler function in gpexpand #11766
  gpMgmt/bin/gpexpand
Labels: community, version: 6X_STABLE

#11555 [6X backport] analyzedb - include FirstNormalObjectId
  gpMgmt/bin/analyzedb
Labels: community

#11245 [6X backport] Enable for partitioned tables to use column-wise statistics setting
  src/backend/commands/analyze.c
  src/backend/commands/analyzeutils.c
  src/test/regress/expected/incremental_analyze.out
  src/test/regress/sql/incremental_analyze.sql
Labels: community, version: 6X_STABLE

#11378 Fix that kill_9_segment_processes can not get a list of processes to kill.
  gpMgmt/bin/gppylib/commands/unix.py
Labels: community, needs: backport

#12278 correct plan for CTAS with volatile functions.
  src/backend/cdb/cdbllize.c
  src/backend/cdb/cdbpath.c
  src/test/regress/expected/bfv_planner.out
  src/test/regress/expected/bfv_planner_optimizer.out
  src/test/regress/expected/rpt.out
  src/test/regress/expected/rpt_optimizer.out
  src/test/regress/sql/bfv_planner.sql
  src/test/regress/sql/rpt.sql
Labels: topic: planner

#12294 GPORCA CI: add workload4 to explain pipeline
  src/backend/gporca/concourse/test_explain_pipeline.yml
Labels: area: gporca, version: 6X_STABLE

#10866 Fix possible wrong completionTag in Copy From
  src/backend/cdb/cdbcopy.c
  src/backend/cdb/cdbsreh.c
  src/backend/cdb/dispatcher/cdbdisp_async.c
  src/backend/commands/copy.c
  src/include/cdb/cdbdispatchresult.h
  src/interfaces/libpq/fe-protocol3.c
  src/interfaces/libpq/libpq-int.h
  src/test/regress/expected/gpcopy_dispatch.out
  src/test/regress/sql/gpcopy_dispatch.sql
Labels: community, needs: backport

#12300 Fix Readme for Mac OS
  README.macOS.bash
Labels: gpcm_in

#12227 init holdTillEndXact and add asserts
  src/backend/storage/lmgr/lock.c
  src/backend/utils/gdd/gddfuncs.c
Labels: version: 7X_ALPHA

#12279 Fix Cardinality estimation for not well defined histograms
  src/backend/gporca/data/dxl/minidump/NotWellDefinedDisjunctConjunctPredicates.mdp
  src/backend/gporca/libnaucrates/src/statistics/CFilterStatsProcessor.cpp
  src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, type: bug, version: 7X_ALPHA

#12293 GPORCA CI: add workload4 to explain pipeline
  src/backend/gporca/concourse/test_explain_pipeline.yml
Labels: area: gporca

#12295 Vacuum should read fresh version of pg_class for update
  src/backend/commands/vacuum.c
  src/test/regress/expected/vacuum_gp.out
  src/test/regress/sql/vacuum_gp.sql
Labels: version: 6X_STABLE

#12274 [Backport to 6X] Fix transaction may be committed on coordinator, aborted on segments
  src/backend/access/transam/xlog.c
  src/backend/cdb/cdbtm.c
  src/test/isolation2/expected/checkpoint_dtx_info.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/checkpoint_dtx_info.sql
Labels: community, version: 6X_STABLE

#12130 Improve performance of DELETEs on randomly distributed tables in ORCA.
  src/backend/gporca/data/dxl/minidump/DeleteRandomDistr.mdp
  src/backend/gporca/data/dxl/minidump/DeleteRandomlyDistributedTable.mdp
  src/backend/gporca/data/dxl/minidump/DeleteRandomlyDistributedTableJoin.mdp
  src/backend/gporca/data/dxl/minidump/SelfUpdate.mdp
  src/backend/gporca/data/dxl/minidump/UpdateRandomDistr.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecRandom.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysical.h
  src/backend/gporca/libgpopt/src/base/CDistributionSpecRandom.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysical.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalDML.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalScan.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CDMLTest.cpp
  src/test/regress/expected/bfv_dml.out
  src/test/regress/expected/bfv_dml_optimizer.out
  src/test/regress/expected/qp_subquery_optimizer.out
  src/test/regress/sql/bfv_dml.sql
Labels: area: gporca, version: 7X_ALPHA

#12292 Improve performance of DELETEs on randomly distributed tables in ORCA (6X)
  src/backend/gporca/data/dxl/minidump/DeleteRandomDistr.mdp
  src/backend/gporca/data/dxl/minidump/DeleteRandomlyDistributedTable.mdp
  src/backend/gporca/data/dxl/minidump/DeleteRandomlyDistributedTableJoin.mdp
  src/backend/gporca/data/dxl/minidump/SelfUpdate.mdp
  src/backend/gporca/data/dxl/minidump/UpdateRandomDistr.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecRandom.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysical.h
  src/backend/gporca/libgpopt/src/base/CDistributionSpecRandom.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysical.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalDML.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalScan.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CDMLTest.cpp
  src/test/regress/expected/bfv_dml.out
  src/test/regress/expected/bfv_dml_optimizer.out
  src/test/regress/expected/qp_subquery_optimizer.out
  src/test/regress/expected/update_gp_optimizer.out
  src/test/regress/sql/bfv_dml.sql
Labels: area: gporca, version: 6X_STABLE

#12283 Update distribution spec for inner child of left outer index NL join to handle random distributions
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftOuterIndexNLJoin.h
  src/backend/gporca/libgpopt/src/engine/CEngine.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftOuterIndexNLJoin.cpp
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 7X_ALPHA

#12303 Update distribution spec for inner child of left outer index NL join to handle random distributions (6X)
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftOuterIndexNLJoin.h
  src/backend/gporca/libgpopt/src/engine/CEngine.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftOuterIndexNLJoin.cpp
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca

#11959 fix missing DESTDIR in pygresql Makefile target
  gpMgmt/bin/Makefile
Labels: community

#12318 Fix tainted replicated motion
  src/backend/gporca/data/dxl/minidump/InsertReplicatedIntoSerialHashDistributedTable.mdp
  src/backend/gporca/data/dxl/minidump/ReplicatedTableGroupBy.mdp
  src/backend/gporca/data/dxl/minidump/ReplicatedTableInClause.mdp
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/rpt_optimizer.out
Labels: area: gporca, type: bug, version: 7X_ALPHA

#12330 GPORCA CI: use 7X stats for workloads in explain_master pipeline
  concourse/tasks/run_explain_suite.yml
Labels: area: gporca

#12319 Enforce Redistribute Motion of insert replicated into random
  src/backend/gporca/data/dxl/minidump/CTAS-random-distributed-from-replicated-distributed-table.mdp
  src/backend/gporca/data/dxl/minidump/Delete-With-Limit-In-Subquery.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/src/base/CDistributionSpecRandom.cpp
  src/backend/gporca/libgpopt/src/base/CDistributionSpecReplicated.cpp
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, version: 7X_ALPHA

#11711 Display the number of failed segments in gprecoverseg -r
  gpMgmt/bin/gppylib/operations/rebalanceSegments.py
Labels: community

#12335 (6x only) Fix flaky test case in bfv_dml.
  src/test/regress/expected/bfv_dml.out
  src/test/regress/expected/bfv_dml_optimizer.out
  src/test/regress/sql/bfv_dml.sql
Labels: version: 6X_STABLE

#11383 Fix orphan temp table on the coordinator
  src/backend/cdb/cdbtm.c
  src/backend/cdb/dispatcher/cdbgang.c
  src/backend/executor/execScan.c
  src/backend/tcop/postgres.c
  src/include/cdb/cdbgang.h
  src/test/isolation2/expected/orphan_temp_table.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/orphan_temp_table.sql
Labels: community

#12342 (backport to 6x) Init holdTillEndXact and add asserts.
  src/backend/storage/lmgr/lock.c
  src/backend/utils/gdd/gddfuncs.c
Labels: version: 6X_STABLE

#12325 [6X backport] Fix Cardinality estimation for not well defined histograms
  src/backend/gporca/data/dxl/minidump/NotWellDefinedDisjunctConjunctPredicates.mdp
  src/backend/gporca/libnaucrates/src/statistics/CFilterStatsProcessor.cpp
  src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, backport, version: 6X_STABLE

#12362 Bump ORCA version to 3.118.0
  config/orca.m4
  configure
  gpAux/releng/releng.mk
Labels: area: gporca, version: 5X_STABLE

#12327 6X: Ensure that pg_dump considers 5X when dumping functions
  src/bin/pg_dump/pg_dump.c
Labels: version: 6X_STABLE

#12368 [5X_STABLE] ci: add rc-build-type-gcs to release candidate rpms
  concourse/pipelines/5X_STABLE-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: version: 5X_STABLE

#12369 Dump extension functions under pg_catalog for 5X
  src/bin/pg_dump/pg_dump.c
Labels: version: 7X_ALPHA

#11904 Fix distribution spec used for CTE producer requirement
  src/backend/gporca/data/dxl/minidump/CTE-Join-Redistribute-Producer.mdp
  src/backend/gporca/data/dxl/minidump/CTE-NoPushProperties.mdp
  src/backend/gporca/data/dxl/minidump/CTE-PushProperties.mdp
  src/backend/gporca/data/dxl/minidump/CTE-volatile.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpec.h
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecHashed.h
  src/backend/gporca/libgpopt/include/gpopt/base/CReqdPropPlan.h
  src/backend/gporca/libgpopt/src/base/CCTEReq.cpp
  src/backend/gporca/libgpopt/src/base/CDistributionSpecHashed.cpp
  src/backend/gporca/libgpopt/src/base/COptimizationContext.cpp
  src/backend/gporca/libgpopt/src/base/CReqdPropPlan.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, version: 6X_STABLE

#12380 Fix clang-tidy errors
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecHashed.h
  src/backend/gporca/libgpopt/src/base/CDistributionSpecHashed.cpp
Labels: area: gporca

#12387 Bump ORCA version to 3.119.0
  config/orca.m4
  configure
  gpAux/releng/releng.mk
Labels: area: gporca, version: 5X_STABLE

#12360 [5X] ci: Enable OS selection for dev pipelines
  concourse/pipelines/gen_pipeline.py
Labels: version: 5X_STABLE

#12379 Fix autovacuum crash
  src/backend/postmaster/autovacuum.c
Labels: area: server, version: 7X_ALPHA

#12297 fix multiple typos
  gpMgmt/bin/gpcheckcat
  gpMgmt/bin/pythonSrc/PyGreSQL-4.0/pgmodule.c
  gpMgmt/demo/gppkg/generate_sample_gppkg.sh
  gpcontrib/gpcloud/src/s3restful_service.cpp
  gpcontrib/gpmapreduce/src/yaml_parse.y
  gpcontrib/orafce/file.c
  gpcontrib/orafce/shmmc.c
  gpdb-doc/dita/admin_guide/managing/backup-s3-plugin.xml
  src/backend/access/appendonly/appendonly_visimap_store.c
  src/backend/access/appendonly/appendonlywriter.c
  src/backend/access/bitmap/bitmapinsert.c
  src/backend/access/transam/xlog.c
  src/backend/cdb/cdbdtxrecovery.c
  src/backend/cdb/dispatcher/cdbgang_async.c
  src/backend/fts/ftsprobe.c
  src/backend/replication/syncrep.c
  src/backend/replication/walsender.c
  src/backend/utils/misc/guc_gp.c
  src/backend/utils/resgroup/resgroup-ops-linux.c
  src/backend/utils/workfile_manager/workfile_mgr.c
  src/include/catalog/pg_control.h
  src/include/gppc/gppc.h
  src/include/replication/walsender_private.h
  src/pl/plpython/plpy_exec.c
  src/test/isolation2/expected/segwalrep/commit_blocking_on_standby.out
  src/test/isolation2/expected/segwalrep/max_slot_wal_keep_size.out
  src/test/isolation2/sql/segwalrep/commit_blocking_on_standby.sql
  src/test/isolation2/sql/segwalrep/max_slot_wal_keep_size.sql
Labels: version: 6X_STABLE

#12375 Check if index pathkeys list is empty in find_usable_indexes() function
  src/backend/optimizer/path/indxpath.c
Labels: community

#12322 Do not pass deprecated flags to gpnetbenchClient
  gpMgmt/bin/gpcheckperf
  gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
Labels: gpcm_in

#12393 Do not pass deprecated flags to gpnetbenchClient
  gpMgmt/bin/gpcheckperf
  gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
Labels: gpcm_in

#12361 Generate additional partitioning request for greedy xform alternative in Orca
  src/backend/gporca/data/dxl/minidump/JoinOrderDPE.mdp
  src/backend/gporca/data/dxl/minidump/Union-On-HJNs.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogical.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalFullOuterJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalInnerJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalLeftAntiSemiJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalLeftAntiSemiJoinNotIn.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalLeftOuterJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalLeftSemiJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalRightOuterJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalFullMergeJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalInnerHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftAntiSemiHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftAntiSemiHashJoinNotIn.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftOuterHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftSemiHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalRightOuterHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorExprToDXL.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrder.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderDP.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderDPv2.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderGreedy.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderMinCard.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXform.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXformExpandNAryJoinGreedy.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXformUtils.h
  src/backend/gporca/libgpopt/src/operators/CExpressionUtils.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalFullOuterJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalInnerJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalLeftAntiSemiJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalLeftAntiSemiJoinNotIn.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalLeftOuterJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalLeftSemiJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalRightOuterJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalFullMergeJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalInnerHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftAntiSemiHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftAntiSemiHashJoinNotIn.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftOuterHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftSemiHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalRightOuterHashJoin.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
  src/backend/gporca/libgpopt/src/xforms/CJoinOrder.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformExpandNAryJoinGreedy.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, version: 7X_ALPHA

#11141 Fix: gpcheckperf did not close the SSH connections completely
  gpMgmt/bin/gpcheckperf
Labels: community

#12394 Fix gpconfig filedescriptor out of range issue
  gpMgmt/bin/gpconfig
  gpMgmt/bin/gppylib/operations/detect_unreachable_hosts.py
  gpMgmt/test/behave/mgmt_utils/gpconfig.feature
Labels: gpcm_in

#12411 [6X] Generate additional partitioning request for greedy xform alternative in Orca
  src/backend/gporca/data/dxl/minidump/JoinOrderDPE.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-DPE-PartitionSelectorRewindability.mdp
  src/backend/gporca/data/dxl/minidump/Union-On-HJNs.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogical.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalFullOuterJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalInnerJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalLeftAntiSemiJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalLeftAntiSemiJoinNotIn.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalLeftOuterJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalLeftSemiJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalRightOuterJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalFullMergeJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalInnerHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftAntiSemiHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftAntiSemiHashJoinNotIn.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftOuterHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftSemiHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalRightOuterHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrder.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderDP.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderDPv2.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderGreedy.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderMinCard.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXform.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXformExpandNAryJoinGreedy.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXformUtils.h
  src/backend/gporca/libgpopt/src/operators/CExpressionUtils.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalFullOuterJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalInnerJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalLeftAntiSemiJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalLeftAntiSemiJoinNotIn.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalLeftOuterJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalLeftSemiJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalRightOuterJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalFullMergeJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalInnerHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftAntiSemiHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftAntiSemiHashJoinNotIn.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftOuterHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftSemiHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalRightOuterHashJoin.cpp
  src/backend/gporca/libgpopt/src/xforms/CJoinOrder.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformExpandNAryJoinGreedy.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/gporca_optimizer.out
Labels: area: gporca, version: 6X_STABLE
