Repository greenplum-db/gpdb, pull requests merged in 2021-11, with the labels that each got.

#12730 [6X] disable cte sharing in subplan
  src/backend/optimizer/plan/subselect.c
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/shared_scan.out
  src/test/regress/expected/shared_scan_optimizer.out
  src/test/regress/sql/gporca.sql
  src/test/regress/sql/shared_scan.sql
Labels: version: 6X_STABLE

#12753 [6X]libpq: Change "options" dispchar to normal
  src/interfaces/libpq/fe-connect.c
Labels: version: 6X_STABLE

#12751 ORCA: Avoid divide-by-zero when intersecting histogram buckets
  src/backend/gporca/libnaucrates/src/statistics/CBucket.cpp
  src/backend/gporca/server/include/unittest/dxl/statistics/CBucketTest.h
  src/backend/gporca/server/src/unittest/dxl/statistics/CBucketTest.cpp
Labels: type: bug, area: gporca, version: 7X_ALPHA

#12586 Allow requesting hashed distribution for NL LOJ inner childs
  src/backend/gpopt/config/CConfigParamMapping.cpp
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalJoin.h
  src/backend/gporca/libgpopt/src/operators/CPhysicalInnerNLJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
  src/backend/gporca/libnaucrates/include/naucrates/traceflags/traceflags.h
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/include/utils/unsync_guc_name.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 6X_STABLE

#12727 Add GUCs to tune TCP keepalives for QD/QE libpq connections
  src/backend/cdb/cdbvars.c
  src/backend/cdb/dispatcher/cdbconn.c
  src/backend/utils/misc/guc_gp.c
  src/include/cdb/cdbvars.h
  src/include/utils/unsync_guc_name.h
  src/test/regress/expected/.gitignore
  src/test/regress/greenplum_schedule
  src/test/regress/input/gp_dispatch_keepalives.source
  src/test/regress/output/gp_dispatch_keepalives.source
  src/test/regress/regress_gp.c
  src/test/regress/sql/.gitignore
Labels: version: 7X_ALPHA, needs: backport

#12775 Modify change tracking disabled assertion to work with gpaddmirrors
  src/backend/cdb/cdbresynchronizechangetracking.c
Labels: version: 5X_STABLE

#9652 fix ResProcSleep doesn't trigger deadlock check
  src/backend/postmaster/autostats.c
  src/backend/storage/lmgr/proc.c
  src/backend/utils/resscheduler/resqueue.c
  src/test/isolation2/expected/resource_queue.out
  src/test/isolation2/expected/resource_queue_deadlock.out
  src/test/isolation2/init_file_isolation2
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/resource_queue.sql
  src/test/isolation2/sql/resource_queue_deadlock.sql
Labels: community

#12744 Improve exhaustive2 algorithm to penalize predicates that create NLJs
  src/backend/gporca/data/dxl/minidump/ExpandJoinOrder.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-CompsiteKey-NoMotion.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-DistKey-Multiple-Predicates.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-MultiDistKeys-IndexKeys.mdp
  src/backend/gporca/data/dxl/minidump/LeftJoinDPv2JoinOrder.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libgpopt/src/xforms/CJoinOrderDPv2.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, version: 7X_ALPHA

#12729 Fix clang++-13 compile error
  src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderDPv2.h
Labels: area: gporca

#12731 Backport bitmap index scan when concurrent insert update full bitmap page on 6X_STABLE
  src/backend/access/bitmap/bitmap.c
  src/backend/access/bitmap/bitmapinsert.c
  src/backend/access/bitmap/bitmapsearch.c
  src/backend/access/bitmap/bitmaputil.c
  src/backend/optimizer/path/indxpath.c
  src/backend/utils/adt/selfuncs.c
  src/include/access/bitmap.h
  src/test/isolation2/expected/bitmap_index_concurrent.out
  src/test/isolation2/expected/bitmap_union.out
  src/test/isolation2/expected/bitmap_union_optimizer.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/bitmap_index_concurrent.sql
  src/test/isolation2/sql/bitmap_union.sql
Labels: version: 6X_STABLE

#12757 fix incorrect isolation2 case segwalrep/recoverseg_from_file
  src/test/isolation2/expected/segwalrep/recoverseg_from_file.out
  src/test/isolation2/sql/segwalrep/recoverseg_from_file.sql
Labels: community

#12481 Changes to avoid gpinitsystem failures in case bash banner is present
  concourse/pipelines/templates/gpdb-tpl.yml
  gpMgmt/bin/gpinitsystem
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/bin/lib/gp_bash_functions.sh
  gpMgmt/bin/lib/gpcreateseg.sh
  gpMgmt/test/behave/mgmt_utils/environment.py
  gpMgmt/test/behave/mgmt_utils/gp_bash_functions.feature
  gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in

#12807 (6x) Fix bug: cdbpullup_findEclassInTargetList not consider compatible types.
  src/backend/cdb/cdbpullup.c
  src/test/regress/input/gpcopy.source
  src/test/regress/output/gpcopy.source
Labels: version: 6X_STABLE

#12802 Improve exhaustive2 algorithm to penalize predicates that create NLJs
  src/backend/gporca/data/dxl/minidump/ExpandJoinOrder.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-CompsiteKey-NoMotion.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-DistKey-Multiple-Predicates.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-MultiDistKeys-IndexKeys.mdp
  src/backend/gporca/data/dxl/minidump/LeftJoinDPv2JoinOrder.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libgpopt/src/xforms/CJoinOrderDPv2.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, version: 6X_STABLE

#12810 gpactivatestandby_ubuntu18 concourse pipeline fix
  concourse/pipelines/gpdb_master-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
  concourse/tasks/run_behave_on_ccp_cluster.yml
Labels: gpcm_in

#12442 search ETag case insensitively
  gpcontrib/gpcloud/src/s3interface.cpp
  gpcontrib/gpcloud/src/s3url.cpp
Labels: community

#12791 [6X] Add GUCs to tune TCP keepalives for QD/QE libpq connections
  src/backend/cdb/cdbvars.c
  src/backend/cdb/dispatcher/cdbconn.c
  src/backend/utils/misc/guc_gp.c
  src/include/cdb/cdbvars.h
  src/include/utils/unsync_guc_name.h
  src/test/regress/expected/.gitignore
  src/test/regress/greenplum_schedule
  src/test/regress/input/gp_dispatch_keepalives.source
  src/test/regress/output/gp_dispatch_keepalives.source
  src/test/regress/regress_gp.c
  src/test/regress/sql/.gitignore
Labels: area: server

#12755 Ensure PrepareTempTablespaces() is called when using temp tablespaces
  src/backend/executor/nodeShareInputScan.c
  src/backend/storage/file/buffile.c
  src/test/regress/input/temp_tablespaces.source
  src/test/regress/output/temp_tablespaces.source
Labels: version: 6X_STABLE

#12860 6X: Disable pg_upgrade check for line datatypes
  contrib/pg_upgrade/check.c
  contrib/pg_upgrade/pg_upgrade.h
  contrib/pg_upgrade/version.c
Labels: version: 6X_STABLE

#12804 Fixing gpdb6 icw_gporca test failures on RHEL8
  gpMgmt/sbin/packcore
  src/test/ssl/Makefile
  src/test/ssl/cas.config
  src/test/ssl/ssl/both-cas-1.crt
  src/test/ssl/ssl/both-cas-2.crt
  src/test/ssl/ssl/client+client_ca.crt
  src/test/ssl/ssl/client-revoked.crt
  src/test/ssl/ssl/client-revoked.key
  src/test/ssl/ssl/client.crl
  src/test/ssl/ssl/client.crt
  src/test/ssl/ssl/client.key
  src/test/ssl/ssl/client_ca.crt
  src/test/ssl/ssl/client_ca.key
  src/test/ssl/ssl/root+client.crl
  src/test/ssl/ssl/root+client_ca.crt
  src/test/ssl/ssl/root+server.crl
  src/test/ssl/ssl/root+server_ca.crt
  src/test/ssl/ssl/root.crl
  src/test/ssl/ssl/root_ca.crt
  src/test/ssl/ssl/root_ca.key
  src/test/ssl/ssl/server-cn-and-alt-names.crt
  src/test/ssl/ssl/server-cn-and-alt-names.key
  src/test/ssl/ssl/server-cn-only.crt
  src/test/ssl/ssl/server-cn-only.key
  src/test/ssl/ssl/server-multiple-alt-names.crt
  src/test/ssl/ssl/server-multiple-alt-names.key
  src/test/ssl/ssl/server-no-names.crt
  src/test/ssl/ssl/server-no-names.key
  src/test/ssl/ssl/server-revoked.crt
  src/test/ssl/ssl/server-revoked.key
  src/test/ssl/ssl/server-single-alt-name.crt
  src/test/ssl/ssl/server-single-alt-name.key
  src/test/ssl/ssl/server-ss.crt
  src/test/ssl/ssl/server-ss.key
  src/test/ssl/ssl/server.crl
  src/test/ssl/ssl/server_ca.crt
  src/test/ssl/ssl/server_ca.key
Labels: gpcm_in

#12861 Remove stale assertion in ORCA
  src/backend/gporca/libgpopt/src/xforms/CSubqueryHandler.cpp
  src/backend/gporca/server/include/unittest/gpopt/xforms/CSubqueryHandlerTest.h
  src/backend/gporca/server/src/unittest/gpopt/xforms/CSubqueryHandlerTest.cpp
  src/test/regress/expected/subselect_optimizer.out
Labels: area: gporca, version: 6X_STABLE

#12849 Updating logs for restricted mode along with gpstart -m
  gpMgmt/bin/gppylib/test/unit/test_unit_gpstart.py
  gpMgmt/bin/gpstart
  gpMgmt/test/behave/mgmt_utils/gpstart.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in

#12811 Fix bug that Orca generates wrong plan for CTAS
  src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, community

#12882 Remove stale assertion in ORCA
  src/backend/gporca/libgpopt/src/xforms/CSubqueryHandler.cpp
  src/backend/gporca/server/include/unittest/gpopt/xforms/CSubqueryHandlerTest.h
  src/backend/gporca/server/src/unittest/gpopt/xforms/CSubqueryHandlerTest.cpp
Labels: area: gporca, version: 7X_ALPHA

#12287 Fixing PR #12238.
  src/backend/cdb/cdbpath.c
  src/backend/optimizer/path/allpaths.c
  src/backend/optimizer/util/pathnode.c
Labels: community
