Repository greenplum-db/gpdb, pull requests merged in 2021-01, with the labels that each got.

#11327 [6X Backport] Fix possible gprecoverseg stuck
  gpMgmt/bin/gppylib/commands/base.py
Labels: area: management utilities, type: bug, version: 6X_STABLE

#11322 Fix Orca stream operator<< precision
  src/backend/gporca/data/dxl/statistics/Basic-Statistics-Output.xml
  src/backend/gporca/data/dxl/statistics/Merge-Output-Numeric.xml
  src/backend/gporca/data/dxl/statistics/Numeric-Output-2-E-MaxBoundary.xml
  src/backend/gporca/data/dxl/statistics/Numeric-Output-2-E-MinBoundary.xml
  src/backend/gporca/data/dxl/statistics/Numeric-Output-2-GT-MinBoundary.xml
  src/backend/gporca/data/dxl/statistics/Numeric-Output-2-GTE-MaxBoundary.xml
  src/backend/gporca/data/dxl/statistics/Numeric-Output-2-GTE-MinBoundary.xml
  src/backend/gporca/data/dxl/statistics/Numeric-Output-2-LT-MaxBoundary.xml
  src/backend/gporca/data/dxl/statistics/Numeric-Output-2-LTE-MaxBoundary.xml
  src/backend/gporca/data/dxl/statistics/Numeric-Output-2-LTE-MinBoundary.xml
  src/backend/gporca/data/dxl/statistics/Numeric-Output-E-MaxBoundary.xml
  src/backend/gporca/data/dxl/statistics/Numeric-Output-E-MinBoundary.xml
  src/backend/gporca/data/dxl/statistics/Numeric-Output-GTE-MaxBoundary.xml
  src/backend/gporca/data/dxl/statistics/Numeric-Output-LTE-MinBoundary.xml
  src/backend/gporca/libgpos/include/gpos/io/IOstream.h
  src/backend/gporca/libgpos/src/io/COstream.cpp
  src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/CXMLSerializer.h
  src/backend/gporca/libnaucrates/src/md/CDXLBucket.cpp
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca

#11334 Fix crash when pg_get_viewdef_name_ext() is passed a non-view relation.
  src/backend/utils/adt/ruleutils.c
Labels: backport, version: 5X_STABLE

#11335 Fix crash when pg_get_viewdef_name_ext() is passed a non-view relation.
  src/backend/utils/adt/ruleutils.c
Labels: backport, version: 6X_STABLE

#11394 Fix memory leak in ORCA translator CreateGroupingSetsForRollup()
  src/backend/gpopt/translate/CTranslatorUtils.cpp
Labels: area: gporca, type: bug

#11402 Remove 3 temporarily dead tests that don't compile
  src/backend/gporca/server/src/unittest/dxl/statistics/CStatisticsTest.cpp
  src/backend/gporca/server/src/unittest/gpopt/operators/CExpressionTest.cpp
  src/backend/gporca/server/src/unittest/gpopt/translate/CTranslatorDXLToExprTest.cpp
Labels: area: gporca

#11312 Add gpload cases of header, error_limit, log errors, force_not_null
  gpMgmt/bin/gpload_test/gpload2/TEST_local_base.py
  gpMgmt/bin/gpload_test/gpload2/TEST_local_options.py
  gpMgmt/bin/gpload_test/gpload2/data/external_file_301.txt
  gpMgmt/bin/gpload_test/gpload2/data/external_file_312.txt
  gpMgmt/bin/gpload_test/gpload2/data/external_file_351.csv
  gpMgmt/bin/gpload_test/gpload2/query301.ans
  gpMgmt/bin/gpload_test/gpload2/query310.ans
  gpMgmt/bin/gpload_test/gpload2/query311.ans
  gpMgmt/bin/gpload_test/gpload2/query312.ans
  gpMgmt/bin/gpload_test/gpload2/query313.ans
  gpMgmt/bin/gpload_test/gpload2/query314.ans
  gpMgmt/bin/gpload_test/gpload2/query351.ans
  gpMgmt/bin/gpload_test/gpload2/query352.ans
Labels: version: 7X_ALPHA

#11366 6X: Ban plans that demand a rescan of a dynamic PartitionSelector
  src/backend/gporca/data/dxl/minidump/DPE-with-unsupported-pred.mdp
  src/backend/gporca/data/dxl/minidump/ExtractPredicateFromDisj.mdp
  src/backend/gporca/data/dxl/minidump/IndexApply-ForPartialIndex.mdp
  src/backend/gporca/data/dxl/minidump/Join-Varchar-Equality.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-AvoidRangePred-DPE.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-DPE-PartitionSelectorRewindability.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-JoinOverIntersect.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-MultiWayJoin.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-MultiWayJoinWithDPE.mdp
  src/backend/gporca/libgpopt/src/operators/CPhysicalPartitionSelector.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, version: 6X_STABLE

#11447 Add test after ORCA banned rescans on DPE PartitionSelectors
  config/orca.m4
  configure
  depends/conanfile_orca.txt
  gpAux/releng/releng.mk
  src/test/regress/expected/dpe.out
  src/test/regress/expected/dpe_optimizer.out
  src/test/regress/sql/dpe.sql
Labels: area: gporca, version: 5X_STABLE
