Repository greenplum-db/gpdb, pull requests merged in 2021-09, with the labels that each got.

#12513 Inclusion of unit tests for more test coverage of gpstart
  gpMgmt/bin/gppylib/test/unit/test_unit_gpstart.py
Labels: gpcm_in

#12499 Add check to ensure stats are not null in implementation stage of Orca
  src/backend/gporca/libgpopt/include/gpopt/engine/CPartialPlan.h
  src/backend/gporca/libgpopt/include/gpopt/exception.h
  src/backend/gporca/libgpopt/src/base/CCostContext.cpp
  src/backend/gporca/libgpopt/src/engine/CPartialPlan.cpp
  src/backend/gporca/libgpopt/src/exception.cpp
  src/backend/gporca/libgpos/src/_api.cpp
  src/backend/gporca/libnaucrates/src/statistics/CStatisticsUtils.cpp
Labels: area: gporca, version: 7X_ALPHA

#12516 6X: Disable the log_lock_waits feature
  src/backend/utils/misc/guc.c
  src/test/regress/expected/guc.out
  src/test/regress/sql/guc.sql
Labels: version: 6X_STABLE

#12424 [6X] Allow non-standby mode in recovery.conf
  src/backend/access/transam/xlog.c
  src/test/Makefile
  src/test/recovery/Makefile
  src/test/recovery/t/010_logical_decoding_timelines.pl
  src/test/recovery/t/101_non_standby_recovery.pl
Labels: version: 6X_STABLE

#11884 Fix segfault in elog.c
  src/backend/utils/error/elog.c
Labels: version: 6X_STABLE

#12480 Fix reset GUC issue that causes inconsistent GUC values
  src/backend/cdb/dispatcher/cdbconn.c
  src/backend/cdb/dispatcher/cdbgang.c
  src/backend/cdb/dispatcher/cdbgang_async.c
  src/backend/postmaster/postmaster.c
  src/backend/utils/init/postinit.c
  src/backend/utils/misc/guc.c
  src/include/cdb/cdbconn.h
  src/include/cdb/cdbgang.h
  src/include/libpq/libpq-be.h
  src/interfaces/libpq/fe-connect.c
  src/interfaces/libpq/fe-protocol3.c
  src/interfaces/libpq/libpq-int.h
  src/test/isolation2/expected/sync_guc.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/sync_guc.sql
Labels: version: 6X_STABLE

#12436 Add CHECK_FOR_INTERRUPTS() to ExecMotion().
  src/backend/executor/nodeMotion.c
Labels: community

#12535 5X: Disable the log_lock_waits feature
  src/backend/utils/misc/guc.c
  src/test/regress/expected/guc.out
  src/test/regress/sql/guc.sql
Labels: version: 5X_STABLE

#12520 [Backport 6x] Inclusion of unit tests for more test coverage of gpstart
  gpMgmt/bin/gppylib/test/unit/test_unit_gpstart.py
Labels: gpcm_in

#12531 Fix: gpcheckperf did not close the SSH connections completely (#11141)
  gpMgmt/bin/gpcheckperf
Labels: gpcm_in

#12445 Compute SharedScan xslice buffer file names during ExecInitNode
  src/backend/executor/nodeMaterial.c
  src/backend/executor/nodeShareInputScan.c
  src/backend/executor/nodeSort.c
  src/include/nodes/execnodes.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, area: server, version: 6X_STABLE

#12472 Fix the invalid oidAssignments list for CTAS query with initplan
  src/backend/executor/execMain.c
  src/test/regress/expected/gpctas.out
  src/test/regress/sql/gpctas.sql
Labels: community

#12447 Fix squelch deadlock in nodeShareInputScan of CTE
  src/backend/executor/nodeShareInputScan.c
Labels: community

#12560 Add NULL pointer check when creating memory pool manager in Orca
  src/backend/gporca/libgpos/include/gpos/memory/CMemoryPoolManager.h
Labels: area: gporca, version: 7X_ALPHA

#12527 [6X]: VACUUM FULL should do permissions check during relation list creation
  src/backend/commands/vacuum.c
  src/test/isolation/expected/vacuum-full-permissions.out
  src/test/isolation/isolation_schedule
  src/test/isolation/specs/vacuum-full-permissions.spec
Labels: version: 6X_STABLE, needs: backport

#12551 [5X] VACUUM FULL should do permissions check during relation list creation
  src/backend/commands/vacuum.c
  src/test/isolation/expected/vacuum-full-permissions.out
  src/test/isolation/isolation_schedule
  src/test/isolation/specs/vacuum-full-permissions.spec
Labels: version: 5X_STABLE

#12525 Improve memory accounting logging for VMEM
  src/backend/utils/mmgr/memaccounting.c
  src/backend/utils/mmgr/test/memaccounting_test.c
Labels: area: gporca, version: 6X_STABLE

#12455 Fix copy command can't read file with special character at the end of line
  src/backend/commands/copy.c
  src/test/regress/expected/copy_eol.out
  src/test/regress/greenplum_schedule
  src/test/regress/input/gpcopy.source
  src/test/regress/output/gpcopy.source
  src/test/regress/sql/copy_eol.sql
Labels: version: 7X_ALPHA, needs: backport

#12549 6X backport: gpinitsystem behave tests fix flakes
  gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: version: 6X_STABLE

#12524 Add NULL pointer check when creating memory pool manager in Orca
  src/backend/gporca/libgpos/include/gpos/memory/CMemoryPoolManager.h
Labels: area: gporca, version: 6X_STABLE

#12572 Protect ResCleanupLock callsite with partitionLock
  src/backend/utils/resscheduler/resqueue.c
Labels: version: 7X_ALPHA

#12593 Fix incomplete hash key in sequence table data. (#12589)
  src/backend/commands/sequence.c
Labels: area: server, version: 6X_STABLE

#12557 Fix assertion failure for AO table.
  src/backend/storage/smgr/md.c
Labels: version: 6X_STABLE

#12591 Autostats skip ownership check
  src/backend/cdb/cdbvars.c
  src/backend/commands/analyze.c
  src/backend/commands/vacuum.c
  src/backend/postmaster/autostats.c
  src/backend/postmaster/autovacuum.c
  src/backend/tcop/utility.c
  src/backend/utils/misc/guc_gp.c
  src/include/cdb/cdbvars.h
  src/include/commands/vacuum.h
  src/include/utils/guc_tables.h
  src/include/utils/unsync_guc_name.h
  src/test/regress/expected/autostats.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/autostats.sql
Labels: area: gporca

#12550 Fix crash on QD when squelching CTE producer with a Motion child
  src/backend/executor/nodeMotion.c
  src/backend/storage/file/fd.c
  src/test/regress/expected/shared_scan.out
  src/test/regress/expected/shared_scan_optimizer.out
  src/test/regress/sql/shared_scan.sql
Labels: area: gporca, area: server, version: 7X_ALPHA, needs: backport

#12579 Fix an assert failure that slice table is incorrect
  src/backend/cdb/cdbmutate.c
  src/backend/executor/execMain.c
  src/test/regress/expected/initplan.out
  src/test/regress/expected/initplan_optimizer.out
  src/test/regress/sql/initplan.sql
Labels: version: 6X_STABLE

#12614 [Backport] Fix crash on QD when squelching CTE producer with a Motion child
  src/backend/executor/nodeMotion.c
  src/test/regress/expected/shared_scan.out
  src/test/regress/expected/shared_scan_optimizer.out
  src/test/regress/sql/shared_scan.sql
Labels: area: gporca, area: server, version: 6X_STABLE

#12574 Limit number of bindings per group expression in Orca
  src/backend/gpopt/utils/COptTasks.cpp
  src/backend/gporca/data/dxl/minidump/NestedSubqLimitBindings.mdp
  src/backend/gporca/libgpopt/include/gpopt/engine/CHint.h
  src/backend/gporca/libgpopt/src/optimizer/COptimizerConfig.cpp
  src/backend/gporca/libgpopt/src/search/CGroupExpression.cpp
  src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerHint.cpp
  src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/include/utils/sync_guc_name.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 7X_ALPHA

#12604 Update GitHub issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull_request_template.md
  CODE-OF-CONDUCT.md
Labels: type: enhancement

#12619 Limit number of bindings per group expression in Orca
  src/backend/gpopt/utils/COptTasks.cpp
  src/backend/gporca/data/dxl/minidump/NestedSubqLimitBindings.mdp
  src/backend/gporca/libgpopt/include/gpopt/engine/CHint.h
  src/backend/gporca/libgpopt/src/optimizer/COptimizerConfig.cpp
  src/backend/gporca/libgpopt/src/search/CGroupExpression.cpp
  src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerHint.cpp
  src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/include/utils/sync_guc_name.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 6X_STABLE

#12620 Bump Orca version to 3.120.0 and add GUC to limit bindings
  config/orca.m4
  configure
  gpAux/releng/releng.mk
  src/backend/gpopt/utils/COptTasks.cpp
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 5X_STABLE

#12624 [Backport] Add GUC for allowing autostats to be triggered by non-owners
  src/backend/cdb/cdbvars.c
  src/backend/commands/analyze.c
  src/backend/postmaster/autostats.c
  src/backend/postmaster/autovacuum.c
  src/backend/tcop/utility.c
  src/backend/utils/misc/guc_gp.c
  src/include/cdb/cdbvars.h
  src/include/nodes/parsenodes.h
  src/include/utils/guc_tables.h
  src/include/utils/unsync_guc_name.h
  src/test/regress/expected/autostats.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/autostats.sql
Labels: area: server, version: 6X_STABLE

#12576 gpstate throws cosmetic errors when gpadmin database is not present
  concourse/pipelines/templates/gpdb-tpl.yml
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/sbin/gpgetstatususingtransition.py
  gpMgmt/test/behave/mgmt_utils/gpstate.feature
Labels: gpcm_in

#12612 Fix ORCA runaway cleaner exception handler
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gporca/libgpopt/src/mdcache/CMDAccessorUtils.cpp
  src/test/isolation2/expected/runaway_query.out
  src/test/isolation2/expected/runaway_query_optimizer.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/runaway_query.sql
Labels: area: gporca, version: 7X_ALPHA

#12581 Fix copy command EOL
  src/backend/commands/copy.c
  src/test/regress/expected/copy_eol.out
  src/test/regress/greenplum_schedule
  src/test/regress/input/gpcopy.source
  src/test/regress/output/gpcopy.source
  src/test/regress/sql/copy_eol.sql
Labels: version: 7X_ALPHA, needs: backport

#12277 Oid bitmapset retire in pg_stat
  src/backend/cdb/cdbcopy.c
  src/backend/postmaster/pgstat.c
  src/include/pgstat.h
Labels: community

#12634 [backport 6X]gpstate throws cosmetic errors when gpadmin database is not present
  concourse/pipelines/templates/gpdb-tpl.yml
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/sbin/gpgetstatususingtransition.py
  gpMgmt/test/behave/mgmt_utils/gpstate.feature
Labels: gpcm_in

#12582 [6x backport and additional fixes] Fix copy command EOL
  src/backend/commands/copy.c
  src/test/regress/expected/copy_eol.out
  src/test/regress/greenplum_schedule
  src/test/regress/input/gpcopy.source
  src/test/regress/output/gpcopy.source
  src/test/regress/sql/copy_eol.sql
Labels: version: 6X_STABLE, backport
