Repository greenplum-db/gpdb, pull requests merged in 2021-12, with the labels that each got.

#12874 [6x] Updating logs for restricted mode along with gpstart -m
  gpMgmt/bin/gppylib/test/unit/test_unit_gpstart.py
  gpMgmt/bin/gpstart
Labels: gpcm_in

#12896 Add GUC to re-enable YYYYMMDDHH24MISS timestamp support
  src/backend/utils/adt/datetime.c
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/include/utils/sync_guc_name.h
  src/test/regress/expected/qp_misc_jiras.out
  src/test/regress/expected/qp_misc_jiras_optimizer.out
  src/test/regress/expected/timestamp.out
  src/test/regress/sql/qp_misc_jiras.sql
  src/test/regress/sql/timestamp.sql
Labels: area: server, version: 6X_STABLE

#12890 Fix a resource queue active stmt leak case
  src/backend/storage/lmgr/proc.c
  src/backend/utils/resscheduler/resqueue.c
  src/test/isolation2/expected/resource_queue.out
  src/test/isolation2/expected/resource_queue_cancel.out
  src/test/isolation2/expected/resource_queue_deadlock.out
  src/test/isolation2/expected/resource_queue_multi_portal.out
  src/test/isolation2/init_file_isolation2
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/resource_queue.sql
  src/test/isolation2/sql/resource_queue_cancel.sql
  src/test/isolation2/sql/resource_queue_deadlock.sql
  src/test/isolation2/sql/resource_queue_multi_portal.sql
Labels: version: 7X_ALPHA, needs: backport

#12889 (6x) Not use temp tablespaces for snapshot buf-file passed to reader cursor.
  src/backend/storage/file/buffile.c
  src/backend/storage/file/fd.c
  src/backend/utils/time/sharedsnapshot.c
  src/include/storage/buffile.h
  src/test/regress/GNUmakefile
  src/test/regress/input/temp_tablespaces.source
  src/test/regress/output/temp_tablespaces.source
Labels: type: bug, version: 6X_STABLE

#12909 5X: Fix a resource queue active stmt leak case
  src/backend/storage/lmgr/proc.c
  src/backend/utils/resscheduler/resqueue.c
  src/test/isolation2/expected/resource_queue.out
  src/test/isolation2/expected/resource_queue_cancel.out
  src/test/isolation2/expected/resource_queue_deadlock.out
  src/test/isolation2/expected/resource_queue_multi_portal.out
  src/test/isolation2/init_file_isolation2
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/resource_queue.sql
  src/test/isolation2/sql/resource_queue_cancel.sql
  src/test/isolation2/sql/resource_queue_deadlock.sql
  src/test/isolation2/sql/resource_queue_multi_portal.sql
Labels: version: 5X_STABLE

#12915 5X: Document that explicit quit syntax is non-blocking
  src/test/isolation2/sql_isolation_testcase.py
Labels: version: 5X_STABLE

#12908 6X: Fix a resource queue active stmt leak case
  src/backend/storage/lmgr/proc.c
  src/backend/utils/resscheduler/resqueue.c
  src/test/isolation2/expected/resource_queue.out
  src/test/isolation2/expected/resource_queue_cancel.out
  src/test/isolation2/expected/resource_queue_deadlock.out
  src/test/isolation2/expected/resource_queue_multi_portal.out
  src/test/isolation2/init_file_isolation2
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/resource_queue.sql
  src/test/isolation2/sql/resource_queue_cancel.sql
  src/test/isolation2/sql/resource_queue_deadlock.sql
  src/test/isolation2/sql/resource_queue_multi_portal.sql
Labels: version: 6X_STABLE

#12914 6X: Document that explicit quit syntax is non-blocking
  src/test/isolation2/sql_isolation_testcase.py
Labels: version: 6X_STABLE

#12901 Add regression test for SetOps casting and bump orca ver to 3.121
  config/orca.m4
  configure
  gpAux/releng/releng.mk
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 5X_STABLE

#12917 Packcore tests were failing on 6x. Current change makes sure that we are in parity with gpdb6.
  gpMgmt/sbin/packcore
Labels: gpcm_in

#12946 Allow cancellable ANALYZE queries
  src/backend/catalog/pg_compression.c
  src/backend/commands/analyze.c
  src/test/isolation2/expected/cancel_query.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/cancel_query.sql
Labels: area: gporca, topic: analyze

#9650 fix panic when a query in res waiting queue is about to cancel itself
  src/backend/storage/lmgr/proc.c
  src/test/isolation2/expected/resource_queue_query_cancel_deadlock_timeout.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/resource_queue_query_cancel_deadlock_timeout.sql
Labels: version: 6X_STABLE, community

#12910 Adding timeout in the testcase when stopping the pg instance.
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in

#12952 Fix PANIC when a query in res waiting queue is about to cancel itself
  src/backend/storage/lmgr/proc.c
  src/backend/utils/misc/faultinjector.c
  src/include/utils/faultinjector.h
  src/test/isolation2/expected/resource_queue_query_cancel_deadlock_timeout.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/resource_queue_query_cancel_deadlock_timeout.sql
Labels: version: 5X_STABLE

#12922 Fix colref in preprocessing for SubqueryALL with outer refs
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/test/regress/expected/notin.out
  src/test/regress/expected/notin_optimizer.out
  src/test/regress/sql/notin.sql
Labels: area: gporca

#12945 Bump ORCA version to 3.122.0
  config/orca.m4
  configure
  gpAux/releng/releng.mk
  src/test/regress/expected/notin.out
  src/test/regress/expected/notin_optimizer.out
  src/test/regress/sql/notin.sql
Labels: area: gporca, backport
