Repository greenplum-db/gpdb, pull requests merged in 2021-06, with the labels that each got.

#11985 pg_dump(all): Allow quote_all_identifiers for 8.3
  src/bin/pg_dump/pg_dump.c
  src/bin/pg_dump/pg_dumpall.c
Labels: topic: upgrade, version: 7X_ALPHA

#12086 [Backport 6X] Check delay eager free in squelch functions.
  src/backend/executor/nodeFunctionscan.c
  src/backend/executor/nodeSort.c
  src/test/regress/expected/subselect_gp2.out
  src/test/regress/sql/subselect_gp2.sql
Labels: version: 6X_STABLE

#12069 [6X backport] Fix logical difference derived constraint property (#12009)
  src/backend/gporca/data/dxl/minidump/InnerJoinOverJoinExcept.mdp
  src/backend/gporca/data/dxl/minidump/InnerJoinOverJoinExceptAll.mdp
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDifference.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDifferenceAll.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalIntersect.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalIntersectAll.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalSetOp.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalUnion.h
  src/backend/gporca/libgpopt/src/operators/CLogicalSetOp.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/qp_dml_joins.out
  src/test/regress/expected/qp_dml_joins_optimizer.out
  src/test/regress/sql/qp_dml_joins.sql
Labels: area: gporca, backport, version: 6X_STABLE

#12071 Explicity call out all locus types in adjust_setop_arguments() (#12026)
  src/backend/cdb/cdbsetop.c
  src/test/regress/expected/rpt.out
  src/test/regress/sql/rpt.sql
Labels: backport, version: 6X_STABLE

#12067 Fix wrong results from nested LOJ in ALL subqueries
  src/backend/gporca/data/dxl/minidump/AllSubqueryWithSubqueryInScalar.mdp
  src/backend/gporca/data/dxl/minidump/MultiLevel-NOT-IN-Subquery.mdp
  src/backend/gporca/data/dxl/minidump/NotInToLASJ.mdp
  src/backend/gporca/libgpopt/src/xforms/CSubqueryHandler.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/qp_misc_jiras_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 6X_STABLE

#12075 Allow debug_query_string exception log messages to be suppressed
  src/backend/tcop/postgres.c
Labels: needs: backport

#12072 [5X] pg_upgrade_support: Detect views with deprecated tables
  contrib/pg_upgrade_support/Makefile
  contrib/pg_upgrade_support/deprecated_objects.c
  contrib/pg_upgrade_support/deprecated_objects.h
  contrib/pg_upgrade_support/pg_upgrade_support.c
Labels: topic: upgrade, version: 5X_STABLE

#12073 [6X] pg_upgrade check: views with deprecated tables
  contrib/pg_upgrade/greenplum/check_gp.c
Labels: topic: upgrade, version: 6X_STABLE

#11932 gprecoverseg: Skip pg_hba update on non-failed hosts
  gpMgmt/bin/gppylib/operations/test/unit/test_unit_update_pg_hba_conf.py
  gpMgmt/bin/gppylib/operations/update_pg_hba_conf.py
  gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
Labels: version: 6X_STABLE

#12102 pg_upgrade_support: Fix 6X->6X upgrade path
  contrib/pg_upgrade/greenplum/check_gp.c
Labels: version: 6X_STABLE

#12080 [6X backport] Fix Distribution Spec for Union ALL where the outer child is External Scan (#11970)
  src/backend/gporca/data/dxl/minidump/CTAS-with-randomly-distributed-external-table.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpec.h
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecExternal.h
  src/backend/gporca/libgpopt/src/base/CDistributionSpecExternal.cpp
  src/backend/gporca/libgpopt/src/base/Makefile
  src/backend/gporca/libgpopt/src/operators/CPhysicalExternalScan.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalMultiExternalScan.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalSerialUnionAll.cpp
  src/test/regress/data/location1.csv
  src/test/regress/data/location2.csv
  src/test/regress/data/location3.csv
  src/test/regress/greenplum_schedule
  src/test/regress/input/external_table_union_all.source
  src/test/regress/output/external_table_union_all.source
  src/test/regress/output/external_table_union_all_optimizer.source
Labels: area: gporca, backport, version: 6X_STABLE

#12101 Fix misleading log: libpq says we are still busy
  src/backend/cdb/dispatcher/cdbdisp_async.c
Labels: needs: backport

#12107 Drop PostmasterContext after InitPostgres()
  src/backend/tcop/postgres.c
Labels: version: 5X_STABLE

#12100 [5X backport] Allow debug_query_string exception log messages to be suppressed
  src/backend/tcop/postgres.c
Labels: backport, version: 5X_STABLE

#12099 [6X backport] Allow debug_query_string exception log messages to be suppressed
  src/backend/tcop/postgres.c
Labels: backport, version: 6X_STABLE

#12155 Migrate qp-gpdbdev image to GCR
  concourse/tasks/build_with_orca.yml
  concourse/tasks/diff_explain_results_with_baseline.yml
  concourse/tasks/test_icg.yml
  concourse/tasks/untar_build_with_orca.yml
Labels: area: gporca, version: 5X_STABLE

#12148 set_append_path_locus should use max numsegments when break loop.
  src/backend/optimizer/util/pathnode.c
  src/test/regress/expected/bfv_planner.out
  src/test/regress/expected/bfv_planner_optimizer.out
  src/test/regress/sql/bfv_planner.sql
Labels: needs: backport

#12156 gpstart -m warning messages change
  gpMgmt/bin/gpstart
Labels: gpcm_in

#12140 Fix out-of-bounds error in CXformPushDownLeftOuterJoin
  src/backend/gporca/data/dxl/minidump/LOJ-PushDown.mdp
  src/backend/gporca/libgpopt/src/xforms/CXformPushDownLeftOuterJoin.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, version: 6X_STABLE

#12157 Missing option in gpstart --help
  gpMgmt/doc/gpstart_help
Labels: gpcm_in

#12122 [6X Backport] Fix stale sequence reference causing duplicate nextval() (#12029)
  src/backend/commands/sequence.c
  src/test/regress/expected/sequence_gp.out
  src/test/regress/sql/sequence_gp.sql
Labels: version: 6X_STABLE

#12051 Fix array overflow for function argument types in orca
  src/backend/gpopt/translate/CTranslatorUtils.cpp
  src/include/gpopt/translate/CTranslatorUtils.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca

#12179 Fix array overflow for function argument types in orca
  src/backend/gpopt/translate/CTranslatorUtils.cpp
  src/include/gpopt/translate/CTranslatorUtils.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca

#12168 pg_upgrade_support: Detect views referring to deprecated columns
  contrib/pg_upgrade_support/deprecated_objects.c
  contrib/pg_upgrade_support/deprecated_objects.h
  contrib/pg_upgrade_support/pg_upgrade_support.c
Labels: version: 5X_STABLE

#12169 pg_upgrade: Detect views referencing deprecated columns
  contrib/pg_upgrade/greenplum/check_gp.c
Labels: version: 6X_STABLE

#12183 [5X] Fix walker that detects deprecated tables
  contrib/pg_upgrade_support/deprecated_objects.c
  contrib/pg_upgrade_support/pg_upgrade_support.c
Labels: version: 5X_STABLE

#12138 Missing option in gpstart --help
  gpMgmt/doc/gpstart_help
Labels: gpcm_in

#12189 6X: Update message of FTS double fault detected
  src/backend/fts/ftsprobe.c
Labels: version: 6X_STABLE

#12142 gpstart -m warning messages change
  gpMgmt/bin/gpstart
Labels: gpcm_in

#12145 6X: Coerce unknown-type literals to type cstring, but hide it
  contrib/pg_upgrade/greenplum/check_gp.c
  contrib/pg_upgrade_support/pg_upgrade_support.c
  src/backend/parser/parse_coerce.c
  src/test/regress/expected/gp_create_view.out
  src/test/regress/expected/gp_types.out
  src/test/regress/expected/gp_types_optimizer.out
  src/test/regress/expected/matview.out
  src/test/regress/expected/matview_optimizer.out
  src/test/regress/expected/subselect.out
  src/test/regress/expected/subselect_optimizer.out
  src/test/regress/expected/with.out
  src/test/regress/sql/gp_create_view.sql
  src/test/regress/sql/gp_types.sql
  src/test/regress/sql/matview.sql
  src/test/regress/sql/subselect.sql
  src/test/regress/sql/with.sql
Labels: version: 6X_STABLE

#12152 [5X Only]Don't forget to assign typmod for RECORD type during eval
  src/backend/executor/execQual.c
  src/test/isolation2/expected/eval_record.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/eval_record.sql
Labels: version: 5X_STABLE

#12176 Ensure materialize does not project in Orca
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca

#12234 pg_upgrade_support: Multiple fixes to deprecated object detection
  contrib/pg_upgrade_support/deprecated_objects.c
Labels: version: 5X_STABLE

#12011 [Backport6] Fix resqueue's CPU priority didn't take effects in segments (#11234)
  src/backend/utils/mmgr/portalmem.c
  src/test/regress/expected/resource_queue.out
  src/test/regress/sql/resource_queue.sql
Labels: backport

#12193 Support implicit CoerceViaIO casts in Subplan test expressions in ORCA (6x)
  src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libnaucrates/include/naucrates/md/IMDCast.h
  src/backend/gporca/libnaucrates/src/md/CMDCastGPDB.cpp
  src/include/gpopt/translate/CTranslatorDXLToScalar.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 6X_STABLE
