Repository greenplum-db/gpdb, pull requests merged in 2021-08, with the labels that each got.

#12412 (6x) Fix wrong levelsup paramenter when coerce_unknown_var for SetOperatio…
  src/backend/parser/analyze.c
  src/backend/parser/parse_coerce.c
  src/test/regress/expected/union_gp.out
  src/test/regress/sql/union_gp.sql
Labels: version: 6X_STABLE, needs: backport

#12341 Don't choose indexscan when you need a motion for a subplan [Backport]
  src/backend/optimizer/path/allpaths.c
  src/backend/optimizer/path/indxpath.c
  src/backend/optimizer/plan/planmain.c
  src/backend/optimizer/plan/planner.c
  src/backend/optimizer/plan/subselect.c
  src/include/nodes/plannerconfig.h
  src/include/nodes/relation.h
  src/test/regress/expected/join_gp.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/expected/subselect_gp_indexes.out
  src/test/regress/expected/subselect_gp_indexes_optimizer.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/subselect_gp_indexes.sql
Labels: community

#12430 Fix: Gang cleanup null pointer reference (#12399)
  src/backend/cdb/dispatcher/cdbdispatchresult.c
  src/test/isolation2/expected/gpdispatch.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/gpdispatch.sql
Labels: area: server, version: 7X_ALPHA

#12432 Adding missing --help option and small formatting correction
  gpMgmt/bin/gpcheckcat
Labels: gpcm_in

#12359 Fixed missing NULL check in LeftAntiSemiHashJoin2HashJoin
  src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca

#12449 (6x only) Disallow unique rowid path when seeing indexonly scan.
  src/backend/optimizer/util/pathnode.c
  src/include/nodes/relation.h
  src/test/regress/expected/bfv_planner.out
  src/test/regress/expected/join_gp.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/bfv_planner.sql
Labels: type: bug, version: 6X_STABLE

#12463 Merge bin/psql/startup.c from PostgreSQL 12
  src/bin/psql/startup.c
Labels: community

#12465 Mitigate a proclock/lock table corruption case
  src/backend/storage/lmgr/proc.c
  src/backend/utils/resscheduler/resqueue.c
Labels: version: 7X_ALPHA, needs: backport

#11371 Fix aocsseg inconsistency when rollback add column
  src/backend/access/aocs/aocssegfiles.c
  src/test/isolation2/expected/uao_crash_compaction_column.out
  src/test/regress/expected/alter_table_aocs.out
  src/test/regress/sql/alter_table_aocs.sql
Labels: community

#12428 gpinitstandby/gprecoverseg utils fail when there is banner on .bashrc present
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/bin/gppylib/commands/pg.py
  gpMgmt/bin/gppylib/commands/unix.py
  gpMgmt/bin/gppylib/operations/detect_unreachable_hosts.py
  gpMgmt/test/behave/mgmt_utils/gpinitstandby.feature
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in

#12470 5X: Mitigate a proclock/lock table corruption case.
  src/backend/storage/lmgr/proc.c
  src/backend/utils/resscheduler/resqueue.c
Labels: version: 5X_STABLE

#12469 6X: Mitigate a proclock/lock table corruption case
  src/backend/storage/lmgr/proc.c
  src/backend/utils/resscheduler/resqueue.c
Labels: version: 6X_STABLE

#12441 Fix reset GUC issue that causes inconsistent GUC values
  src/backend/cdb/dispatcher/cdbconn.c
  src/backend/cdb/dispatcher/cdbgang.c
  src/backend/cdb/dispatcher/cdbgang_async.c
  src/backend/postmaster/postmaster.c
  src/backend/utils/init/postinit.c
  src/backend/utils/misc/guc.c
  src/include/cdb/cdbconn.h
  src/include/cdb/cdbgang.h
  src/include/libpq/libpq-be.h
  src/interfaces/libpq/fe-connect.c
  src/interfaces/libpq/fe-protocol3.c
  src/interfaces/libpq/libpq-int.h
  src/test/isolation2/expected/sync_guc.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/sync_guc.sql
Labels: needs: backport

#12457 [5X]Use the correct flow in ParallelizeSubplan for subplan
  src/backend/cdb/cdbllize.c
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/sql/subselect_gp.sql
Labels: version: 5X_STABLE

#12475 [6X]Use the correct flow in ParallelizeSubplan for subplan
  src/backend/cdb/cdbllize.c
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/sql/subselect_gp.sql
Labels: version: 6X_STABLE

#12452 Fixed missing NULL check in LeftAntiSemiHashJoin2HashJoin (6X)
  src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 6X_STABLE

#12486 Gpinitstandby gprecoverseg gpstart gpstop fails when there is a banner on bashrc --6x
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/bin/gppylib/commands/pg.py
  gpMgmt/bin/gppylib/commands/unix.py
  gpMgmt/bin/gppylib/operations/detect_unreachable_hosts.py
  gpMgmt/bin/gppylib/operations/test/unit/test_unit_utils.py
  gpMgmt/bin/gppylib/operations/utils.py
  gpMgmt/test/behave/mgmt_utils/gpinitstandby.feature
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in

#12506 Fix environment variables generation when using symlinks
  gpMgmt/bin/generate-greenplum-path.sh
Labels: gpcm_in

#12510 gpinitstandby/gprecoverseg utils fail when there is banner on .bashrc…
  gpMgmt/bin/gppylib/commands/pg.py
Labels: gpcm_in
