Repository greenplum-db/gpdb, pull requests merged in 2022-03, with the labels that each got.

#13094 Using poll instead of select in nodeShareInputScan
  src/backend/executor/nodeShareInputScan.c
  src/test/regress/expected/shared_scan.out
  src/test/regress/expected/shared_scan_optimizer.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/shared_scan.sql
Labels: version: 6X_STABLE

#13010 [6x] Add another version of gp_inject_funtion() to fix flaky case
  gpcontrib/gp_inject_fault/gp_inject_fault--1.0.sql
  gpcontrib/gp_inject_fault/gp_inject_fault.c
  src/backend/utils/misc/faultinjector.c
  src/include/utils/faultinjector.h
  src/test/regress/expected/psql_gp_commands.out
  src/test/regress/input/dispatch.source
  src/test/regress/output/dispatch.source
Labels: version: 6X_STABLE

#13149 Fix bug: gpfdist loads partial records if the data file is gz compressed
  src/backend/utils/misc/fstream/gfile.c
  src/bin/gpfdist/regress/data/gpfdist2/gz_multi_chunk.tbl.gz
  src/bin/gpfdist/regress/data/gpfdist2/gz_multi_chunk_2.tbl.gz
  src/bin/gpfdist/regress/input/gpfdist2.source
  src/bin/gpfdist/regress/output/gpfdist2.source
Labels: version: 5X_STABLE

#13138 Fix flaky brin testcase
  src/test/regress/expected/brin.out
  src/test/regress/expected/brin_ao.out
  src/test/regress/expected/brin_ao_optimizer.out
  src/test/regress/expected/brin_aocs.out
  src/test/regress/expected/brin_aocs_optimizer.out
  src/test/regress/expected/brin_optimizer.out
  src/test/regress/sql/brin.sql
  src/test/regress/sql/brin_ao.sql
  src/test/regress/sql/brin_aocs.sql
Labels: area: gporca

#13168 Revert "Revert "Introducing parallel array_agg (#13051)""
  gpcontrib/Makefile
  gpcontrib/gp_array_agg/.gitignore
  gpcontrib/gp_array_agg/Makefile
  gpcontrib/gp_array_agg/README.md
  gpcontrib/gp_array_agg/expected/gp_array_agg.out
  gpcontrib/gp_array_agg/expected/gp_array_agg_optimizer.out
  gpcontrib/gp_array_agg/gp_array_agg--1.0.0.sql
  gpcontrib/gp_array_agg/gp_array_agg.c
  gpcontrib/gp_array_agg/gp_array_agg.control
  gpcontrib/gp_array_agg/sql/gp_array_agg.sql
Labels: version: 6X_STABLE

#13162 [6X]Fix gpfdist loads partial records if the data file is gz compressed
  src/backend/utils/misc/fstream/gfile.c
  src/bin/gpfdist/regress/data/gpfdist2/gz_multi_chunk.tbl.gz
  src/bin/gpfdist/regress/data/gpfdist2/gz_multi_chunk_2.tbl.gz
  src/bin/gpfdist/regress/input/gpfdist2.source
  src/bin/gpfdist/regress/output/gpfdist2.source
Labels: version: 6X_STABLE

#13164 Resolve a MERGE 12 FIXME in nodeModifyTable.c.
  src/backend/executor/nodeModifyTable.c
Labels: type: fixme

#13180 Resolve GPDB_12_MERGE_FIXMEs: TOAST for AO_ROW Table
  src/backend/access/appendonly/appendonlyam.c
Labels: type: fixme

#13183 Fix flaky fts_unblock_primary isolation2 test
  src/test/isolation2/expected/segwalrep/fts_unblock_primary.out
  src/test/isolation2/sql/segwalrep/fts_unblock_primary.sql
Labels: version: 7X_ALPHA, needs: backport

#12990 Changes to avoid gpstop errors when standby is not reachable.
  gpMgmt/bin/gpstop
  gpMgmt/test/behave/mgmt_utils/gpstop.feature
  gpMgmt/test/behave/mgmt_utils/steps/gpstart.py
Labels: gpcm_in

#13165 Fix segno being incorrectly reset in mdsync()
  src/backend/storage/smgr/md.c
Labels: type: bug, version: 6X_STABLE

#13186 [6X] be-gssapi-common.h: Introduce configure guard
  src/include/libpq/be-gssapi-common.h
Labels: version: 6X_STABLE

#13197 Direct looking for AppendRelInfos by relid in the append_rel_array instead of trawl through the append_rel_list.
  src/backend/cdb/cdbpathlocus.c
Labels: type: fixme

#13176 remove gpdb_12_merge_fixme in pg_import_system_collations
  src/backend/commands/collationcmds.c
Labels: type: fixme

#13193 Correct some spelling mistakes about word "Greenplum".
  gpdb-doc/dita/analytics/text.xml
  gpdb-doc/markdown/install_guide/prep_os.html.md
Labels: community

#13207 Resolve GPDB_12_MERGE_FIXME in psql/command.c
  src/bin/psql/command.c
Labels: type: fixme

#13075 Some gp wrapper function should not execute on entrydb QE
  src/backend/catalog/cdb_schema.sql
  src/backend/catalog/system_views.sql
  src/test/regress/expected/db_size_functions.out
  src/test/regress/sql/db_size_functions.sql
Labels: needs: backport

#13066 Including PGOPTIONS="-c gp_role=utility" to use utility mode when inv…
  gpMgmt/sbin/gpgetstatususingtransition.py
  gpMgmt/test/behave/mgmt_utils/gpstate.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  gpMgmt/test/behave_utils/utils.py
Labels: gpcm_in

#13231 Wiped out fake "Failed to kill processes for segment" message on gpst…
  gpMgmt/bin/gppylib/commands/pg.py
Labels: community

#11820 Add check for appendonly materialized view to pg_upgrade
  src/bin/pg_upgrade/check.c
Labels: pg_upgrade

#13148 Replace usages of InterruptPending to the flag of query cancellation
  src/backend/cdb/cdbcopy.c
  src/backend/cdb/dispatcher/cdbdisp_async.c
  src/backend/cdb/dispatcher/cdbdisp_query.c
  src/backend/cdb/motion/ic_tcp.c
  src/backend/tcop/postgres.c
  src/include/miscadmin.h
Labels: community

#13219 Fix spelling errors in binaries
  src/backend/commands/tablecmds.c
  src/backend/utils/mmgr/memprot.c
  src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
  src/test/isolation2/expected/oom_startup_memory.out
  src/test/isolation2/expected/query_gp_partitions_view.out
  src/test/isolation2/sql/oom_startup_memory.sql
  src/test/isolation2/sql/query_gp_partitions_view.sql
  src/test/regress/expected/exclusion_constraints.out
  src/test/regress/expected/parruleord.out
  src/test/regress/expected/partition.out
  src/test/regress/expected/partition_expand.out
  src/test/regress/expected/partition_optimizer.out
  src/test/regress/input/gpcopy.source
  src/test/regress/output/gpcopy.source
  src/test/regress/sql/exclusion_constraints.sql
  src/test/regress/sql/parruleord.sql
  src/test/regress/sql/partition.sql
Labels: version: 6X_STABLE, backport

#13240 Fix Printing Expression Properties
  src/backend/gporca/libgpopt/src/base/CDrvdPropScalar.cpp
  src/backend/gporca/libgpopt/src/operators/CExpression.cpp
Labels: area: gporca

#13203 [6X backport] Fix flaky fts_unblock_primary isolation2 test
  src/test/isolation2/expected/segwalrep/fts_unblock_primary.out
  src/test/isolation2/sql/segwalrep/fts_unblock_primary.sql
Labels: version: 6X_STABLE, backport

#13258 Add tests for GUC of PGC_STRING type value rollback
  src/backend/commands/createas.c
  src/backend/tcop/postgres.c
  src/test/regress/expected/guc_gp.out
  src/test/regress/sql/guc_gp.sql
Labels: version: 6X_STABLE

#13252 Fix memory leak in dtx recovery process
  src/backend/cdb/cdbdtxrecovery.c
Labels: community, Priority 1

#13229 Resolve GPDB_12_MERGE_FIXME: taken almost verbadim from appendonly_va…
  src/backend/commands/vacuum_ao.c
Labels: type: fixme

#13251 Fix flaky test fts_errors with nondeterminsitc error in FETCH
  src/test/isolation2/expected/fts_errors.out
  src/test/isolation2/expected/fts_errors_1.out
  src/test/isolation2/sql/fts_errors.sql
Labels: version: 7X_ALPHA

#13275 Make test resgroup_seg_down_2pc stable.
  src/test/isolation2/expected/resgroup/resgroup_seg_down_2pc.out
  src/test/isolation2/sql/resgroup/resgroup_seg_down_2pc.sql
Labels: needs: backport

#13279 Fix a flakiness in pg_rewind_fail_missing_xlog where FTS could not promote not-in-sync mirror
  src/test/isolation2/expected/pg_rewind_fail_missing_xlog.out
  src/test/isolation2/sql/pg_rewind_fail_missing_xlog.sql
Labels: version: 7X_ALPHA

#12772 [6X backport] ORCA: avoid returning output of a CTE producer
  src/backend/executor/nodeShareInputScan.c
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/optimizer/plan/planshare.c
  src/include/nodes/plannodes.h
Labels: area: gporca, version: 6X_STABLE, backport, community

#11215 Revalidate plan in SPI taking params into account
  src/backend/executor/spi.c
  src/test/regress/expected/plpgsql_cache.out
  src/test/regress/sql/plpgsql_cache.sql
Labels: community

#13247 Error out in DECLARE if gp_parallel_retrieve_cursor is not installed
  src/backend/commands/portalcmds.c
  src/test/isolation2/.gitignore
  src/test/isolation2/expected/parallel_retrieve_cursor/set.out
  src/test/isolation2/sql/parallel_retrieve_cursor/set.sql
Labels: version: 6X_STABLE

#13230 [6X] gpstate -e: Changes to avoid fatal message on primary segments
  gpMgmt/sbin/gpgetstatususingtransition.py
  gpMgmt/test/behave/mgmt_utils/gpstate.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in

#13239 Fix Printing Expression Properties
  src/backend/gporca/libgpopt/src/base/CDrvdPropScalar.cpp
  src/backend/gporca/libgpopt/src/operators/CExpression.cpp
Labels: area: gporca

#13122 upgrade: pg_strdup should not be run on the bool params
  src/bin/pg_upgrade/greenplum/option_gp.c
  src/bin/pg_upgrade/greenplum/pg_upgrade_greenplum.h
  src/bin/pg_upgrade/option.c
Labels: pg_upgrade

#13228 Fallback to planner for functions returning composite types
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
  src/test/regress/expected/qp_orca_fallback.out
  src/test/regress/expected/qp_orca_fallback_optimizer.out
  src/test/regress/sql/qp_orca_fallback.sql
Labels: area: gporca, version: 6X_STABLE

#13283 [6X Only] fix cache look up failed for relation 25 in pg_catalog.gp_dump_query_oids()
  src/backend/parser/parse_coerce.c
  src/test/regress/expected/gp_dump_query_oids.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gp_dump_query_oids.sql
Labels: version: 6X_STABLE

#12223 Detect client disconnection while running query and interrupt execution of query
  gpdb-doc/dita/ref_guide/config_params/guc-list.xml
  gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
  gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap
  src/backend/cdb/motion/ic_udpifc.c
  src/backend/libpq/pqcomm.c
  src/backend/tcop/postgres.c
  src/backend/utils/init/globals.c
  src/backend/utils/init/postinit.c
  src/backend/utils/misc/guc.c
  src/backend/utils/misc/timeout.c
  src/include/libpq/libpq.h
  src/include/miscadmin.h
  src/include/tcop/tcopprot.h
  src/include/utils/timeout.h
  src/include/utils/unsync_guc_name.h
Labels: community

#13293 Fix banning window agg in recursive queries.
  src/backend/parser/parse_cte.c
  src/test/regress/expected/with.out
  src/test/regress/expected/with_clause.out
  src/test/regress/expected/with_clause_optimizer.out
  src/test/regress/sql/with_clause.sql
Labels: version: 7X_ALPHA, needs: backport

#13209 GPDB_12_MERGE_FIXME: Add QueryFinishPending handling to mergeruns()
  src/backend/utils/sort/tuplesort.c
  src/test/regress/expected/query_finish_pending.out
  src/test/regress/sql/query_finish_pending.sql
Labels: type: fixme

#13301 (6x backport) Fix banning window agg in recursive queries.
  src/backend/parser/parse_cte.c
  src/test/regress/expected/with.out
  src/test/regress/expected/with_clause.out
  src/test/regress/expected/with_clause_optimizer.out
  src/test/regress/sql/with_clause.sql
Labels: version: 6X_STABLE, backport

#13296 Fix testexpr translation of outer expr
  src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
  src/include/gpopt/translate/CTranslatorDXLToScalar.h
  src/test/regress/expected/correlated_subquery.out
  src/test/regress/sql/correlated_subquery.sql
Labels: area: gporca, version: 7X_ALPHA, needs: backport

#13302 Fix paramcolid for param in ORCA translator
  src/backend/gpopt/translate/CMappingColIdVarPlStmt.cpp
  src/test/regress/expected/qp_misc.out
  src/test/regress/expected/qp_misc_optimizer.out
  src/test/regress/sql/qp_misc.sql
Labels: area: gporca

#13303 Fix testexpr translation of outer expr (#13296)
  src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
  src/include/gpopt/translate/CTranslatorDXLToScalar.h
  src/test/regress/expected/correlated_subquery.out
  src/test/regress/sql/correlated_subquery.sql
Labels: area: gporca, version: 6X_STABLE, backport

#13292 Fix risk of deadlock failure while dropping a partitioned index.
  src/backend/commands/tablecmds.c
  src/test/isolation/expected/partition-drop-index-locking.out
  src/test/isolation/isolation_schedule
  src/test/isolation/specs/partition-drop-index-locking.spec
Labels: version: 7X_ALPHA

#13304 Fix paramcollid for param in ORCA translator (#13302)
  src/backend/gpopt/translate/CMappingColIdVarPlStmt.cpp
  src/test/regress/expected/qp_misc.out
  src/test/regress/expected/qp_misc_optimizer.out
  src/test/regress/sql/qp_misc.sql
Labels: area: gporca, version: 6X_STABLE, backport

#13248 [6X] add original storage options to AO table with index when expanding
  src/backend/access/common/reloptions_gp.c
  src/backend/commands/tablecmds.c
  src/include/access/reloptions.h
  src/test/regress/expected/expand_table_ao.out
  src/test/regress/sql/expand_table_ao.sql
Labels: backport

#13204 Allow setting direct dispatch info if predicate on gp_segment_id for…
  src/backend/cdb/cdbtargeteddispatch.c
  src/test/regress/expected/direct_dispatch.out
  src/test/regress/expected/direct_dispatch_optimizer.out
  src/test/regress/sql/direct_dispatch.sql
Labels: version: 6X_STABLE, backport

#13257 conf on mirror seg doesn't get updated with mirror port number
  gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
  gpMgmt/bin/lib/gp_bash_functions.sh
  gpMgmt/bin/lib/gpconfigurenewsegment
  gpMgmt/bin/lib/gpcreateseg.sh
  gpMgmt/sbin/gpsegrecovery.py
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
  gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
Labels: gpcm_in

#13173 [7X] Fix FNullRejecting() error while trying to process zero-placed predicate
  src/backend/gporca/data/dxl/minidump/LOJNullRejectingZeroPlacePredicates.mdp
  src/backend/gporca/libgpopt/src/operators/CScalar.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 7X_ALPHA, community

#13313 Fix plpgsql testcase for ORCA
  src/test/regress/expected/plpgsql.out
  src/test/regress/expected/plpgsql_optimizer.out
  src/test/regress/sql/plpgsql.sql
Labels: area: gporca, version: 5X_STABLE

#13310 Enable merging leaf stats for data types with no equality operator
  src/backend/commands/analyze.c
  src/test/regress/expected/analyze.out
  src/test/regress/sql/analyze.sql
Labels: area: gporca, topic: partitions, version: 7X_ALPHA

#13320 Remove Merge FIXME in test gangsize.
  src/test/regress/expected/gangsize.out
  src/test/regress/expected/gangsize_optimizer.out
  src/test/regress/sql/gangsize.sql
Labels: merge_fixme

#13321 Remove FIXME in test olap_plan.
  src/test/regress/expected/olap_plans.out
  src/test/regress/expected/olap_plans_optimizer.out
  src/test/regress/sql/olap_plans.sql
Labels: merge_fixme

#13169 Introducing parallel array_agg
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gpopt/translate/CTranslatorUtils.cpp
  src/backend/utils/adt/array_userfuncs.c
  src/backend/utils/adt/arrayfuncs.c
  src/include/catalog/pg_aggregate.dat
  src/include/catalog/pg_proc.dat
  src/include/gpopt/translate/CTranslatorUtils.h
  src/include/utils/array.h
  src/test/regress/expected/gp_array_agg.out
  src/test/regress/expected/gp_array_agg_optimizer.out
  src/test/regress/expected/groupingsets.out
  src/test/regress/expected/groupingsets_optimizer.out
  src/test/regress/expected/qp_union_intersect.out
  src/test/regress/expected/qp_union_intersect_optimizer.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/gp_array_agg.sql
  src/test/regress/sql/groupingsets.sql
Labels: area: gporca, version: 7X_ALPHA

#13309 (6x) Fix planner bug: correctly handling NULL when pulling-up NOT-IN.
  src/backend/executor/nodeNestloop.c
  src/test/regress/expected/notin.out
  src/test/regress/expected/notin_optimizer.out
  src/test/regress/sql/notin.sql
Labels: version: 6X_STABLE

#13307 [6X] Support writable s3 external table on master
  gpcontrib/gpcloud/regress/input/3_01_create_wet.source
  gpcontrib/gpcloud/regress/output/3_01_create_wet.source
  src/backend/access/external/fileam.c
  src/backend/cdb/cdbcat.c
Labels: version: 6X_STABLE

#13317 resolve pull_up_sublinks fixme
  src/backend/optimizer/prep/prepjointree.c
Labels: merge_fixme

#13012 Speed up AOCS index build by only scan needed columns.
  src/backend/access/aocs/aocsam_handler.c
  src/test/regress/input/aocs.source
  src/test/regress/output/aocs.source
Labels: community

#13274 Clean the deprecated lockmode logic of AcquireExecutorLocks in plancache
  src/backend/parser/analyze.c
  src/backend/parser/parse_clause.c
  src/backend/parser/parse_relation.c
  src/backend/utils/cache/plancache.c
  src/test/isolation2/expected/lockmodes.out
  src/test/isolation2/expected/lockmodes_optimizer.out
  src/test/isolation2/output/uao/parallel_delete.source
  src/test/isolation2/output/uao/parallel_update.source
  src/test/isolation2/sql/lockmodes.sql
  src/test/regress/expected/ao_locks.out
  src/test/regress/expected/partition_locking.out
  src/test/regress/expected/partition_locking_optimizer.out
Labels: type: fixme, merge_fixme

#13295 Revert C++11 nullptr usage
  src/backend/gpopt/gpopt.mk
Labels: area: gporca, version: 6X_STABLE

#13343 resolve fixme update table about oids
  src/backend/optimizer/prep/preptlist.c
Labels: merge_fixme

#13326 Refactor IC motion socket setup
  src/backend/cdb/cdbutil.c
  src/backend/cdb/dispatcher/cdbgang.c
  src/backend/cdb/motion/ic_tcp.c
  src/backend/cdb/motion/ic_udpifc.c
  src/test/regress/expected/motion_socket.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/motion_socket.sql
Labels: version: 7X_ALPHA

#13172 [6X] Fix FNullRejecting() error while trying to process zero-placed predicate
  src/backend/gporca/data/dxl/minidump/LOJNullRejectingZeroPlacePredicates.mdp
  src/backend/gporca/libgpopt/src/operators/CScalar.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 6X_STABLE, community
