Repository greenplum-db/gpdb, pull requests merged in 2022-11, with the labels that each got.

#14236 ADBDEV-3108: Postmaster process may exhaust all signal slots under intensive connections pressure (6X)
  src/backend/postmaster/postmaster.c
Labels: community

#14345 docs - update sql ref pages for ALTER/CREATE/DROP LANGUAGE commands
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_LANGUAGE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_LANGUAGE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_LANGUAGE.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_language.html.md
Labels: 7X_Docs

#14307 docs - update sql ref pages for GROUP/ROLE/USER commands
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_GROUP.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_ROLE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_USER.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_GROUP.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_ROLE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_USER.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_GROUP.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_USER.html.md
Labels: 7X_Docs

#10879 Remove unnecessary code that dealt with locus of UNION plans.
  src/backend/optimizer/prep/prepunion.c
  src/test/regress/expected/with_clause.out
Labels: community

#14336 Add test coverage for the partition inheritance behavior
  src/test/regress/expected/partition.out
  src/test/regress/expected/partition_optimizer.out
  src/test/regress/sql/partition.sql
Labels: version: 7X_ALPHA

#14355 pg_dump: fix upgrading external tables with dropped cols
  src/bin/pg_dump/pg_dump.c
  src/test/regress/expected/pg_dump_binary_upgrade.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/pg_dump_binary_upgrade.sql
Labels: topic: upgrade, area: server, needs: backport, pg_upgrade, pg_dump

#14356 [6X backport] pg_dump: fix upgrading external tables with dropped cols
  src/bin/pg_dump/pg_dump.c
  src/test/regress/expected/pg_dump_binary_upgrade.out
  src/test/regress/sql/pg_dump_binary_upgrade.sql
Labels: version: 6X_STABLE

#14387 docs - update sql ref pages for ALTER/CREATE/DROP SERVER
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_SERVER.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_SERVER.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_SERVER.html.md
Labels: 7X_Docs

#14377 Fix a wrong unlock mode in DefineRelation
  src/backend/commands/tablecmds.c
  src/test/regress/expected/partition_locking.out
  src/test/regress/expected/partition_locking_optimizer.out
Labels: version: 7X_ALPHA

#14339 ORCA: Fix query preprocessor for nested Select-Project-NaryJoin combination
  src/backend/gporca/data/dxl/minidump/NestedJoinWithCastedColumn.mdp
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionPreprocessor.h
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, version: 7X_ALPHA, needs: backport

#14379 Fix CBitSet Intersection logic in Orca
  src/backend/gporca/data/dxl/minidump/NestedInSubqWithPrjListOuterRefNoInnerRef.mdp
  src/backend/gporca/libgpos/server/src/unittest/gpos/common/CBitSetTest.cpp
  src/backend/gporca/libgpos/src/common/CBitSet.cpp
Labels: area: gporca, version: 7X_ALPHA

#14334 docs - add content for jsonpath, SQL/JSON path language
  gpdb-doc/markdown/admin_guide/query/topics/json-data.html.md
  gpdb-doc/markdown/ref_guide/function-summary.html.md
Labels: 7X_Docs

#14403 docs - update sql ref pages for TEXT SEARCH-related commands
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TEXT_SEARCH_CONFIGURATION.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TEXT_SEARCH_DICTIONARY.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TEXT_SEARCH_TEMPLATE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TEXT_SEARCH_CONFIGURATION.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TEXT_SEARCH_DICTIONARY.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TEXT_SEARCH_PARSER.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TEXT_SEARCH_TEMPLATE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_TEXT_SEARCH_CONFIGURATION.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_TEXT_SEARCH_DICTIONARY.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_TEXT_SEARCH_PARSER.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_TEXT_SEARCH_TEMPLATE.html.md
Labels: 7X_Docs

#14413 ao/co: Move unique index DML tests to new group
  src/test/regress/greenplum_schedule
Labels: version: 7X_ALPHA

#14414 ao/co: Fix snapshot setup for unique index checks
  src/backend/access/aocs/aocsam_handler.c
  src/backend/access/appendonly/appendonlyam_handler.c
Labels: version: 7X_ALPHA, area: aoco

#14410 Fix disjunctive constraint colid remapping
  src/backend/gporca/libgpopt/src/operators/CLogicalDynamicGet.cpp
  src/test/regress/expected/bfv_partition.out
  src/test/regress/sql/bfv_partition.sql
Labels: area: gporca, version: 7X_ALPHA

#14421 Remove gp_allow_rename_relation_without_lock
  src/backend/commands/tablecmds.c
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/include/utils/unsync_guc_name.h
  src/test/regress/expected/alter_table_gp.out
  src/test/regress/sql/alter_table_gp.sql
Labels: version: 7X_ALPHA

#14349 [6X] ORCA: Fix query preprocessor for nested Select-Project-NaryJoin
  src/backend/gporca/data/dxl/minidump/NestedJoinWithCastedColumn.mdp
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionPreprocessor.h
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, version: 6X_STABLE

#14406 [6X] Fix CBitSet Intersection logic in Orca
  src/backend/gporca/data/dxl/minidump/NestedInSubqWithPrjListOuterRefNoInnerRef.mdp
  src/backend/gporca/libgpos/server/src/unittest/gpos/common/CBitSetTest.cpp
  src/backend/gporca/libgpos/src/common/CBitSet.cpp
Labels: area: gporca, version: 6X_STABLE

#14288 Implement pg_get_expr() for subpartition template
  src/backend/utils/adt/ruleutils.c
  src/test/regress/expected/AOCO_Compression.out
  src/test/regress/expected/bfv_partition.out
  src/test/regress/expected/column_compression.out
  src/test/regress/expected/gp_partition_template.out
  src/test/regress/expected/partition.out
  src/test/regress/expected/partition_optimizer.out
  src/test/regress/sql/AOCO_Compression.sql
  src/test/regress/sql/bfv_partition.sql
  src/test/regress/sql/column_compression.sql
  src/test/regress/sql/gp_partition_template.sql
  src/test/regress/sql/partition.sql
Labels: topic: partitions, area: server, version: 7X_ALPHA

#14194 Add reloption to force table to collect HLL stats
  src/backend/access/common/reloptions.c
  src/backend/access/common/reloptions_gp.c
  src/backend/commands/analyze.c
  src/bin/psql/tab-complete.c
  src/include/access/reloptions.h
  src/include/utils/guc.h
  src/include/utils/rel.h
  src/test/regress/expected/incremental_analyze.out
  src/test/regress/expected/incremental_analyze_optimizer.out
  src/test/regress/sql/incremental_analyze.sql
Labels: area: gporca, version: 7X_ALPHA

#14418 Fix Range Tables related relations opening's locking issue inside ExecInitModifyTable().
  src/backend/executor/nodeModifyTable.c
  src/test/regress/expected/delete.out
  src/test/regress/sql/delete.sql
Labels: merge_fixme

#14111 Resolve a FIXME in merge_leaf_stats()
  src/backend/commands/analyze.c
  src/test/isolation2/expected/lockmodes.out
  src/test/isolation2/expected/lockmodes_optimizer.out
  src/test/isolation2/sql/lockmodes.sql
Labels: version: 7X_ALPHA, merge_fixme

#14366 Orca enable multiple grouping set specs
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/backend/gpopt/translate/CTranslatorUtils.cpp
  src/include/gpopt/translate/CTranslatorQueryToDXL.h
  src/include/gpopt/translate/CTranslatorUtils.h
  src/test/regress/expected/groupingsets_optimizer.out
  src/test/regress/expected/orca_groupingsets_fallbacks.out
  src/test/regress/expected/orca_groupingsets_fallbacks_optimizer.out
  src/test/regress/sql/orca_groupingsets_fallbacks.sql
Labels: area: gporca, version: 7X_ALPHA

#14422 ao/co: Correct tuple visibility reporting for index builds
  src/backend/access/aocs/aocsam_handler.c
  src/backend/access/appendonly/appendonlyam_handler.c
  src/test/isolation2/input/uao/index_build_reltuples.source
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/output/uao/index_build_reltuples.source
  src/test/regress/greenplum_schedule
  src/test/regress/input/uao_dml/ao_unique_index_build.source
  src/test/regress/output/uao_dml/ao_unique_index_build.source
Labels: version: 7X_ALPHA, area: aoco, merge_fixme

#14449 DOCS: Document new parameter to force collection of HLL stats for tables that are part of a partitioned table
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
Labels: version: 7X_ALPHA

#13499 Resolve GPDB_12_MERGE_FIXMEs: assertion in swap_relation_files in cluster.c
  src/backend/commands/cluster.c
Labels: merge_fixme

#14469 Replaced gpscp_help with gpsync_help
  gpMgmt/doc/Makefile
Labels: gpcm_in

#14351 Dump more info of releasing resource queue lock info
  src/backend/tcop/postgres.c
  src/backend/utils/resscheduler/resqueue.c
  src/test/isolation2/expected/resource_queue_multi_portal.out
  src/test/isolation2/sql/resource_queue_multi_portal.sql
Labels: version: 6X_STABLE

#14375 Fix typos
  gpMgmt/bin/gppylib/operations/startSegments.py
  gpMgmt/bin/gppylib/system/ComputeCatalogUpdate.py
  gpMgmt/bin/gppylib/system/configurationImplGpdb.py
Labels: version: 6X_STABLE, community

#14435 docs - update sql ref pages for ALTER/CREATE/DROP TABLESPACE
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLESPACE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLESPACE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_TABLESPACE.html.md
Labels: 7X_Docs

#14471 DOCS: Document ALTER TABLE column encodings feature
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
Labels: 7X_Docs

#14415 fix ic-proxy mis-disconnect addrs after reloading config file
  src/backend/cdb/motion/ic_proxy_addr.c
Labels: flaky test

#14149 (6x only) CUBE is limited to at most have 12 elements.
  src/backend/parser/gram.y
  src/backend/parser/parse_clause.c
  src/include/nodes/parsenodes.h
  src/test/regress/expected/olap_group.out
  src/test/regress/sql/olap_group.sql
Labels: version: 6X_STABLE

#14451 6X:Add a GUC to display create gang time while executing statements
  src/backend/cdb/dispatcher/cdbconn.c
  src/backend/cdb/dispatcher/cdbdisp_query.c
  src/backend/cdb/dispatcher/cdbgang.c
  src/backend/cdb/dispatcher/cdbgang_async.c
  src/backend/utils/misc/guc_gp.c
  src/include/cdb/cdbconn.h
  src/include/cdb/cdbgang.h
  src/include/utils/unsync_guc_name.h
  src/test/regress/init_file
  src/test/regress/input/dispatch.source
  src/test/regress/output/dispatch.source
Labels: backport

#14437 [6X] Add reloption to force table to collect HLL stats
  src/backend/access/common/reloptions.c
  src/backend/access/common/reloptions_gp.c
  src/backend/commands/analyze.c
  src/include/access/reloptions.h
  src/include/utils/guc.h
  src/include/utils/rel.h
  src/test/regress/expected/incremental_analyze.out
  src/test/regress/sql/incremental_analyze.sql
Labels: area: gporca, version: 6X_STABLE

#14551 RESET newly added GUC to pass binary swap tests
  src/test/isolation2/input/parallel_retrieve_cursor/concurrency.source
  src/test/isolation2/output/parallel_retrieve_cursor/concurrency.source
Labels: version: 6X_STABLE

#14453 FIX bug of multi-level correlated subquery
  src/backend/cdb/cdbsubselect.c
  src/backend/optimizer/plan/subselect.c
  src/backend/optimizer/util/paramassign.c
  src/include/optimizer/subselect.h
  src/test/regress/expected/bfv_catalog.out
  src/test/regress/expected/gporca.out
  src/test/regress/expected/qp_subquery.out
Labels: area: server

#14507 FIX multi-level correlated subquery bug 6X backport
  src/backend/cdb/cdbsubselect.c
  src/backend/optimizer/plan/subselect.c
  src/include/optimizer/subselect.h
  src/test/regress/expected/bfv_catalog.out
  src/test/regress/expected/gporca.out
  src/test/regress/expected/qp_subquery.out
Labels: version: 6X_STABLE

#14504 [6X] Skip invalid socks in checkDispatchResult()
  src/backend/cdb/dispatcher/cdbdisp_async.c
  src/test/regress/input/dispatch.source
  src/test/regress/output/dispatch.source
Labels: version: 6X_STABLE, needs: backport

#14521 Skip invalid socks in checkDispatchResult()
  src/backend/cdb/dispatcher/cdbdisp_async.c
  src/test/regress/input/dispatch.source
  src/test/regress/output/dispatch.source
Labels: version: 7X_ALPHA, backport

#14346 Fixme: basebackup slot creation
  gpMgmt/bin/gppylib/commands/pg.py
  gpMgmt/bin/gppylib/commands/test/unit/test_unit_pg_base_backup.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
  gpMgmt/bin/lib/gpconfigurenewsegment
  gpMgmt/sbin/gpsegrecovery.py
  gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
  gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: type: fixme, gpcm_in

#14505 Fix failure when DynamicSeqScan has a subPlan
  src/backend/executor/nodeDynamicBitmapHeapscan.c
  src/backend/executor/nodeDynamicSeqscan.c
  src/include/nodes/execnodes.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/qp_dropped_cols.out
  src/test/regress/expected/qp_dropped_cols_optimizer.out
  src/test/regress/sql/gporca.sql
  src/test/regress/sql/qp_dropped_cols.sql
Labels: area: gporca, version: 7X_ALPHA, community
