Repository greenplum-db/gpdb, pull requests merged in 2022-10, with the labels that each got.

#14129 Orca enable update and delete on partitioned tables
  src/backend/executor/nodeModifyTable.c
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/backend/gporca/data/dxl/minidump/DeleteMismatchedDistribution.mdp
  src/backend/gporca/data/dxl/minidump/Insert-AO.mdp
  src/backend/gporca/data/dxl/minidump/UpdateDistKeyMismatchedDistribution.mdp
  src/backend/gporca/data/dxl/minidump/UpdateNoDistKeyMismatchedDistribution.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformUpdate2DML.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerPhysicalDML.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CDMLTest.cpp
  src/backend/gporca/server/src/unittest/gpopt/translate/CTranslatorExprToDXLTest.cpp
  src/backend/nodes/copyfuncs.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfuncs.c
  src/backend/optimizer/plan/createplan.c
  src/include/nodes/plannodes.h
  src/test/isolation2/expected/lockmodes_optimizer.out
  src/test/regress/expected/DML_over_joins.out
  src/test/regress/expected/DML_over_joins_optimizer.out
  src/test/regress/expected/bfv_partition_plans.out
  src/test/regress/expected/bfv_partition_plans_optimizer.out
  src/test/regress/expected/direct_dispatch_optimizer.out
  src/test/regress/expected/inherit_optimizer.out
  src/test/regress/expected/partition_prune_optimizer.out
  src/test/regress/expected/qp_dml_joins_optimizer.out
  src/test/regress/expected/update_optimizer.out
  src/test/regress/sql/DML_over_joins.sql
  src/test/regress/sql/bfv_partition_plans.sql
Labels: area: gporca, version: 7X_ALPHA, merge_fixme

#14209 Revamp ic-proxy logging
  src/backend/cdb/motion/ic_proxy.h
  src/backend/cdb/motion/ic_proxy_addr.c
  src/backend/cdb/motion/ic_proxy_backend.c
  src/backend/cdb/motion/ic_proxy_client.c
  src/backend/cdb/motion/ic_proxy_iobuf.c
  src/backend/cdb/motion/ic_proxy_main.c
  src/backend/cdb/motion/ic_proxy_peer.c
  src/backend/cdb/motion/ic_proxy_pkt_cache.c
  src/backend/cdb/motion/ic_proxy_router.c
Labels: version: 7X_ALPHA, needs: backport, area: inter-connect

#14191 [ORCA] Fix window frame translator related FIXMEs
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
  src/backend/gporca/data/dxl/minidump/WindowFrameExcludeCurrentRow.mdp
  src/backend/gporca/data/dxl/minidump/WindowFrameExcludeGroup.mdp
  src/backend/gporca/data/dxl/minidump/WindowFrameExcludeTies.mdp
  src/backend/gporca/data/dxl/minidump/WindowFrameGroups.mdp
  src/backend/gporca/data/dxl/minidump/WindowFrameRangePrecedingAndFollowing.mdp
  src/backend/gporca/data/dxl/parse_tests/q45-WindowWithFraming.xml
  src/backend/gporca/libgpopt/include/gpopt/base/CWindowFrame.h
  src/backend/gporca/libgpopt/src/base/CWindowFrame.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
  src/backend/gporca/libnaucrates/include/naucrates/dxl/operators/CDXLWindowFrame.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerWindowFrame.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
  src/backend/gporca/libnaucrates/src/operators/CDXLOperatorFactory.cpp
  src/backend/gporca/libnaucrates/src/operators/CDXLWindowFrame.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerWindowFrame.cpp
  src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CWindowTest.cpp
  src/include/gpopt/translate/CTranslatorScalarToDXL.h
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/window.out
  src/test/regress/expected/window_optimizer.out
  src/test/regress/sql/window.sql
Labels: area: gporca, version: 7X_ALPHA, merge_fixme

#14201 [ORCA] Avoid pushdown of predicate with set-returning function
  src/backend/gporca/data/dxl/minidump/JoinOnViewWithSetReturningColumn.mdp
  src/backend/gporca/data/dxl/minidump/JoinWithSubqueryProjectColumn.mdp
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/qp_subquery.out
  src/test/regress/expected/qp_subquery_optimizer.out
  src/test/regress/sql/qp_subquery.sql
Labels: area: gporca, version: 7X_ALPHA, needs: backport

#14199 Support ALTER TABLE SET DISTRIBUTED BY for external tables
  src/backend/commands/tablecmds.c
  src/test/regress/input/external_table.source
  src/test/regress/output/external_table.source
Labels: version: 7X_ALPHA, needs: backport

#14210 [6X] Fix memory leak in DynamicBitmapScans
  src/backend/executor/nodeBitmapIndexscan.c
Labels: area: gporca, version: 6X_STABLE

#14189 [6X_STABLE] Ignore XLOG archive check when creating restart point on mirror segment
  src/backend/access/transam/xlog.c
  src/backend/access/transam/xlogarchive.c
  src/test/gpdb_pitr/expected/test_mirror_wal_recycling.out
  src/test/gpdb_pitr/sql/test_mirror_wal_recycling.sql
  src/test/gpdb_pitr/test_gpdb_pitr.sh
Labels: version: 6X_STABLE

#14217 [ORCA] Avoid pushdown of predicate with set-returning function (#14201)
  src/backend/gporca/data/dxl/minidump/JoinOnViewWithSetReturningColumn.mdp
  src/backend/gporca/data/dxl/minidump/JoinWithSubqueryProjectColumn.mdp
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/qp_subquery.out
  src/test/regress/expected/qp_subquery_optimizer.out
  src/test/regress/sql/qp_subquery.sql
Labels: area: gporca, version: 6X_STABLE, backport

#14222 Resolve FIXME in typecmds.c
  src/backend/commands/typecmds.c
Labels: version: 7X_ALPHA, pg_upgrade, merge_fixme, pg_dump

#14193 Derive combined hashed spec outer join
  src/backend/gporca/data/dxl/minidump/CTEWithMergedGroup.mdp
  src/backend/gporca/data/dxl/minidump/DynamicBitmapTableScan-PartAO-SemiJoin.mdp
  src/backend/gporca/data/dxl/minidump/DynamicIndexGet-OuterRefs.mdp
  src/backend/gporca/data/dxl/minidump/EagerAggGroupColumnInJoin.mdp
  src/backend/gporca/data/dxl/minidump/ExpandFullOuterJoin.mdp
  src/backend/gporca/data/dxl/minidump/ExpandNAryJoinGreedyWithLOJOnly.mdp
  src/backend/gporca/data/dxl/minidump/InSubqueryWithNotNullCol.mdp
  src/backend/gporca/data/dxl/minidump/InferPredicatesForProcessedColumn.mdp
  src/backend/gporca/data/dxl/minidump/InferPredicatesInnerOfLOJ.mdp
  src/backend/gporca/data/dxl/minidump/InnerJoinBroadcastTableHashSpec.mdp
  src/backend/gporca/data/dxl/minidump/InnerJoinOverJoinExcept.mdp
  src/backend/gporca/data/dxl/minidump/InnerJoinOverJoinExceptAll.mdp
  src/backend/gporca/data/dxl/minidump/InnerJoinReplicatedTableHashSpec.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-MultiDistKey-MultiIndexKey-NoExtraFilter.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-MultiDistKey-MultiIndexKey.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-MultiDistKeys-Bitmap-WithComplexPreds.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-MultiDistKeys-WithComplexPreds.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-WithComplexPredicates.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-With-Agg.mdp
  src/backend/gporca/data/dxl/minidump/LOJNonNullRejectingPredicates.mdp
  src/backend/gporca/data/dxl/minidump/LOJReorderComplexNestedLOJs.mdp
  src/backend/gporca/data/dxl/minidump/LOJ_bb_mpph.mdp
  src/backend/gporca/data/dxl/minidump/LeftJoinBroadcastTableHashSpec.mdp
  src/backend/gporca/data/dxl/minidump/LeftJoinNullsNotColocated.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-AggWithExistentialSubquery.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-DPE-GroupBy.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-MultiWayJoin.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-RightOuterHashJoin-DPE-IsNull.mdp
  src/backend/gporca/data/dxl/minidump/RightJoinNoDPSNonDistKey.mdp
  src/backend/gporca/data/dxl/minidump/RightJoinRedistribute.mdp
  src/backend/gporca/data/dxl/minidump/UnnestSQJoins.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecHashed.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalFullMergeJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalInnerHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftAntiSemiHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftAntiSemiHashJoinNotIn.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftOuterHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftSemiHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalRightOuterHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXformUtils.h
  src/backend/gporca/libgpopt/src/base/CDistributionSpecHashed.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalFullMergeJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalInnerHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftAntiSemiHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftAntiSemiHashJoinNotIn.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftOuterHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftSemiHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalRightOuterHashJoin.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/backend/gporca/server/src/unittest/gpopt/base/CDistributionSpecTest.cpp
  src/test/regress/expected/bfv_joins.out
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/expected/bfv_statistic_optimizer.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/join_optimizer.out
  src/test/regress/expected/notin_optimizer.out
  src/test/regress/sql/bfv_joins.sql
Labels: area: gporca, version: 6X_STABLE

#14200 pg_upgrade: Remove flags to add/remove data checksums
  src/bin/pg_upgrade/controldata.c
  src/bin/pg_upgrade/greenplum/option_gp.c
  src/bin/pg_upgrade/greenplum/pg_upgrade_greenplum.h
  src/bin/pg_upgrade/option.c
  src/bin/pg_upgrade/test_gpdb.sh
Labels: version: 7X_ALPHA, pg_upgrade

#14225 Dump number of segments during minirepro
  gpMgmt/bin/gpsd
  gpMgmt/bin/minirepro
  src/test/regress/expected/minirepro.out
Labels: area: gporca, version: 7X_ALPHA

#13925 COPY/CLUSTER: Use ntuples for gp_fastsequence allocation
  src/backend/access/aocs/aocs_compaction.c
  src/backend/access/aocs/aocsam.c
  src/backend/access/aocs/aocsam_handler.c
  src/backend/access/appendonly/appendonly_compaction.c
  src/backend/access/appendonly/appendonlyam.c
  src/backend/access/appendonly/appendonlyam_handler.c
  src/backend/catalog/gp_fastsequence.c
  src/include/cdb/cdbaocsam.h
  src/include/cdb/cdbappendonlyam.h
  src/test/regress/greenplum_schedule
  src/test/regress/input/uao_dml/gp_fastsequence.source
  src/test/regress/output/appendonly.source
  src/test/regress/output/uao_dml/gp_fastsequence.source
Labels: type: fixme, area: aoco, area: copy

#11563 Forward complete QE notice messages
  src/backend/cdb/dispatcher/cdbconn.c
Labels: community

#14240 Fix ALTER TABLE .. ENABLE/DISABLE TRIGGER recursion
  src/backend/commands/tablecmds.c
  src/backend/commands/trigger.c
  src/test/regress/expected/triggers.out
  src/test/regress/sql/triggers.sql
Labels: version: 7X_ALPHA

#14224 Fix errors when trying to DELETE FROM AO/CO auxiliary tables
  src/backend/executor/nodeModifyTable.c
  src/backend/rewrite/rewriteHandler.c
  src/test/regress/expected/uao_catalog_tables.out
  src/test/regress/expected/uaocs_catalog_tables.out
  src/test/regress/sql/uao_catalog_tables.sql
  src/test/regress/sql/uaocs_catalog_tables.sql
Labels: needs: backport

#14190 Support high security SSL encryption algorithms in libpq of 5X_STABLE
  src/backend/libpq/be-secure.c
Labels: version: 5X_STABLE

#14108 Fixed bug in legacy optimizer convert_EXPR_to_join (#14107) :
  src/backend/cdb/cdbsubselect.c
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/sql/subselect_gp.sql
Labels: community

#14271 ao/co: Perform serializable isolation check early
  src/backend/access/aocs/aocsam_handler.c
  src/backend/access/appendonly/appendonlyam_handler.c
  src/backend/executor/nodeModifyTable.c
Labels: version: 7X_ALPHA, merge_fixme

#14254 Make ALTER TABLE ... OWNER recurse by default
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_table.out
  src/test/regress/expected/vacuum.out
  src/test/regress/sql/alter_table.sql
  src/test/regress/sql/vacuum.sql
Labels: version: 7X_ALPHA

#14272 Comment out assertion in CBucket::SplitAndMergeBuckets
  src/backend/gporca/libgpos/src/string/CWStringDynamic.cpp
  src/backend/gporca/libnaucrates/src/statistics/CBucket.cpp
Labels: area: gporca, version: 7X_ALPHA

#14188 [6X only] Error out with wrong syntax into cause in AlterPartitionCmd.
  src/backend/commands/tablecmds.c
  src/test/regress/expected/partition.out
  src/test/regress/expected/partition_optimizer.out
  src/test/regress/sql/partition.sql
Labels: type: bug

#14001 Free underlying Dynamic Seq Scan structures after processing of each partition
  src/backend/access/aocs/aocsam.c
  src/backend/access/appendonly/appendonlyam.c
  src/backend/access/heap/heapam.c
  src/backend/executor/nodeDynamicSeqscan.c
  src/include/access/heapam.h
  src/include/cdb/cdbaocsam.h
  src/include/cdb/cdbappendonlyam.h
  src/test/regress/expected/bfv_partition_plans.out
  src/test/regress/expected/bfv_partition_plans_optimizer.out
  src/test/regress/sql/bfv_partition_plans.sql
Labels: version: 6X_STABLE, community

#14283 Patch handling of composite type returning TVF that evaluates to const
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
Labels: area: gporca, version: 7X_ALPHA

#14284 Simplify Nary join with inner joins if predicate is false in Orca
  src/backend/gporca/data/dxl/minidump/AggSubqCollapseFalseFilter.mdp
  src/backend/gporca/libgpopt/src/operators/CNormalizer.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, version: 7X_ALPHA

#14065 NEW SYNTAX of resource group cpuset
  src/backend/commands/resgroupcmds.c
  src/backend/utils/resgroup/resgroup.c
  src/include/utils/resgroup.h
  src/test/isolation2/expected/resgroup/resgroup_syntax.out
  src/test/isolation2/input/resgroup/resgroup_cpuset.source
  src/test/isolation2/output/resgroup/resgroup_cpuset.source
  src/test/isolation2/sql/resgroup/resgroup_syntax.sql
Labels: area: server

#13620 Error out if any segment has a running basebackup
  gpMgmt/bin/gpexpand
  gpMgmt/bin/gpmovemirrors
  gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
  gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment_triples.py
  gpMgmt/test/behave/mgmt_utils/environment.py
  gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
  gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
Labels: gpcm_in, Priority 1

#14263 Dispatch ALTER DATABASE with options
  src/backend/commands/dbcommands.c
  src/backend/nodes/outfast.c
  src/backend/nodes/readfast.c
  src/backend/nodes/readfuncs.c
  src/test/regress/expected/connection_limits.out
  src/test/regress/expected/dboptions.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/connection_limits.sql
  src/test/regress/sql/dboptions.sql
Labels: version: 7X_ALPHA, area: dispatch

#14315 Change FIXME to note in join_hash case.
  src/test/regress/expected/join_hash.out
  src/test/regress/expected/join_hash_optimizer.out
  src/test/regress/sql/join_hash.sql
Labels: type: fixme, merge_fixme

#14316 Remove get_selected_parts FIXME.
  src/test/regress/expected/partition_pruning.out
  src/test/regress/expected/partition_pruning_optimizer.out
  src/test/regress/sql/partition_pruning.sql
Labels: type: fixme, merge_fixme

#14318 Remove already fixed non-default collate orca fallback in test.
  src/test/regress/expected/arrays.out
  src/test/regress/expected/bfv_index.out
  src/test/regress/expected/bfv_index_optimizer.out
  src/test/regress/sql/arrays.sql
  src/test/regress/sql/bfv_index.sql
Labels: type: fixme, merge_fixme

#14301 Fix gpload regress case failure when OS user is not gpadmin
  gpMgmt/bin/gpload_test/gpload2/TEST_local_config.py
Labels: community

#14247 [6X backport] Fix errors when trying to DELETE FROM AO/CO auxiliary tables
  src/backend/executor/nodeModifyTable.c
  src/backend/rewrite/rewriteHandler.c
  src/test/regress/expected/uao_catalog_tables.out
  src/test/regress/expected/uaocs_catalog_tables.out
  src/test/regress/sql/uao_catalog_tables.sql
  src/test/regress/sql/uaocs_catalog_tables.sql
Labels: version: 6X_STABLE

#14048 Invalidate CatCache in AbortTransaction to clear reader gang's cache.
  src/backend/access/transam/xact.c
  src/test/regress/expected/catcache.out
  src/test/regress/expected/catcache_optimizer.out
  src/test/regress/expected/qp_union_intersect.out
  src/test/regress/expected/qp_union_intersect_optimizer.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/catcache.sql
  src/test/regress/sql/qp_union_intersect.sql
Labels: type: fixme, merge_fixme

#14289 Fix crash of not-in pullup sublink with Params
  src/backend/cdb/cdbsubselect.c
  src/test/regress/expected/notin.out
  src/test/regress/expected/notin_optimizer.out
  src/test/regress/sql/notin.sql
Labels: area: server

#14232 docs - update sql ref pages for ALTER DEFAULT PRIVS, GRANT, REVOKE
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_DEFAULT_PRIVILEGES.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/GRANT.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/REVOKE.html.md
Labels: 7X_Docs

#14342 [5X] Clear retry flags properly in replacement OpenSSL sock_write function.
  src/backend/libpq/be-secure.c
Labels: version: 5X_STABLE

#14273 Fix bug that Orca may crash on null pointer in case of DPE with dynamic partial scan
  src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
  src/backend/gporca/libgpos/src/string/CWStringDynamic.cpp
  src/backend/gporca/libnaucrates/src/statistics/CBucket.cpp
Labels: area: gporca, version: 6X_STABLE

#14285 Orca supports propagating predicate from scalar any subquery to outer relation
  src/backend/gporca/data/dxl/minidump/CorrelatedSubqueryWithAggWindowFunc.mdp
  src/backend/gporca/data/dxl/minidump/DynamicIndexScan-Heterogenous-UnsupportedPredicate.mdp
  src/backend/gporca/data/dxl/minidump/InferPredicatesFromExistsSubquery.mdp
  src/backend/gporca/data/dxl/minidump/InferPredicatesFromMultiSubquery.mdp
  src/backend/gporca/data/dxl/minidump/InferPredicatesIntFromExistsSubquery.mdp
  src/backend/gporca/data/dxl/minidump/InferPredicatesIntFromSubquery.mdp
  src/backend/gporca/data/dxl/minidump/InferPredicatesJoinSubquery.mdp
  src/backend/gporca/data/dxl/minidump/InferPredicatesMultiColumns.mdp
  src/backend/gporca/data/dxl/minidump/NotWellDefinedDisjunctConjunctPredicates.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-DPE-GroupBy.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-NEqPredicate.mdp
  src/backend/gporca/data/dxl/minidump/PushFilterToSemiJoinLeftChild.mdp
  src/backend/gporca/data/dxl/minidump/SemiJoin2InnerJoin.mdp
  src/backend/gporca/data/dxl/minidump/SemiJoinWithWindowsFuncInSubquery.mdp
  src/backend/gporca/data/dxl/minidump/Subq-JoinWithOuterRef.mdp
  src/backend/gporca/data/dxl/minidump/Subq2PartialDecorrelate.mdp
  src/backend/gporca/data/dxl/minidump/SubqExists-With-External-Corrs.mdp
  src/backend/gporca/data/dxl/minidump/SubqExists-Without-External-Corrs.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CConstraint.h
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionPreprocessor.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionUtils.h
  src/backend/gporca/libgpopt/src/base/CConstraint.cpp
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/libgpopt/src/operators/CExpressionUtils.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalSelect.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/qp_correlated_query_optimizer.out
  src/test/regress/expected/subselect_gp_optimizer.out
Labels: area: gporca, version: 6X_STABLE

#14297 Patch handling of composite type returning TVF that evaluates to cons…
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
Labels: area: gporca, version: 6X_STABLE

#14246 [6X] Fix dependency bug with minirepro and materialized views (#14223)
  src/backend/rewrite/rewriteHandler.c
  src/backend/tcop/postgres.c
  src/backend/utils/adt/gp_dump_oids.c
  src/include/nodes/parsenodes.h
  src/include/tcop/tcopprot.h
  src/test/regress/expected/gp_dump_query_oids.out
  src/test/regress/sql/gp_dump_query_oids.sql
Labels: area: gporca, version: 6X_STABLE

#14299 [6X] Simplify Nary join with inner joins if predicate is false in Orca (#14284)
  src/backend/gporca/data/dxl/minidump/AggSubqCollapseFalseFilter.mdp
  src/backend/gporca/libgpopt/src/operators/CNormalizer.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, version: 6X_STABLE

#14282 [6X] Allow direct dispatch when filtering on gp_segment_id
  src/backend/gporca/data/dxl/minidump/DirectDispatch-GpSegmentId-MultiCol-Conjunction.mdp
  src/backend/gporca/data/dxl/minidump/DirectDispatch-GpSegmentId-SingleCol-Conjunction.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CConstraint.h
  src/backend/gporca/libgpopt/include/gpopt/base/CConstraintConjunction.h
  src/backend/gporca/libgpopt/include/gpopt/base/CConstraintInterval.h
  src/backend/gporca/libgpopt/src/base/CConstraintConjunction.cpp
  src/backend/gporca/libgpopt/src/base/CConstraintInterval.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXLUtils.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CDirectDispatchTest.cpp
  src/test/regress/expected/direct_dispatch.out
  src/test/regress/expected/direct_dispatch_optimizer.out
  src/test/regress/sql/direct_dispatch.sql
Labels: area: gporca, version: 6X_STABLE

#14145 Replace scp with rsync
  gpMgmt/bin/Makefile
  gpMgmt/bin/README.md
  gpMgmt/bin/gpcheckperf
  gpMgmt/bin/gpexpand
  gpMgmt/bin/gpmemwatcher
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/bin/gppylib/commands/unix.py
  gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
  gpMgmt/bin/gppylib/operations/package.py
  gpMgmt/bin/gppylib/operations/test/regress/test_package/__init__.py
  gpMgmt/bin/gppylib/operations/test/regress/test_package/test_regress_muck_with_internals.py
  gpMgmt/bin/gppylib/operations/test/regress/test_package/test_regress_muck_with_internals_on_standby.py
  gpMgmt/bin/gppylib/operations/test/test_package.py
  gpMgmt/bin/gppylib/test/unit/test_unit_package.py
  gpMgmt/bin/gpssh-exkeys
  gpMgmt/bin/gpsync
  gpMgmt/bin/lib/gp_bash_functions.sh
  gpMgmt/test/behave/mgmt_utils/gppkg.feature
  gpMgmt/test/behave/mgmt_utils/steps/gpconfig_mgmt_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/gpssh_exkeys_mgmt_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in

#14329 [ORCA] Enable CUBE result grouping set
  src/backend/gpopt/translate/CTranslatorUtils.cpp
  src/include/gpopt/translate/CTranslatorUtils.h
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/groupingsets_optimizer.out
  src/test/regress/expected/orca_groupingsets_fallbacks_optimizer.out
  src/test/regress/expected/tsrf.out
  src/test/regress/expected/tsrf_optimizer.out
  src/test/regress/sql/tsrf.sql
Labels: area: gporca, version: 7X_ALPHA
