Repository greenplum-db/gpdb, pull requests merged in 2022-12, with the labels that each got.

#14332 NEW SYNTAX for resource group cpuset
  src/backend/commands/resgroupcmds.c
  src/backend/utils/resgroup/resgroup.c
  src/include/utils/resgroup.h
  src/test/isolation2/expected/resgroup/resgroup_syntax.out
  src/test/isolation2/input/resgroup/resgroup_cpuset.source
  src/test/isolation2/output/resgroup/resgroup_cpuset.source
  src/test/isolation2/sql/resgroup/resgroup_syntax.sql
Labels: area: server

#14519 Add test for pg_attribute_encoding entries with various AOCS table creation syntax
  src/test/regress/input/aocs.source
  src/test/regress/output/aocs.source
Labels: version: 7X_ALPHA

#14457 ORCA: Fix data corruption error for text related domain types
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
  src/include/gpopt/gpdbwrappers.h
  src/include/gpopt/translate/CTranslatorScalarToDXL.h
  src/test/regress/expected/domain.out
  src/test/regress/expected/domain_optimizer.out
  src/test/regress/sql/domain.sql
Labels: area: gporca, version: 7X_ALPHA, needs: backport

#14585 Update Orca explain pipeline for rhel8 changes
  concourse/tasks/run_explain_suite.yml
  src/backend/gporca/concourse/test_explain_pipeline.yml
Labels: area: gporca

#14581 [6X] Always add 'true' to 'appendonly'/'appendoptimized' reloptions
  src/backend/parser/gram.y
  src/test/regress/input/aocs.source
  src/test/regress/output/aocs.source
Labels: version: 6X_STABLE

#14598 [6x backport] If QEs hit errors in explain analyze, rethrow the error before ExplainPrintPlan
  src/backend/commands/explain.c
  src/backend/executor/nodeSort.c
  src/test/regress/expected/gp_explain.out
  src/test/regress/expected/gp_explain_optimizer.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/gp_explain.sql
Labels: backport

#14192 Penalize skewed hash join
  src/backend/gpopt/utils/COptTasks.cpp
  src/backend/gporca/data/dxl/minidump/CTAS_OrderedAgg_multiple_cols.mdp
  src/backend/gporca/data/dxl/minidump/HAWQ-TPCH-Stat-Derivation.mdp
  src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
  src/backend/gporca/libgpopt/include/gpopt/cost/ICostModel.h
  src/backend/gporca/libgpopt/include/gpopt/engine/CHint.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysical.h
  src/backend/gporca/libgpopt/src/optimizer/COptimizerConfig.cpp
  src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CBucket.h
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CHistogram.h
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerHint.cpp
  src/backend/gporca/libnaucrates/src/statistics/CBucket.cpp
  src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp
  src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/include/utils/unsync_guc_name.h
  src/test/regress/expected/qp_skew.out
  src/test/regress/expected/qp_skew_optimizer.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/qp_skew.sql
Labels: area: gporca, version: 7X_ALPHA

#14577 Fix crash of AggNode in executor casued by ORCA plan
  src/backend/executor/execExpr.c
  src/backend/executor/nodeAgg.c
  src/test/regress/expected/gp_dqa.out
  src/test/regress/expected/gp_dqa_optimizer.out
  src/test/regress/sql/gp_dqa.sql
Labels: area: gporca, area: server

#14367 docs - row-level security
  gpdb-doc/markdown/admin_guide/partIII.html.md
  gpdb-doc/markdown/admin_guide/roles_privs.html.md
  gpdb-doc/markdown/admin_guide/row_security.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_POLICY.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_POLICY.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_POLICY.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/sql_ref.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-html.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-tables.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_policies.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_policy.html.md
  gpdb-doc/markdown/ref_guide/toc.md
Labels: 7X_Docs

#14616 docs - ALTER/CREATE/DROP RULE sql ref page updates
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RULE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RULE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_RULE.html.md
Labels: 7X_Docs

#14626 Change Tanzu Greenplum to VMware Greenplum for v7
  gpdb-doc/markdown/admin_guide/highavail/topics/g-enabling-high-availability-features.html.md
  gpdb-doc/markdown/admin_guide/highavail/topics/g-overview-of-high-availability-in-greenplum-database.html.md
  gpdb-doc/markdown/admin_guide/highavail/topics/g-understanding-segment-recovery.html.md
  gpdb-doc/markdown/admin_guide/intro/about_ha.html.md
  gpdb-doc/markdown/admin_guide/intro/arch_overview.html.md
  gpdb-doc/markdown/admin_guide/load/topics/g-loading-and-unloading-data.html.md
  gpdb-doc/markdown/admin_guide/managing/backup-main.html.md
  gpdb-doc/markdown/admin_guide/managing/gpcopy-migrate.html.md
  gpdb-doc/markdown/admin_guide/managing/monitor.html.md
  gpdb-doc/markdown/admin_guide/parallel_retrieve_cursor.html.md
  gpdb-doc/markdown/admin_guide/perf_troubleshoot.html.md
  gpdb-doc/markdown/admin_guide/query/topics/xml-data.html.md
  gpdb-doc/markdown/admin_guide/textsearch/full-text-search.html.md
  gpdb-doc/markdown/admin_guide/textsearch/intro.html.md
  gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
  gpdb-doc/markdown/analytics/overview.html.md
  gpdb-doc/markdown/analytics/pl_container.html.md
  gpdb-doc/markdown/analytics/postGIS.html.md
  gpdb-doc/markdown/analytics/text.html.md
  gpdb-doc/markdown/best_practices/ha.html.md
  gpdb-doc/markdown/best_practices/resgroups.html.md
  gpdb-doc/markdown/common/gpdb-features.html.md.erb
  gpdb-doc/markdown/install_guide/apx_mgmt_utils.html.md
  gpdb-doc/markdown/install_guide/data_sci_pkgs.html.md
  gpdb-doc/markdown/install_guide/install_extensions.html.md
  gpdb-doc/markdown/install_guide/install_gpdb.html.md
  gpdb-doc/markdown/install_guide/install_guide.html.md
  gpdb-doc/markdown/install_guide/install_modules.html.md
  gpdb-doc/markdown/install_guide/install_pxf.html.md
  gpdb-doc/markdown/install_guide/install_python_dsmod.html.md
  gpdb-doc/markdown/install_guide/install_r_dslib.html.md
  gpdb-doc/markdown/install_guide/migrate.html.md
  gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
  gpdb-doc/markdown/install_guide/platform-requirements.html.md
  gpdb-doc/markdown/install_guide/preinstall_concepts.html.md
  gpdb-doc/markdown/install_guide/prep_os.html.md
  gpdb-doc/markdown/install_guide/upgrade_intro.html.md
  gpdb-doc/markdown/install_guide/upgrading.html.md
  gpdb-doc/markdown/install_guide/verify_sw.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
  gpdb-doc/markdown/ref_guide/datatype-pseudo.html.md
  gpdb-doc/markdown/ref_guide/extensions/srvapi_intro.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TYPE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE_AS.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TYPE.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_appendonly.html.md
  gpdb-doc/markdown/security-guide/topics/preface.html.md
  gpdb-doc/markdown/utility_guide/about-utils.html.md
  gpdb-doc/markdown/utility_guide/ref/gpcopy.html.md
  gpdb-doc/markdown/utility_guide/utility-programs.html.md
Labels: 7X_Docs

#14610 [6X] use correct hash function when summing AO tuple counts
  src/backend/cdb/dispatcher/cdbdispatchresult.c
  src/backend/cdb/dispatcher/test/cdbdispatchresult_test.c
Labels: version: 6X_STABLE

#14591 Fix failure when DynamicSeqScan has a subPlan
  src/backend/executor/nodeDynamicBitmapHeapscan.c
  src/backend/executor/nodeDynamicSeqscan.c
  src/include/nodes/execnodes.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/qp_dropped_cols.out
  src/test/regress/expected/qp_dropped_cols_optimizer.out
  src/test/regress/sql/gporca.sql
  src/test/regress/sql/qp_dropped_cols.sql
Labels: area: gporca, version: 6X_STABLE, community

#14594 Fix GRANT/REVOKE when some tables are partitioned and some are not
  src/backend/catalog/aclchk.c
  src/test/regress/expected/privileges.out
  src/test/regress/sql/privileges.sql
Labels: version: 6X_STABLE, community

#14607 Fix incorrect plan / output in multi stage agg
  src/backend/executor/nodeAgg.c
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
  src/include/nodes/nodes.h
  src/test/regress/expected/gp_dqa.out
  src/test/regress/expected/gp_dqa_optimizer.out
  src/test/regress/sql/gp_dqa.sql
Labels: area: gporca, version: 7X_ALPHA

#14663 ao/co: Clarify compute_xid_horizon_for_tuples API
  src/backend/access/aocs/aocsam_handler.c
  src/backend/access/appendonly/appendonlyam_handler.c
Labels: version: 7X_ALPHA, merge_fixme

#14666 Fix relcache lookup in Orca when selecting from sequence
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
Labels: area: gporca

#14669 ao/co: Clarify tuple_lock API
  src/backend/access/aocs/aocsam_handler.c
  src/backend/access/appendonly/appendonlyam_handler.c
Labels: version: 7X_ALPHA, area: aoco, merge_fixme

#14620 Penalize redistributed hash join in case of skew
  src/backend/gpopt/utils/COptTasks.cpp
  src/backend/gporca/data/dxl/minidump/HAWQ-TPCH-Stat-Derivation.mdp
  src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
  src/backend/gporca/libgpopt/include/gpopt/cost/ICostModel.h
  src/backend/gporca/libgpopt/include/gpopt/engine/CHint.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysical.h
  src/backend/gporca/libgpopt/src/optimizer/COptimizerConfig.cpp
  src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CBucket.h
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CHistogram.h
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerHint.cpp
  src/backend/gporca/libnaucrates/src/statistics/CBucket.cpp
  src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp
  src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/include/utils/unsync_guc_name.h
  src/test/regress/expected/qp_skew.out
  src/test/regress/expected/qp_skew_optimizer.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/qp_skew.sql
Labels: area: gporca, version: 6X_STABLE

#14212 ADBDEV-2947: SIGPIPE during fechine external table data by extended protocol
  src/backend/executor/execUtils.c
  src/test/regress/input/external_table.source
  src/test/regress/output/external_table.source
Labels: community

#14652 Fixing ONLY keyword for multiple tables in GRANT/REVOKE
  src/backend/parser/gram.y
  src/test/regress/expected/role.out
  src/test/regress/sql/role.sql
Labels: version: 7X_ALPHA

#14391 Docs - Update syntax for CPUSET to account for separate core specifications …
  gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
  gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
Labels: 7X_Docs

#14668 ao/co: Ban speculative insert in parse analysis
  src/backend/access/aocs/aocsam_handler.c
  src/backend/access/appendonly/appendonlyam_handler.c
  src/backend/parser/analyze.c
  src/test/regress/input/uao_dml/uao_dml.source
  src/test/regress/output/uao_dml/uao_dml.source
Labels: version: 7X_ALPHA, merge_fixme

#14675 [6X] Do not consider certain relkinds when dumping 5X cluster
  src/bin/pg_dump/pg_dump.c
Labels: version: 6X_STABLE

#13959 Support intermediate aggregate in planner
  src/backend/cdb/cdbgroupingpaths.c
  src/backend/optimizer/plan/planner.c
  src/backend/optimizer/plan/setrefs.c
  src/include/nodes/nodes.h
  src/test/regress/expected/gp_dqa.out
  src/test/regress/expected/gp_dqa_optimizer.out
  src/test/regress/expected/partition_aggregate.out
  src/test/regress/sql/gp_dqa.sql
Labels: area: server

#14681 Fix CI job references of gate_release_candidate_start
  concourse/pipelines/gpdb_6X_STABLE-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: version: 6X_STABLE, area:ci

#14556 Remove GPDB_12_MERGE_FIXME in cdb_create_multistage_grouping_paths()
  src/backend/cdb/cdbgroupingpaths.c
Labels: merge_fixme

#14642 Add a GUC to discard redistribute hashjoin for Orca
  src/backend/gpopt/config/CConfigParamMapping.cpp
  src/backend/gporca/data/dxl/minidump/DiscardRedistributeHashJoin.mdp
  src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
  src/backend/gporca/libnaucrates/include/naucrates/traceflags/traceflags.h
  src/backend/gporca/server/CMakeLists.txt
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/include/utils/unsync_guc_name.h
Labels: area: gporca, version: 7X_ALPHA

#13958 Remove PartitionSelector insertion for DML operation
  src/backend/gporca/data/dxl/minidump/DeleteMismatchedDistribution.mdp
  src/backend/gporca/data/dxl/minidump/Insert-Parquet-Partitioned-SortDisabled.mdp
  src/backend/gporca/data/dxl/minidump/InsertMismatchedDistrubution-2.mdp
  src/backend/gporca/data/dxl/minidump/InsertMismatchedDistrubution.mdp
  src/backend/gporca/data/dxl/minidump/LeftJoin-With-Pred-On-Inner2.mdp
  src/backend/gporca/data/dxl/minidump/UpdateDistKeyMismatchedDistribution.mdp
  src/backend/gporca/data/dxl/minidump/UpdateDroppedCols.mdp
  src/backend/gporca/data/dxl/minidump/UpdateNoDistKeyMismatchedDistribution.mdp
  src/backend/gporca/data/dxl/minidump/UpdatePartTable.mdp
  src/backend/gporca/libgpopt/src/xforms/CXformUpdate2DML.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
  src/test/regress/expected/gp_unique_rowid_optimizer.out
  src/test/regress/expected/partition_pruning_optimizer.out
  src/test/regress/expected/update_gp_optimizer.out
Labels: area: gporca, version: 6X_STABLE, community
