Repository greenplum-db/gpdb, pull requests merged in 2022-05, with the labels that each got.

#13441 Fix flaky test checkpoint_dtx_info
  src/test/isolation2/expected/checkpoint_dtx_info.out
  src/test/isolation2/sql/checkpoint_dtx_info.sql
Labels: version: 7X_ALPHA, needs: backport

#13444 [6x] Fix flaky test checkpoint_dtx_info
  src/test/isolation2/expected/checkpoint_dtx_info.out
  src/test/isolation2/sql/checkpoint_dtx_info.sql
Labels: version: 6X_STABLE, backport

#13436 remove fixme in gang_reuse.sql
  src/test/regress/expected/gang_reuse.out
  src/test/regress/expected/gang_reuse_optimizer.out
  src/test/regress/sql/gang_reuse.sql
Labels: type: fixme

#13447 Preserve AO storage options during internal CTAS
  src/backend/commands/tablecmds.c
  src/test/regress/expected/expand_table_ao.out
  src/test/regress/sql/expand_table_ao.sql
Labels: needs: backport

#13455 Check the return value of get_database_name() in external_set_env_vars_ext()
  src/backend/access/external/fileam.c
Labels: version: 5X_STABLE

#13461 6X: Preserve AO storage options during internal CTAS
  src/backend/commands/tablecmds.c
  src/test/regress/expected/expand_table_ao.out
  src/test/regress/sql/expand_table_ao.sql
Labels: area: server, version: 6X_STABLE

#13421 [ORCA] Enable more HashAggregate alternative plans
  src/backend/gporca/data/dxl/minidump/AggregateWithSkew.mdp
  src/backend/gporca/data/dxl/minidump/DQA-GroupBy-HashAggregate1.mdp
  src/backend/gporca/data/dxl/minidump/DQA-GroupBy-HashAggregate2.mdp
  src/backend/gporca/data/dxl/minidump/DQA-InnerJoin-GroupBy-HashAggregate.mdp
  src/backend/gporca/data/dxl/minidump/DQA-NonRedistributableCol.mdp
  src/backend/gporca/data/dxl/minidump/DqaNoRedistribute.mdp
  src/backend/gporca/data/dxl/minidump/LOJ_bb_mpph.mdp
  src/backend/gporca/data/dxl/minidump/MultiColumnDQA-InnerJoin-GroupBy-HashAggregate.mdp
  src/backend/gporca/data/dxl/minidump/ScalarDQAWithNonScalarAgg.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-DistinctOnComputedCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-DistinctOnDistrCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-DistinctOnSameNonDistrCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-GbMultipleCol-DistinctOnDistrCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-GbandDistinctOnDistrCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg.mdp
  src/backend/gporca/data/dxl/minidump/UnionOfDQAQueries.mdp
  src/backend/gporca/data/dxl/minidump/WinFunc-Redistribute-Sort-CTE-Producer.mdp
  src/backend/gporca/libgpopt/src/operators/CPhysicalAgg.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformSplitDQA.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CAggTest.cpp
Labels: area: gporca

#13412 gpstate -e: Remove progress for killed recoverseg
  gpMgmt/bin/gppylib/programs/clsSystemState.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/gpstate.feature
  gpMgmt/test/behave/mgmt_utils/steps/gpstate_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in

#13206 Resolve Fixmes in cdbgang_async.c and cdbdisp_async.c
  src/backend/cdb/dispatcher/cdbdisp_async.c
  src/backend/cdb/dispatcher/cdbgang_async.c
  src/backend/postmaster/pgstat.c
  src/backend/tcop/postgres.c
  src/include/pgstat.h
  src/test/isolation2/expected/gpdispatch.out
  src/test/isolation2/expected/gpdispatch_1.out
  src/test/isolation2/sql/gpdispatch.sql
Labels: type: fixme

#13468 Fixed 'select distinct <tbl_name> from <tbl_name>' for inheritance/partition table in GP7
  src/backend/utils/adt/selfuncs.c
  src/test/regress/expected/select_distinct.out
  src/test/regress/expected/select_distinct_optimizer.out
  src/test/regress/sql/select_distinct.sql
Labels: community

#13460 Remove the gpdb_12_merge_fixmes in workfile_mgr_test.c
  src/backend/executor/nodeHash.c
  src/backend/executor/nodeHashjoin.c
  src/backend/storage/file/buffile.c
  src/include/storage/buffile.h
  src/test/isolation2/input/workfile_mgr_test.source
  src/test/isolation2/output/workfile_mgr_test.source
  src/test/isolation2/workfile_mgr_test.c
Labels: type: fixme

#13350 Initialize lastSequence only for the target scanning segments before index scan.
  src/backend/access/aocs/aocsam.c
  src/backend/access/aocs/aocsam_handler.c
  src/backend/access/aocs/aocssegfiles.c
  src/backend/access/appendonly/aosegfiles.c
  src/backend/access/appendonly/appendonly_visimap_udf.c
  src/backend/access/appendonly/appendonlyam.c
  src/backend/access/brin/brin.c
  src/backend/access/heap/heapam_handler.c
  src/backend/commands/tablecmds.c
  src/backend/commands/vacuum_ao.c
  src/include/access/aocssegfiles.h
  src/include/access/aosegfiles.h
  src/include/access/tableam.h
  src/include/cdb/cdbaocsam.h
  src/include/cdb/cdbappendonlyam.h
  src/test/isolation2/input/uao/limit_indexscan_inits.source
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/output/uao/limit_indexscan_inits.source
Labels: type: enhancement

#13466 Resolve GPDB_12_MERGE_FIXME in pathnode.c
  src/backend/optimizer/util/pathnode.c
  src/test/regress/expected/qp_functions_in_contexts_setup.out
  src/test/regress/expected/qp_functions_in_subquery.out
  src/test/regress/sql/qp_functions_in_contexts_setup.sql
  src/test/regress/sql/qp_functions_in_subquery.sql
Labels: type: fixme

#13254 6X: Add GUC gp_log_endpoints to print endpoints information to server log
  src/backend/cdb/endpoint/cdbendpoint.c
  src/backend/cdb/endpoint/cdbendpointretrieve.c
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/include/utils/sync_guc_name.h
Labels: version: 6X_STABLE

#13411 [6X] Disregard dtx when pruning IC history
  src/backend/cdb/motion/ic_udpifc.c
Labels: version: 6X_STABLE, backport, area: inter-connect

#13498 (6x) Use hostname instead of ip to compute the host_segments.
  src/backend/cdb/cdbutil.c
Labels: version: 6X_STABLE

#13213 6X: dispatch temporary namespace ID to all Gangs.
  src/backend/catalog/namespace.c
  src/backend/cdb/dispatcher/cdbdisp_query.c
  src/backend/tcop/postgres.c
  src/include/catalog/namespace.h
  src/test/regress/expected/bfv_temp.out
  src/test/regress/sql/bfv_temp.sql
Labels: version: 6X_STABLE

#13177 Updated CPhysicalJoin to derive the inner distribution in the case of tainted replicated
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpec.h
  src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
  src/test/regress/expected/rpt.out
  src/test/regress/expected/rpt_optimizer.out
  src/test/regress/sql/rpt.sql
Labels: area: gporca, version: 7X_ALPHA

#13497 remove GPDB_12_MERGE_FIXME in tidbitmap.h: make sure TBM_BITS_PER_BITMAPWORD is 64-bit
  src/include/nodes/tidbitmap.h
Labels: type: fixme

#13508 Remove FIXME about maxdistinct/sort_flags
  src/backend/executor/nodeSort.c
Labels: type: fixme

#13353 [6X] Restore visibility of some GUCs to be viewable from pg_settings
  src/backend/utils/misc/guc.c
Labels: version: 6X_STABLE

#13422 Support Const TVF returning composite type in ORCA
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/gpopt/translate/CTranslatorUtils.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalTVF.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalTVF.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
  src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
  src/backend/gporca/libnaucrates/include/naucrates/md/IMDRelation.h
  src/backend/gporca/libnaucrates/src/md/IMDRelation.cpp
  src/backend/gporca/libnaucrates/src/operators/CDXLLogicalTVF.cpp
  src/backend/gporca/libnaucrates/src/operators/CDXLPhysicalTVF.cpp
  src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
  src/include/gpopt/translate/CTranslatorUtils.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca

#13413 Update mirror port in postgresql.conf
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
  gpMgmt/bin/gppylib/operations/test/unit/test_unit_buildMirrorSegments.py
  gpMgmt/bin/gppylib/recoveryinfo.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
  gpMgmt/bin/gppylib/test/unit/test_unit_recoveryinfo.py
  gpMgmt/bin/lib/gp_bash_functions.sh
  gpMgmt/bin/lib/gpcreateseg.sh
  gpMgmt/sbin/gpsegrecovery.py
  gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
  gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
  gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/gprecoverseg_newhost.feature
Labels: gpcm_in

#13530 fix failed pipeline caused in pr[13413].
  gpMgmt/bin/gppylib/test/unit/test_unit_recoveryinfo.py
Labels: gpcm_in

#13472 Fix double free in debug build
  src/backend/gporca/data/dxl/minidump/DqaAddRef.mdp
  src/backend/gporca/libgpopt/src/xforms/CXformSplitDQA.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, version: 6X_STABLE

#13503 [ORCA] Enable more HashAggregate alternative plans
  src/backend/gporca/data/dxl/minidump/AggregateWithSkew.mdp
  src/backend/gporca/data/dxl/minidump/DQA-1-RegularAgg.mdp
  src/backend/gporca/data/dxl/minidump/DQA-2-RegularAgg.mdp
  src/backend/gporca/data/dxl/minidump/DQA-GroupBy-HashAggregate1.mdp
  src/backend/gporca/data/dxl/minidump/DQA-GroupBy-HashAggregate2.mdp
  src/backend/gporca/data/dxl/minidump/DQA-InnerJoin-GroupBy-HashAggregate.mdp
  src/backend/gporca/data/dxl/minidump/DQA-NonRedistributableCol.mdp
  src/backend/gporca/data/dxl/minidump/DqaNoRedistribute.mdp
  src/backend/gporca/data/dxl/minidump/LOJ_bb_mpph.mdp
  src/backend/gporca/data/dxl/minidump/MDQA-SameDQAColumn.mdp
  src/backend/gporca/data/dxl/minidump/MultiColumnDQA-InnerJoin-GroupBy-HashAggregate.mdp
  src/backend/gporca/data/dxl/minidump/ScalarDQAWithNonScalarAgg.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-DistinctOnComputedCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-DistinctOnDistrCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-DistinctOnSameNonDistrCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-GbMultipleCol-DistinctOnDistrCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-GbandDistinctOnDistrCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg.mdp
  src/backend/gporca/data/dxl/minidump/UnionOfDQAQueries.mdp
  src/backend/gporca/data/dxl/minidump/WinFunc-Redistribute-Sort-CTE-Producer.mdp
  src/backend/gporca/data/dxl/minidump/retail_28.mdp
  src/backend/gporca/libgpopt/src/operators/CPhysicalAgg.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformSplitDQA.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CAggTest.cpp
Labels: area: gporca, version: 6X_STABLE, backport

#13415 Speed up planning times by marking some partition constraints as dummy constraints (6X)
  src/backend/gporca/libgpopt/src/operators/CLogicalDynamicGetBase.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformJoin2IndexApply.cpp
Labels: area: gporca, version: 6X_STABLE

#13519 resolve GPDB_12_MERGE_FIXME in createplan.c
  src/backend/optimizer/plan/createplan.c
  src/test/regress/expected/select_distinct.out
  src/test/regress/expected/select_distinct_optimizer.out
  src/test/regress/sql/select_distinct.sql
Labels: type: fixme, merge_fixme

#13550 [6X] Reduce flakiness in test fts_segment_reset
  src/test/isolation2/expected/fts_segment_reset.out
  src/test/isolation2/sql/fts_segment_reset.sql
Labels: version: 6X_STABLE, backport, flaky test

#13515 resolve GPDB_12_MERGE_FIXME in planner to revert 1 phase limit path to 2 phase limit path
  src/backend/optimizer/plan/planner.c
  src/test/regress/expected/subselect.out
  src/test/regress/expected/subselect_optimizer.out
  src/test/regress/sql/subselect.sql
Labels: topic: planner, type: fixme, merge_fixme

#13545 metadata tracking for GPDB specific ALTER PARTITION commands
  src/backend/commands/tablecmds.c
  src/backend/commands/tablecmds_gp.c
  src/include/commands/tablecmds.h
  src/test/regress/expected/pg_stat_last_operation.out
  src/test/regress/sql/pg_stat_last_operation.sql
Labels: type: fixme

#13463 [6X] Add MASTER ONLY option for LOCK TABLE
  src/backend/commands/lockcmds.c
  src/backend/nodes/copyfuncs.c
  src/backend/nodes/equalfuncs.c
  src/backend/parser/gram.y
  src/include/nodes/parsenodes.h
  src/test/regress/expected/gp_lock.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/gp_lock.sql
Labels: version: 6X_STABLE, backport

#13416 Fix missing Redistribute on top of Split Update
  src/backend/gporca/data/dxl/minidump/UpdateDistKeyWithNestedJoin.mdp
  src/backend/gporca/libgpopt/src/operators/CPhysicalSplit.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CDMLTest.cpp
Labels: area: gporca, version: 7X_ALPHA, needs: backport
