Repository greenplum-db/gpdb, pull requests merged in 2022-01, with the labels that each got.

#12787 RHEL8: README.Linux.md update on 6X_STABLE
  README.linux.md
Labels: version: 6X_STABLE, gpcm_in

#12878 6X: Authenticate internal connections via domain sockets
  src/backend/libpq/auth.c
Labels: version: 6X_STABLE

#12793 ORCA: Fix CreateStatsPredDisj with an ArrayCmpALL disjunct
  src/backend/gporca/data/dxl/minidump/ArrayCmpAll-Disjunct.mdp
  src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: type: bug, area: gporca, version: 7X_ALPHA, needs: backport

#12944 Pageinspect for bitmap
  contrib/pageinspect/Makefile
  contrib/pageinspect/bmfuncs.c
  contrib/pageinspect/pageinspect--1.7--1.8.sql
  contrib/pageinspect/pageinspect.control
  src/test/isolation2/expected/bitmap_index_inspect.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/bitmap_index_inspect.sql
Labels: version: 7X_ALPHA

#12948 fix: root name may not necessary for root user
  gpMgmt/bin/gpinitsystem
Labels: community

#12974 [6X_STABLE] Fix CreateStatsPredDisj with an ArrayCmpALL disjunct
  src/backend/gporca/data/dxl/minidump/ArrayCmpAll-Disjunct-2.mdp
  src/backend/gporca/data/dxl/minidump/ArrayCmpAll-Disjunct.mdp
  src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, version: 6X_STABLE, backport

#12970 Fix SIGSEGV due to non-derived statistics
  src/backend/gporca/libgpopt/src/xforms/CXformRightOuterJoin2HashJoin.cpp
Labels: area: gporca

#12985 Fix SIGSEGV due to non-derived statistics (#12970)
  src/backend/gporca/libgpopt/src/xforms/CXformRightOuterJoin2HashJoin.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/backend/gporca/server/include/unittest/gpopt/CTestUtils.h
  src/backend/gporca/server/include/unittest/gpopt/xforms/CXformRightOuterJoin2HashJoinTest.h
  src/backend/gporca/server/src/startup/main.cpp
  src/backend/gporca/server/src/unittest/CTestUtils.cpp
  src/backend/gporca/server/src/unittest/gpopt/xforms/CXformRightOuterJoin2HashJoinTest.cpp
Labels: area: gporca, version: 6X_STABLE, backport

#12898 Fix flaky concurrent update on 6x
  src/backend/cdb/cdbtm.c
  src/test/isolation2/expected/concurrent_update.out
  src/test/isolation2/expected/gdd/concurrent_update.out
  src/test/isolation2/expected/gdd/concurrent_update_optimizer.out
  src/test/isolation2/sql/gdd/concurrent_update.sql
Labels: version: 6X_STABLE

#12924 Set correct resultcollid for RelabelType
  src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
  src/test/regress/expected/domain_optimizer.out
  src/test/regress/expected/qp_misc.out
  src/test/regress/sql/qp_misc.sql
Labels: area: gporca

#12647 Backport synchronization of amgetbitmap definition with upstream
  src/backend/access/bitmap/bitmap.c
  src/backend/access/gin/ginget.c
  src/backend/access/gist/gistget.c
  src/backend/access/hash/hash.c
  src/backend/access/index/indexam.c
  src/backend/access/nbtree/nbtree.c
  src/backend/access/spgist/spgscan.c
  src/backend/executor/nodeBitmapIndexscan.c
  src/include/access/genam.h
  src/test/regress/expected/gp_explain.out
  src/test/regress/expected/gp_explain_optimizer.out
  src/test/regress/sql/gp_explain.sql
Labels: community

#12806 Reconcile duplicate pg_hba update logic
  concourse/pipelines/templates/gpdb-tpl.yml
  gpMgmt/bin/gpexpand
  gpMgmt/bin/gpinitstandby
  gpMgmt/bin/gppylib/operations/detect_unreachable_hosts.py
  gpMgmt/bin/gppylib/operations/initstandby.py
  gpMgmt/bin/gppylib/operations/test/unit/test_unit_initstandby.py
  gpMgmt/bin/gppylib/operations/test/unit/test_unit_update_pg_hba_on_segments.py
  gpMgmt/bin/gppylib/operations/update_pg_hba_on_segments.py
  gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
  gpMgmt/test/behave/mgmt_utils/gpinitstandby.feature
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in

#12712 ORCA: Improve cardinality estimation for Dynamic Table Scan under SPE
  src/backend/gporca/data/dxl/minidump/BitmapIndexProbeMergeFilters.mdp
  src/backend/gporca/data/dxl/minidump/DynamicIndexScan-Heterogenous-PartSelectRange.mdp
  src/backend/gporca/data/dxl/minidump/JoinOrderDPE.mdp
  src/backend/gporca/data/dxl/minidump/NLJ-Broadcast-DPE-Outer-Child.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-JoinOverGbAgg-2.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-MultiWayJoinWithDPE.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-List-Cost1.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-List-Cost2.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-List-Cost3.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-List-Cost4.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-List-Cost5.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-Range-Cost1.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-Range-Cost2.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-Range-Cost3.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-Range-Cost4.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-Range-Cost5.mdp
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDynamicGet.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDynamicGetBase.h
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/libgpopt/src/operators/CLogical.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalDynamicGet.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalDynamicGetBase.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, topic: partitions, version: 7X_ALPHA

#12976 [6X_STABLE] Remove unnecessary projection of recheck/scalar filter columns from Bitmap Scan
  src/backend/gporca/data/dxl/minidump/BitmapIndexScan.mdp
  src/backend/gporca/data/dxl/minidump/BitmapTableScan-Basic.mdp
  src/backend/gporca/data/dxl/minidump/GinIndex.mdp
  src/backend/gporca/data/dxl/minidump/GinIndexPathOpfamily.mdp
  src/backend/gporca/data/dxl/minidump/GinIndexSearchModeAll.mdp
  src/backend/gporca/data/dxl/minidump/Gist-AOCOTable-NonLossy-BitmapIndexPlan.mdp
  src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorExprToDXL.h
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/output/qp_gist_indexes2_optimizer.source
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 6X_STABLE

#13009 6X: Add interconnect test for RHEL 8
  concourse/pipelines/gpdb_6X_STABLE-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: version: 6X_STABLE

#13020 [Backport 6X]Adding timeout to stop the segment in the testcase.
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in
