Repository greenplum-db/gpdb, pull requests merged in 2022-04, with the labels that each got.

#13174 Resolve GPDB_12_MERGE_FIXME in catalog/*.dat
  src/backend/utils/adt/genfile.c
  src/backend/utils/adt/pivot.c
  src/include/catalog/pg_aggregate.dat
  src/include/catalog/pg_cast.dat
  src/include/catalog/pg_operator.dat
  src/include/catalog/pg_proc.dat
  src/test/regress/expected/opr_sanity.out
Labels: type: fixme

#13340 Restore visibility of some GUCs to be viewable from pg_settings
  src/backend/utils/misc/guc.c
Labels: version: 7X_ALPHA

#13347 Update the comments for commit 9116c93
  src/backend/cdb/dispatcher/cdbgang_async.c
Labels: version: 7X_ALPHA

#13351 motion_socket.sql: additional test coverage
  src/test/regress/expected/motion_socket.out
  src/test/regress/sql/motion_socket.sql
Labels: version: 7X_ALPHA, needs: backport

#13352 motion_socket.sql: Correct regex match and ignore
  src/test/regress/expected/motion_socket.out
  src/test/regress/sql/motion_socket.sql
Labels: version: 7X_ALPHA, needs: backport

#13306 Fix FTS prematurely failing primary over due to long reset period
  src/backend/cdb/dispatcher/cdbgang.c
  src/backend/cdb/dispatcher/cdbgang_async.c
  src/backend/fts/ftsprobe.c
  src/backend/postmaster/bgwriter.c
  src/backend/postmaster/postmaster.c
  src/include/libpq/libpq-be.h
  src/include/postmaster/ftsprobe.h
  src/include/postmaster/postmaster.h
  src/test/isolation2/expected/fts_segment_reset.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/fts_segment_reset.sql
  src/test/isolation2/sql_isolation_testcase.py
  src/test/regress/output/dispatch.source
Labels: version: 7X_ALPHA

#13348 [6X] Fix FTS prematurely failing primary over due to long reset period
  src/backend/cdb/dispatcher/cdbgang.c
  src/backend/cdb/dispatcher/cdbgang_async.c
  src/backend/fts/ftsprobe.c
  src/backend/postmaster/bgwriter.c
  src/backend/postmaster/postmaster.c
  src/include/libpq/libpq-be.h
  src/include/postmaster/ftsprobe.h
  src/include/postmaster/postmaster.h
  src/test/isolation2/expected/fts_segment_reset.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/fts_segment_reset.sql
  src/test/isolation2/sql_isolation_testcase.py
  src/test/regress/output/dispatch.source
Labels: version: 6X_STABLE

#13294 [7X] Enable GatherMerge plan alternative for non-EstMaster singleton distribution (GPORCA).
  src/backend/gporca/data/dxl/minidump/UpdateWindowGatherMerge.mdp
  src/backend/gporca/libgpopt/src/base/CDistributionSpecSingleton.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CDMLTest.cpp
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 7X_ALPHA, community

#13280 [6X] Enable execution of recovery_end_command GUC
  src/backend/access/transam/xlog.c
  src/test/gpdb_pitr/test_gpdb_pitr.sh
  src/test/gpdb_pitr/test_gpdb_pitr_cleanup.sh
Labels: version: 6X_STABLE

#13358 Allow ORCA to reuse cached PL/pgSQL fallback plans
  src/backend/executor/spi.c
Labels: area: gporca, version: 5X_STABLE

#13346 Remove duplicate code of file allocation in pgstat_read_statsfile().
  src/backend/postmaster/pgstat.c
Labels: version: 5X_STABLE

#13225 [6X] Replace usages of InterruptPending to the flag of query cancellation
  src/backend/cdb/cdbcopy.c
  src/backend/cdb/dispatcher/cdbdisp_async.c
  src/backend/cdb/dispatcher/cdbdisp_query.c
  src/backend/cdb/motion/ic_tcp.c
  src/backend/tcop/postgres.c
  src/include/miscadmin.h
Labels: community

#13276 Resolve GPDB_12_MERGE_FIXME in nodeHash.c and nodeHashjoin.c
  src/backend/executor/nodeHash.c
  src/backend/executor/nodeHashjoin.c
  src/include/executor/hashjoin.h
  src/test/regress/expected/dpe.out
  src/test/regress/expected/dpe_optimizer.out
  src/test/regress/expected/partition_prune.out
  src/test/regress/expected/partition_prune_optimizer.out
  src/test/regress/sql/dpe.sql
  src/test/regress/sql/partition_prune.sql
Labels: type: fixme

#13370 fix inaccurate int type total_memory_coordinator of PlannedStmt
  src/backend/executor/execMain.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfuncs.c
  src/include/nodes/plannodes.h
Labels: version: 7X_ALPHA

#13363 remove DynamicTableScanInfo struct and correlative codes
  src/backend/executor/execMain.c
  src/include/nodes/execnodes.h
Labels: merge_fixme

#13372 Cherrypick TAP test for "Detect client disconnection while running query and interrupt execution"
  src/test/recovery/t/201_close_connection.pl
Labels: version: 7X_ALPHA, needs: backport

#13373 [6X] Cherrypick TAP test for "Detect client disconnection while running query and interrupt execution"
  src/test/isolation2/expected/pg_terminate_backend.out
  src/test/isolation2/sql/pg_terminate_backend.sql
  src/test/modules/Makefile
  src/test/modules/connection/Makefile
  src/test/modules/connection/t/001_close_connection.pl
Labels: version: 6X_STABLE, backport

#13287 Prevent gp_tablespace_segment_location() from executing on entrydb QE
  src/backend/executor/execQual.c
  src/backend/utils/adt/dbsize.c
  src/test/regress/expected/db_size_functions.out
  src/test/regress/sql/db_size_functions.sql
Labels: version: 6X_STABLE

#13332 remove redundant codes of invoking paramFetch before preprocess_initplans
  src/backend/executor/execMain.c
Labels: merge_fixme

#13316 Remove gpdb_12_merge_fixme in buffile.c.
  src/backend/storage/file/buffile.c
  src/test/regress/expected/workfile_limits.out
  src/test/regress/sql/workfile_limits.sql
Labels: type: fixme

#13377 Fix subquery all subquery context
  src/backend/gporca/data/dxl/minidump/AllSubqueryWithSubqueryInScalar.mdp
  src/backend/gporca/libgpopt/src/xforms/CSubqueryHandler.cpp
  src/test/regress/expected/qp_correlated_query.out
  src/test/regress/expected/qp_correlated_query_optimizer.out
  src/test/regress/sql/qp_correlated_query.sql
Labels: area: gporca

#13389 Add GPDB PITR tests to GPDB CI [GPDB6]
  concourse/pipelines/gpdb_6X_STABLE-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
  concourse/scripts/gpdb_pitr.bash
  concourse/tasks/gpdb_pitr.yml
  src/test/gpdb_pitr/Makefile
  src/test/gpdb_pitr/init_file
  src/test/gpdb_pitr/test_gpdb_pitr.sh
Labels: version: 6X_STABLE

#13390 Revert "conf on mirror seg doesn't get updated with mirror port numbe…
  gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
  gpMgmt/bin/lib/gp_bash_functions.sh
  gpMgmt/bin/lib/gpconfigurenewsegment
  gpMgmt/bin/lib/gpcreateseg.sh
  gpMgmt/sbin/gpsegrecovery.py
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
  gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
Labels: gpcm_in

#13355 Disregard dtx when pruning IC history
  src/backend/cdb/motion/ic_udpifc.c
Labels: needs: backport, area: inter-connect

#13380 Remove gpdb_12_merge_fixme in functioncmds.c
  src/backend/commands/functioncmds.c
Labels: type: fixme

#13399 [6X] Add SSL connection regression test cases
  src/test/Makefile
  src/test/regress/pg_regress.c
  src/test/ssl/.gitignore
  src/test/ssl/Makefile
  src/test/ssl/clear_ssl.sh
  src/test/ssl/configure_ssl.sh
  src/test/ssl/gen_gpdb_certs.sh
  src/test/ssl/init_file_ssl_connection
  src/test/ssl/input/basic_connection.source
  src/test/ssl/input/set.source
  src/test/ssl/input/unset.source
  src/test/ssl/input/utility_connection.source
  src/test/ssl/output/basic_connection.source
  src/test/ssl/output/set.source
  src/test/ssl/output/unset.source
  src/test/ssl/output/utility_connection.source
  src/test/ssl/ssl_connection_schedule
Labels: version: 6X_STABLE

#13392 fix incorrect RTE's rellockmode in the process of translating DXL to PlannedStmt
  src/backend/executor/execMain.c
  src/backend/executor/execUtils.c
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/test/isolation2/output/uao/parallel_delete_optimizer.source
  src/test/isolation2/output/uao/parallel_update_optimizer.source
  src/test/regress/expected/ao_locks_optimizer.out
Labels: type: fixme

#13364 Resolve GPDB_12_MERGE_FIXME: Implement relation_vacuum AM for AO/CO tables.
  src/backend/access/aocs/aocsam_handler.c
  src/backend/access/appendonly/appendonly_compaction.c
  src/backend/access/appendonly/appendonlyam_handler.c
  src/backend/commands/tablecmds.c
  src/backend/commands/vacuum.c
  src/backend/commands/vacuum_ao.c
  src/include/access/appendonly_compaction.h
  src/include/commands/vacuum.h
Labels: type: fixme

#13151 Resolve a FIXME about not opening table in CondUpgradeRelLock() when possible
  src/backend/access/table/table.c
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/storage/lmgr/lmgr.c
  src/include/storage/lmgr.h
Labels: type: fixme, version: 7X_ALPHA

#13170 Resolve GPDB_12_MERGE_FIXMEs in nodeShareInputScan.c
  src/backend/executor/nodeShareInputScan.c
  src/backend/postmaster/pgstat.c
  src/include/pgstat.h
  src/test/isolation2/expected/gpdispatch.out
  src/test/isolation2/expected/gpdispatch_1.out
  src/test/isolation2/sql/gpdispatch.sql
Labels: type: fixme

#13376 Remove overload raise function with severity_level
  src/backend/gpopt/translate/CTranslatorUtils.cpp
  src/backend/gpopt/utils/COptTasks.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXLUtils.cpp
  src/backend/gporca/libgpos/include/gpos/error/CException.h
  src/backend/gporca/libgpos/src/error/CException.cpp
  src/include/gpopt/utils/COptTasks.h
Labels: area: gporca

#13434 remove useless lockmode upgrade in inherit.c
  src/backend/optimizer/util/inherit.c
Labels: type: fixme

#13417 Use winner QE's nfiltered1 and nfiltered2 in the output of EXPLAIN ANALYZE
  src/backend/commands/explain_gp.c
Labels: type: fixme
