Repository greenplum-db/gpdb, pull requests merged in 2022-09, with the labels that each got.

#14038 Cleanup a FIXME in ATExecAddIndex
  src/backend/commands/tablecmds.c
Labels: version: 7X_ALPHA, merge_fixme

#13471 Enable direct dispatch for DML statements with ORCA
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gporca/data/dxl/minidump/DeleteWithTriggers.mdp
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
  src/test/isolation2/output/uao/parallel_delete_optimizer.source
  src/test/regress/expected/ao_locks_optimizer.out
  src/test/regress/expected/direct_dispatch_optimizer.out
Labels: area: gporca, version: 7X_ALPHA, Priority 1

#13995 Support setting reloptions for partition tables
  src/backend/access/common/reloptions.c
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_table_set.out
  src/test/regress/expected/alter_table_set_am.out
  src/test/regress/expected/partition_locking.out
  src/test/regress/expected/partition_locking_optimizer.out
  src/test/regress/sql/alter_table_set.sql
Labels: version: 7X_ALPHA

#14039 Update gp_create_restore_point() catalog function
  src/backend/access/transam/xlogfuncs_gp.c
  src/include/catalog/catversion.h
  src/include/catalog/pg_proc.dat
  src/test/gpdb_pitr/expected/gpdb_pitr_setup.out
  src/test/gpdb_pitr/expected/test_gp_create_restore_point.out
  src/test/gpdb_pitr/expected/test_gp_switch_wal.out
  src/test/gpdb_pitr/init_file_gpdb_pitr
  src/test/gpdb_pitr/sql/gpdb_pitr_setup.sql
  src/test/gpdb_pitr/sql/test_gp_create_restore_point.sql
  src/test/gpdb_pitr/sql/test_gp_switch_wal.sql
  src/test/gpdb_pitr/test_gpdb_pitr.sh
Labels: needs: backport, area: wal

#14025 [6X backport] Update gp_switch_wal() to include pg_walfile_name() output
  gpcontrib/gp_pitr/gp_pitr--1.0--1.1.sql
  gpcontrib/gp_pitr/gp_pitr--1.1.sql
  gpcontrib/gp_pitr/gp_pitr.c
  src/backend/access/transam/xlogfuncs_gp.c
  src/include/access/xlog_fn.h
  src/test/gpdb_pitr/.gitignore
  src/test/gpdb_pitr/Makefile
  src/test/gpdb_pitr/expected/gpdb_pitr_setup.out
  src/test/gpdb_pitr/expected/test_gp_switch_wal.out
  src/test/gpdb_pitr/sql/gpdb_pitr_setup.sql
  src/test/gpdb_pitr/sql/test_gp_switch_wal.sql
  src/test/gpdb_pitr/test_gpdb_pitr.sh
Labels: version: 6X_STABLE

#14029 Allow definition of lock mode for custom reloptions
  contrib/bloom/blutils.c
  src/backend/access/common/reloptions.c
  src/backend/access/common/reloptions_gp.c
  src/include/access/reloptions.h
Labels: community

#14054 change verify checksum FIXME to FEATURE NOT SUPPORTED
  gpMgmt/bin/gppylib/commands/pg.py
Labels: type: fixme

#14017 Resolve GPDB_12_MERGE_FIXME in describe.c about legacy partitioning.
  src/bin/psql/describe.c
Labels: type: fixme, merge_fixme

#14042 [6X] support ldapsearchfilter option for LDAP authentication
  src/backend/libpq/auth.c
  src/backend/libpq/hba.c
  src/include/libpq/hba.h
Labels: version: 6X_STABLE, backport

#13534 Fix gpinitsystem fails with custom locale
  gpMgmt/bin/gpinitsystem
  gpMgmt/bin/lib/gp_bash_functions.sh
  gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
Labels: community, Priority 1

#14058 [6X backport] Update gp_create_restore_point() gp_pitr extension function
  gpcontrib/gp_pitr/gp_pitr--1.0--1.1.sql
  gpcontrib/gp_pitr/gp_pitr--1.1.sql
  src/backend/access/transam/xlogfuncs_gp.c
  src/test/gpdb_pitr/expected/gpdb_pitr_setup.out
  src/test/gpdb_pitr/expected/test_gp_create_restore_point.out
  src/test/gpdb_pitr/expected/test_gp_switch_wal.out
  src/test/gpdb_pitr/init_file_gpdb_pitr
  src/test/gpdb_pitr/sql/gpdb_pitr_setup.sql
  src/test/gpdb_pitr/sql/test_gp_create_restore_point.sql
  src/test/gpdb_pitr/sql/test_gp_switch_wal.sql
  src/test/gpdb_pitr/test_gpdb_pitr.sh
Labels: version: 6X_STABLE

#14059 Update gp_stat_archiver view definition in gp_pitr extension
  gpcontrib/gp_pitr/gp_pitr--1.0--1.1.sql
  gpcontrib/gp_pitr/gp_pitr--1.1.sql
Labels: version: 6X_STABLE

#13846 auto_explain: fix failure when executor hooks are run in QEs
  contrib/auto_explain/Makefile
  contrib/auto_explain/auto_explain.c
  contrib/auto_explain/expected/bfv_preload_auto_explain.out
  contrib/auto_explain/expected/bfv_preload_auto_explain_optimizer.out
  contrib/auto_explain/init_file
  contrib/auto_explain/sql/bfv_preload_auto_explain.sql
Labels: community

#13715 Fix wrong results with a WITH RECURSIVE query
  src/backend/executor/nodeRecursiveunion.c
  src/backend/executor/nodeWorktablescan.c
  src/backend/optimizer/path/allpaths.c
  src/backend/optimizer/plan/subselect.c
  src/include/nodes/execnodes.h
  src/include/optimizer/subselect.h
  src/test/regress/expected/subselect.out
  src/test/regress/expected/subselect_optimizer.out
  src/test/regress/sql/subselect.sql
Labels: type: fixme

#14021 Resolve a FIXME in MergeAttributes()
  src/backend/commands/createas.c
  src/backend/commands/exttablecmds.c
  src/backend/commands/sequence.c
  src/backend/commands/tablecmds.c
  src/backend/commands/typecmds.c
  src/backend/commands/view.c
  src/backend/nodes/copyfuncs.c
  src/backend/nodes/equalfuncs.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfast.c
  src/backend/parser/gram.y
  src/backend/parser/parse_partition_gp.c
  src/include/nodes/parsenodes.h
Labels: version: 7X_ALPHA, merge_fixme

#13873 Allow certain functions to be safely executed on replicated slices in Orca
  src/backend/gporca/data/dxl/minidump/ReplicatedTableGroupBy.mdp
  src/backend/gporca/data/dxl/minidump/ReplicatedTableInClause.mdp
  src/backend/gporca/data/dxl/minidump/ReplicatedTableWithAggNoMotion.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CDrvdPropScalar.h
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpression.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionHandle.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CScalarProjectList.h
  src/backend/gporca/libgpopt/src/base/CDrvdPropScalar.cpp
  src/backend/gporca/libgpopt/src/operators/CExpression.cpp
  src/backend/gporca/libgpopt/src/operators/CExpressionHandle.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalAgg.cpp
  src/backend/gporca/libgpopt/src/operators/CScalarProjectList.cpp
  src/backend/gporca/libnaucrates/include/naucrates/md/CMDTypeOidGPDB.h
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/rpt_optimizer.out
Labels: area: gporca, version: 7X_ALPHA

#14061 [ORCA] Fix duplicate cast predicates
  src/backend/gporca/data/dxl/minidump/Date-TimeStamp-HashJoin.mdp
  src/backend/gporca/data/dxl/minidump/NotWellDefinedDisjunctConjunctPredicates.mdp
  src/backend/gporca/data/dxl/minidump/TimeStamp-Date-HashJoin.mdp
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CCastTest.cpp
Labels: area: gporca, version: 7X_ALPHA, merge_fixme

#14071 Change default permissions on gp_create_restore_point and gp_switch_wal
  src/backend/catalog/system_views.sql
  src/include/catalog/catversion.h
  src/test/gpdb_pitr/expected/test_gp_create_restore_point.out
  src/test/gpdb_pitr/expected/test_gp_switch_wal.out
  src/test/gpdb_pitr/sql/test_gp_create_restore_point.sql
  src/test/gpdb_pitr/sql/test_gp_switch_wal.sql
Labels: warning: catalog change

#14091 pg_upgrade: Fix core dump in report_progress()
  src/bin/pg_upgrade/greenplum/reporting.c
  src/bin/pg_upgrade/test_gpdb.sh
Labels: version: 7X_ALPHA, pg_upgrade, merge_fixme

#13834 Fix gpcheckcat false alarms for pg_default_acl
  gpMgmt/bin/gppylib/gpcatalog.py
  gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
Labels: topic: cluster mgmt, version: 7X_ALPHA, needs: backport

#14056 Support multistage hash aggregation for grouping set with unsortable refs
  src/backend/cdb/cdbgroupingpaths.c
  src/backend/optimizer/plan/planner.c
  src/test/regress/expected/groupingsets.out
  src/test/regress/expected/groupingsets_optimizer.out
  src/test/regress/sql/groupingsets.sql
Labels: type: fixme

#14068 Put some locale related GUCs to sync guc array
  src/include/utils/sync_guc_name.h
  src/include/utils/unsync_guc_name.h
  src/test/regress/expected/gp_sync_lc_gucs.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/gp_sync_lc_gucs.sql
Labels: community

#14106 Fixme: gp_partition_template for segments
  gpMgmt/bin/gppylib/gpcatalog.py
Labels: type: fixme, gpcm_in

#14116 Fixme: removed fixme tag as the changes have no impact
  gpMgmt/bin/gpcheckcat
Labels: type: fixme, gpcm_in

#14095 6X: Allow certain functions to be safely executed on replicated slices in Orca
  src/backend/gporca/data/dxl/minidump/ReplicatedTableGroupBy.mdp
  src/backend/gporca/data/dxl/minidump/ReplicatedTableInClause.mdp
  src/backend/gporca/data/dxl/minidump/ReplicatedTableWithAggNoMotion.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CDrvdPropScalar.h
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpression.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionHandle.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CScalarProjectList.h
  src/backend/gporca/libgpopt/src/base/CDrvdPropScalar.cpp
  src/backend/gporca/libgpopt/src/operators/CExpression.cpp
  src/backend/gporca/libgpopt/src/operators/CExpressionHandle.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalAgg.cpp
  src/backend/gporca/libgpopt/src/operators/CScalarProjectList.cpp
  src/backend/gporca/libnaucrates/include/naucrates/md/CMDTypeOidGPDB.h
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/rpt_optimizer.out
Labels: area: gporca, version: 6X_STABLE

#14104 Address FIXMEs in gpdbwrappers.cpp file
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/include/gpopt/gpdbwrappers.h
  src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
Labels: area: gporca, type: fixme, version: 7X_ALPHA

#14119 Correctly report instrumentation of zero-ouput node
  src/backend/commands/explain_gp.c
  src/test/regress/expected/dpe.out
  src/test/regress/expected/dpe_optimizer.out
  src/test/regress/expected/explain_analyze.out
  src/test/regress/expected/explain_analyze_optimizer.out
  src/test/regress/expected/explain_format.out
  src/test/regress/expected/explain_format_optimizer.out
  src/test/regress/expected/partition_prune.out
  src/test/regress/expected/partition_prune_optimizer.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/explain_analyze.sql
Labels: type: bug, version: 7X_ALPHA, EXPLAIN ANALYZE

#14089 aoblkdir: remove hole filling mechanism
  src/backend/access/aocs/aocsam.c
  src/backend/access/appendonly/appendonlyam.c
  src/backend/access/appendonly/appendonlyblockdirectory.c
  src/include/catalog/pg_appendonly.h
  src/include/cdb/cdbappendonlyblockdirectory.h
  src/test/isolation2/expected/ao_blkdir.out
  src/test/isolation2/expected/uao_crash_compaction_row.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/output/uao/compaction_utility_insert.source
  src/test/isolation2/output/uao/max_concurrency.source
  src/test/isolation2/output/uao/max_concurrency2.source
  src/test/isolation2/output/uao/select_after_vacuum.source
  src/test/isolation2/output/uao/vacuum_cleanup.source
  src/test/isolation2/output/uao/vacuum_self_serializable.source
  src/test/isolation2/sql/ao_blkdir.sql
  src/test/regress/expected/alter_table_set_am.out
  src/test/regress/expected/gp_toolkit_ao_funcs.out
  src/test/regress/output/gp_tablespace.source
Labels: version: 7X_ALPHA, area: aoco

#14105 FIXME remove gp_enable_sort_distinct and noduplicates optimizing
  src/backend/commands/explain.c
  src/backend/executor/nodeSort.c
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/nodes/copyfuncs.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfuncs.c
  src/backend/optimizer/path/allpaths.c
  src/backend/optimizer/plan/createplan.c
  src/backend/utils/misc/guc_gp.c
  src/backend/utils/misc/postgresql.conf.sample
  src/include/cdb/cdbvars.h
  src/include/nodes/execnodes.h
  src/include/nodes/plannodes.h
  src/include/utils/unsync_guc_name.h
  src/test/regress/expected/join_gp.out
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/tpch500GB.out
Labels: merge_fixme

#14112 [6X_Backport] Fix gpcheckcat false alarms for pg_default_acl
  gpMgmt/bin/gppylib/gpcatalog.py
  gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
Labels: version: 6X_STABLE, backport, gpcm_in

#13739 [6X] Fix cross-slice interaction detection for subplans
  src/backend/cdb/cdbmutate.c
  src/backend/executor/execMain.c
  src/backend/executor/nodeMaterial.c
  src/backend/optimizer/plan/orca.c
  src/backend/optimizer/plan/planner.c
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/shared_scan.out
  src/test/regress/expected/shared_scan_optimizer.out
  src/test/regress/sql/shared_scan.sql
Labels: community

#14000 (6x backport) Eliminate alien nodes before execution for entry db
  src/backend/cdb/dispatcher/cdbdisp_query.c
  src/backend/executor/execMain.c
  src/backend/executor/execProcnode.c
  src/test/regress/expected/memconsumption.out
  src/test/regress/sql/memconsumption.sql
Labels: version: 6X_STABLE, backport, community

#14138 ao: Remove dead AppendOnlyUpdateDescData struct
  src/backend/access/appendonly/appendonlyam.c
Labels: version: 7X_ALPHA, area: aoco

#14142 Introduce timeout to tcp ic teardown select loop
  src/backend/cdb/motion/ic_tcp.c
  src/test/isolation2/expected/tcp_ic_teardown.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/tcp_ic_teardown.sql
Labels: version: 7X_ALPHA, needs: backport, area: inter-connect

#12800 Break early when creating Memtuple binding from TupleDesc
  src/backend/access/common/memtuple.c
Labels: area: server, version: 7X_ALPHA, community

#14066 Resolve one GPDB_12_MERGE_FIXME in describe.c
  src/bin/psql/describe.c
  src/test/regress/expected/psql_gp_commands.out
  src/test/regress/sql/psql_gp_commands.sql
Labels: type: fixme

#14167 tcp-ic: Add more detail to register msg error
  src/backend/cdb/motion/ic_tcp.c
Labels: version: 7X_ALPHA, needs: backport, area: inter-connect

#13305 Improve gp_hyperloglog codes and add tests for it.
  src/backend/utils/hyperloglog/gp_hyperloglog.c
  src/include/utils/hyperloglog/gp_hyperloglog.h
  src/test/regress/expected/gp_hyperloglog.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/gp_hyperloglog.sql
Labels: wip: draft for feedback

#14094 Change cryptography package version
  gpMgmt/requirements-dev.txt
Labels: gpcm_in

#14159 [ORCA] Allow empty target list
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/backend/gpopt/translate/CTranslatorUtils.cpp
  src/backend/gporca/libgpopt/src/base/CKeyCollection.cpp
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformDifference2LeftAntiSemiJoin.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
  src/test/regress/expected/union.out
  src/test/regress/expected/union_optimizer.out
  src/test/regress/sql/union.sql
Labels: area: gporca, version: 7X_ALPHA, merge_fixme

#14045 Derive combined hashed spec for outer join
  src/backend/gporca/data/dxl/minidump/CTEWithMergedGroup.mdp
  src/backend/gporca/data/dxl/minidump/ExpandFullOuterJoin.mdp
  src/backend/gporca/data/dxl/minidump/ExpandNAryJoinGreedyWithLOJOnly.mdp
  src/backend/gporca/data/dxl/minidump/InSubqueryWithNotNullCol.mdp
  src/backend/gporca/data/dxl/minidump/InferPredicatesInnerOfLOJ.mdp
  src/backend/gporca/data/dxl/minidump/InnerJoinBroadcastTableHashSpec.mdp
  src/backend/gporca/data/dxl/minidump/InnerJoinReplicatedTableHashSpec.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-MultiDistKey-MultiIndexKey-NoExtraFilter.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-MultiDistKey-MultiIndexKey.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-MultiDistKeys-Bitmap-WithComplexPreds.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-MultiDistKeys-WithComplexPreds.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-WithComplexPredicates.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-With-Agg.mdp
  src/backend/gporca/data/dxl/minidump/LOJNonNullRejectingPredicates.mdp
  src/backend/gporca/data/dxl/minidump/LOJReorderComplexNestedLOJs.mdp
  src/backend/gporca/data/dxl/minidump/LOJ_bb_mpph.mdp
  src/backend/gporca/data/dxl/minidump/LeftJoinNullsNotColocated.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-AggWithExistentialSubquery.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-DPE-GroupBy.mdp
  src/backend/gporca/data/dxl/minidump/RightJoinNoDPSNonDistKey.mdp
  src/backend/gporca/data/dxl/minidump/RightJoinRedistribute.mdp
  src/backend/gporca/data/dxl/minidump/UnnestSQJoins.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecHashed.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalFullMergeJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalInnerHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftAntiSemiHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftAntiSemiHashJoinNotIn.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftOuterHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftSemiHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalRightOuterHashJoin.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXformUtils.h
  src/backend/gporca/libgpopt/src/base/CDistributionSpecHashed.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalFullMergeJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalInnerHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftAntiSemiHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftAntiSemiHashJoinNotIn.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftOuterHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftSemiHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalRightOuterHashJoin.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/backend/gporca/server/src/unittest/gpopt/base/CDistributionSpecTest.cpp
  src/test/regress/expected/bfv_joins.out
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/expected/bfv_statistic_optimizer.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/join_optimizer.out
  src/test/regress/expected/notin_optimizer.out
  src/test/regress/sql/bfv_joins.sql
Labels: area: gporca, version: 7X_ALPHA

#14158 [6X] Introduce timeout to tcp ic teardown select loop
  src/backend/cdb/motion/ic_tcp.c
  src/test/isolation2/expected/tcp_ic_teardown.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/tcp_ic_teardown.sql
Labels: version: 6X_STABLE, backport, area: inter-connect

#14100 Explain plan shows the number of leaf partitions for dynamic scans
  src/backend/commands/explain.c
  src/test/regress/expected/dpe_optimizer.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/inherit_optimizer.out
  src/test/regress/expected/orca_static_pruning_optimizer.out
  src/test/regress/expected/partition_prune_optimizer.out
Labels: area: gporca, version: 7X_ALPHA, merge_fixme

#14020 ADBDEV-2982: SIGPIPE during ending not exhausted external table scan
  src/backend/executor/execUtils.c
  src/test/regress/input/external_table.source
  src/test/regress/output/external_table.source
Labels: community

#14153 Unify ic-proxy log level under GUC gp_log_interconnect's control, and remove macro IC_PROXY_LOG_LEVEL
  src/backend/cdb/motion/ic_proxy.h
  src/backend/cdb/motion/ic_proxy_addr.c
  src/backend/cdb/motion/ic_proxy_client.c
  src/backend/cdb/motion/ic_proxy_main.c
  src/backend/cdb/motion/ic_proxy_pkt_cache.c
Labels: version: 7X_ALPHA, needs: backport, area: inter-connect

#14208 Disable flaky qp_union_intersect test
  src/test/regress/expected/qp_union_intersect.out
  src/test/regress/expected/qp_union_intersect_optimizer.out
  src/test/regress/sql/qp_union_intersect.sql
Labels: version: 7X_ALPHA

#14202 Fix memory leak in Dynamic Bitmap Scans
  src/backend/executor/nodeBitmapIndexscan.c
Labels: area: gporca, version: 7X_ALPHA

#14139 Make 6X_STABLE work with Apple M1
  gpMgmt/bin/generate-greenplum-path.sh
  gpMgmt/bin/pythonSrc/PyGreSQL-4.0/setup.py
  src/backend/gporca/libgpos/include/gpos/utils.h
Labels: version: 6X_STABLE
