Repository greenplum-db/gpdb, pull requests merged in 2022-06, with the labels that each got.

#13586 Fix missing Redistribute on top of Split Update with Orca
  src/backend/gporca/data/dxl/minidump/UpdateDistKeyWithNestedJoin.mdp
  src/backend/gporca/libgpopt/src/operators/CPhysicalSplit.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CDMLTest.cpp
Labels: area: gporca, version: 6X_STABLE

#13535 Support Const TVF returning composite type in ORCA
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/backend/gpopt/translate/CTranslatorUtils.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalTVF.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalTVF.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
  src/backend/gporca/libnaucrates/src/operators/CDXLLogicalTVF.cpp
  src/backend/gporca/libnaucrates/src/operators/CDXLPhysicalTVF.cpp
  src/include/gpopt/translate/CTranslatorUtils.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/qp_orca_fallback.out
  src/test/regress/expected/qp_orca_fallback_optimizer.out
  src/test/regress/sql/gporca.sql
  src/test/regress/sql/qp_orca_fallback.sql
Labels: area: gporca, version: 6X_STABLE, backport

#13585 Fix another flaky aggregates test
  src/test/regress/expected/aggregates.out
  src/test/regress/expected/aggregates_optimizer.out
  src/test/regress/sql/aggregates.sql
Labels: area: gporca, version: 7X_ALPHA

#13512 Updated CPhysicalJoin to derive the inner distribution in the case of tainted replicated (6X)
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpec.h
  src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
  src/test/regress/expected/rpt.out
  src/test/regress/expected/rpt_optimizer.out
  src/test/regress/sql/rpt.sql
Labels: area: gporca, version: 6X_STABLE

#13570 Fix txns_using_rel leak in AppendOnlyHash entry
  src/backend/access/appendonly/appendonlywriter.c
  src/test/isolation2/input/uao/max_concurrency2.source
  src/test/isolation2/output/uao/max_concurrency2.source
Labels: version: 6X_STABLE

#13587 Support both unicast and wildcard address binding
  src/backend/cdb/cdbutil.c
  src/backend/cdb/cdbvars.c
  src/backend/cdb/motion/ic_tcp.c
  src/backend/cdb/motion/ic_udpifc.c
  src/backend/utils/misc/guc_gp.c
  src/include/cdb/cdbvars.h
  src/include/utils/sync_guc_name.h
Labels: version: 7X_ALPHA, needs: backport

#13383 Materialize aggregations in NL Join inner child
  src/backend/gporca/data/dxl/minidump/AnyPredicate-Over-UnionOfConsts.mdp
  src/backend/gporca/data/dxl/minidump/AnySubq-With-NonScalarSubqueryChild-1.mdp
  src/backend/gporca/data/dxl/minidump/AnySubq-With-NonScalarSubqueryChild-2.mdp
  src/backend/gporca/data/dxl/minidump/CTEWithMergedGroup.mdp
  src/backend/gporca/data/dxl/minidump/CannotPullGrpColAboveAgg.mdp
  src/backend/gporca/data/dxl/minidump/CorrelatedIN-LeftSemiJoin-Limit.mdp
  src/backend/gporca/data/dxl/minidump/CorrelatedIN-LeftSemiJoin-True.mdp
  src/backend/gporca/data/dxl/minidump/CorrelatedLeftSemiNLJoinWithLimit.mdp
  src/backend/gporca/data/dxl/minidump/Correlation-With-Casting-1.mdp
  src/backend/gporca/data/dxl/minidump/InSubqWithPrjListOuterRefNoInnerRefColumnIn.mdp
  src/backend/gporca/data/dxl/minidump/InSubqWithPrjListOuterRefNoInnerRefColumnPlusConstIn.mdp
  src/backend/gporca/data/dxl/minidump/InSubqWithPrjListOuterRefNoInnerRefConstIn.mdp
  src/backend/gporca/data/dxl/minidump/Join-With-Subq-Preds-1.mdp
  src/backend/gporca/data/dxl/minidump/Join-With-Subq-Preds-2.mdp
  src/backend/gporca/data/dxl/minidump/Join_OuterChild_DistUniversal.mdp
  src/backend/gporca/data/dxl/minidump/LOJNullRejectingZeroPlacePredicates.mdp
  src/backend/gporca/data/dxl/minidump/LeftOuter2InnerUnionAllAntiSemiJoin-Tpcds.mdp
  src/backend/gporca/data/dxl/minidump/LeftOuter2InnerUnionAllAntiSemiJoin.mdp
  src/backend/gporca/data/dxl/minidump/MultiLevel-CorrelatedExec.mdp
  src/backend/gporca/data/dxl/minidump/NLJ-Rewindability-CTAS.mdp
  src/backend/gporca/data/dxl/minidump/NLJ-Rewindability.mdp
  src/backend/gporca/data/dxl/minidump/NestedInSubqWithPrjListOuterRefNoInnerRef.mdp
  src/backend/gporca/data/dxl/minidump/OneLevel-CorrelatedExec.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-SubqueryOuterRef.mdp
  src/backend/gporca/data/dxl/minidump/Project-With-NonScalar-Func.mdp
  src/backend/gporca/data/dxl/minidump/PushSelectWithOuterRefBelowUnion.mdp
  src/backend/gporca/data/dxl/minidump/ScalarSubqueryCountStarInJoin.mdp
  src/backend/gporca/data/dxl/minidump/SimplifyExistsSubquery2Limit.mdp
  src/backend/gporca/data/dxl/minidump/Subq-With-OuterRefCol.mdp
  src/backend/gporca/data/dxl/minidump/SubqueryInsideScalarIf.mdp
  src/backend/gporca/data/dxl/minidump/SubqueryNoPullUpTableValueFunction.mdp
  src/backend/gporca/data/dxl/minidump/TVF-With-Deep-Subq-Args.mdp
  src/backend/gporca/data/dxl/minidump/UnnestSQJoins.mdp
  src/backend/gporca/data/dxl/minidump/WinFunc-Redistribute-Sort-CTE-Producer.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CRewindabilitySpec.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXformUtils.h
  src/backend/gporca/libgpopt/src/base/CRewindabilitySpec.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalAgg.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalNLJoin.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/select_parallel_optimizer.out
Labels: area: gporca, version: 7X_ALPHA, needs: backport

#13603 6X: Support both unicast and wildcard address binding
  src/backend/cdb/cdbutil.c
  src/backend/cdb/cdbvars.c
  src/backend/cdb/motion/ic_tcp.c
  src/backend/cdb/motion/ic_udpifc.c
  src/backend/utils/misc/guc_gp.c
  src/include/cdb/cdbvars.h
  src/include/utils/sync_guc_name.h
  src/test/isolation2/expected/motion_socket.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/motion_socket.sql
  src/test/regress/greenplum_schedule
  src/test/regress/sql/motion_socket.sql
Labels: version: 6X_STABLE, backport

#13341 Add support in ORCA to generate efficient plans for ordered-set aggs
  src/backend/gporca/data/dxl/minidump/CTAS_OrderedAgg_multiple_cols.mdp
  src/backend/gporca/data/dxl/minidump/OrderedAgg_array_fraction.mdp
  src/backend/gporca/data/dxl/minidump/OrderedAgg_computed_col.mdp
  src/backend/gporca/data/dxl/minidump/OrderedAgg_multiple_diffcol.mdp
  src/backend/gporca/data/dxl/minidump/OrderedAgg_multiple_samecol.mdp
  src/backend/gporca/data/dxl/minidump/OrderedAgg_multiple_samecol_difforderespec.mdp
  src/backend/gporca/data/dxl/minidump/OrderedAgg_single.mdp
  src/backend/gporca/data/dxl/minidump/OrderedAgg_with_groupby.mdp
  src/backend/gporca/data/dxl/minidump/OrderedAgg_with_nonOrderedAgg.mdp
  src/backend/gporca/data/dxl/minidump/OrderedAgg_with_nonconst_fraction.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CDrvdPropScalar.h
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpression.h
  src/backend/gporca/libgpopt/include/gpopt/operators/COrderedAggPreprocessor.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CScalarProjectList.h
  src/backend/gporca/libgpopt/src/base/CDrvdPropScalar.cpp
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libgpopt/src/operators/CExpression.cpp
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/libgpopt/src/operators/COrderedAggPreprocessor.cpp
  src/backend/gporca/libgpopt/src/operators/CScalarProjectList.cpp
  src/backend/gporca/libgpopt/src/operators/Makefile
  src/backend/gporca/libnaucrates/include/naucrates/dxl/gpdb_types.h
  src/backend/gporca/server/CMakeLists.txt
  src/backend/utils/adt/orderedsetaggs.c
  src/include/catalog/pg_aggregate.dat
  src/include/catalog/pg_proc.dat
  src/test/regress/expected/opr_sanity.out
  src/test/regress/expected/qp_functions_idf.out
  src/test/regress/sql/qp_functions_idf.sql
Labels: area: gporca, version: 7X_ALPHA

#13572 Resolve GPDB_12_MERGE_FIXME on index fetch tuple routines for Append-Optimized table.
  src/backend/access/aocs/aocsam_handler.c
  src/backend/access/appendonly/appendonlyam_handler.c
Labels: type: fixme

#13575 Resolve GPDB_12_MERGE_FIXME: exclude PROC_IN_VACUUM flag in procarray.c
  src/backend/storage/ipc/procarray.c
  src/include/storage/procarray.h
Labels: type: fixme

#13564 Resolve GPDB_12_MERGE_FIXME in PartitionSelector to support walking prune info
  src/backend/nodes/nodeFuncs.c
  src/backend/optimizer/plan/subselect.c
Labels: type: fixme

#13605 Materialize aggregations in NL Join inner child
  src/backend/gporca/data/dxl/minidump/AnyPredicate-Over-UnionOfConsts.mdp
  src/backend/gporca/data/dxl/minidump/AnySubq-With-NonScalarSubqueryChild-1.mdp
  src/backend/gporca/data/dxl/minidump/AnySubq-With-NonScalarSubqueryChild-2.mdp
  src/backend/gporca/data/dxl/minidump/CTEWithMergedGroup.mdp
  src/backend/gporca/data/dxl/minidump/CannotPullGrpColAboveAgg.mdp
  src/backend/gporca/data/dxl/minidump/CorrelatedIN-LeftSemiJoin-Limit.mdp
  src/backend/gporca/data/dxl/minidump/CorrelatedIN-LeftSemiJoin-True.mdp
  src/backend/gporca/data/dxl/minidump/CorrelatedLeftSemiNLJoinWithLimit.mdp
  src/backend/gporca/data/dxl/minidump/Correlation-With-Casting-1.mdp
  src/backend/gporca/data/dxl/minidump/DynamicIndexGet-OuterRefs.mdp
  src/backend/gporca/data/dxl/minidump/InSubqWithPrjListOuterRefNoInnerRefColumnIn.mdp
  src/backend/gporca/data/dxl/minidump/InSubqWithPrjListOuterRefNoInnerRefColumnPlusConstIn.mdp
  src/backend/gporca/data/dxl/minidump/InSubqWithPrjListOuterRefNoInnerRefConstIn.mdp
  src/backend/gporca/data/dxl/minidump/Join-With-Subq-Preds-1.mdp
  src/backend/gporca/data/dxl/minidump/Join-With-Subq-Preds-2.mdp
  src/backend/gporca/data/dxl/minidump/Join_OuterChild_DistUniversal.mdp
  src/backend/gporca/data/dxl/minidump/LOJNullRejectingZeroPlacePredicates.mdp
  src/backend/gporca/data/dxl/minidump/LeftOuter2InnerUnionAllAntiSemiJoin-Tpcds.mdp
  src/backend/gporca/data/dxl/minidump/LeftOuter2InnerUnionAllAntiSemiJoin.mdp
  src/backend/gporca/data/dxl/minidump/MultiLevel-CorrelatedExec.mdp
  src/backend/gporca/data/dxl/minidump/NLJ-Rewindability-CTAS.mdp
  src/backend/gporca/data/dxl/minidump/NLJ-Rewindability.mdp
  src/backend/gporca/data/dxl/minidump/NestedInSubqWithPrjListOuterRefNoInnerRef.mdp
  src/backend/gporca/data/dxl/minidump/OneLevel-CorrelatedExec.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-SubqueryOuterRef.mdp
  src/backend/gporca/data/dxl/minidump/Project-With-NonScalar-Func.mdp
  src/backend/gporca/data/dxl/minidump/PushSelectWithOuterRefBelowUnion.mdp
  src/backend/gporca/data/dxl/minidump/ScalarSubqueryCountStarInJoin.mdp
  src/backend/gporca/data/dxl/minidump/SimplifyExistsSubquery2Limit.mdp
  src/backend/gporca/data/dxl/minidump/Subq-With-OuterRefCol.mdp
  src/backend/gporca/data/dxl/minidump/SubqueryInsideScalarIf.mdp
  src/backend/gporca/data/dxl/minidump/SubqueryNoPullUpTableValueFunction.mdp
  src/backend/gporca/data/dxl/minidump/TVF-With-Deep-Subq-Args.mdp
  src/backend/gporca/data/dxl/minidump/UnnestSQJoins.mdp
  src/backend/gporca/data/dxl/minidump/WinFunc-Redistribute-Sort-CTE-Producer.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CRewindabilitySpec.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXformUtils.h
  src/backend/gporca/libgpopt/src/base/CRewindabilitySpec.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalAgg.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalNLJoin.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/gporca_optimizer.out
Labels: area: gporca, version: 6X_STABLE, backport

#13580 fixme: delete toast values of invisible AppendOptimized tuple during vacuum.
  src/backend/access/aocs/aocs_compaction.c
  src/backend/access/appendonly/appendonly_compaction.c
  src/backend/access/appendonly/appendonlyam_handler.c
  src/backend/access/heap/tuptoaster.c
  src/include/access/appendonly_compaction.h
  src/include/access/tuptoaster.h
  src/include/executor/tuptable.h
  src/test/regress/expected/toast.out
  src/test/regress/sql/toast.sql
Labels: type: fixme, merge_fixme

#13596 [6X_STABLE] Add support in ORCA to generate efficient plans for ordered-set aggs
  gpcontrib/Makefile
  gpcontrib/gp_percentile_agg/Makefile
  gpcontrib/gp_percentile_agg/README.md
  gpcontrib/gp_percentile_agg/expected/gp_percentile_agg.out
  gpcontrib/gp_percentile_agg/expected/gp_percentile_agg_optimizer.out
  gpcontrib/gp_percentile_agg/gp_percentile_agg--1.0.0.sql
  gpcontrib/gp_percentile_agg/gp_percentile_agg.c
  gpcontrib/gp_percentile_agg/gp_percentile_agg.control
  gpcontrib/gp_percentile_agg/sql/gp_percentile_agg.sql
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
  src/backend/gporca/data/dxl/minidump/CTAS_OrderedAgg_multiple_cols.mdp
  src/backend/gporca/data/dxl/minidump/OrderedAgg_array_fraction.mdp
  src/backend/gporca/data/dxl/minidump/OrderedAgg_computed_col.mdp
  src/backend/gporca/data/dxl/minidump/OrderedAgg_multiple_diffcol.mdp
  src/backend/gporca/data/dxl/minidump/OrderedAgg_multiple_samecol.mdp
  src/backend/gporca/data/dxl/minidump/OrderedAgg_multiple_samecol_difforderespec.mdp
  src/backend/gporca/data/dxl/minidump/OrderedAgg_single.mdp
  src/backend/gporca/data/dxl/minidump/OrderedAgg_with_groupby.mdp
  src/backend/gporca/data/dxl/minidump/OrderedAgg_with_nonOrderedAgg.mdp
  src/backend/gporca/data/dxl/minidump/OrderedAgg_with_nonconst_fraction.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CDrvdPropScalar.h
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpression.h
  src/backend/gporca/libgpopt/include/gpopt/operators/COrderedAggPreprocessor.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CScalarAggFunc.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CScalarProjectList.h
  src/backend/gporca/libgpopt/src/base/CDrvdPropScalar.cpp
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libgpopt/src/operators/CExpression.cpp
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/libgpopt/src/operators/COrderedAggPreprocessor.cpp
  src/backend/gporca/libgpopt/src/operators/CScalarAggFunc.cpp
  src/backend/gporca/libgpopt/src/operators/CScalarProjectList.cpp
  src/backend/gporca/libgpopt/src/operators/Makefile
  src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
  src/backend/gporca/libnaucrates/include/naucrates/dxl/gpdb_types.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/operators/CDXLScalarAggref.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
  src/backend/gporca/libnaucrates/src/operators/CDXLOperatorFactory.cpp
  src/backend/gporca/libnaucrates/src/operators/CDXLScalarAggref.cpp
  src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/backend/utils/cache/lsyscache.c
  src/include/gpopt/gpdbwrappers.h
  src/include/utils/lsyscache.h
Labels: area: gporca, version: 6X_STABLE, backport

#13624 remove FIXME in execExpr.c:ExecInitExprRec
  src/backend/executor/execExpr.c
Labels: type: fixme

#13634 Print errno for QE->QD dispatch checks
  src/backend/cdb/endpoint/cdbendpoint.c
  src/backend/cdb/motion/ic_udpifc.c
Labels: version: 7X_ALPHA, needs: backport

#13645 6X: Print errno for QE->QD dispatch checks
  src/backend/cdb/endpoint/cdbendpoint.c
  src/backend/cdb/motion/ic_udpifc.c
Labels: version: 6X_STABLE, backport

#13576 UDP interconnect: Modernize IC socket setup
  src/backend/cdb/motion/ic_udpifc.c
  src/include/cdb/cdbicudpfaultinjection.h
Labels: version: 7X_ALPHA

#13602 Fixed bug in resGroupPalloc about the allocated memory size.
  src/test/regress/regress_gp.c
Labels: community

#13510 [6X] Docs - remove redundant *.xml
  gpdb-doc/markdown/ref_guide/*.xml
Labels: area: documentation, community

#13642 Fix possible wrong mocking path in mocker.py
  src/test/unit/mock/mocker.py
Labels: community

#13448 (6x backport) Fix master crash when there is an error during cdbdisp_destroyDispatherState
  src/backend/cdb/dispatcher/cdbgang.c
  src/test/regress/input/dispatch.source
  src/test/regress/output/dispatch.source
Labels: version: 6X_STABLE

#13655 Rely on plan_cache_mode to force generic plans in partition_prune test.
  src/test/regress/expected/partition_prune.out
  src/test/regress/expected/partition_prune_optimizer.out
  src/test/regress/sql/partition_prune.sql
Labels: merge_fixme

#13643 Fix assertion failure in InitPostgres when resgroup is on
  src/backend/utils/mmgr/vmem_tracker.c
Labels: topic: resource group, community

#13653 Remove one merge_fixme in regress/subselect.
  src/test/regress/expected/subselect.out
  src/test/regress/expected/subselect_optimizer.out
  src/test/regress/sql/subselect.sql
Labels: type: fixme, merge_fixme

#13660 Remove one fixme in cdbgroupingpaths.c
  src/backend/cdb/cdbgroupingpaths.c
Labels: type: fixme, merge_fixme

#13626 Resolve fixme in test qp_olap_windowerr, temp_relation
  src/test/regress/expected/qp_olap_windowerr.out
  src/test/regress/expected/qp_olap_windowerr_optimizer.out
  src/test/regress/input/temp_relation.source
  src/test/regress/output/temp_relation.source
  src/test/regress/sql/qp_olap_windowerr.sql
Labels: type: fixme

#13631 remove parallel StreamBitmap scan FIXME
  src/backend/executor/execParallel.c
  src/backend/executor/nodeBitmapHeapscan.c
  src/backend/optimizer/plan/createplan.c
Labels: type: fixme

#13670 [README][typo] fix gpdemo path typo
  configure
  gpAux/gpdemo/README
Labels: community

#13671 [6X] Fix a flaky test checkpoint_memleak
  src/test/isolation2/expected/checkpoint_memleak.out
  src/test/isolation2/sql/checkpoint_memleak.sql
Labels: version: 6X_STABLE, flaky test

#13650 Remove fixme in hashagg_spill test.
  src/test/regress/expected/workfile/hashagg_spill.out
  src/test/regress/sql/workfile/hashagg_spill.sql
Labels: type: fixme

#13674 Fix a flakiness in recovery test overwrite_contrecord
  src/test/perl/PostgresNode.pm
Labels: flaky test

#13656 [ORCA] Fix memory leak in translator
  src/backend/gpopt/translate/CTranslatorUtils.cpp
Labels: area: gporca, needs: backport

#13683 [ORCA] Fix memory leaks in translator (#13656)
  src/backend/gpopt/translate/CTranslatorUtils.cpp
Labels: area: gporca, version: 6X_STABLE

#13677 OpenAOSegmentFile: minor cleanups
  src/backend/access/aocs/aocs_compaction.c
  src/backend/access/appendonly/aomd.c
  src/backend/access/appendonly/appendonly_compaction.c
  src/include/access/aomd.h
Labels: version: 7X_ALPHA, needs: backport

#13672 [gpdemo] polish checkDemoConfig
  gpAux/gpdemo/demo_cluster.sh
Labels: community

#13638 Remove fixme in nodeAgg.c:ExecSquelchAgg.
  src/backend/executor/nodeAgg.c
  src/include/executor/nodeAgg.h
  src/test/regress/expected/eagerfree.out
  src/test/regress/expected/eagerfree_optimizer.out
  src/test/regress/sql/eagerfree.sql
Labels: type: fixme

#13681 remove a superfluous variable
  gpMgmt/bin/gpinitsystem
  gpMgmt/bin/lib/gp_bash_functions.sh
Labels: community

#13676 Remove a MERGE_FIXME from the test select_parallel
  src/test/regress/expected/select_parallel.out
  src/test/regress/expected/select_parallel_optimizer.out
  src/test/regress/sql/select_parallel.sql
Labels: type: fixme

#13628 Resolve GPDB_12_MERGE_FIXME in test bfv_xxx file
  src/test/regress/expected/bfv_aggregate.out
  src/test/regress/expected/bfv_aggregate_optimizer.out
  src/test/regress/expected/bfv_partition_plans.out
  src/test/regress/expected/bfv_partition_plans_optimizer.out
  src/test/regress/sql/bfv_aggregate.sql
  src/test/regress/sql/bfv_partition_plans.sql
Labels: type: fixme

#13686 resolve fixme in cdbpath.c about update distribution key
  src/backend/cdb/cdbpath.c
Labels: merge_fixme

#13688 [doc] fix some gpinitsystem usage and doc mismatch
  gpMgmt/bin/gpinitsystem
  gpMgmt/doc/gpinitsystem_help
Labels: community

#13702 [typo] fix a typo to make the comment more precise
  src/include/access/appendonlytid.h
Labels: community

#13667 [GPORCA CI] Don't setup gpadmin user if database already exists
  concourse/scripts/build_gpdb.py
  concourse/scripts/builds/GpBuild.py
Labels: area: gporca, topic: continuous integration, version: 6X_STABLE

#13684 6X: OpenAOSegmentFile: minor cleanups
  src/backend/access/aocs/aocs_compaction.c
  src/backend/access/appendonly/aomd.c
  src/backend/access/appendonly/appendonly_compaction.c
  src/include/access/aomd.h
Labels: version: 6X_STABLE

#13696 Avoid further planning in case of result relation was pruned
  src/backend/optimizer/path/allpaths.c
  src/test/regress/expected/partition_pruning.out
  src/test/regress/expected/partition_pruning_optimizer.out
  src/test/regress/sql/partition_pruning.sql
Labels: community

#13695 added cluster health check for gpexpand
  gpMgmt/bin/gpexpand
  gpMgmt/bin/gppylib/test/unit/test_unit_gpexpand.py
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
Labels: gpcm_in

#13708 [5X] GUC: Bypass dtx visibility checks for tuples
  src/backend/cdb/cdbdistributedsnapshot.c
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/test/isolation2/expected/vacuum_full_recently_dead_tuple_due_to_distributed_snapshot.out
  src/test/isolation2/sql/vacuum_full_recently_dead_tuple_due_to_distributed_snapshot.sql
Labels: version: 5X_STABLE

#13719 Gut the appendoptimized_basic test
  src/test/regress/expected/appendoptimized_basic.out
  src/test/regress/sql/appendoptimized_basic.sql
Labels: version: 7X_ALPHA

#13705 [6X_STABLE] resolve compiler warnings
  src/backend/cdb/dispatcher/cdbdisp_async.c
  src/backend/tcop/postgres.c
  src/bin/gpfdist/gpfdist.c
  src/include/miscadmin.h
Labels: version: 6X_STABLE

#13664 Resolve GPDB_12_MERGE_FIXME in subselect.sql
  src/backend/optimizer/path/allpaths.c
  src/test/regress/expected/subselect.out
  src/test/regress/expected/subselect_optimizer.out
  src/test/regress/sql/subselect.sql
Labels: type: fixme

#13742 [5X]: Fix vacuum full utility mode test
  src/test/isolation2/expected/vacuum_full_recently_dead_tuple_due_to_distributed_snapshot.out
  src/test/isolation2/sql/vacuum_full_recently_dead_tuple_due_to_distributed_snapshot.sql
Labels: version: 5X_STABLE

#13752 Revert "added cluster health check for gpexpand"
  gpMgmt/bin/gpexpand
  gpMgmt/bin/gppylib/test/unit/test_unit_gpexpand.py
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
Labels: gpcm_in
