Repository greenplum-db/gpdb, pull requests merged in 2022-02, with the labels that each got.

#13038 [Backport 6X] Undo the banner changes on behave tests once the test h…
  gpMgmt/test/behave/mgmt_utils/environment.py
  gpMgmt/test/behave/mgmt_utils/gpinitstandby.feature
  gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in

#13047 Added Behave testcase for guc with same prefix
  gpMgmt/test/behave/mgmt_utils/gpconfig.feature
Labels: gpcm_in

#13024 Remove flaky isolation test reindex-partitions
  src/test/isolation/expected/reindex-partitions.out
  src/test/isolation/isolation_schedule
  src/test/isolation/specs/reindex-partitions.spec
Labels: version: 7X_ALPHA

#12994 [6X] [backport] pageinspect bitmap support
  contrib/pageinspect/Makefile
  contrib/pageinspect/bmfuncs.c
  contrib/pageinspect/pageinspect--1.2--1.8.sql
  contrib/pageinspect/pageinspect--1.8.sql
  contrib/pageinspect/pageinspect.control
  src/test/isolation2/expected/bitmap_index_inspect.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/bitmap_index_inspect.sql
Labels: version: 6X_STABLE

#13049 Changes to avoid gpinitsystem failure when multiple address interfaces
  gpMgmt/bin/lib/gp_bash_functions.sh
  gpMgmt/bin/lib/gpcreateseg.sh
Labels: gpcm_in

#13081 removed redefined PG_AUTOCONF_FILENAME in guc.h
  src/include/utils/guc.h
Labels: community

#13086 GPORCA CI: add workload6 to explain pipeline
  src/backend/gporca/concourse/test_explain_pipeline.yml
Labels: area: gporca, version: 7X_ALPHA

#13087 GPORCA CI: add workload6 to explain pipeline
  src/backend/gporca/concourse/test_explain_pipeline.yml
Labels: area: gporca, version: 6X_STABLE

#13044 Fix typo in DeserializeResGroupInfo()
  src/backend/utils/resgroup/resgroup.c
Labels: community

#13028 [6X] Refactor how we handle dropped column references in partition tables during major version upgrades
  contrib/pg_upgrade/greenplum/check_gp.c
  contrib/pg_upgrade/greenplum/check_gp.h
  src/bin/pg_dump/pg_dump.c
  src/bin/pg_dump/pg_dump.h
  src/test/regress/expected/pg_dump_binary_upgrade.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/pg_dump_binary_upgrade.sql
Labels: version: 6X_STABLE

#13092 "New options" shouldn't affect redistribution in ALTER TABLE ... DISTRIBUTE BY
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_distribution_policy.out
  src/test/regress/sql/alter_distribution_policy.sql
Labels: type: bug, version: 7X_ALPHA, needs: backport

#13077 Optimize retrieving indexes on partitions within Orca
  src/backend/cdb/cdbpartindex.c
  src/backend/cdb/partitionselection.c
Labels: area: gporca, version: 6X_STABLE

#12124 6X: Fix segfault on execution of multilevel correlated queries.
  src/backend/optimizer/plan/subselect.c
  src/include/optimizer/subselect.h
  src/test/regress/expected/qp_correlated_query.out
  src/test/regress/expected/qp_correlated_query_optimizer.out
  src/test/regress/sql/qp_correlated_query.sql
Labels: version: 6X_STABLE

#12776 ShareInputScan Node in subplans of Sequence Node returns earlier, avoid unnecessary read from tuplestore.
  src/backend/executor/nodeShareInputScan.c
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/optimizer/plan/planshare.c
  src/include/nodes/plannodes.h
Labels: area: gporca, community

#13099 Resolve a merge FIXME for ATExecSetDistributedBy()
  src/backend/commands/tablecmds.c
Labels: type: fixme, version: 7X_ALPHA

#13025 [6X]Fix flaky failed cases pg_rewind_fail_missing_xlog.
  src/test/isolation2/expected/pg_rewind_fail_missing_xlog.out
  src/test/isolation2/sql/pg_rewind_fail_missing_xlog.sql
Labels: version: 6X_STABLE

#12937 Install pg_attribute_encoding for AOCS during CTAS
  src/backend/access/aocs/aocsam.c
  src/backend/commands/createas.c
  src/backend/tcop/utility.c
  src/test/regress/expected/gpctas.out
  src/test/regress/sql/gpctas.sql
Labels: community

#12863 Fix index corruption when invalid snapshot used with AO tables.
  src/backend/access/aocs/aocsam.c
  src/backend/access/appendonly/appendonlyam.c
  src/test/isolation2/input/uao/snapshot_index_corruption.source
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/output/uao/snapshot_index_corruption.source
Labels: community

#12797 [6X] Fix index corruption when invalid snapshot used with AO tables.
  src/backend/catalog/index.c
  src/backend/commands/indexcmds.c
  src/test/isolation2/input/uao/snapshot_index_corruption.source
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/output/uao/snapshot_index_corruption.source
Labels: version: 6X_STABLE, needs: backport, community

#13100 [6X] Existing reloption shouldn't affect redistribution in SET DISTRIBUTE BY
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_distribution_policy.out
  src/test/regress/sql/alter_distribution_policy.sql
Labels: version: 6X_STABLE, backport

#13105 [6X] Close AO segment file
  src/backend/cdb/cdbappendonlystoragewrite.c
Labels: version: 6X_STABLE, backport

#13107 [6X] Free disk space for dropped relations on commit.
  src/backend/storage/smgr/md.c
Labels: version: 6X_STABLE, backport

#13062 Changes to avoid gpstop errors when standby is not reachable.
  gpMgmt/bin/gpstop
  gpMgmt/test/behave/mgmt_utils/gpstop.feature
  gpMgmt/test/behave/mgmt_utils/steps/gpstart.py
Labels: gpcm_in

#13127 Fix index corruption when invalid snapshot used with AO tables. (#12797)
  src/backend/catalog/index.c
  src/backend/commands/indexcmds.c
  src/test/isolation2/input/uao/snapshot_index_corruption.source
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/output/uao/snapshot_index_corruption.source
Labels: version: 6X_STABLE
