Repository greenplum-db/gpdb, pull requests merged in 2023-08, with the labels that each got.

#15164 Fix memory leaks in auto_explain
  contrib/auto_explain/Makefile
  contrib/auto_explain/auto_explain.c
  contrib/auto_explain/expected/memory_leaks.out
  contrib/auto_explain/sql/memory_leaks.sql
  src/backend/commands/explain.c
  src/backend/commands/explain_gp.c
  src/backend/tcop/pquery.c
  src/include/cdb/cdbexplain.h
Labels: version: 6X_STABLE, community

#16072 [6X] Fix replication slot inactive issue post differential recovery. (#15981)
  gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
  gpMgmt/sbin/gpsegrecovery.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in

#16097 Remove a FIXME in cdbaocsam.h
  src/include/cdb/cdbaocsam.h
Labels: version: 7X_ALPHA, merge_fixme

#16076 docs - new gp_toolkit views for missing/orphaned files
  gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
Labels: 7X_Docs

#16116 gp_system views: Remove \n from sed replacement
  src/backend/catalog/Makefile
Labels: version: 7X_ALPHA, 7X_beta_testing

#16048 [6x] gpcheckcat: Add new option -x to set session level GUCs
  gpMgmt/bin/gpcheckcat
  gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
Labels: version: 6X_STABLE, backport, gpcm_in

#16043 Remove GPDB_12_MERGE_FIXME from gpcheckcat.feature
  concourse/pipelines/gpdb_main-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
  gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
Labels: version: 7X_ALPHA, gpcm_in, merge_fixme

#16103 AT-SET-AM/AT-SET-RELOPTIONS: Skip foreign tables
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_table_set_am.out
  src/test/regress/sql/alter_table_set_am.sql
Labels: version: 7X_ALPHA

#16111 Docs: new option -x for gpcheckcat
  gpdb-doc/markdown/utility_guide/ref/gpcheckcat.html.md
Labels: 7X_Docs

#16075 Docs: added wal_compression to list of gucs
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
Labels: 7X_Docs

#16123 docs - add content for new pgvector module
  gpdb-doc/markdown/install_guide/install_modules.html.md
  gpdb-doc/markdown/ref_guide/modules/intro.html.md
  gpdb-doc/markdown/ref_guide/modules/pgvector/LICENSE
  gpdb-doc/markdown/ref_guide/modules/pgvector/pgvector.html.md
  gpdb-doc/markdown/ref_guide/toc.md
Labels: 7X_Docs

#16122 docs - postgres_fdw improvements, new options
  gpdb-doc/markdown/ref_guide/modules/postgres_fdw.html.md
Labels: 7X_Docs

#16125 Flag persistent WalSndError on repslot invalidation
  src/backend/replication/slot.c
  src/include/replication/walsender_private.h
Labels: version: 7X_ALPHA

#16095 analyzedb should be skipped on Temp tables
  gpMgmt/bin/analyzedb
  gpMgmt/test/behave/mgmt_utils/analyzedb.feature
Labels: area: gporca, version: 7X_ALPHA, topic: analyze

#16130 Fix gpcheckcat error against pg_description
  gpMgmt/bin/gpcheckcat
  gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  gpMgmt/test/behave_utils/utils.py
Labels: version: 7X_ALPHA, gpcm_in

#16055 Enable ORCA to generate IndexScan plans with ScalarArrayOp quals
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gporca/data/dxl/minidump/BTreeIndex-Against-InList.mdp
  src/backend/gporca/libgpopt/include/gpopt/operators/CPredicateUtils.h
  src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
  src/test/regress/expected/bfv_index.out
  src/test/regress/expected/bfv_index_optimizer.out
  src/test/regress/expected/create_index_optimizer.out
  src/test/regress/sql/bfv_index.sql
Labels: area: gporca, version: 7X_ALPHA, needs: backport

#15103 Change GetAppendOnlyEntryAuxOids/GetAppendOnlyEntry to macros
  src/backend/access/appendonly/appendonlyam.c
  src/backend/catalog/pg_appendonly.c
  src/include/catalog/pg_appendonly.h
Labels: version: 7X_ALPHA

#15967 Fix flaky case resource_queue_stat
  src/test/regress/expected/resource_queue_stat.out
  src/test/regress/sql/resource_queue_stat.sql
Labels: version: 7X_ALPHA, community

#16150 [6X] Fix flaky case resource_queue_stat
  src/test/regress/expected/resource_queue_stat.out
  src/test/regress/sql/resource_queue_stat.sql
Labels: version: 6X_STABLE, backport, flaky test

#16136 Rewrite test interrupt_holdoff_count
  src/test/regress/expected/interrupt_holdoff_count.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/interrupt_holdoff_count.sql
Labels: version: 7X_ALPHA, community

#16049 Do not convert IN query to Exists for set returning function
  src/backend/gporca/data/dxl/minidump/InSubqWithPrjListReturnSet.mdp
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/gp_tsrf.out
  src/test/regress/expected/gp_tsrf_optimizer.out
  src/test/regress/sql/gp_tsrf.sql
Labels: area: gporca, version: 7X_ALPHA

#16143 Fix test test_HandleFtsWalRepPromoteMirror variable reference
  src/backend/fts/test/ftsmessagehandler_test.c
Labels: area: server, version: 7X_ALPHA

#16166 Add a missing NOTICE log message in test alter_table_set_am
  src/test/regress/expected/alter_table_set_am.out
Labels: version: 7X_ALPHA

#16140 [6x Backport] Fix gpcheckcat error against pg_description
  gpMgmt/bin/gpcheckcat
  gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  gpMgmt/test/behave_utils/utils.py
Labels: version: 6X_STABLE, backport, gpcm_in

#15586 Add exclude of directory "db_analyze" to generate template to gpexpand
  gpMgmt/bin/gppylib/commands/pg.py
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: area: management utilities, version: 6X_STABLE, gpcm_in, community

#16159 Fix flaky privileges tests
  src/test/regress/expected/privileges.out
  src/test/regress/expected/privileges_optimizer.out
  src/test/regress/sql/privileges.sql
Labels: area: gporca, version: 7X_ALPHA

#16155 [6x Backport] analyzedb should be skipped on Temp tables (#16095)
  gpMgmt/bin/analyzedb
  gpMgmt/test/behave/mgmt_utils/analyzedb.feature
Labels: topic: analyze

#16165 5X: Convert disallow_unique_rowid_path to a GUC
  src/backend/optimizer/util/pathnode.c
  src/backend/utils/misc/guc_gp.c
  src/include/nodes/relation.h
  src/include/utils/guc.h
  src/test/isolation2/expected/vacuum_full_recently_dead_tuple_due_to_distributed_snapshot.out
  src/test/regress/input/table_functions.source
  src/test/regress/output/table_functions.source
  src/test/regress/output/table_functions_optimizer.source
Labels: version: 5X_STABLE

#16142 docs - minor edits to EXTERNAL TABLE sql ref pages
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_EXTERNAL_TABLE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_EXTERNAL_TABLE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_EXTERNAL_TABLE.html.md
Labels: 7X_Docs

#15755 brin ao/co: Correctly derive numRanges for costing
  src/backend/utils/adt/selfuncs.c
  src/include/access/appendonlytid.h
Labels: topic: planner, version: 7X_ALPHA, area: aoco, topic:brin

#15861 gpcheckperf: add buffer size parameter
  gpMgmt/bin/gpcheckperf
  gpMgmt/doc/gpcheckperf_help
  gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
Labels: version: 6X_STABLE, gpcm_in, community

#16181 Re-used index after ALTER COLUMN TYPE shouldn't change relfilenode
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_table_gp.out
  src/test/regress/sql/alter_table_gp.sql
Labels: version: 7X_ALPHA

#16145 [7X] ORCA initialization refactoring
  src/backend/gpopt/CGPOptimizer.cpp
  src/backend/gpopt/utils/CMemoryPoolPallocManager.cpp
  src/backend/gporca/libgpopt/include/gpopt/exception.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXformFactory.h
  src/backend/gporca/libgpopt/src/exception.cpp
  src/backend/gporca/libgpopt/src/init.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformFactory.cpp
  src/backend/gporca/libgpos/include/gpos/error/CMessageRepository.h
  src/backend/gporca/libgpos/include/gpos/memory/CCacheFactory.h
  src/backend/gporca/libgpos/include/gpos/memory/CMemoryPoolManager.h
  src/backend/gporca/libgpos/include/gpos/task/CWorkerPoolManager.h
  src/backend/gporca/libgpos/src/_api.cpp
  src/backend/gporca/libgpos/src/common/CDebugCounter.cpp
  src/backend/gporca/libgpos/src/error/CMessageRepository.cpp
  src/backend/gporca/libgpos/src/memory/CCacheFactory.cpp
  src/backend/gporca/libgpos/src/memory/CMemoryPoolManager.cpp
  src/backend/gporca/libgpos/src/task/CWorkerPoolManager.cpp
  src/backend/gporca/libnaucrates/include/naucrates/exception.h
  src/backend/gporca/libnaucrates/src/exception.cpp
  src/backend/gporca/libnaucrates/src/init.cpp
  src/backend/gporca/server/src/startup/main.cpp
  src/include/gpopt/utils/CMemoryPoolPallocManager.h
Labels: area: gporca, version: 7X_ALPHA, community

#16199 planner: Adjust index scan path by numsegments
  contrib/postgres_fdw/expected/gp2pg_postgres_fdw.out
  src/backend/optimizer/path/costsize.c
  src/test/regress/expected/bfv_olap.out
  src/test/regress/expected/gp_covering_index.out
  src/test/regress/expected/join.out
  src/test/regress/expected/partition_join.out
  src/test/regress/expected/qp_join_union_all.out
  src/test/regress/expected/rpt.out
  src/test/regress/expected/select.out
  src/test/regress/expected/subselect_gp_indexes.out
  src/test/regress/output/uao_dml/ao_covering_index.source
Labels: topic: planner, version: 7X_ALPHA

#16163 Fall back to planner for queries on relations with pgvector index
  src/backend/access/index/amapi.c
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/include/access/amapi.h
  src/include/gpopt/gpdbwrappers.h
Labels: area: gporca, version: 7X_ALPHA

#16214 Update ORCA ans files for index costing change
  contrib/postgres_fdw/expected/gp2pg_postgres_fdw_optimizer.out
  src/test/regress/expected/select_optimizer.out
Labels: version: 7X_ALPHA

#15973 Make slabs and generations use gp_malloc|free
  src/backend/utils/mmgr/generation.c
  src/backend/utils/mmgr/slab.c
Labels: version: 7X_ALPHA

#16176 [6X Backport]Enable ORCA to generate IndexScan plans with ScalarArrayOp quals
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gporca/data/dxl/minidump/BTreeIndex-Against-InList.mdp
  src/backend/gporca/libgpopt/include/gpopt/operators/CPredicateUtils.h
  src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
  src/test/regress/expected/bfv_index.out
  src/test/regress/expected/bfv_index_optimizer.out
  src/test/regress/expected/create_index_optimizer.out
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/bfv_index.sql
  src/test/regress/sql/gporca.sql
Labels: area: gporca, backport

#16183 docs - add optimizer_enable_push_join_below_union_all to guc ref
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
Labels: 7X_Docs

#16208 docs - correct the optimizer_join_order guc ref info
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
Labels: 7X_Docs

#16171 [6X Backport] Do not convert IN query to Exists for set returning function (#16049)
  src/backend/gporca/data/dxl/minidump/InSubqWithPrjListReturnSet.mdp
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 6X_STABLE

#16212 Fix Orca crash due to improper colref mapping with CTEs
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatistics.h
  src/backend/gporca/libnaucrates/src/statistics/CStatistics.cpp
  src/test/regress/expected/bfv_joins.out
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/sql/bfv_joins.sql
Labels: area: gporca, version: 7X_ALPHA

#16175 Fix test case resgroup_views
  src/test/isolation2/input/resgroup/resgroup_views.source
  src/test/isolation2/output/resgroup/resgroup_views.source
Labels: version: 7X_ALPHA, community

#16213 Hintbit WAL syncrep should not throttle when holding exclusive lock
  src/backend/access/transam/xlog.c
  src/backend/storage/buffer/bufmgr.c
  src/backend/storage/lmgr/lwlock.c
  src/include/storage/lwlock.h
  src/test/isolation2/expected/segwalrep/hintbit_throttle.out
  src/test/isolation2/expected/segwalrep/select_throttle.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/segwalrep/hintbit_throttle.sql
Labels: version: 7X_ALPHA, needs: backport

#16078 [CI] Rename check_[[ test_os ]] job to gpmgmt_unit_tests_[[ os_type ]].
  concourse/pipelines/gpdb_main-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: gpcm_in

#16162 [ORCA] Enable index-only scan on AO tables
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/gporca/data/dxl/minidump/AllowIndexOnlyScanOnAppendOnlyTable.mdp
  src/backend/gporca/data/dxl/minidump/AllowIndexOnlyScanOnMixedAppendOnlyPartitionedTable.mdp
  src/backend/gporca/data/dxl/minidump/AllowIndexOnlyScanOnMixedPartitionedTable.mdp
  src/backend/gporca/data/dxl/minidump/BTreeIndex-Against-InListLarge.mdp
  src/backend/gporca/data/dxl/minidump/BitmapScan-Hetrogeneous-Partitioned.mdp
  src/backend/gporca/data/dxl/minidump/BitmapTableScan-AO-Btree-PickIndexWithNoGap.mdp
  src/backend/gporca/data/dxl/minidump/DoubleNDVCardinalityEquals.mdp
  src/backend/gporca/data/dxl/minidump/PreventIndexOnlyScanOnAppendOnlyVersion6UpgradedTable.mdp
  src/backend/gporca/data/dxl/minidump/PreventIndexOnlyScanOnMixedAppendOnlyPartitionedTableContainingAppendOnlyVersion6Child.mdp
  src/backend/gporca/data/dxl/minidump/PreventIndexOnlyScanOnMixedPartitionedTableContainingAppendOnlyVersion6Child.mdp
  src/backend/gporca/data/dxl/minidump/SubqInIndexPred.mdp
  src/backend/gporca/data/dxl/parse_tests/q26-Metadata.xml
  src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
  src/backend/gporca/libgpopt/include/gpopt/metadata/CIndexDescriptor.h
  src/backend/gporca/libgpopt/include/gpopt/metadata/CTableDescriptor.h
  src/backend/gporca/libgpopt/src/metadata/CIndexDescriptor.cpp
  src/backend/gporca/libgpopt/src/metadata/CTableDescriptor.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformDynamicIndexGet2DynamicIndexOnlyScan.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformDynamicIndexGet2DynamicIndexScan.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformIndexGet2IndexOnlyScan.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformIndexGet2IndexScan.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerMDRelation.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
  src/backend/gporca/libnaucrates/include/naucrates/md/CMDRelationCtasGPDB.h
  src/backend/gporca/libnaucrates/include/naucrates/md/CMDRelationGPDB.h
  src/backend/gporca/libnaucrates/include/naucrates/md/IMDRelation.h
  src/backend/gporca/libnaucrates/src/md/CMDRelationGPDB.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerMDRelation.cpp
  src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
  src/backend/gporca/scripts/cal_bitmap_test.py
  src/backend/gporca/server/CMakeLists.txt
  src/backend/gporca/server/src/unittest/CTestUtils.cpp
  src/backend/gporca/server/src/unittest/dxl/statistics/CStatisticsTest.cpp
  src/backend/gporca/server/src/unittest/gpopt/translate/CTranslatorDXLToExprTest.cpp
  src/test/regress/expected/bfv_index_optimizer.out
  src/test/regress/expected/co_nestloop_idxscan.out
  src/test/regress/expected/co_nestloop_idxscan_optimizer.out
  src/test/regress/expected/gp_covering_index.out
  src/test/regress/expected/gp_covering_index_optimizer.out
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/output/uao_dml/ao_covering_index_optimizer.source
  src/test/regress/sql/co_nestloop_idxscan.sql
  src/test/regress/sql/gp_covering_index.sql
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 7X_ALPHA

#16131 docs - sql ref page updates for CHECKPOINT, CLUSTER, COMMENT
  gpdb-doc/markdown/ref_guide/sql_commands/CHECKPOINT.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CLUSTER.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/COMMENT.html.md
Labels: 7X_Docs

#16033 docs - part 3 of partitioning-related updates: terms, narrative content
  gpdb-doc/markdown/admin_guide/ddl/about-part-changes.html.md
  gpdb-doc/markdown/admin_guide/ddl/classic-partition.html.md
  gpdb-doc/markdown/admin_guide/ddl/ddl-basics.html.md
  gpdb-doc/markdown/admin_guide/ddl/ddl-index.html.md
  gpdb-doc/markdown/admin_guide/ddl/ddl-partition.html.md
  gpdb-doc/markdown/admin_guide/ddl/ddl-storage.html.md
  gpdb-doc/markdown/admin_guide/dml.html.md
  gpdb-doc/markdown/admin_guide/intro/about_statistics.html.md
  gpdb-doc/markdown/admin_guide/managing/maintain.html.md
  gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-changed.html.md
  gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-notes.html.md
  gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-root-partition.html.md
  gpdb-doc/markdown/admin_guide/query/topics/query-profiling.html.md
  gpdb-doc/markdown/best_practices/analyze.html.md
  gpdb-doc/markdown/best_practices/schema.html.md
  gpdb-doc/markdown/best_practices/summary.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ANALYZE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/COPY.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/GRANT.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/INSERT.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/REVOKE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/UPDATE.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/gp_partition_template.html.md
  gpdb-doc/markdown/utility_guide/ref/analyzedb.html.md
  gpdb-doc/markdown/utility_guide/ref/gpreload.html.md
  gpdb-doc/markdown/utility_guide/ref/pg_dump.html.md
  gpdb-doc/markdown/utility_guide/ref/psql.html.md
Labels: 7X_Docs

#16255 Fix flaky plan diffs for select.sql
  src/test/regress/expected/select.out
  src/test/regress/expected/select_optimizer.out
  src/test/regress/sql/select.sql
Labels: topic: planner, version: 7X_ALPHA, flaky test

#16141 Fix segmentation fault during dispatch interrupt
  src/backend/cdb/dispatcher/test/Makefile
  src/backend/cdb/dispatcher/test/cdbdisp_query_test.c
  src/backend/cdb/dispatcher/test/gpsegconfig_dump
  src/interfaces/libpq/fe-connect.c
  src/interfaces/libpq/fe-misc.c
Labels: version: 7X_ALPHA, needs: backport, community, Priority 1, area: dispatch

#16257 docs - add optimizer_enable_dynamicindexonlyscan to guc ref
  gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-limitations.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
Labels: 7X_Docs

#16275 Remove a FIXME in tupser.c
  src/backend/cdb/motion/tupser.c
Labels: version: 7X_ALPHA, merge_fixme

#16209 6X: Change Query Parameter fallback message in Orca to notice type
  src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
  src/test/regress/expected/aggregates_optimizer.out
  src/test/regress/expected/gporca_optimizer.out
Labels: area: gporca, version: 6X_STABLE

#15932 Docs: reorder of Platform Requirements page
  gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
Labels: 7X_Docs

#16217 [6X] ORCA initialization refactoring
  src/backend/gpopt/CGPOptimizer.cpp
  src/backend/gpopt/utils/CMemoryPoolPallocManager.cpp
  src/backend/gporca/libgpopt/include/gpopt/exception.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXformFactory.h
  src/backend/gporca/libgpopt/src/exception.cpp
  src/backend/gporca/libgpopt/src/init.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformFactory.cpp
  src/backend/gporca/libgpos/include/gpos/error/CFSimulator.h
  src/backend/gporca/libgpos/include/gpos/error/CMessageRepository.h
  src/backend/gporca/libgpos/include/gpos/memory/CCacheFactory.h
  src/backend/gporca/libgpos/include/gpos/memory/CMemoryPoolManager.h
  src/backend/gporca/libgpos/include/gpos/task/CWorkerPoolManager.h
  src/backend/gporca/libgpos/src/_api.cpp
  src/backend/gporca/libgpos/src/common/CDebugCounter.cpp
  src/backend/gporca/libgpos/src/error/CFSimulator.cpp
  src/backend/gporca/libgpos/src/error/CMessageRepository.cpp
  src/backend/gporca/libgpos/src/memory/CCacheFactory.cpp
  src/backend/gporca/libgpos/src/memory/CMemoryPoolManager.cpp
  src/backend/gporca/libgpos/src/task/CWorkerPoolManager.cpp
  src/backend/gporca/libnaucrates/include/naucrates/exception.h
  src/backend/gporca/libnaucrates/src/exception.cpp
  src/backend/gporca/libnaucrates/src/init.cpp
  src/backend/gporca/server/src/startup/main.cpp
  src/include/gpopt/utils/CMemoryPoolPallocManager.h
Labels: area: gporca, version: 6X_STABLE, community

#15917 Add explain analyze detailed info of hash agg
  src/backend/commands/explain.c
  src/backend/executor/nodeAgg.c
  src/include/executor/nodeAgg.h
  src/include/lib/simplehash.h
  src/test/regress/expected/explain_format.out
  src/test/regress/expected/explain_format_optimizer.out
  src/test/regress/sql/explain_format.sql
Labels: version: 7X_ALPHA, EXPLAIN ANALYZE

#14574 Fixed EXPLAIN ANALYZE bug when foreign scan's gang size larger than number of segments
  contrib/postgres_fdw/expected/gp_postgres_fdw.out
  contrib/postgres_fdw/expected/gp_postgres_fdw_optimizer.out
  contrib/postgres_fdw/sql/gp_postgres_fdw.sql
  src/backend/commands/explain_gp.c
Labels: version: 7X_ALPHA, community

#16218 Analyzing leaf partitions of multi-level partition table causes resampling of intermediate partition.
  src/backend/commands/vacuum.c
  src/test/regress/expected/analyze.out
  src/test/regress/sql/analyze.sql
Labels: area: gporca

#16249 [6X] Hintbit WAL syncrep should not throttle when holding exclusive lock
  src/backend/storage/buffer/bufmgr.c
  src/test/isolation2/expected/segwalrep/hintbit_throttle.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/segwalrep/hintbit_throttle.sql
Labels: version: 6X_STABLE

#16232 Docs: added instructions to support python3.9 with Rocky
  gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
Labels: 7X_Docs

#16242 Fix gpstop pipeline flakiness after #15727
  gpMgmt/test/behave/mgmt_utils/gpstop.feature
  gpMgmt/test/behave/mgmt_utils/steps/unreachable_hosts_mgmt_utils.py
Labels: gpcm_in

#16289 Fix flaky test case vacuum_stats
  src/test/regress/expected/vacuum_stats.out
  src/test/regress/sql/vacuum_stats.sql
Labels: version: 7X_ALPHA, community

#16296 Optimize string length checks in Orca
  src/backend/gporca/libgpos/include/gpos/string/CWStringBase.h
  src/backend/gporca/libgpos/src/string/CWStringBase.cpp
  src/backend/gporca/libgpos/src/string/CWStringConst.cpp
Labels: area: gporca, version: 7X_ALPHA

#16234 Don't export libpq.so symbols in the postgres binary.
  contrib/postgres_fdw/expected/gp_postgres_fdw.out
  contrib/postgres_fdw/expected/gp_postgres_fdw_optimizer.out
  contrib/postgres_fdw/sql/gp_postgres_fdw.sql
  gpcontrib/gp_exttable_fdw/Makefile
  gpcontrib/gp_inject_fault/Makefile
  src/backend/.gitignore
  src/backend/Makefile
  src/test/regress/GNUmakefile
Labels: version: 7X_ALPHA, community

#16308 Allocate histogram sample array on heap
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CHistogram.h
  src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp
Labels: area: gporca, version: 6X_STABLE, backport

#16235 [6x Backport] Fix gprecoverseg with unreachable failed host
  gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
  gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
  gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment_triples.py
  gpMgmt/test/behave/mgmt_utils/environment.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg_newhost.feature
  gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/unreachable_hosts_mgmt_utils.py
Labels: version: 6X_STABLE, backport, gpcm_in

#16282 Fixing column width of partitioned tables
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/include/gpopt/gpdbwrappers.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 7X_ALPHA

#16112 gprecoverseg differential: Data integrity scenario
  gpMgmt/bin/gppylib/commands/base.py
  gpMgmt/test/behave/mgmt_utils/environment.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in

#16322 Disallow non-standalone ALTER distribution
  src/backend/commands/tablecmds.c
  src/test/isolation2/expected/aoco_column_rewrite.out
  src/test/isolation2/sql/aoco_column_rewrite.sql
  src/test/regress/expected/alter_distribution_policy.out
  src/test/regress/sql/alter_distribution_policy.sql
Labels: version: 7X_ALPHA, needs: backport

#16265 Support FIELDSELECT node from ORCA
  src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
  src/backend/gporca/data/dxl/minidump/FieldSelect.mdp
  src/backend/gporca/libgpopt/include/gpopt/operators/COperator.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CScalarFieldSelect.h
  src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorDXLToExpr.h
  src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorExprToDXL.h
  src/backend/gporca/libgpopt/src/operators/CScalarFieldSelect.cpp
  src/backend/gporca/libgpopt/src/operators/Makefile
  src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
  src/backend/gporca/libnaucrates/include/naucrates/dxl/operators/CDXLOperator.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/operators/CDXLOperatorFactory.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/operators/CDXLScalarFieldSelect.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerFactory.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerScalarFieldSelect.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/parsehandlers.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
  src/backend/gporca/libnaucrates/src/operators/CDXLOperatorFactory.cpp
  src/backend/gporca/libnaucrates/src/operators/CDXLScalarFieldSelect.cpp
  src/backend/gporca/libnaucrates/src/operators/Makefile
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerFactory.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerScalarFieldSelect.cpp
  src/backend/gporca/libnaucrates/src/parser/Makefile
  src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/include/gpopt/translate/CTranslatorDXLToScalar.h
  src/include/gpopt/translate/CTranslatorScalarToDXL.h
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/output/external_table_persistent_error_log_optimizer.source
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 7X_ALPHA

#16319 docs - gporca now supports backwards index scan
  gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-limitations.html.md
Labels: 7X_Docs

#16318 Docs: LDAP page corrections
  gpdb-doc/markdown/admin_guide/ldap.html.md
Labels: 7X_Docs

#16336 Docs: removed reference of removed configuration parameter krb_srvname
  gpdb-doc/markdown/admin_guide/kerberos.html.md
Labels: 7X_Docs

#16287 Docs: modified Synchronizing System Clocks section
  gpdb-doc/markdown/install_guide/prep_os.html.md
Labels: 7X_Docs

#16290 docs - external table changes, misc related edits/reorg
  gpdb-doc/markdown/admin_guide/external/about_exttab_7.html.md
  gpdb-doc/markdown/admin_guide/external/g-accessing-ext-files-custom-protocol.html.md
  gpdb-doc/markdown/admin_guide/external/g-devel-fdw.html.md
  gpdb-doc/markdown/admin_guide/external/g-external-tables.html.md
  gpdb-doc/markdown/admin_guide/external/g-file-protocol.html.md
  gpdb-doc/markdown/admin_guide/external/g-foreign.html.md
  gpdb-doc/markdown/admin_guide/external/g-working-with-file-based-ext-tables.html.md
  gpdb-doc/markdown/admin_guide/external/map_ext_to_foreign.html.md
  gpdb-doc/markdown/admin_guide/external/pxf-overview.html.md
  gpdb-doc/markdown/admin_guide/load/topics/g-loading-and-unloading-data.html.md
  gpdb-doc/markdown/ref_guide/modules/gp_exttable_fdw.html.md
  gpdb-doc/markdown/ref_guide/modules/intro.html.md
  gpdb-doc/markdown/ref_guide/toc.md
Labels: 7X_Docs
