Repository greenplum-db/gpdb, pull requests merged in 2023-09, with the labels that each got.

#16264 [6x]: Fix failed jobs for rocky9/oel9/rhel9
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/bin/gppylib/test/unit/test_unit_recovery_base.py
  gpMgmt/bin/lib/multidd
Labels: version: 6X_STABLE, gpcm_in

#16335 [6X] gprecoverseg differential: Data integrity scenario
  gpMgmt/bin/gppylib/commands/unix.py
  gpMgmt/test/behave/mgmt_utils/environment.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in

#16355 url.h: Fix ABI breakage in extvar_t
  src/include/access/url.h
Labels: version: 7X_ALPHA

#16220 [7X] Abort rebalance if replay lag is big on mirror
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/bin/gppylib/operations/rebalanceSegments.py
  gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py
  gpMgmt/bin/gppylib/test/unit/test_unit_rebalance_segment.py
  gpMgmt/doc/gprecoverseg_help
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpdb-doc/markdown/utility_guide/ref/gprecoverseg.html.md
Labels: version: 7X_ALPHA, gpcm_in

#16340 Corrected comment mistake about `looks_like_temp_rel_name` function.
  src/backend/storage/file/fd.c
Labels: version: 7X_ALPHA, community

#16128 [6X] Fix flacky case 002_archiving.pl
  src/test/recovery/t/002_archiving.pl
Labels: version: 6X_STABLE, community

#16368 Fix flaky test case in create_index
  src/test/regress/expected/polygon.out
  src/test/regress/expected/polygon_optimizer.out
  src/test/regress/sql/polygon.sql
Labels: area: gporca

#16369 Fix gpfdsits old ssl test cases
  src/bin/gpfdist/regress/input/gpfdist_old_ssl.source
  src/bin/gpfdist/regress/output/gpfdist_old_ssl.source
Labels: version: 6X_STABLE

#16307 Archive current timeline history file after recovery finishes if needed
  src/backend/access/transam/xlog.c
  src/test/recovery/t/138_archive_current_timeline_history.pl
Labels: needs: backport

#15976 Fixes self.relation_types assignment without a trailing semicolon
  gpMgmt/bin/gpload.py
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/bin/gppylib/commands/unix.py
  gpMgmt/bin/gppylib/gpparseopts.py
  gpMgmt/bin/gppylib/programs/clsSystemState.py
  gpcontrib/gp_replica_check/gp_replica_check.py
Labels: version: 7X_ALPHA, community

#16342 Correcting derived distribution spec for CPhysicalJoin.
  src/backend/gporca/data/dxl/minidump/JoinOnReplicatedUniversal.mdp
  src/backend/gporca/data/dxl/minidump/SubqueryOuterRefTVF.mdp
  src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/rpt.out
  src/test/regress/expected/rpt_optimizer.out
  src/test/regress/sql/rpt.sql
Labels: area: gporca, version: 7X_ALPHA

#16195 [7X] Fix Differential recovery tablespace issue
  gpMgmt/bin/gppylib/commands/pg.py
  gpMgmt/bin/gppylib/commands/unix.py
  gpMgmt/bin/gppylib/operations/segment_tablespace_locations.py
  gpMgmt/bin/gppylib/operations/test/unit/test_unit_segment_tablespace_locations.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
  gpMgmt/sbin/gpsegrecovery.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/steps/tablespace_mgmt_utils.py
Labels: gpcm_in

#16338 [6X] Disallow non-standalone ALTER distribution
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_distribution_policy.out
  src/test/regress/sql/alter_distribution_policy.sql
Labels: version: 6X_STABLE, backport

#16373 docs - postgres_fdw supports limit pushdown
  gpdb-doc/markdown/ref_guide/modules/postgres_fdw.html.md
Labels: 7X_Docs

#16372 docs - greenplum_fdw works between versions 6 <=> 7
  gpdb-doc/markdown/ref_guide/modules/greenplum_fdw.html.md
Labels: version: 6X_STABLE, 7X_Docs

#16330 Update anti-virus note with non-support notice
  gpdb-doc/markdown/admin_guide/perf_intro.html.md
  gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
  gpdb-doc/markdown/install_guide/prep_os.html.md
Labels: 7X_Docs

#16341 Docs: Document ALTER TABLE REPACK BY COLUMNS
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
Labels: 7X_Docs

#16377 Fix clang-formatting in CPhysicalJoin.cpp and MDP file
  src/backend/gporca/data/dxl/minidump/JoinOnReplicatedUniversal.mdp
  src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
Labels: area: gporca, version: 7X_ALPHA

#16309 [6X backport] Archive current timeline history file after recovery finishes if needed
  src/backend/access/transam/xlog.c
  src/test/recovery/t/138_archive_current_timeline_history.pl
Labels: version: 6X_STABLE

#16299 [6X] Fix segmentation fault during dispatch interrupt
  src/backend/cdb/dispatcher/test/Makefile
  src/backend/cdb/dispatcher/test/cdbdisp_query_test.c
  src/backend/cdb/dispatcher/test/gpsegconfig_dump
  src/interfaces/libpq/fe-connect.c
  src/interfaces/libpq/fe-misc.c
Labels: version: 6X_STABLE, area: dispatch

#16167 gprecoverseg: Fix CI flakiness after #15700
  gpMgmt/sbin/gpsegrecovery.py
  gpMgmt/sbin/recovery_base.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/gprecoverseg_newhost.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
Labels: version: 7X_ALPHA, gpcm_in, flaky test

#16384 [ORCA] Add fallback on relations with 'hnsw' index type
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/gporca/libgpos/include/gpos/string/CWStringBase.h
  src/backend/gporca/libgpos/server/src/unittest/gpos/string/CWStringTest.cpp
  src/backend/gporca/libgpos/src/string/CWStringBase.cpp
  src/backend/gporca/libgpos/src/string/CWStringConst.cpp
Labels: area: gporca, version: 7X_ALPHA

#16358 Formalize assert build high mem alloc protection
  src/backend/utils/misc/guc_gp.c
  src/backend/utils/mmgr/memprot.c
  src/backend/utils/mmgr/test/memprot_test.c
  src/include/utils/gp_alloc.h
  src/include/utils/sync_guc_name.h
Labels: type: dev environment improvement, version: 7X_ALPHA

#16357 Bring work_mem out of deprecation
  src/backend/utils/misc/guc.c
  src/pl/plpgsql/src/expected/plpgsql_transaction.out
  src/test/regress/expected/aggregates.out
  src/test/regress/expected/aggregates_optimizer.out
  src/test/regress/expected/bitmapops.out
  src/test/regress/expected/bitmapops_optimizer.out
  src/test/regress/expected/groupingsets.out
  src/test/regress/expected/groupingsets_optimizer.out
  src/test/regress/expected/guc.out
  src/test/regress/expected/guc_gp.out
  src/test/regress/expected/join.out
  src/test/regress/expected/join_hash.out
  src/test/regress/expected/join_hash_optimizer.out
  src/test/regress/expected/join_optimizer.out
  src/test/regress/expected/rangefuncs.out
  src/test/regress/expected/rangefuncs_optimizer.out
  src/test/regress/expected/select_distinct.out
  src/test/regress/expected/select_distinct_optimizer.out
  src/test/regress/expected/select_parallel.out
  src/test/regress/expected/select_parallel_optimizer.out
  src/test/regress/output/aocs.source
  src/test/regress/output/appendonly.source
Labels: version: 7X_ALPHA

#16391 ci: Fix unit test failure in without_asserts build
  src/backend/utils/mmgr/test/memprot_test.c
Labels: version: 7X_ALPHA, area:ci

#16379 Remove check restricting some array casts by orca
  src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca

#16190 Introduce Non-Replicated Distribution Spec
  contrib/postgres_fdw/expected/gp_postgres_fdw_optimizer.out
  src/backend/gporca/data/dxl/minidump/AddRedistributeBeforeInsert-4.mdp
  src/backend/gporca/data/dxl/minidump/BTreeIndex-Against-ScalarSubquery.mdp
  src/backend/gporca/data/dxl/minidump/CTAS-With-Global-Local-Agg.mdp
  src/backend/gporca/data/dxl/minidump/CTEWithMergedGroup.mdp
  src/backend/gporca/data/dxl/minidump/ConstTblGetUnderSubqWithNoOuterRef.mdp
  src/backend/gporca/data/dxl/minidump/DML-With-HJ-And-UniversalChild.mdp
  src/backend/gporca/data/dxl/minidump/DontAddRedistributeBeforeInsert-1.mdp
  src/backend/gporca/data/dxl/minidump/ForeignPartOneTimeFilterDPE.mdp
  src/backend/gporca/data/dxl/minidump/ForeignScanExecLocAnyJoin.mdp
  src/backend/gporca/data/dxl/minidump/Index-Join-With-Subquery-In-Pred.mdp
  src/backend/gporca/data/dxl/minidump/IndexApply-Redistribute-Const-Table.mdp
  src/backend/gporca/data/dxl/minidump/Join_OuterChild_DistUniversal.mdp
  src/backend/gporca/data/dxl/minidump/LOJ-DynBtreeIndexWithSelect.mdp
  src/backend/gporca/data/dxl/minidump/ManyTextUnionsInSubquery.mdp
  src/backend/gporca/data/dxl/minidump/NLJ-Rewindability-CTAS.mdp
  src/backend/gporca/data/dxl/minidump/NoBroadcastUnderGatherForWindowFunction.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-MultiWayJoinWithDPE-2.mdp
  src/backend/gporca/data/dxl/minidump/PushGbBelowJoin-NegativeCase.mdp
  src/backend/gporca/data/dxl/minidump/SqlFuncDmlTvf.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpec.h
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecNonReplicated.h
  src/backend/gporca/libgpopt/src/base/CDistributionSpecHashed.cpp
  src/backend/gporca/libgpopt/src/base/CDistributionSpecRandom.cpp
  src/backend/gporca/libgpopt/src/base/CDistributionSpecReplicated.cpp
  src/backend/gporca/libgpopt/src/base/CDistributionSpecSingleton.cpp
  src/backend/gporca/libgpopt/src/base/CDistributionSpecStrictRandom.cpp
  src/backend/gporca/libgpopt/src/base/CDistributionSpecStrictSingleton.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalHashJoin.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalInnerNLJoin.cpp
  src/test/regress/expected/bfv_planner_optimizer.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/join_optimizer.out
  src/test/regress/expected/misc_functions_optimizer.out
  src/test/regress/expected/partition_prune_optimizer.out
  src/test/regress/expected/qp_correlated_query_optimizer.out
  src/test/regress/expected/qp_join_universal.out
  src/test/regress/expected/qp_join_universal_optimizer.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/expected/tsrf_optimizer.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/qp_join_universal.sql
Labels: area: gporca, version: 7X_ALPHA

#16332 Optimize string creation in Orca
  src/backend/gporca/libgpos/include/gpos/string/CStringStatic.h
  src/backend/gporca/libgpos/include/gpos/string/CWStringBase.h
  src/backend/gporca/libgpos/include/gpos/string/CWStringConst.h
  src/backend/gporca/libgpos/server/src/unittest/gpos/string/CWStringTest.cpp
  src/backend/gporca/libgpos/src/string/CWStringConst.cpp
  src/backend/gporca/libnaucrates/src/CDXLUtils.cpp
Labels: area: gporca, version: 7X_ALPHA

#16403 Fix the failure of src/backend/cdb/dispatcher/test/cdbdisp_query_test.c
  src/backend/cdb/dispatcher/test/Makefile
Labels: version: 6X_STABLE, test

#16404 Revert "Fix segmentation fault during dispatch interrupt (#16299)"
  src/backend/cdb/dispatcher/test/Makefile
  src/backend/cdb/dispatcher/test/cdbdisp_query_test.c
  src/backend/cdb/dispatcher/test/gpsegconfig_dump
  src/interfaces/libpq/fe-connect.c
  src/interfaces/libpq/fe-misc.c
Labels: version: 6X_STABLE

#16416 docs - add non-supported note about ALTER SYSTEM
  gpdb-doc/markdown/ref_guide/config_params/guc_config.html.md
Labels: 7X_Docs

#16339 Optimize serialization of IMDId objects in Orca to be lazy
  src/backend/gporca/libnaucrates/include/naucrates/md/CMDIdCast.h
  src/backend/gporca/libnaucrates/include/naucrates/md/CMDIdColStats.h
  src/backend/gporca/libnaucrates/include/naucrates/md/CMDIdGPDB.h
  src/backend/gporca/libnaucrates/include/naucrates/md/CMDIdRelStats.h
  src/backend/gporca/libnaucrates/include/naucrates/md/CMDIdScCmp.h
  src/backend/gporca/libnaucrates/src/md/CMDIdCast.cpp
  src/backend/gporca/libnaucrates/src/md/CMDIdColStats.cpp
  src/backend/gporca/libnaucrates/src/md/CMDIdGPDB.cpp
  src/backend/gporca/libnaucrates/src/md/CMDIdGPDBCtas.cpp
  src/backend/gporca/libnaucrates/src/md/CMDIdRelStats.cpp
  src/backend/gporca/libnaucrates/src/md/CMDIdScCmp.cpp
Labels: area: gporca, version: 7X_ALPHA

#16410 [7x]: Analyzedb add materialized views to list of tables to be analyzed
  gpMgmt/bin/analyzedb
  gpMgmt/test/behave/mgmt_utils/analyzedb.feature
  gpMgmt/test/behave/mgmt_utils/steps/analyzedb_mgmt_utils.py
Labels: area: gporca, version: 7X_ALPHA, community

#16426 [Releng][6X] Fix wrong var name for resource reduced-frequency-trigger
  concourse/pipelines/gpdb_6X_STABLE-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: cla-not-required

#16427 docs - open parallel retrieve cursor for current user (6x)
  gpdb-doc/markdown/ref_guide/modules/gp_parallel_retrieve_cursor.html.md
Labels: cla-not-required

#16271 docs - update SELECT, SELECT INTO sql ref pages
  gpdb-doc/markdown/ref_guide/sql_commands/SELECT.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/SELECT_INTO.html.md
Labels: 7X_Docs

#16405 ao/co IndexOnlyScan: Use the last cached minipage
  src/backend/access/appendonly/README.md
  src/backend/access/appendonly/appendonlyblockdirectory.c
Labels: version: 7X_ALPHA, area: aoco

#16419 ao/co: Update cost model for Index Only Scans
  src/backend/optimizer/path/costsize.c
  src/test/isolation2/input/uao/index_only_scan.source
  src/test/isolation2/output/uao/index_only_scan.source
  src/test/isolation2/output/uao/snapshot_index_corruption.source
  src/test/regress/expected/bfv_index.out
  src/test/regress/expected/bfv_index_optimizer.out
  src/test/regress/expected/qp_indexscan.out
  src/test/regress/expected/qp_indexscan_optimizer.out
  src/test/regress/input/uao_dml/ao_covering_index.source
  src/test/regress/output/uao_dml/ao_covering_index.source
  src/test/regress/output/uao_dml/ao_covering_index_optimizer.source
  src/test/regress/sql/bfv_index.sql
  src/test/regress/sql/qp_indexscan.sql
Labels: topic: planner, version: 7X_ALPHA, area: aoco

#16207 Fix the wrong permissions warning on the pgpass file
  gpMgmt/bin/gppylib/db/dbconn.py
  gpMgmt/test/behave/mgmt_utils/gpstart.feature
  gpMgmt/test/behave/mgmt_utils/steps/gpstart.py
Labels: 7X_beta_testing

#16392 [7X] Refactoring. Declare methods as static if they work with static member variables only
  src/backend/gporca/libgpopt/src/base/CColumnFactory.cpp
  src/backend/gporca/libgpopt/src/init.cpp
  src/backend/gporca/libgpopt/src/search/CSchedulerContext.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformFactory.cpp
  src/backend/gporca/libgpos/include/gpos/common/DbgPrintMixin.h
  src/backend/gporca/libgpos/include/gpos/error/CMessageRepository.h
  src/backend/gporca/libgpos/include/gpos/memory/CCache.h
  src/backend/gporca/libgpos/include/gpos/memory/CCacheAccessor.h
  src/backend/gporca/libgpos/include/gpos/memory/CCacheFactory.h
  src/backend/gporca/libgpos/include/gpos/memory/CMemoryPoolManager.h
  src/backend/gporca/libgpos/src/_api.cpp
  src/backend/gporca/libgpos/src/common/CDebugCounter.cpp
  src/backend/gporca/libgpos/src/error/CMessageRepository.cpp
  src/backend/gporca/libgpos/src/memory/CAutoMemoryPool.cpp
  src/backend/gporca/libgpos/src/memory/CCacheFactory.cpp
  src/backend/gporca/libgpos/src/memory/CMemoryPoolManager.cpp
  src/backend/gporca/libgpos/src/task/CTask.cpp
  src/backend/gporca/libgpos/src/task/CWorkerPoolManager.cpp
  src/backend/gporca/libnaucrates/src/init.cpp
  src/backend/gporca/server/src/unittest/CTestUtils.cpp
Labels: area: gporca, version: 7X_ALPHA, community

#16424 docs - queries on hnsw indexes fall back to planner
  gpdb-doc/markdown/ref_guide/modules/pgvector/pgvector.html.md
Labels: 7X_Docs, cla-not-required

#16256 docs - add reference info for some wal gucs
  gpdb-doc/markdown/install_guide/capacity_planning.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_config.html.md
Labels: 7X_Docs

#16236 Docs: updated the content of Managing Roles and Privileges page
  gpdb-doc/markdown/admin_guide/roles_privs.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
Labels: 7X_Docs

#16436 DOCS: Document pg_sequence catalog table
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-tables.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_sequence.html.md
Labels: cla-not-required

#16425 docs - gporca supports indexonlyscan on gist for some ops
  gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-limitations.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
Labels: 7X_Docs, cla-not-required

#16376 Fix "cache lookup failed for foreign table" ERROR when ORCA handles multi-level partition table with foreign tables.
  contrib/postgres_fdw/expected/gp_postgres_fdw.out
  contrib/postgres_fdw/expected/gp_postgres_fdw_optimizer.out
  contrib/postgres_fdw/sql/gp_postgres_fdw.sql
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
Labels: area: gporca, version: 7X_ALPHA, community, status: fully approved

#16390 Docs: modified the default value of guc gp_autostats_mode
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
Labels: 7X_Docs

#16453 Docs: add deprecation notice for gpreload
  gpdb-doc/markdown/utility_guide/ref/gpreload.html.md
Labels: 7X_Docs, cla-not-required

#16450 [6X Backport] - Analyzedb add materialized views to list of tables to be analyzed
  gpMgmt/bin/analyzedb
  gpMgmt/test/behave/mgmt_utils/analyzedb.feature
  gpMgmt/test/behave/mgmt_utils/steps/analyzedb_mgmt_utils.py
Labels: area: gporca, version: 6X_STABLE, community

#16382 docs - use resource groups to limit greenplum_fdw concurrency
  gpdb-doc/markdown/ref_guide/modules/greenplum_fdw.html.md
Labels: 7X_Docs

#16337 docs - update madlib docs for version 2.0.0 for gp7
  gpdb-doc/markdown/analytics/madlib.html.md
  gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
Labels: 7X_Docs

#16202 DOCS: Document new option for specifying the directory to which gppkg writes temporary files
  gpdb-doc/markdown/utility_guide/ref/gppkg.html.md
Labels: 7X_Docs

#16457 Fix the use of PORTNAME in gp_toolkit makefile
  gpcontrib/gp_toolkit/Makefile
Labels: cla-not-required

#16459 io limit: fix double free
  src/backend/commands/resgroupcmds.c
  src/test/isolation2/input/resgroup/resgroup_io_limit.source
  src/test/isolation2/output/resgroup/resgroup_io_limit.source
Labels: cla-not-required

#16451 Fix bug: copy to a replicated table from an empty file (7X)
  src/backend/cdb/cdbcopy.c
  src/test/regress/data/empty.data
  src/test/regress/input/gpcopy.source
  src/test/regress/output/gpcopy.source
Labels: cla-not-required

#16433 [7X]Fix utilities does not honor -d flag when COORDINATOR_DATA_DIRECTORY is not set.
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/bin/gppylib/mainUtils.py
  gpMgmt/bin/gppylib/system/environment.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/gpstart.feature
  gpMgmt/test/behave/mgmt_utils/gpstate.feature
  gpMgmt/test/behave/mgmt_utils/gpstop.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in

#16423 Fix derived distribution spec for CPhysicalJoin
  src/backend/gporca/data/dxl/minidump/JoinOnReplicatedUniversal.mdp
  src/backend/gporca/data/dxl/minidump/SubqueryOuterRefTVF.mdp
  src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/rpt.out
  src/test/regress/expected/rpt_optimizer.out
  src/test/regress/sql/rpt.sql
Labels: area: gporca, version: 6X_STABLE, status: merge window, cla-not-required, status: fully approved

#16463 Fix flaky test alter_distribution_policy
  src/test/regress/expected/alter_distribution_policy.out
  src/test/regress/sql/alter_distribution_policy.sql
Labels: version: 7X_ALPHA, flaky test, cla-not-required

#16452 Docs: new two gucs for timestamp9 module
  gpdb-doc/markdown/ref_guide/modules/timestamp9.html.md
Labels: 7X_Docs, cla-not-required

#16464 Fix explain pipeline performance summary script bugs
  concourse/scripts/perfsummary.py
Labels: area: gporca, version: 7X_ALPHA, cla-not-required

#16468 Fix flaky test gp_tablespace_with_faults
  src/test/regress/input/gp_tablespace_with_faults.source
  src/test/regress/output/gp_tablespace_with_faults.source
Labels: flaky test, 7X_beta_testing, cla-not-required

#16470 DOCS: GPCC not yet supported for gpsupport gp_log_collector
  gpdb-doc/markdown/utility_guide/ref/gpsupport-gp_log_collector.html.md
Labels: cla-not-required

#16469 Fix a flakiness with test gp_check_files
  src/test/regress/input/gp_check_files.source
  src/test/regress/output/gp_check_files.source
Labels: flaky test, 7X_beta_testing, cla-not-required

#16471 Due to IC failures, rever this fix
  src/backend/cdb/motion/ic_udpifc.c
Labels: cla-not-required

#16279 Fix ORCA invalid processing of nested SubLinks referenced in GROUP BY clause
  src/backend/gpopt/translate/CQueryMutators.cpp
  src/test/regress/expected/subselect.out
  src/test/regress/expected/subselect_optimizer.out
  src/test/regress/sql/subselect.sql
Labels: area: gporca, version: 7X_ALPHA, community, status: fully approved

#16445 Fix flaky basebackup tap test that relied on pg_current_wal_lsn
  src/bin/pg_basebackup/t/010_pg_basebackup.pl
Labels: cla-not-required

#16475 [DOC] R is not a mandatory dependency
  gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
Labels: 7X_Docs, cla-not-required

#16472 Added Documentation gpcheckperf option for GP 7.0
  gpdb-doc/markdown/utility_guide/ref/gpcheckperf.html.md
Labels: 7X_Docs, cla-not-required

#16328 Fix ORCA invalid processing of nested SubLinks under aggregates.
  src/backend/gpopt/translate/CQueryMutators.cpp
  src/test/regress/expected/aggregates_optimizer.out
  src/test/regress/expected/select_parallel_optimizer.out
  src/test/regress/expected/subselect.out
  src/test/regress/expected/subselect_optimizer.out
  src/test/regress/sql/subselect.sql
Labels: area: gporca, version: 7X_ALPHA, community, status: fully approved

#16484 [Releng][7X]Change tanzunet concourse resource
  concourse/pipelines/gen_pipeline.py
  concourse/pipelines/gpdb_main-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: cla-not-required

#16465 fix REFRESH MATERIALIZED VIEW on AO table with index
  src/backend/commands/matview.c
  src/test/regress/expected/matview.out
  src/test/regress/expected/matview_optimizer.out
  src/test/regress/sql/matview.sql
Labels: cla-not-required

#16329 [7x]gprecoverseg: Raise exception when -F option is used in rebalance and recovery to new host options
  gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
Labels: gpcm_in

#16400 Docs resgroups new
  gpdb-doc/markdown/admin_guide/about-resgroups-changes.html.md
Labels: 7X_Docs

#16476 Disable autovacuum for flaky test gp_check_files
  src/test/regress/greenplum_schedule
Labels: flaky test, 7X_beta_testing, cla-not-required

#16467 Docs: add configuration parameter work_mem
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
Labels: 7X_Docs, cla-not-required

#16474 Docs llvm
  gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
Labels: 7X_Docs, cla-not-required

#16389 [6x]: Fix gpcheckperf discrepancy in network test results (v6.23 vs v6.25)
  gpMgmt/bin/gpcheckperf
  gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckperf.py
  gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: version: 6X_STABLE, gpcm_in

#16478 [6X backport]Fix utilities do not honor -d flag when MASTER_DATA_DIRECTORY is not set (#16433)
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/bin/gppylib/mainUtils.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/gpstart.feature
  gpMgmt/test/behave/mgmt_utils/gpstate.feature
  gpMgmt/test/behave/mgmt_utils/gpstop.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in, cla-not-required

#16485 [6X] fix REFRESH MATERIALIZED VIEW on AO table with index
  src/backend/commands/matview.c
  src/test/regress/expected/matview.out
  src/test/regress/expected/matview_optimizer.out
  src/test/regress/sql/matview.sql
Labels: cla-not-required

#16444 gpexpand: Fix error when database has tablespaces
  gpMgmt/bin/gpexpand
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: topic: gpexpand, version: 7X_ALPHA, gpcm_in

#16449 [7X] gpconfig does not escape '$' char
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gpconfig.py
  gpMgmt/sbin/gpconfig_helper.py
  gpMgmt/test/behave/mgmt_utils/gpconfig.feature
Labels: gpcm_in, cla-not-required

#16490 Remove resource groups support for pl/container
  gpdb-doc/markdown/analytics/pl_container_using.html.md
Labels: 7X_Docs, cla-not-required

#16489 Update gpdb pgvector docs for new 0.5 featurtes
  gpdb-doc/markdown/ref_guide/modules/pgvector/pgvector.html.md
Labels: 7X_Docs, cla-not-required

#16488 Add new python data science packages for GP7
  gpdb-doc/markdown/install_guide/install_python_dsmod.html.md
Labels: 7X_Docs, cla-not-required

#16491 Add GUC optimizer_enable_orderedagg to enable/disable ordered aggregates
  src/backend/gpopt/config/CConfigParamMapping.cpp
  src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
  src/backend/gporca/libnaucrates/include/naucrates/traceflags/traceflags.h
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/include/utils/unsync_guc_name.h
  src/test/regress/expected/qp_orca_fallback.out
  src/test/regress/expected/qp_orca_fallback_optimizer.out
  src/test/regress/sql/qp_orca_fallback.sql
Labels: area: gporca, version: 7X_ALPHA, cla-not-required, status: fully approved

#16483 DOCS: Document new PostgresML extension for AI/machine learning in GPDB database.
  gpdb-doc/markdown/ref_guide/modules/intro.html.md
  gpdb-doc/markdown/ref_guide/modules/postgresml.html.md
Labels: cla-not-required

#16486 Fix orphaned temp namespace catalog entry left on coordinator
  src/backend/catalog/namespace.c
  src/backend/cdb/dispatcher/cdbgang.c
  src/backend/cdb/dispatcher/test/cdbgang_test.c
  src/include/catalog/namespace.h
  src/test/isolation2/expected/orphan_temp_table.out
  src/test/isolation2/sql/orphan_temp_table.sql
Labels: version: 7X_ALPHA, community

#16455 DOCS: All new/changed topics pertaining to moving from GPDB6 to GPDB7
  gpdb-doc/markdown/admin_guide/managing/gpcopy-migrate.html.md
  gpdb-doc/markdown/install_guide/changes-6-7-landing-page.html.md
  gpdb-doc/markdown/install_guide/install_guide.html.md
  gpdb-doc/markdown/install_guide/upgrade_intro.html.md
  gpdb-doc/markdown/install_guide/upgrading.html.md
  gpdb-doc/markdown/install_guide/upgrading_6_to_7.html.md
  gpdb-doc/markdown/ref_guide/guc-changes-6to7.html.md.erb
  gpdb-doc/markdown/ref_guide/removed-features-objects.html.md
  gpdb-doc/markdown/ref_guide/system-changes-6to7.html.md.erb
Labels: 7X_Docs, cla-not-required

#16321 Docs: resource group modifications
  gpdb-doc/markdown/admin_guide/wlmgmt.html.md
  gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
Labels: 7X_Docs

#16317 Docs: added -k option for gpfdist
  gpdb-doc/markdown/utility_guide/ref/gpfdist.html.md
Labels: 7X_Docs

#16515 Docs: updated the Software Dependencies page for 6
  gpdb-doc/markdown/install_guide/platform-requirements-overview.md.hbs
Labels: cla-not-required

#16514 Docs: updated Software Dependencies for GP 7
  gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
Labels: 7X_Docs, cla-not-required

#16517 DOCS: Rework task steps in upgrading 6 => 7 procedural topic
  gpdb-doc/markdown/install_guide/upgrading_6_to_7.html.md
Labels: cla-not-required

#16520 docs - remove some extra the s
  gpdb-doc/markdown/admin_guide/parallel_retrieve_cursor.html.md
  gpdb-doc/markdown/admin_guide/textsearch/controlling.html.md
  gpdb-doc/markdown/ref_guide/modules/diskquota.html.md
  gpdb-doc/markdown/ref_guide/modules/greenplum_fdw.html.md
  gpdb-doc/markdown/ref_guide/modules/postgresml.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
Labels: 7X_Docs, cla-not-required

#16487 Compute statistics for a column of table
  src/backend/gporca/data/dxl/minidump/AssertMaxOneRow.mdp
  src/backend/gporca/data/dxl/minidump/CoveringIndex-1.mdp
  src/backend/gporca/data/dxl/minidump/CoveringIndex-2.mdp
  src/backend/gporca/data/dxl/minidump/DynamicIndexOnlyScan-InnerJoin.mdp
  src/backend/gporca/data/dxl/minidump/DynamicIndexOnlyScan-LeftJoin.mdp
  src/backend/gporca/data/dxl/minidump/DynamicIndexOnlyScanCosting.mdp
  src/backend/gporca/data/dxl/minidump/IndexNLJ-IndexGet-OuterRef.mdp
  src/backend/gporca/data/dxl/minidump/IndexOnLeaf-NonOverlappingHeterogenousIndex-ANDPredicate-HEAP.mdp
  src/backend/gporca/data/dxl/minidump/IndexOnlyScanCosting.mdp
  src/backend/gporca/data/dxl/minidump/LogicalIndexGetDroppedCols.mdp
  src/backend/gporca/data/dxl/minidump/OverlappingHomogenousIndexesOnRoot-HEAP.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-DPE-DynamicIndexOnlyScan-Range.mdp
  src/backend/gporca/data/dxl/minidump/UnnestSQJoins.mdp
  src/backend/gporca/libgpdbcost/include/gpdbcost/CCostModelGPDB.h
  src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatistics.h
  src/backend/gporca/libnaucrates/include/naucrates/statistics/IStatistics.h
  src/backend/gporca/libnaucrates/src/statistics/CStatistics.cpp
  src/test/regress/expected/dpe.out
  src/test/regress/expected/dpe_optimizer.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/sql/dpe.sql
Labels: area: gporca, version: 7X_ALPHA, cla-not-required, status: fully approved

#16522 ao/co: Consider all blocks as all-visible in ORCA
  src/backend/gporca/data/dxl/minidump/AllowIndexOnlyScanOnAppendOnlyTable.mdp
  src/backend/gporca/data/dxl/minidump/BTreeIndex-Against-InListLarge.mdp
  src/backend/gporca/data/dxl/minidump/DoubleNDVCardinalityEquals.mdp
  src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
Labels: area: gporca, version: 7X_ALPHA, area: aoco, cla-not-required

#16501 [ORCA] Fix unused nested CTE pruning
  src/backend/gporca/data/dxl/minidump/CTE-NestedWithPrunedProducer.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CCTEInfo.h
  src/backend/gporca/libgpopt/src/base/CCTEInfo.cpp
  src/backend/gporca/libgpopt/src/base/CQueryContext.cpp
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CCTETest.cpp
  src/test/regress/expected/qp_with_clause.out
  src/test/regress/expected/qp_with_clause_optimizer.out
  src/test/regress/sql/qp_with_clause.sql
Labels: area: gporca, version: 7X_ALPHA, needs: backport, cla-not-required, status: fully approved

#16479 Hash subplans in Orca plans when possible
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
  src/backend/optimizer/plan/subselect.c
  src/include/gpopt/gpdbwrappers.h
  src/include/optimizer/subselect.h
  src/test/regress/expected/qp_subquery.out
  src/test/regress/expected/qp_subquery_optimizer.out
  src/test/regress/sql/qp_subquery.sql
Labels: area: gporca, version: 7X_ALPHA, cla-not-required, status: fully approved

#16527 DOCS: Correct JDBC version numbers and remove two unnecessary notes in platform requirements overview
  gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
Labels: cla-not-required

#16511 print log message with write_stderr when reach vmem or resgroup limit
  src/backend/utils/mmgr/memprot.c
Labels: cla-not-required

#16528 Update docs to reference the correct extension name for PostgresML
  gpdb-doc/markdown/ref_guide/modules/postgresml.html.md
Labels: cla-not-required

#16503 Add testcase for fixed issue of panic in ORCA
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/sql/subselect_gp.sql
Labels: area: gporca, version: 7X_ALPHA, cla-not-required, status: fully approved

#16505 Change copyright of minirepro and gpsd
  gpMgmt/bin/gpsd
  gpMgmt/bin/minirepro
Labels: area: gporca, version: 7X_ALPHA, cla-not-required, status: fully approved
