Repository greenplum-db/gpdb, pull requests merged in 2023-02, with the labels that each got.

#14226 docs - update sql ref pages for ALTER/CREATE/DROP DOMAIN
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_DOMAIN.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_DOMAIN.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_DOMAIN.html.md
Labels: 7X_Docs

#14621 docs - ALTER/CREATE/DROP SEQUENCE sql ref page updates
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_SEQUENCE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_SEQUENCE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_SEQUENCE.html.md
Labels: 7X_Docs

#14227 docs - update sql ref pages for ALTER/CREATE/DROP AGGREGATE
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_AGGREGATE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_AGGREGATE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_AGGREGATE.html.md
Labels: area: server, 7X_Docs

#14433 docs - update sql ref pages for ALTER/CREATE/DROP OPERATOR, OPERATOR CLASS, OPERATOR FAMILY
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_OPERATOR.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_OPERATOR_CLASS.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_OPERATOR_FAMILY.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_OPERATOR.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_OPERATOR_CLASS.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_OPERATOR_FAMILY.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_OPERATOR.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_OPERATOR_CLASS.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_OPERATOR_FAMILY.html.md
Labels: 7X_Docs

#14231 docs - sql ref page updates for COLLATION/CONVERSION commands
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_COLLATION.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_CONVERSION.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_COLLATION.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_CONVERSION.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_COLLATION.html.md
Labels: area: server, 7X_Docs

#14805 docs - new sql ref pages for CREATE/DROP ACCESS METHOD
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_ACCESS_METHOD.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_ACCESS_METHOD.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/sql_ref.html.md
  gpdb-doc/markdown/ref_guide/toc.md
Labels: 7X_Docs

#14388 docs - update sql ref pages for ALTER/CREATE/DROP USER MAPPING
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_USER_MAPPING.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_USER_MAPPING.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_USER_MAPPING.html.md
Labels: area: server, 7X_Docs

#14269 docs - update sql ref pages for ALTER/CREATE/DROP FDW, FOREIGN TABLE; IMPORT FOREIGN SCHEMA
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_FOREIGN_DATA_WRAPPER.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_FOREIGN_TABLE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_FOREIGN_DATA_WRAPPER.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_FOREIGN_TABLE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_FOREIGN_DATA_WRAPPER.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_FOREIGN_TABLE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/IMPORT_FOREIGN_SCHEMA.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/sql_ref.html.md
  gpdb-doc/markdown/ref_guide/toc.md
Labels: area: server, Priority 2, 7X_Docs

#14293 docs - new and updated SQL ref pages for FUNCTION/PROCEDURE/ROUTINE/CALL
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_FUNCTION.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_PROCEDURE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_ROUTINE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CALL.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_FUNCTION.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_PROCEDURE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_FUNCTION.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_PROCEDURE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_ROUTINE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/sql_ref.html.md
  gpdb-doc/markdown/ref_guide/toc.md
Labels: area: server, Priority 2, 7X_Docs

#14761 docs - PUBLICATION, SUBSCRIPTION not supported
  gpdb-doc/markdown/ref_guide/feature_summary.html.md
Labels: 7X_Docs

#14430 docs - update sql ref pages for ALTER/CREATE/DROP INDEX, REINDEX; rei…
  gpdb-doc/markdown/admin_guide/ddl/ddl-index.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_INDEX.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_INDEX.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_INDEX.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/REINDEX.html.md
  gpdb-doc/markdown/utility_guide/ref/reindexdb.html.md
Labels: 7X_Docs

#14766 docs - sql ref page updates for DEALLOCATE/EXECUTE/PREPARE
  gpdb-doc/markdown/ref_guide/sql_commands/DEALLOCATE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/EXECUTE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/PREPARE.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-html.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_prepared_statements.html.md
  gpdb-doc/markdown/ref_guide/toc.md
Labels: 7X_Docs

#14842 Vacuum enhancements
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ANALYZE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/VACUUM.html.md
  gpdb-doc/markdown/utility_guide/ref/analyzedb.html.md
  gpdb-doc/markdown/utility_guide/ref/vacuumdb.html.md
Labels: 7X_Docs

#14888 Docs pg appendonly changes
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_appendonly.html.md
Labels: 7X_Docs

#14830 docs - misc updates/additions related to stored procedures
  gpdb-doc/markdown/admin_guide/query/topics/functions-operators.html.md
  gpdb-doc/markdown/analytics/pl_perl.html.md
  gpdb-doc/markdown/analytics/pl_python.html.md
  gpdb-doc/markdown/analytics/pl_sql.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_proc.html.md
Labels: 7X_Docs

#14829 docs - ALTER TABLE SET DISTRIBUTED for external tables
  gpdb-doc/markdown/admin_guide/external/g-example-8-writable-external-table-with-gpfdist.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_EXTERNAL_TABLE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
Labels: 7X_Docs

#14181 Fix error out when partitioned children has different am with parent.
  src/backend/commands/tablecmds.c
  src/test/regress/expected/partition_storage.out
  src/test/regress/sql/partition_storage.sql
Labels: area: server

#14867 gpinitsystem: Fix bug when calling ss remotely
  gpMgmt/bin/lib/gp_bash_functions.sh
Labels: type: bug, version: 7X_ALPHA, gpcm_in

#14163 Add assert to the length of shared hash table name
  src/backend/storage/ipc/shmem.c
Labels: area: server, version: 7X_ALPHA

#14898 Fall back in Orca for queries with RTE of type TableFunc
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/test/regress/expected/qp_orca_fallback.out
  src/test/regress/expected/qp_orca_fallback_optimizer.out
  src/test/regress/sql/qp_orca_fallback.sql
Labels: area: gporca, version: 7X_ALPHA

#14909 (6X backport) Fix inFunction for auto_stats in CTAS, COPY and AlterTable.
  src/backend/commands/copy.c
  src/backend/commands/createas.c
  src/backend/commands/tablecmds.c
  src/backend/executor/execMain.c
  src/include/executor/executor.h
  src/test/regress/expected/autostats.out
  src/test/regress/sql/autostats.sql
Labels: version: 6X_STABLE, backport

#14781 (6X_STABLE)Fix bug about functional dependency on primary key of group by clause
  src/backend/cdb/cdbgroup.c
  src/test/regress/expected/functional_deps.out
  src/test/regress/sql/functional_deps.sql
Labels: area: server, version: 6X_STABLE

#14535 Incorrect result for query on date and timestamp predicate in partition table scenario
  src/backend/cdb/cdbpartition.c
  src/test/regress/expected/partition.out
  src/test/regress/expected/partition_optimizer.out
  src/test/regress/sql/partition.sql
Labels: area: gporca, version: 6X_STABLE, status: merge window

#14877 Fix inFunction for auto_stats in CTAS, COPY and AlterTable.
  src/backend/commands/copy.c
  src/backend/commands/createas.c
  src/backend/commands/tablecmds.c
  src/backend/executor/execMain.c
  src/backend/tcop/utility.c
  src/include/executor/executor.h
  src/include/tcop/utility.h
  src/test/regress/expected/autostats.out
  src/test/regress/sql/autostats.sql
Labels: needs: backport

#14802 docs - sql ref page updates for DROP/REASSIGN OWNED
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_OWNED.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/REASSIGN_OWNED.html.md
Labels: 7X_Docs

#14378 docs - update sql ref pages for ALTER/CREATE/DROP/REFRESH MATERIALIZE…
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_MATERIALIZED_VIEW.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_MATERIALIZED_VIEW.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_MATERIALIZED_VIEW.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/REFRESH_MATERIALIZED_VIEW.html.md
Labels: area: server, 7X_Docs

#14815 [6X_STABLE] Set replication slot's restart_lsn to not greater than redo location
  src/backend/access/transam/xlog.c
  src/backend/replication/walsender.c
  src/include/replication/slot.h
  src/test/isolation2/expected/pg_rewind_fail_missing_xlog.out
  src/test/isolation2/helpers/server_helpers.sql
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/pg_rewind_fail_missing_xlog.sql
Labels: type: bug, area: server, version: 6X_STABLE, backport, area: wal

#14919 Remove unused mdpart_constraint from indexes in Orca
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/gporca/data/dxl/minidump/IndexOnLeaf-NonOverlappingHeterogenousIndex-ANDPredicate-AO.mdp
  src/backend/gporca/data/dxl/minidump/IndexOnLeaf-OverlappingHeterogenousIndex-ANDPredicate-AO.mdp
  src/backend/gporca/data/dxl/minidump/IndexOnLeaf-OverlappingHeterogenousIndex-ORPredicate-AO.mdp
  src/backend/gporca/data/dxl/minidump/IndexOnLeaf-SingleColumnHeterogenousIndexOnRoot-2-AO.mdp
  src/backend/gporca/data/dxl/parse_tests/q26-Metadata.xml
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerMDIndex.h
  src/backend/gporca/libnaucrates/include/naucrates/md/CMDIndexGPDB.h
  src/backend/gporca/libnaucrates/include/naucrates/md/IMDIndex.h
  src/backend/gporca/libnaucrates/src/md/CMDIndexGPDB.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerMDIndex.cpp
Labels: area: gporca, version: 7X_ALPHA

#14875 Fix minirepro utility to create view dependencies for explain queries
  src/backend/utils/adt/gp_dump_oids.c
  src/test/regress/expected/gp_dump_query_oids.out
  src/test/regress/sql/gp_dump_query_oids.sql
Labels: area: gporca, version: 6X_STABLE

#14916 [FIXME] Wrong results on main branch for INDF query
  src/backend/executor/nodeHash.c
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/expected/groupingsets.out
  src/test/regress/expected/groupingsets_optimizer.out
  src/test/regress/expected/select_distinct.out
  src/test/regress/expected/select_distinct_optimizer.out
  src/test/regress/sql/groupingsets.sql
  src/test/regress/sql/select_distinct.sql
Labels: area: gporca, version: 7X_ALPHA

#14931 Disable drop resource group `system_group`.
  src/backend/commands/resgroupcmds.c
  src/test/isolation2/expected/resgroup/resgroup_syntax.out
  src/test/isolation2/sql/resgroup/resgroup_syntax.sql
Labels: version: 7X_ALPHA, community

#14800 Reuse the epoll object to fix the dispatcher performance downgrade
  src/backend/cdb/dispatcher/cdbdisp_async.c
  src/backend/cdb/dispatcher/cdbgang.c
  src/backend/cdb/dispatcher/cdbgang_async.c
  src/backend/cdb/motion/ic_udpifc.c
  src/backend/storage/ipc/latch.c
  src/include/cdb/cdbgang.h
  src/include/storage/latch.h
Labels: version: 7X_ALPHA, area: dispatch

#14856 Rename master instances to coordinator
  gpMgmt/bin/gpactivatestandby
  gpMgmt/bin/gpdeletesystem
  gpMgmt/bin/gpmovemirrors
  gpMgmt/bin/gppylib/mainUtils.py
  gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in

#14934 Fix pg_dump compilation for Windows client
  src/bin/pg_dump/pg_dump.c
Labels: version: 6X_STABLE

#14943 Run gp_fastsequence_row|column test sequentially
  src/test/regress/greenplum_schedule
Labels: version: 7X_ALPHA, flaky test

#14942 Fix unused variable compiler warnings
  src/backend/gpopt/relcache/CMDProviderRelcache.cpp
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gpopt/utils/COptTasks.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
  src/include/gpopt/relcache/CMDProviderRelcache.h
Labels: area: gporca, version: 7X_ALPHA

#14863 Docs cgroup version
  gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
Labels: 7X_Docs

#14940 Removed duplicate resource group Oid definitions
  src/backend/commands/resgroupcmds.c
  src/backend/utils/resgroup/cgroup-ops-linux-v1.c
  src/backend/utils/resgroup/cgroup-ops-linux-v2.c
  src/backend/utils/resgroup/resgroup.c
  src/include/catalog/pg_resgroup.dat
  src/include/utils/cgroup.h
Labels: version: 7X_ALPHA, community

#14905 Fix bug that Orca fails to decorrelate subqueries order by outer reference
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/sql/subselect_gp.sql
Labels: area: gporca, version: 7X_ALPHA

#14947 Reformat extended stats build files
  src/backend/Makefile
  src/backend/statistics/.gitignore
  src/backend/statistics/Makefile
  src/backend/statistics/dependencies.c
  src/backend/statistics/statistics_gram.y
  src/backend/statistics/statistics_scanner.l
Labels: area: gporca

#14870 No need pstrdup to initialize the dispatched query string
  src/backend/tcop/postgres.c
Labels: version: 7X_ALPHA

#14872 [ORCA] Allow push down of filter with BETWEEN predicate
  src/backend/gporca/data/dxl/minidump/AnyPredicate-Over-UnionOfConsts.mdp
  src/backend/gporca/data/dxl/minidump/InferPredicatesBCC-oid-oid.mdp
  src/backend/gporca/data/dxl/minidump/InferPredicatesBCC-txt-txt.mdp
  src/backend/gporca/data/dxl/minidump/InferPredicatesBCC-vc-txt.mdp
  src/backend/gporca/data/dxl/minidump/InferPredicatesBCC-vc-vc.mdp
  src/backend/gporca/data/dxl/minidump/InferredPredicatesConstraintSimplification.mdp
  src/backend/gporca/data/dxl/minidump/PushConstantSelectPredicateThruJoin-1.mdp
  src/backend/gporca/data/dxl/minidump/PushConstantSelectPredicateThruJoin-10.mdp
  src/backend/gporca/data/dxl/minidump/PushConstantSelectPredicateThruJoin-2.mdp
  src/backend/gporca/data/dxl/minidump/PushConstantSelectPredicateThruJoin-3.mdp
  src/backend/gporca/data/dxl/minidump/PushConstantSelectPredicateThruJoin-4.mdp
  src/backend/gporca/data/dxl/minidump/PushConstantSelectPredicateThruJoin-5.mdp
  src/backend/gporca/data/dxl/minidump/PushConstantSelectPredicateThruJoin-6.mdp
  src/backend/gporca/data/dxl/minidump/PushConstantSelectPredicateThruJoin-7.mdp
  src/backend/gporca/data/dxl/minidump/PushConstantSelectPredicateThruJoin-8.mdp
  src/backend/gporca/data/dxl/minidump/PushConstantSelectPredicateThruJoin-9.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionPreprocessor.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPredicateUtils.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CScalarIdent.h
  src/backend/gporca/libgpopt/src/base/CConstraintInterval.cpp
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/backend/gporca/server/src/unittest/gpopt/operators/CExpressionPreprocessorTest.cpp
Labels: area: gporca, version: 7X_ALPHA, needs: backport

#14959 Fix value in the cpu_usage column returned from the pg_resgroup_get_status() function
  src/include/catalog/catversion.h
  src/include/catalog/pg_proc.dat
  src/test/isolation2/expected/resgroup/resgroup_functions.out
  src/test/isolation2/sql/resgroup/resgroup_functions.sql
Labels: version: 7X_ALPHA, community

#14725 Support Direct Dispatch for a randomly distributed table, when filtered on gp_segment_id
  src/backend/gporca/data/dxl/minidump/DirectDispatch-RandDistTable-Disjunction.mdp
  src/backend/gporca/data/dxl/minidump/DirectDispatch-RandDistTable.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecRandom.h
  src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorExprToDXLUtils.h
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXLUtils.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CDirectDispatchTest.cpp
  src/test/regress/expected/direct_dispatch.out
  src/test/regress/expected/direct_dispatch_optimizer.out
  src/test/regress/sql/direct_dispatch.sql
Labels: area: gporca, version: 7X_ALPHA

#14958 Orca FIXME: Improve stats calculation during static partition selection
  src/backend/gporca/data/dxl/minidump/CastedScalarIf-On-Index-Key.mdp
  src/backend/gporca/data/dxl/minidump/DPE-SemiJoin.mdp
  src/backend/gporca/data/dxl/minidump/DeleteMismatchedDistribution.mdp
  src/backend/gporca/data/dxl/minidump/DynamicBitmapBoolOp.mdp
  src/backend/gporca/data/dxl/minidump/DynamicBitmapTableScan-Heterogeneous.mdp
  src/backend/gporca/data/dxl/minidump/DynamicBitmapTableScan-UUID.mdp
  src/backend/gporca/data/dxl/minidump/DynamicIndexScan-BoolFalse.mdp
  src/backend/gporca/data/dxl/minidump/DynamicIndexScan-BoolTrue.mdp
  src/backend/gporca/data/dxl/minidump/DynamicIndexScan-Relabel.mdp
  src/backend/gporca/data/dxl/minidump/EffectOfLocalPredOnJoin2.mdp
  src/backend/gporca/data/dxl/minidump/HJN-DPE-Bitmap-Outer-Child.mdp
  src/backend/gporca/data/dxl/minidump/IndexApply-InnerSelect-PartTable2.mdp
  src/backend/gporca/data/dxl/minidump/PartPredsWithRandom.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-CSQ-NonPartKey.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-DPE-GroupBy.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-LASJ.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-MultiWayJoinWithDPE-2.mdp
  src/backend/gporca/data/dxl/minidump/Select-Over-PartTbl.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CReqdPropRelational.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogical.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalSelect.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPredicateUtils.h
  src/backend/gporca/libgpopt/src/base/CReqdPropRelational.cpp
  src/backend/gporca/libgpopt/src/operators/CLogical.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalDynamicGet.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalSelect.cpp
  src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
Labels: area: gporca, version: 7X_ALPHA

#14985 DOCS: Document SKIP LOCKED support for SELECT command
  gpdb-doc/markdown/ref_guide/sql_commands/SELECT.html.md
Labels: 7X_Docs

#14920 Fix bug that Orca fails to decorrelate subqueries order by outer reference
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/sql/subselect_gp.sql
Labels: area: gporca, version: 6X_STABLE

#14926 Add magic number field in the ICProxyPkt
  src/backend/cdb/motion/ic_proxy_backend.c
  src/backend/cdb/motion/ic_proxy_client.c
  src/backend/cdb/motion/ic_proxy_packet.c
  src/backend/cdb/motion/ic_proxy_packet.h
  src/backend/cdb/motion/ic_proxy_peer.c
  src/backend/cdb/motion/ic_proxy_router.c
Labels: version: 7X_ALPHA, needs: backport, area: inter-connect

#14899 Move oid_wraparound to the bottom of the schedule
  src/backend/commands/schemacmds.c
  src/test/regress/expected/pg_stat_last_operation.out
  src/test/regress/sql/pg_stat_last_operation.sql
Labels: needs: backport, flaky test

#14986 Fix incorrect result from hash join on char column
  src/backend/gporca/libgpopt/src/base/CConstraint.cpp
  src/backend/gporca/libgpopt/src/mdcache/CMDAccessorUtils.cpp
  src/test/regress/expected/bfv_joins.out
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/sql/bfv_joins.sql
Labels: area: gporca, version: 7X_ALPHA

#14826 Docs: Just-in-Time (JIT) content for GP 7
  gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
  gpdb-doc/markdown/admin_guide/query/topics/query.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
Labels: 7X_Docs

#15020 Remove merge fixme from transformGpPartitionDefinition()
  src/backend/parser/parse_partition_gp.c
Labels: merge_fixme

#14344 [7X] Skip the foreign key constraint validation.
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_table_gp.out
  src/test/regress/sql/alter_table_gp.sql
Labels: area: server

#15026 Modify 019_replslot_limit.pl test for Greenplum, take 2
  src/test/recovery/t/019_replslot_limit.pl
Labels: area: server

#15007 Fix LWLockHeldByMe assert failure in SharedSnapshotDump
  src/backend/utils/time/sharedsnapshot.c
Labels: version: 7X_ALPHA, community

#15028 Remove a redundant if(info == XLOG_OVERWRITE_CONTRECORD) in xlog.c
  src/backend/access/transam/xlog.c
Labels: version: 7X_ALPHA

#14024 Resolve a FIXME in prepare_AlterTableStmt_for_dispatch()
  src/backend/commands/tablecmds.c
Labels: area: server, version: 7X_ALPHA, merge_fixme

#15045 Make LOG "autovacuum: processing database..." to be DEBUG1
  src/backend/postmaster/autovacuum.c
Labels: version: 7X_ALPHA, needs: backport

#14992 Bring back pg_appendonly to relcache
  src/backend/access/aocs/aocsam.c
  src/backend/access/aocs/aocsam_handler.c
  src/backend/access/aocs/aocssegfiles.c
  src/backend/access/appendonly/aosegfiles.c
  src/backend/access/appendonly/appendonly_blkdir_udf.c
  src/backend/access/appendonly/appendonly_compaction.c
  src/backend/access/appendonly/appendonly_visimap.c
  src/backend/access/appendonly/appendonly_visimap_udf.c
  src/backend/access/appendonly/appendonlyam.c
  src/backend/access/appendonly/appendonlyam_handler.c
  src/backend/access/appendonly/appendonlyblockdirectory.c
  src/backend/access/appendonly/appendonlywriter.c
  src/backend/catalog/aocatalog.c
  src/backend/catalog/index.c
  src/backend/catalog/pg_appendonly.c
  src/backend/catalog/pg_attribute_encoding.c
  src/backend/commands/cluster.c
  src/backend/commands/indexcmds.c
  src/backend/commands/tablecmds.c
  src/backend/commands/vacuum.c
  src/backend/commands/vacuum_ao.c
  src/backend/utils/adt/dbsize.c
  src/backend/utils/cache/relcache.c
  src/include/catalog/pg_appendonly.h
  src/include/utils/rel.h
Labels: version: 7X_ALPHA

#15044 Fix error in ATSETAM to ao_column with dropped column
  src/backend/catalog/pg_attribute_encoding.c
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_table_set_am.out
  src/test/regress/sql/alter_table_set_am.sql
Labels: version: 7X_ALPHA

#15061 Remove dead relid variables
  src/backend/access/appendonly/appendonlyam_handler.c
  src/backend/commands/tablecmds.c
Labels: version: 7X_ALPHA

#15072 Orca FIXME: Remove references to RelIsPartitioned
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CContextDXLToPlStmt.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/utils/cache/lsyscache.c
  src/include/gpopt/gpdbwrappers.h
  src/include/gpopt/translate/CContextDXLToPlStmt.h
  src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
  src/include/utils/lsyscache.h
Labels: area: gporca, version: 7X_ALPHA

#15000 Support for HashIndexes in Orca
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/gporca/data/dxl/minidump/Hash-BitmapScan.mdp
  src/backend/gporca/data/dxl/minidump/Hash-IndexScan.mdp
  src/backend/gporca/libgpopt/src/operators/CLogical.cpp
  src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
  src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
  src/backend/gporca/libnaucrates/include/naucrates/md/IMDIndex.h
  src/backend/gporca/libnaucrates/src/md/CMDIndexGPDB.cpp
  src/backend/gporca/libnaucrates/src/md/IMDIndex.cpp
  src/backend/gporca/libnaucrates/src/operators/CDXLOperatorFactory.cpp
  src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/bfv_index.out
  src/test/regress/expected/bfv_index_optimizer.out
  src/test/regress/expected/create_index_optimizer.out
  src/test/regress/expected/hash_index.out
  src/test/regress/sql/bfv_index.sql
  src/test/regress/sql/hash_index.sql
Labels: area: gporca

#15076 [6X] fix: unsafe tar extract for gppkg
  gpMgmt/bin/gppylib/operations/package.py
Labels: version: 6X_STABLE

#14753 [6X backport] Record pg_controldata output of failed segment
  gpMgmt/bin/gppylib/heapchecksum.py
  gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
Labels: gpcm_in

#14896 ADBDEV-3168-1: ORCA produces bogus plan for queries with CTE during handling distribution for Sequence children
  src/backend/gporca/data/dxl/minidump/CTE-4.mdp
  src/backend/gporca/data/dxl/minidump/CTE15HAReplicated.mdp
  src/backend/gporca/data/dxl/minidump/CTE15Replicated.mdp
  src/backend/gporca/data/dxl/minidump/CTE2HAReplicated.mdp
  src/backend/gporca/data/dxl/minidump/CTE2Replicated.mdp
  src/backend/gporca/data/dxl/minidump/ProjectWithTextConstant.mdp
  src/backend/gporca/data/dxl/minidump/UnionOfDQAQueries.mdp
  src/backend/gporca/libgpopt/src/operators/CPhysicalFilter.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalSequence.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CCTETest.cpp
  src/test/regress/expected/with_clause_optimizer.out
Labels: area: gporca, version: 7X_ALPHA, community

#15057 Force two-stage local aggregate to remove duplicates
  src/backend/executor/nodeAgg.c
  src/backend/gporca/data/dxl/minidump/AggregateWithSkew.mdp
  src/backend/gporca/data/dxl/minidump/DQA-GroupBy-HashAggregate1.mdp
  src/backend/gporca/data/dxl/minidump/DQA-GroupBy-HashAggregate2.mdp
  src/backend/gporca/data/dxl/minidump/DQA-InnerJoin-GroupBy-HashAggregate.mdp
  src/backend/gporca/data/dxl/minidump/DqaNoRedistribute.mdp
  src/backend/gporca/data/dxl/minidump/MultiColumnDQA-InnerJoin-GroupBy-HashAggregate.mdp
  src/backend/gporca/data/dxl/minidump/ScalarDQAWithNonScalarAgg.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-DistinctOnDistrCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-GbMultipleCol-DistinctOnDistrCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-GbandDistinctOnDistrCol.mdp
  src/backend/gporca/libgpopt/src/xforms/CXformSplitDQA.cpp
  src/test/isolation2/expected/spilling_hashagg.out
  src/test/isolation2/expected/spilling_hashagg_optimizer.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/spilling_hashagg.sql
  src/test/regress/expected/gp_dqa_optimizer.out
Labels: area: gporca, version: 7X_ALPHA, needs: backport

#15084 Prevent duplicate filter issue
  src/backend/gporca/data/dxl/minidump/PushConstantSelectPredicateThruJoin-11.mdp
  src/backend/gporca/data/dxl/minidump/PushConstantSelectPredicateThruJoin-12.mdp
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, version: 7X_ALPHA
