Repository greenplum-db/gpdb, pull requests merged in 2023-12, with the labels that each got.

#16777 Fix query fallback when subqury present within LEAST()/GREATEST()
  src/backend/gporca/data/dxl/minidump/Least-Greatest-Subselect.mdp
  src/backend/gporca/data/dxl/minidump/SubqueryInsideArrayRef.mdp
  src/backend/gporca/data/dxl/minidump/SubqueryInsideArrayRefIndexList.mdp
  src/backend/gporca/libgpopt/src/xforms/CSubqueryHandler.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CICGTest.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CSubqueryTest.cpp
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/sql/subselect_gp.sql
Labels: area: gporca

#16628 Implementation of network throttling in gprecoverseg
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/bin/gppylib/commands/pg.py
  gpMgmt/bin/gppylib/commands/test/unit/test_unit_pg_base_backup.py
  gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
  gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
  gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
  gpMgmt/bin/gppylib/test/unit/test_unit_recovery_base.py
  gpMgmt/bin/gppylib/test/unit/test_unit_recoveryinfo.py
  gpMgmt/doc/gprecoverseg_help
  gpMgmt/sbin/gpsegrecovery.py
  gpMgmt/sbin/recovery_base.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpdb-doc/markdown/utility_guide/ref/gprecoverseg.html.md
Labels: gpcm_in, cla-not-required, 7X_STABLE

#16796 Rocky8/oel8/rhel8 needs zstd 1.4.4 to be vendored
  concourse/scripts/compile_gpdb.bash
Labels: cla-not-required

#16764 fix resource group reserve memory
  src/backend/cdb/dispatcher/cdbdisp_async.c
  src/backend/utils/resgroup/resgroup.c
  src/test/isolation2/input/resgroup/enable_resgroup.source
  src/test/isolation2/output/resgroup/enable_resgroup.source
Labels: cla-not-required

#16641 Enable tablefunc extension in gpdb7
  GNUmakefile.in
Labels: cla-not-required

#16730 docs - tablefunc to xref to pg v12 docs
  gpdb-doc/markdown/ref_guide/modules/tablefunc.html.md
Labels: 7X_Docs, cla-not-required

#16799 Fix query fallback when subqury present within LEAST()/GREATEST()
  src/backend/gporca/data/dxl/minidump/Least-Greatest-Subselect.mdp
  src/backend/gporca/data/dxl/minidump/SubqueryInsideArrayRef.mdp
  src/backend/gporca/data/dxl/minidump/SubqueryInsideArrayRefIndexList.mdp
  src/backend/gporca/libgpopt/src/xforms/CSubqueryHandler.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CICGTest.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CSubqueryTest.cpp
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/sql/subselect_gp.sql
Labels: area: gporca, version: 6X_STABLE, cla-not-required

#16800 Fix incorrect ORCA plan for "Left Semi Join with replicated outer table"
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/gporca/data/dxl/minidump/LeftSemiJoinWithRepOuterTab.mdp
  src/backend/gporca/server/CMakeLists.txt
  src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
  src/test/regress/expected/join_gp.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/sql/join_gp.sql
Labels: area: gporca, version: 6X_STABLE, cla-not-required

#16732 Add one more hierarchy for resgroup cgroup root
  src/backend/utils/resgroup/cgroup-ops-linux-v1.c
  src/backend/utils/resgroup/cgroup-ops-linux-v2.c
  src/backend/utils/resgroup/cgroup.c
  src/include/utils/cgroup.h
  src/test/isolation2/expected/resgroup/resgroup_auxiliary_tools_v2.out
  src/test/isolation2/sql/resgroup/resgroup_auxiliary_tools_v2.sql
Labels: cla-not-required

#16773 Checking interrupt more frequently in HashJoin
  src/backend/executor/nodeAgg.c
  src/backend/executor/nodeAppend.c
  src/backend/executor/nodeBitmapHeapscan.c
  src/backend/executor/nodeGroup.c
  src/backend/executor/nodeHash.c
  src/backend/executor/nodeHashjoin.c
  src/backend/executor/nodeIndexonlyscan.c
  src/backend/executor/nodeIndexscan.c
  src/backend/executor/nodeLimit.c
  src/backend/executor/nodeLockRows.c
  src/backend/executor/nodeMaterial.c
  src/backend/executor/nodeMergeAppend.c
  src/backend/executor/nodeMergejoin.c
  src/backend/executor/nodeModifyTable.c
  src/backend/executor/nodeNestloop.c
  src/backend/executor/nodeRecursiveunion.c
  src/backend/executor/nodeResult.c
  src/backend/executor/nodeSubplan.c
  src/backend/executor/nodeTidscan.c
  src/backend/executor/nodeUnique.c
  src/backend/executor/nodeWindowAgg.c
Labels: backport, cla-not-required

#16789 Do not throw error for INSERT into a table w/ foreign key constraint
  src/backend/commands/trigger.c
  src/test/regress/expected/foreign_key_gp.out
  src/test/regress/expected/triggers_gp.out
  src/test/regress/greenplum_schedule
  src/test/regress/parallel_schedule
  src/test/regress/sql/foreign_key_gp.sql
  src/test/regress/sql/triggers_gp.sql
Labels: cla-not-required, 7X_STABLE

#16762 pg_dumpall: dump 6x resource groups correctly for 6 > 7 upgrade
  src/bin/pg_dump/pg_dumpall.c
Labels: cla-not-required

#16821 ignore CreateDir in abi-check
  .abi-check/7.0.0/postgres.symbols.ignore
Labels: cla-not-required

#16736 docs - optimizer_enable_orderedagg guc added to gp7
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
  gpdb-doc/markdown/ref_guide/guc-changes-6to7.html.md.erb
Labels: 7X_Docs, cla-not-required

#16816 Docs: add gppkg option to specify package to migrate
  gpdb-doc/markdown/utility_guide/ref/gppkg.html.md
Labels: 7X_Docs, cla-not-required

#16724 Adjust subquery's locus for recurse_set_operations
  src/backend/optimizer/prep/prepunion.c
  src/test/regress/expected/union.out
Labels: cla-not-required

#16744 docs - add pgbouncer reference and using content
  gpdb-doc/markdown/admin_guide/access_db/topics/pgbouncer.html.md
  gpdb-doc/markdown/security-guide/topics/ports_and_protocols.html.md
  gpdb-doc/markdown/utility_guide/ref/pgbouncer-admin.html.md
  gpdb-doc/markdown/utility_guide/ref/pgbouncer-ini.html.md
  gpdb-doc/markdown/utility_guide/ref/pgbouncer.html.md
  gpdb-doc/markdown/utility_guide/utility-programs.html.md
Labels: cla-not-required

#16829 DOCS: Update utility name for migrating from Linux 7 to Linux 8 topic
  gpdb-doc/markdown/install_guide/migrate-linux.html.md
Labels: cla-not-required

#16828 Docs: pgbouncer supports encrypted ldap password
  gpdb-doc/markdown/admin_guide/access_db/topics/pgbouncer.html.md
  gpdb-doc/markdown/utility_guide/ref/pgbouncer-ini.html.md
Labels: cla-not-required

#16827 Fix deadlock between coordinator and segments
  src/backend/commands/indexcmds.c
  src/test/isolation2/expected/create_index_deadlock.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/create_index_deadlock.sql
Labels: community

#16728 docs - ip4r version 2.4.2
  gpdb-doc/markdown/ref_guide/modules/ip4r.html.md
Labels: 7X_Docs, cla-not-required

#16826 Fix flaky test autovacuum-temp-table
  src/test/isolation2/expected/autovacuum-temp-table.out
  src/test/isolation2/sql/autovacuum-temp-table.sql
Labels: flaky test, cla-not-required, 7X_STABLE

#16836 Docs: added note for gppkg remove force option
  gpdb-doc/markdown/utility_guide/ref/gppkg.html.md
Labels: 7X_Docs, cla-not-required

#16835 Docs: edited the gprecoverseg reference page for max-rate
  gpdb-doc/markdown/utility_guide/ref/gprecoverseg.html.md
Labels: 7X_Docs, cla-not-required

#15735 Fix memory accounting bug when move memory context
  src/backend/utils/mmgr/aset.c
Labels: version: 7X_ALPHA, community

#16833 Vendor LLVM for Greenplum 7 on EL 8
  concourse/pipelines/gpdb_main-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
  concourse/scripts/common.bash
  concourse/scripts/compile_gpdb.bash
  concourse/tasks/ic_gpdb.yml
  concourse/tasks/ic_gpdb_binary_swap.yml
Labels: cla-not-required

#16823 Have ExecFindPartition cache the last found partition
  src/backend/executor/execPartition.c
  src/backend/partitioning/partdesc.c
  src/include/partitioning/partdesc.h
Labels: topic: partitions, backport, cla-not-required, 7X_STABLE

#16822 Backport improvements to partition bound manipulation
  src/backend/partitioning/partbounds.c
Labels: topic: partitions, backport, cla-not-required, 7X_STABLE

#16749 Resolve FIXME in create_ctescan_path() in pathnode.c.
  src/backend/optimizer/util/pathnode.c
  src/test/regress/expected/subselect.out
  src/test/regress/expected/subselect_optimizer.out
Labels: cla-not-required

#16830 delete cgroup leaf dir only when use group-v2
  src/backend/utils/resgroup/cgroup.c
Labels: cla-not-required

#16825 [ORCA] Fix boolean testing when the child is not an ident but an expression
  src/backend/gporca/data/dxl/minidump/PartTbl-SPE-Boolean2.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CConstraintInterval.h
  src/backend/gporca/libgpopt/src/base/CConstraintInterval.cpp
  src/test/regress/expected/partition_prune_optimizer.out
  src/test/regress/expected/partition_pruning.out
  src/test/regress/expected/partition_pruning_optimizer.out
  src/test/regress/sql/partition_pruning.sql
Labels: area: gporca, 7X_STABLE

#16831 Add volatile qualifier missed in ao segfiles
  src/backend/access/aocs/aocssegfiles.c
  src/backend/access/appendonly/aosegfiles.c
Labels: community

#16760 Fix gpcheckcat 'oid does not exist' error for catalog tables
  gpMgmt/bin/gpcheckcat
  gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
  gpMgmt/test/behave/mgmt_utils/steps/tablespace_mgmt_utils.py
Labels: version: 6X_STABLE, gpcm_in, cla-not-required

#16793 Fix gpcheckcat 'oid does not exist' error for catalog tables
  gpMgmt/bin/gpcheckcat
  gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
  gpMgmt/test/behave/mgmt_utils/steps/tablespace_mgmt_utils.py
Labels: gpcm_in, cla-not-required, 7X_STABLE

#16844 Change the output filename for compile_gpdb_with_llvm_asserts job
  concourse/pipelines/gpdb_main-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
  concourse/scripts/common.bash
  concourse/tasks/compile_gpdb.yml
Labels: cla-not-required

#16832 [6X] Printing const-folder expression in ruleutils.c
  src/backend/utils/adt/ruleutils.c
  src/test/regress/expected/create_view.out
  src/test/regress/expected/create_view_optimizer.out
  src/test/regress/sql/create_view.sql
Labels: cla-not-required

#16839 Printing const-folder expression in ruleutils.c
  src/backend/utils/adt/ruleutils.c
  src/test/regress/expected/create_view.out
  src/test/regress/expected/create_view_optimizer.out
  src/test/regress/sql/create_view.sql
Labels: cla-not-required

#16807 Fix memory leak in Dynamic Index/IndexOnly/BitmapIndex Scan during execution (#16797)
  src/backend/executor/execDynamicIndexes.c
  src/backend/executor/nodeDynamicBitmapIndexscan.c
Labels: area: gporca, community, Priority 1, 7X_STABLE

#16843 Produce stable explain_format test output
  src/test/regress/expected/explain_format.out
  src/test/regress/expected/explain_format_optimizer.out
  src/test/regress/sql/explain_format.sql
Labels: cla-not-required

#16846 Fix comment on 'performDtxProtocolPrepare'
  src/backend/cdb/cdbtm.c
Labels: cla-not-required

#16852 Ignore variable JIT gucs in explain_format output
  src/test/regress/expected/explain_format.out
  src/test/regress/expected/explain_format_optimizer.out
  src/test/regress/sql/explain_format.sql
Labels: cla-not-required

#16583 docs - clarify ALTER SERVER option actions
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_SERVER.html.md
Labels: cla-not-required

#16858 DOCS: Update link to GPDR ref pages
  gpdb-doc/markdown/utility_guide/utility-programs.html.md
Labels: cla-not-required

#16859 DOCS: Fix link to GPDR ref pages
  gpdb-doc/markdown/utility_guide/utility-programs.html.md
Labels: cla-not-required

#16815 Docs: add gp_move_orphaned_files gp_toolkit
  gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
Labels: 7X_Docs, cla-not-required

#16837 Docs: Add note for rsync version gpstate
  gpdb-doc/markdown/utility_guide/ref/gpstate.html.md
Labels: 7X_Docs, cla-not-required

#16814 Docs: add reference to GSS file unloading
  gpdb-doc/markdown/admin_guide/load/topics/g-loading-and-unloading-data.html.md
  gpdb-doc/markdown/admin_guide/load/topics/g-unloading-data-from-greenplum-database.html.md
  gpdb-doc/markdown/admin_guide/load/topics/g-unloading-data-using-gpss.html.md
Labels: 7X_Docs, cla-not-required

#16818 Fix view gp_toolkit.gp_stats_missing to only show tables missing stats
  gpcontrib/gp_toolkit/expected/gp_toolkit.out
  gpcontrib/gp_toolkit/gp_toolkit--1.3.sql
  gpcontrib/gp_toolkit/sql/gp_toolkit.sql
Labels: area: gporca, cla-not-required, 7X_STABLE

#16870 Fix ICW output file for resgroup gp_toolkit
  gpcontrib/gp_toolkit/expected/gp_toolkit_resgroup.out
Labels: area: gporca, cla-not-required, 7X_STABLE

#16738 Add guc: gp_resource_group_cgroup_parent
  .abi-check/7.0.0/postgres.symbols.ignore
  gpMgmt/bin/gpconfig
  src/backend/cdb/cdbvars.c
  src/backend/utils/misc/guc_gp.c
  src/backend/utils/resgroup/cgroup.c
  src/include/utils/guc.h
  src/include/utils/resgroup.h
  src/include/utils/unsync_guc_name.h
  src/test/isolation2/expected/resgroup/resgroup_auxiliary_tools_v2.out
  src/test/isolation2/sql/resgroup/resgroup_auxiliary_tools_v2.sql
Labels: cla-not-required

#16840 Fix lateral panic when using motion to pass through params
  src/backend/cdb/cdbmutate.c
  src/backend/optimizer/plan/createplan.c
  src/include/cdb/cdbmutate.h
  src/test/regress/expected/bfv_joins.out
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/expected/gporca.out
  src/test/regress/init_file
  src/test/regress/sql/bfv_joins.sql
Labels: cla-not-required

#16810 Fix ORCA returning wrong column type modifier info
  contrib/postgres_fdw/expected/gp2pg_postgres_fdw_optimizer.out
  src/backend/optimizer/plan/orca.c
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, cla-not-required, status: fully approved, 7X_STABLE

#16851 Fix memory leak in Dynamic Index/BitmapIndex Scan during execution
  src/backend/executor/nodeDynamicBitmapIndexscan.c
  src/backend/executor/nodeDynamicIndexscan.c
Labels: area: gporca, version: 6X_STABLE, status: fully approved

#16855 Docs gp stat progress dtx recovery
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
Labels: 7X_Docs, cla-not-required

#16533 Docs - Removing references to informatica connector
  gpdb-doc/markdown/admin_guide/load/topics/g-loading-and-unloading-data.html.md
  gpdb-doc/markdown/best_practices/data_loading.html.md
  gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
Labels: 7X_Docs, cla-not-required

#16838 Docs: document the guc log_directory
  gpdb-doc/markdown/best_practices/logfiles.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
Labels: 7X_Docs, cla-not-required

#16868 Remove unused index strategy and subtype information from Orca
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gpopt/translate/CTranslatorUtils.cpp
  src/include/gpopt/translate/CIndexQualInfo.h
  src/include/gpopt/translate/CTranslatorDXLToPlStmt.h
  src/include/gpopt/translate/CTranslatorUtils.h
Labels: area: gporca, cla-not-required, status: fully approved, 7X_STABLE

#16884 Fix resource ‘filedump_src’ is not used for genpipeline cli
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: cla-not-required

#16857 gpinitsystem should return code 1 when invalid option is used
  gpMgmt/bin/lib/gp_bash_functions.sh
  gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
Labels: gpcm_in, cla-not-required

#16889 Add src/test/regress init_file to pg_buffercache tests
  contrib/pg_buffercache/Makefile
Labels: cla-not-required

#16888 Add compile with llvm asserts to gate pass conditions
  concourse/pipelines/gpdb_main-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: cla-not-required

#16894 Fix CDatumSortedSet handling of empty arrays causing errors in ORCA
  src/backend/gporca/libgpopt/src/base/CDatumSortedSet.cpp
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, status: fully approved, 7X_STABLE

#16883 Remove redundant hash keys of motion
  src/backend/gporca/data/dxl/minidump/DQA-1-RegularAgg.mdp
  src/backend/gporca/data/dxl/minidump/DQA-2-RegularAgg.mdp
  src/backend/gporca/data/dxl/minidump/DQA-GroupBy-HashAggregate1.mdp
  src/backend/gporca/data/dxl/minidump/DQA-SplitScalar.mdp
  src/backend/gporca/data/dxl/minidump/DQA-SplitScalarOnDistCol.mdp
  src/backend/gporca/data/dxl/minidump/DQA-SplitScalarWithAggAndGuc.mdp
  src/backend/gporca/data/dxl/minidump/DQA-SplitScalarWithGuc.mdp
  src/backend/gporca/data/dxl/minidump/DistinctQueryWithMotions.mdp
  src/backend/gporca/data/dxl/minidump/LOJ_bb_mpph.mdp
  src/backend/gporca/data/dxl/minidump/MDQA-SameDQAColumn.mdp
  src/backend/gporca/data/dxl/minidump/MDQAs-Grouping-OrderBy.mdp
  src/backend/gporca/data/dxl/minidump/MDQAs-Grouping.mdp
  src/backend/gporca/data/dxl/minidump/MDQAs-Union.mdp
  src/backend/gporca/data/dxl/minidump/MDQAs1.mdp
  src/backend/gporca/data/dxl/minidump/ScalarDQAWithNonScalarAgg.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-DistinctOnComputedCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-DistinctOnSameNonDistrCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-GbandDistinctOnDistrCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-ScalarAgg-DistinctComputedCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-ScalarAgg-DistinctDistrCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-ScalarAgg-DistinctNonDistrCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg.mdp
  src/backend/gporca/data/dxl/minidump/UnionOfDQAQueries.mdp
  src/backend/gporca/data/dxl/minidump/WinFunc-Redistribute-Sort-CTE-Producer.mdp
  src/backend/gporca/libgpopt/src/operators/CPhysicalAgg.cpp
  src/test/regress/expected/gp_dqa.out
  src/test/regress/expected/gp_dqa_optimizer.out
  src/test/regress/sql/gp_dqa.sql
Labels: area: gporca, cla-not-required, status: fully approved, 7X_STABLE

#16784 Fix AO table fsync memory leak
  src/backend/storage/smgr/md.c
Labels: community

#16902 Fix for gpcheckcat when issue `gpcheckcat -C pg_class`
  gpMgmt/bin/gpcheckcat
  gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
Labels: gpcm_in, cla-not-required, 7X_STABLE

#16845 Turn down `gp_resource_group_cpu_limit` may cause the database to fail to start
  src/backend/utils/resgroup/cgroup-ops-linux-v1.c
  src/test/isolation2/expected/resgroup/resgroup_syntax.out
  src/test/isolation2/sql/resgroup/resgroup_syntax.sql
Labels: community

#16907 fix motion toast error
  src/backend/cdb/motion/tupser.c
  src/test/regress/expected/toast.out
  src/test/regress/sql/toast.sql
Labels: community

#16891 Code cleanup of Subquery Scan
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gporca/data/dxl/parse_tests/q21-SubqueryScan.xml
  src/backend/gporca/libnaucrates/include/naucrates/dxl/operators/CDXLOperator.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/operators/CDXLOperatorFactory.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/operators/CDXLPhysicalSubqueryScan.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerSubqueryScan.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/parsehandlers.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
  src/backend/gporca/libnaucrates/src/operators/CDXLOperatorFactory.cpp
  src/backend/gporca/libnaucrates/src/operators/CDXLPhysicalSubqueryScan.cpp
  src/backend/gporca/libnaucrates/src/operators/Makefile
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerFactory.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerSubqueryScan.cpp
  src/backend/gporca/libnaucrates/src/parser/Makefile
  src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
  src/backend/gporca/server/src/unittest/dxl/CParseHandlerTest.cpp
  src/include/gpopt/translate/CTranslatorDXLToPlStmt.h
Labels: area: gporca, cla-not-required, status: fully approved, 7X_STABLE

#16803 introduce the variable of allow_append_initplan_for_function_scan
  src/backend/cdb/cdbpath.c
  src/backend/optimizer/plan/createplan.c
  src/backend/optimizer/plan/subselect.c
  src/include/cdb/cdbpath.h
  src/test/regress/expected/function_extensions.out
  src/test/regress/expected/function_extensions_optimizer.out
  src/test/regress/sql/function_extensions.sql
Labels: cla-not-required

#16898 [ORCA] Fix Missing pdshashedEquiv in IndexOnlyScan, Especially under InnerIndexNLJoin.
  src/backend/gporca/data/dxl/minidump/DynamicIndexOnlyScan-InnerJoin.mdp
  src/backend/gporca/data/dxl/minidump/DynamicIndexOnlyScan-LeftJoin.mdp
  src/backend/gporca/libgpopt/src/operators/CPhysicalScan.cpp
  src/test/regress/expected/bfv_index.out
  src/test/regress/expected/bfv_index_optimizer.out
  src/test/regress/expected/gp_covering_index_optimizer.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/select_parallel_optimizer.out
  src/test/regress/expected/subselect_optimizer.out
  src/test/regress/sql/bfv_index.sql
Labels: area: gporca, status: fully approved, 7X_STABLE

#16896 updated max range value in help file for gpexpand -n option
  gpMgmt/doc/gpexpand_help
Labels: cla-not-required
