Repository greenplum-db/gpdb, pull requests merged in 2023-06, with the labels that each got.

#15619 Fix dangling pointer in ExecDynamicIndexScan()
  src/backend/executor/nodeDynamicIndexscan.c
Labels: area: gporca, version: 7X_ALPHA

#15601 [6X Backport] gpstate -e: Fix gprecoverseg progress reporting
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/bin/gppylib/commands/test/unit/test_unit_gp.py
  gpMgmt/bin/gppylib/programs/clsSystemState.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/gpstate.feature
  gpMgmt/test/behave/mgmt_utils/steps/data/pid_background_script.py
  gpMgmt/test/behave/mgmt_utils/steps/gpstate_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: version: 6X_STABLE, backport, gpcm_in

#15590 Fix "cannot execute squelched plan node of type" error (greenplum-db#11673)
  src/backend/executor/nodeHashjoin.c
  src/test/regress/expected/bfv_joins.out
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/sql/bfv_joins.sql
Labels: version: 7X_ALPHA, community

#15678 Disallow "LIKE <AO/AOCO> INCLUDING STORAGE" if table AM is already set
  src/backend/parser/parse_utilcmd.c
  src/test/regress/expected/create_table_like_gp.out
  src/test/regress/sql/create_table_like_gp.sql
Labels: area: server, area: aoco

#15653 Set next OID before restoring schema during pg_upgrade
  src/bin/pg_upgrade/pg_upgrade.c
Labels: needs: backport

#15669 Fix dangling pointer in ExecDynamicIndexScan()
  src/backend/executor/nodeDynamicIndexscan.c
Labels: version: 6X_STABLE

#15150 remove stale mentions of round-robin distribution
  gpdb-doc/markdown/admin_guide/ddl/ddl-table.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE_AS.html.md
Labels: version: 7X_ALPHA, community

#15687 Fix cannot execute squelched plan node of type error
  src/backend/executor/nodeHashjoin.c
  src/test/regress/expected/bfv_joins.out
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/sql/bfv_joins.sql
Labels: backport

#15397 Fix coordinator crash in MPPnoticeReceiver
  src/backend/cdb/dispatcher/cdbconn.c
Labels: version: 6X_STABLE, community

#15623 [6X backport] Replace List with RBTree for preassigned Oids
  src/backend/catalog/oid_dispatch.c
Labels: version: 6X_STABLE

#15668 [6X backport] Do not check new relfilenodes against the preserved oid list for upgrade
  src/backend/catalog/catalog.c
  src/backend/utils/cache/relcache.c
Labels: version: 6X_STABLE, backport

#15682 [6X backport] Set next OID before restoring schema during pg_upgrade
  contrib/pg_upgrade/pg_upgrade.c
Labels: version: 6X_STABLE, backport

#15659 Hardcode the opfamily of GpSegmentId in GetContentIdsFromPlanForSingleRelation()
  src/backend/cdb/cdbtargeteddispatch.c
Labels: topic: performance, version: 7X_ALPHA, needs: backport

#15713 Resolve a FIXME for gpcheckcat
  gpMgmt/bin/gpcheckcat_modules/foreign_key_check.py
  gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: version: 7X_ALPHA, merge_fixme

#15706 Fall back to planner for queries with foreign partitions using greenplum_fdw
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/include/gpopt/gpdbwrappers.h
Labels: area: gporca, version: 7X_ALPHA

#15708 Resolve two FIXMEs in extractPageInfo()
  src/bin/pg_rewind/parsexlog.c
Labels: version: 7X_ALPHA, merge_fixme

#15629 Support DPE for duplicate sensitive random motions in Orca
  contrib/postgres_fdw/expected/gp_postgres_fdw.out
  contrib/postgres_fdw/expected/gp_postgres_fdw_optimizer.out
  contrib/postgres_fdw/sql/gp_postgres_fdw.sql
  src/backend/gporca/data/dxl/minidump/ForeignPartOneTimeFilterDPE.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecRandom.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysical.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalMotion.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalMotionRandom.h
  src/backend/gporca/libgpopt/src/base/CDistributionSpecNonSingleton.cpp
  src/backend/gporca/libgpopt/src/base/CDistributionSpecRandom.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalMotionRandom.cpp
  src/backend/gporca/server/CMakeLists.txt
Labels: area: gporca, version: 7X_ALPHA

#15543 DOCS: Update all reference topics to reflect changes to memory and resource groups in 7X
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
  gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
Labels: 7X_Docs

#15577 docs - new topic, updated ref pages for progress reporting views and some utilities
  gpdb-doc/markdown/admin_guide/managing/partII.html.md
  gpdb-doc/markdown/admin_guide/managing/progress_reporting.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
  gpdb-doc/markdown/utility_guide/ref/clusterdb.html.md
  gpdb-doc/markdown/utility_guide/ref/pg_checksums.html.md
  gpdb-doc/markdown/utility_guide/ref/reindexdb.html.md
  gpdb-doc/markdown/utility_guide/toc.md
  gpdb-doc/markdown/utility_guide/utility-programs.html.md
Labels: 7X_Docs

#15170 ORCA should generate plans with the ProjectSet node
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/optimizer/util/tlist.c
  src/include/gpopt/gpdbwrappers.h
  src/include/gpopt/translate/CTranslatorDXLToPlStmt.h
  src/test/regress/expected/DML_over_joins_optimizer.out
  src/test/regress/expected/gp_dqa_optimizer.out
  src/test/regress/expected/gp_tsrf.out
  src/test/regress/expected/gp_tsrf_optimizer.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/qp_misc_optimizer.out
  src/test/regress/expected/tsrf_optimizer.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/gp_tsrf.sql
Labels: area: gporca, version: 7X_ALPHA

#15741 Update MERGE_FIXME comment for `appendonly_rescan`
  src/backend/access/aocs/aocsam_handler.c
  src/backend/access/appendonly/appendonlyam.c
Labels: area: server, merge_fixme

#15714 Revised support for AO/ENCODING in CREATE TABLE .. LIKE INCLUDING
  src/backend/commands/tablecmds.c
  src/backend/parser/gram.y
  src/backend/parser/parse_utilcmd.c
  src/include/commands/tablecmds.h
  src/include/nodes/parsenodes.h
  src/include/parser/kwlist.h
  src/test/regress/expected/create_table_like_gp.out
  src/test/regress/sql/create_table_like_gp.sql
Labels: area: server, area: aoco

#15702 6x backport: Hardcode the attributes of GpSegmentId in GetContentIdsFromPlanForSingleRelation()
  src/backend/cdb/cdbtargeteddispatch.c
Labels: topic: performance, version: 6X_STABLE

#15617 [6X] new operator shouldn't return NULL
  src/backend/gpopt/utils/CMemoryPoolPalloc.cpp
  src/backend/gporca/libgpos/src/memory/CMemoryPoolTracker.cpp
Labels: area: gporca, version: 6X_STABLE, community, status: merge window

#15633 FIX BUG: COPY FORM doesn't throw out ERROR: extra data after last expected column (6X)
  src/backend/commands/copy.c
  src/test/regress/data/copy.data
  src/test/regress/input/copy.source
  src/test/regress/output/copy.source
Labels: version: 6X_STABLE

#15686 [6X Backport] Fix bug in ORCA of removing required redistribution motion when query uses GROUP BY over gp_segment_id
  src/backend/gporca/data/dxl/minidump/DistinctQueryWithMotions.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecHashed.h
  src/backend/gporca/libgpopt/src/base/CDistributionSpecHashed.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/bfv_aggregate.out
  src/test/regress/expected/bfv_aggregate_optimizer.out
  src/test/regress/expected/direct_dispatch_optimizer.out
  src/test/regress/sql/bfv_aggregate.sql
Labels: area: gporca, version: 6X_STABLE, backport, status: merge window

#15742 [6X] Only run GPDB upgrade checks against the coordinator segment
  contrib/pg_upgrade/check.c
Labels: version: 6X_STABLE

#15786 Remove fixme in relation_open()
  src/backend/access/common/relation.c
Labels: merge_fixme

#15777 docs - gpfdist supports multi-threaded compression and data transfer
  gpdb-doc/markdown/utility_guide/ref/gpfdist.html.md
Labels: 7X_Docs

#15350 Autocompletion for create EXTERNAL TABLE in psql
  src/bin/psql/tab-complete.c
Labels: version: 7X_ALPHA, community

#15751 Docs resgroups narrative
  gpdb-doc/markdown/admin_guide/wlmgmt.html.md
  gpdb-doc/markdown/admin_guide/wlmgmt_intro.html.md
  gpdb-doc/markdown/admin_guide/workload_mgmt.html.md
  gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
Labels: 7X_Docs

#15763 docs - add info for index-only scan, covering index info; gporca limits
  gpdb-doc/markdown/admin_guide/ddl/ddl-index.html.md
  gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-limitations.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_INDEX.html.md
Labels: 7X_Docs

#15253 Fix concurrent update core of partiton table in Dynamic scan
  src/backend/executor/execPartition.c
  src/test/isolation2/expected/gdd/concurrent_update.out
  src/test/isolation2/expected/gdd/concurrent_update_optimizer.out
  src/test/isolation2/sql/gdd/concurrent_update.sql
Labels: area: gporca

#15779 Remove MemoryContext s_tupSerMemCtxt
  src/backend/cdb/motion/tupser.c
Labels: area: server, executor

#15698 [6X] Allow pg_upgrade --jobs to also run GPDB upgrade checks in parallel
  contrib/pg_upgrade/greenplum/check_gp.c
  contrib/pg_upgrade/pg_upgrade.h
  contrib/pg_upgrade/util.c
Labels: version: 6X_STABLE

#15823 [6X] Do not preserve relfrozenxid of user tables for pg_dump --binary-upgrade
  contrib/pg_upgrade/pg_upgrade.c
  src/bin/pg_dump/pg_dump.c
Labels: version: 6X_STABLE

#15795 Fix REORGANIZE=true not redistributing randomly-distributed tables
  src/backend/cdb/cdbpath.c
  src/backend/commands/tablecmds.c
  src/backend/utils/misc/guc_gp.c
  src/include/cdb/cdbvars.h
  src/include/utils/unsync_guc_name.h
  src/test/regress/expected/alter_distribution_policy.out
  src/test/regress/expected/guc_gp.out
  src/test/regress/init_file
  src/test/regress/sql/alter_distribution_policy.sql
  src/test/regress/sql/guc_gp.sql
Labels: version: 7X_ALPHA

#15788 Add two macros RelationStorageIsAoRows|RelationStorageIsAoCols
  src/backend/access/aocs/aocs_compaction.c
  src/backend/access/aocs/aocssegfiles.c
  src/backend/access/appendonly/aomd.c
  src/backend/access/appendonly/aosegfiles.c
  src/backend/access/appendonly/appendonly_compaction.c
  src/backend/access/appendonly/appendonlywriter.c
  src/backend/catalog/gp_fastsequence.c
  src/backend/commands/tablecmds.c
  src/backend/commands/vacuum_ao.c
  src/backend/executor/nodeIndexonlyscan.c
  src/backend/optimizer/util/plancat.c
  src/include/utils/rel.h
  src/test/regress/expected/alter_table_set_am.out
Labels: version: 7X_ALPHA

#15599 [7x] starting segments in execute mode post recovery
  gpMgmt/sbin/gpsegrecovery.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/tablespace_mgmt_utils.py
Labels: gpcm_in

#15838 Fix flaky test AOCO_Compression
  src/test/regress/expected/AOCO_Compression.out
  src/test/regress/sql/AOCO_Compression.sql
Labels: version: 7X_ALPHA, flaky test

#15776 Docs jit gporca
  gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
Labels: area: gporca, 7X_Docs

#15697 [ORCA] Update index cost model to account for INCLUDE columns
  src/backend/gporca/data/dxl/minidump/CoveringIndex-1.mdp
  src/backend/gporca/data/dxl/minidump/CoveringIndex-2.mdp
  src/backend/gporca/data/dxl/minidump/CoveringIndex-Cost-1.mdp
  src/backend/gporca/data/dxl/minidump/CoveringIndex-Cost-2.mdp
  src/backend/gporca/data/dxl/minidump/IndexOnlyScan-CTE.mdp
  src/backend/gporca/libgpdbcost/include/gpdbcost/CCostModelParamsGPDB.h
  src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
  src/backend/gporca/libgpdbcost/src/CCostModelParamsGPDB.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/gp_covering_index.out
  src/test/regress/expected/gp_covering_index_optimizer.out
  src/test/regress/expected/join_optimizer.out
  src/test/regress/expected/select_parallel_optimizer.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/sql/gp_covering_index.sql
Labels: area: gporca, version: 7X_ALPHA

#15504 [6X] Skip recovery of failed segment if it already has runni…
  concourse/pipelines/gpdb_6X_STABLE-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
  gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
  gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment_triples.py
  gpMgmt/test/behave/mgmt_utils/environment.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/unreachable_hosts_mgmt_utils.py
  src/bin/pg_rewind/pg_rewind.c
  src/bin/pg_rewind/t/005_same_timeline.pl
Labels: gpcm_in

#15851 Add latest tag to gpdb6-centos7-build image
  src/backend/gporca/concourse/test_explain_pipeline.yml
Labels: area: gporca

#14848 gpcheckperf: add buffer size parameter
  gpMgmt/bin/gpcheckperf
  gpMgmt/doc/gpcheckperf_help
  gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
Labels: topic: cluster mgmt, version: 7X_ALPHA, gpcm_in, community

#15613 Error out when DROP TYPE..CASCADE tries dropping partition key dependency
  src/backend/catalog/dependency.c
  src/backend/cdb/cdbpartition.c
  src/backend/commands/tablecmds.c
  src/include/catalog/dependency.h
  src/include/cdb/cdbpartition.h
  src/test/regress/expected/qp_orca_fallback.out
  src/test/regress/expected/qp_orca_fallback_optimizer.out
  src/test/regress/sql/qp_orca_fallback.sql
Labels: area: server, version: 6X_STABLE, dependencies

#15852 Add assert cases for the attributes of GpSegmentId
  src/test/regress/expected/misc_sanity.out
  src/test/regress/sql/misc_sanity.sql
Labels: version: 7X_ALPHA

#15292 [6X]gpcheckperf: Added support for rsync
  concourse/pipelines/gpdb_6X_STABLE-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
  gpMgmt/bin/gpcheckperf
  gpMgmt/bin/gppylib/commands/unix.py
  gpMgmt/bin/gppylib/test/unit/test_unit_commands_unix.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckperf.py
  gpMgmt/test/behave/mgmt_utils/environment.py
  gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
  gpMgmt/test/behave/mgmt_utils/gpinitstandby.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: version: 6X_STABLE, gpcm_in

#15845 Fix to remove Asserts on release build
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
Labels: area: gporca, version: 7X_ALPHA

#15225 Add grant_hook to capture grant event.
  src/backend/catalog/aclchk.c
  src/include/utils/acl.h
Labels: version: 6X_STABLE

#15840 Fix statement leak for holdable cursors
  src/backend/storage/lmgr/lock.c
  src/backend/utils/resscheduler/resqueue.c
  src/include/storage/lock.h
  src/test/isolation2/expected/resource_queue.out
  src/test/isolation2/sql/resource_queue.sql
Labels: version: 7X_ALPHA, needs: backport

#15648 Fixing crash in ORCA with skip-level correlated query
  src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
  src/test/regress/expected/qp_correlated_query.out
  src/test/regress/expected/qp_correlated_query_optimizer.out
  src/test/regress/sql/qp_correlated_query.sql
Labels: area: gporca, version: 7X_ALPHA

#15839 Do not include unused system attributes for AO
  src/backend/catalog/aclchk.c
  src/backend/catalog/heap.c
  src/test/regress/expected/storage_pg_attributes.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/storage_pg_attributes.sql
Labels: area: server, version: 7X_ALPHA, warning: on-disk change, improvement

#14820 Assert AO/CO exclusion for anti-wraparound vacuums
  src/backend/postmaster/autovacuum.c
Labels: version: 7X_ALPHA, area: aoco, autovacuum

#15709 Update distribution policy when DROP TYPE..CASCADE drops distribution key dependency
  src/backend/catalog/heap.c
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_distribution_policy.out
  src/test/regress/expected/alter_table.out
  src/test/regress/expected/bfv_partition.out
  src/test/regress/expected/column_compression.out
  src/test/regress/expected/generated.out
  src/test/regress/expected/generated_optimizer.out
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/index_including_gist_optimizer.out
  src/test/regress/expected/partition_pruning.out
  src/test/regress/expected/partition_pruning_optimizer.out
  src/test/regress/expected/qp_dropped_cols.out
  src/test/regress/expected/qp_dropped_cols_optimizer.out
  src/test/regress/expected/rpt.out
  src/test/regress/expected/rpt_optimizer.out
  src/test/regress/expected/vacuum_gp.out
  src/test/regress/output/table_functions.source
  src/test/regress/output/table_functions_optimizer.source
  src/test/regress/output/uao_ddl/alter_drop_allcol.source
  src/test/regress/sql/alter_distribution_policy.sql
  src/test/regress/sql/qp_dropped_cols.sql
Labels: area: server, version: 7X_ALPHA, needs: backport

#15454 docs - ALTER/CREATE/DROP VIEW sql ref page updates
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_VIEW.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_VIEW.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_VIEW.html.md
Labels: 7X_Docs

#15843 Docs: updated catalog tables and views
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-html.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-tables.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_am.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_authid.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_exttable.html.md
Labels: 7X_Docs

#15879 resqueue test: Close holdable cursor instead
  src/test/isolation2/expected/resource_queue.out
  src/test/isolation2/sql/resource_queue.sql
Labels: version: 7X_ALPHA

#15875 [6X] Update distribution policy for dropping distribution key dependency
  src/backend/catalog/heap.c
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_distribution_policy.out
  src/test/regress/expected/qp_dropped_cols.out
  src/test/regress/expected/qp_dropped_cols_optimizer.out
  src/test/regress/sql/alter_distribution_policy.sql
  src/test/regress/sql/qp_dropped_cols.sql
Labels: version: 6X_STABLE, backport

#15726 Move JIT GUCs of ORCA to 'sync_guc_name.h'
  concourse/pipelines/gpdb_main-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
  src/backend/jit/jit.c
  src/backend/optimizer/plan/planner.c
  src/backend/utils/misc/guc_gp.c
  src/backend/utils/misc/postgresql.conf.sample
  src/include/jit/jit.h
  src/include/utils/guc.h
  src/include/utils/sync_guc_name.h
  src/include/utils/unsync_guc_name.h
  src/test/regress/expected/explain_format.out
  src/test/regress/expected/explain_format_optimizer.out
  src/test/regress/sql/explain_format.sql
Labels: area: gporca, version: 7X_ALPHA

#15665 Fix unlock the pruned partitions of partition table
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/optimizer/util/plancat.c
  src/test/isolation2/expected/lockmodes_optimizer.out
  src/test/regress/expected/partition_locking.out
  src/test/regress/expected/partition_locking_optimizer.out
  src/test/regress/sql/partition_locking.sql
Labels: area: gporca, version: 7X_ALPHA

#15818 Fix gp_stat_bgwriter which shows incomplete/incorrect results
  src/backend/catalog/system_views.sql
  src/test/regress/expected/sysviews_gp.out
  src/test/regress/sql/sysviews_gp.sql
Labels: version: 7X_ALPHA

#15886 Fix a flaky case in sysviews_gp
  src/test/regress/greenplum_schedule
Labels: version: 7X_ALPHA, flaky test

#15816 Fix for supporting deferrable keyword on primary/unique keys
  src/backend/utils/cache/lsyscache.c
  src/test/regress/expected/aggregates_optimizer.out
  src/test/regress/expected/bfv_aggregate.out
  src/test/regress/expected/bfv_aggregate_optimizer.out
  src/test/regress/sql/bfv_aggregate.sql
Labels: area: gporca, version: 7X_ALPHA

#15832 Move temp files to results dir to avoid untracked files.
  src/test/regress/input/copy.source
  src/test/regress/output/copy.source
Labels: version: 7X_ALPHA, community

#15888 function_extensions: Fix tmpdir ls flake
  src/test/regress/expected/function_extensions.out
  src/test/regress/expected/function_extensions_optimizer.out
  src/test/regress/sql/function_extensions.sql
Labels: version: 7X_ALPHA, flaky test

#15895 Fix another flaky aggregates ICW test
  src/test/regress/expected/aggregates.out
  src/test/regress/expected/aggregates_optimizer.out
  src/test/regress/sql/aggregates.sql
Labels: area: gporca, version: 7X_ALPHA
