Repository greenplum-db/gpdb, pull requests merged in 2023-03, with the labels that each got.

#14997 Use partition key opclass to get equality operator for PARTITION BY LIST
  src/backend/parser/parse_partition.c
  src/backend/utils/cache/lsyscache.c
  src/include/utils/lsyscache.h
  src/test/regress/expected/partition.out
  src/test/regress/expected/partition_optimizer.out
  src/test/regress/sql/partition.sql
Labels: version: 6X_STABLE

#15085 Force two-stage local aggregate to remove duplicates
  src/backend/executor/execHHashagg.c
  src/backend/gporca/data/dxl/minidump/AggregateWithSkew.mdp
  src/backend/gporca/data/dxl/minidump/DQA-GroupBy-HashAggregate1.mdp
  src/backend/gporca/data/dxl/minidump/DQA-GroupBy-HashAggregate2.mdp
  src/backend/gporca/data/dxl/minidump/DQA-InnerJoin-GroupBy-HashAggregate.mdp
  src/backend/gporca/data/dxl/minidump/DqaNoRedistribute.mdp
  src/backend/gporca/data/dxl/minidump/MultiColumnDQA-InnerJoin-GroupBy-HashAggregate.mdp
  src/backend/gporca/data/dxl/minidump/ScalarDQAWithNonScalarAgg.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-DistinctOnDistrCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-GbMultipleCol-DistinctOnDistrCol.mdp
  src/backend/gporca/data/dxl/minidump/ThreeStageAgg-GbandDistinctOnDistrCol.mdp
  src/backend/gporca/data/dxl/minidump/retail_28.mdp
  src/backend/gporca/libgpopt/src/xforms/CXformSplitDQA.cpp
  src/test/isolation2/expected/spilling_hashagg.out
  src/test/isolation2/expected/spilling_hashagg_optimizer.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/spilling_hashagg.sql
Labels: area: gporca, version: 6X_STABLE, backport

#13196 Resolve GPDB_12_MERGE_FIXMEs in explain.c / explain_gp.c
  src/backend/commands/explain.c
  src/backend/commands/explain_gp.c
  src/include/nodes/execnodes.h
  src/test/regress/expected/explain_format.out
  src/test/regress/expected/explain_format_optimizer.out
  src/test/regress/expected/select_parallel.out
  src/test/regress/expected/select_parallel_optimizer.out
  src/test/regress/expected/subselect.out
  src/test/regress/expected/subselect_optimizer.out
  src/test/regress/sql/explain_format.sql
  src/test/regress/sql/select_parallel.sql
  src/test/regress/sql/subselect.sql
Labels: area: server, wip: draft for feedback, type: fixme

#15100 Fix a gpcheckcat query after removing blkdiridxid
  gpMgmt/bin/gpcheckcat
Labels: version: 7X_ALPHA

#15081 Fix flaky aggregates test
  src/test/regress/expected/aggregates.out
  src/test/regress/expected/aggregates_optimizer.out
  src/test/regress/sql/aggregates.sql
Labels: version: 7X_ALPHA

#15107 Enhance logging for dispatch conn liveness checks
  src/backend/cdb/motion/ic_udpifc.c
Labels: version: 7X_ALPHA, needs: backport

#14784 FIXME enable 64bit bitmapset and update visimap
  src/backend/access/appendonly/appendonly_visimap_entry.c
  src/backend/nodes/bitmapset.c
  src/backend/utils/misc/bitmap_compression.c
  src/backend/utils/misc/test/bitmap_compression_test.c
  src/include/access/appendonly_visimap.h
  src/include/nodes/bitmapset.h
  src/include/utils/bitmap_compression.h
Labels: merge_fixme

#15101 Fix ATSETAM to heap that doesn't clear reloptions for partitioned root
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_table_set_am.out
  src/test/regress/sql/alter_table_set_am.sql
Labels: version: 7X_ALPHA

#15128 pg_attribute_encoding: Use correct scan regproc
  src/backend/catalog/pg_attribute_encoding.c
Labels: version: 7X_ALPHA, area: aoco

#15132 Fix pg_rewind when log is a symlink
  src/bin/pg_rewind/filemap.c
Labels: version: 7X_ALPHA, needs: backport

#14865 gpcheckperf: Fix memory calculation function
  gpMgmt/bin/gpcheckperf
  gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckperf.py
  gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
Labels: version: 7X_ALPHA, needs: backport, gpcm_in

#15087 Throws ERROR when statement_mem is set to greater than max_statement_mem
  src/backend/cdb/cdbvars.c
  src/test/regress/expected/guc_gp.out
  src/test/regress/sql/guc_gp.sql
Labels: version: 7X_ALPHA, community

#15016 [6X] Drop metadata tracking info when dropping schemas
  src/backend/commands/schemacmds.c
  src/test/regress/expected/pg_stat_last_operation.out
  src/test/regress/sql/pg_stat_last_operation.sql
Labels: version: 6X_STABLE

#15046 [6X] Make LOG "autovacuum: processing database..." to be DEBUG1
  src/backend/postmaster/autovacuum.c
Labels: version: 6X_STABLE

#15135 [6X] Fix pg_rewind when pg_log is a symlink
  src/bin/pg_rewind/filemap.c
Labels: version: 6X_STABLE, backport

#14998 Add magic number field in the ICProxyPkt
  src/backend/cdb/motion/ic_proxy_backend.c
  src/backend/cdb/motion/ic_proxy_client.c
  src/backend/cdb/motion/ic_proxy_iobuf.c
  src/backend/cdb/motion/ic_proxy_packet.c
  src/backend/cdb/motion/ic_proxy_packet.h
  src/backend/cdb/motion/ic_proxy_peer.c
  src/backend/cdb/motion/ic_proxy_router.c
  src/test/isolation2/expected/ic_proxy_socket.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/ic_proxy_socket.sql
Labels: version: 6X_STABLE, backport, area: inter-connect

#14641 Add a GUC to discard redistribute hashjoin for Orca
  src/backend/gpopt/config/CConfigParamMapping.cpp
  src/backend/gporca/data/dxl/minidump/DiscardRedistributeHashJoin.mdp
  src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
  src/backend/gporca/libnaucrates/include/naucrates/traceflags/traceflags.h
  src/backend/gporca/server/CMakeLists.txt
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/include/utils/unsync_guc_name.h
Labels: area: gporca, version: 6X_STABLE, status: merge window

#15049 Run analyzedb after loading dump file in the pg_upgrade CI job
  concourse/scripts/test_upgrade.bash
Labels: version: 6X_STABLE

#15118 Fix ic_proxy compilation for when HOST_NAME_MAX is unavailable
  src/backend/cdb/motion/ic_proxy_addr.h
Labels: needs: backport

#15082 Fix incorrect result from hash join on char column
  src/backend/gporca/libgpopt/src/base/CConstraint.cpp
  src/backend/gporca/libgpopt/src/mdcache/CMDAccessorUtils.cpp
  src/test/regress/expected/bfv_joins.out
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/sql/bfv_joins.sql
Labels: area: gporca, version: 6X_STABLE, backport

#15147 [ORCA] Fix flaky "Invalid key is inaccessible" fallback
  src/backend/gporca/libgpos/include/gpos/memory/CMemoryPool.h
Labels: area: gporca

#14839 Fix memory leaks in auto_explain
  contrib/auto_explain/Makefile
  contrib/auto_explain/auto_explain.c
  contrib/auto_explain/expected/memory_leaks.out
  contrib/auto_explain/sql/memory_leaks.sql
  src/backend/commands/explain.c
  src/backend/commands/explain_gp.c
  src/backend/tcop/pquery.c
  src/include/cdb/cdbexplain.h
Labels: version: 7X_ALPHA, community

#15139 Fix IC bugs in ic_proxy_ibuf_push()
  src/backend/cdb/motion/ic_proxy_backend.c
  src/backend/cdb/motion/ic_proxy_client.c
  src/backend/cdb/motion/ic_proxy_iobuf.c
  src/backend/cdb/motion/ic_proxy_peer.c
  src/test/regress/expected/ic_proxy_socket.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/ic_proxy_socket.sql
Labels: version: 7X_ALPHA

#15071 Resolve a FIXME for ADD COLUMN for AOCO table
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_table.out
  src/test/regress/sql/alter_table.sql
Labels: version: 7X_ALPHA, merge_fixme

#15099 Fix the pg_resgroup_get_status_kv() function
  src/backend/utils/resgroup/resgroup_helper.c
  src/include/catalog/catversion.h
  src/include/catalog/pg_proc.dat
  src/test/isolation2/expected/resgroup/resgroup_dumpinfo.out
  src/test/isolation2/sql/resgroup/resgroup_dumpinfo.sql
Labels: version: 7X_ALPHA, community

#15140 fix format error of the lib name on Mac m1
  gpMgmt/bin/Makefile
Labels: version: 7X_ALPHA, community

#14963 Support Direct Dispatch for a randomly distributed table(6X_STABLE)
  src/backend/gporca/data/dxl/minidump/DirectDispatch-RandDistTable-Disjunction.mdp
  src/backend/gporca/data/dxl/minidump/DirectDispatch-RandDistTable.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecRandom.h
  src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorExprToDXLUtils.h
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXLUtils.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CDirectDispatchTest.cpp
  src/test/regress/expected/direct_dispatch.out
  src/test/regress/expected/direct_dispatch_optimizer.out
  src/test/regress/sql/direct_dispatch.sql
Labels: area: gporca, version: 6X_STABLE, status: merge window

#15174 Protect function execution in entrydb QE
  src/backend/executor/functions.c
  src/test/regress/expected/qp_functions.out
  src/test/regress/sql/qp_functions.sql
Labels: version: 7X_ALPHA, community

#15124 [6X] ORCA produces bogus plan for queries with CTE during handling distribution for Sequence children
  src/backend/gporca/data/dxl/minidump/CTE-4.mdp
  src/backend/gporca/data/dxl/minidump/CTE15HAReplicated.mdp
  src/backend/gporca/data/dxl/minidump/CTE15Replicated.mdp
  src/backend/gporca/data/dxl/minidump/CTE2HAReplicated.mdp
  src/backend/gporca/data/dxl/minidump/CTE2Replicated.mdp
  src/backend/gporca/data/dxl/minidump/ProjectWithTextConstant.mdp
  src/backend/gporca/data/dxl/minidump/UnionOfDQAQueries.mdp
  src/backend/gporca/libgpopt/src/operators/CPhysicalFilter.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalSequence.cpp
  src/backend/gporca/server/src/unittest/gpopt/minidump/CCTETest.cpp
Labels: area: gporca, version: 6X_STABLE, community

#14822 Fix index DDL operations are recorded in QEs' pg_last_stat_operation
  src/backend/catalog/index.c
  src/test/regress/expected/pg_stat_last_operation.out
  src/test/regress/sql/pg_stat_last_operation.sql
Labels: version: 7X_ALPHA, community

#15173 Fix pullup error when the target list contains RelabelType node
  src/backend/cdb/cdbpullup.c
  src/test/regress/expected/gp_pullup_expr.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/gp_pullup_expr.sql
Labels: version: 7X_ALPHA, community

#15096 Protect function execution in entrydb QE
  src/backend/executor/functions.c
  src/test/regress/expected/qp_functions.out
  src/test/regress/sql/qp_functions.sql
Labels: version: 6X_STABLE, community

#15025 gpexpand: Fix tables not copied to new segments
  gpMgmt/bin/gppylib/gpcatalog.py
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: version: 7X_ALPHA, needs: backport, gpcm_in

#15197 docs - ref info for gp_autovacuum_scope, autovacuum_naptime gucs
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
Labels: 7X_Docs

#15040 Docs backport views
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_stat_slru.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_stat_wal.html.md
Labels: 7X_Docs

#15161 Add views/functions to check missing and orphaned data files
  src/backend/catalog/gp_toolkit.sql
  src/backend/utils/adt/misc.c
  src/include/catalog/catversion.h
  src/include/catalog/pg_proc.dat
  src/test/regress/greenplum_schedule
  src/test/regress/input/alter_db_set_tablespace.source
  src/test/regress/input/gp_check_files.source
  src/test/regress/input/gp_tablespace.source
  src/test/regress/output/alter_db_set_tablespace.source
  src/test/regress/output/gp_check_files.source
  src/test/regress/output/gp_tablespace.source
  src/test/regress/regress_gp.c
Labels: version: 7X_ALPHA

#15209 Disable GUC optimizer_penalize_broadcast_threshold when set to 0
  src/backend/gporca/data/dxl/minidump/DisableBroadcastThreshold.mdp
  src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/backend/utils/misc/guc_gp.c
Labels: area: gporca, version: 7X_ALPHA

#15083 Orca FIXME: Add checks to ensure plans with part selectors are valid
  src/backend/gporca/libgpopt/include/gpopt/base/CPartitionPropagationSpec.h
  src/backend/gporca/libgpopt/src/base/CPartitionPropagationSpec.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalMotion.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalPartitionSelector.cpp
  src/backend/gporca/libgpopt/src/operators/CPhysicalSpool.cpp
Labels: area: gporca, version: 7X_ALPHA

#15160 Collect I/O stats for append-optimized tables
  src/backend/access/aocs/aocsam.c
  src/backend/access/appendonly/appendonlyam.c
  src/include/pgstat.h
  src/test/isolation2/input/uao/collected_stats_views.source
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/output/uao/collected_stats_views.source
Labels: area: server, version: 7X_ALPHA, area: aoco

#15219 Fix compilation warning in ic_proxy_peer.c
  src/backend/cdb/motion/ic_proxy.h
Labels: version: 7X_ALPHA, needs: backport

#15220 Changing IC_PROXY_INVALID_CONTENT to int16
  src/backend/cdb/motion/ic_proxy.h
Labels: version: 6X_STABLE

#15171 Fix leaking hash tables when inserting into AO tables
  src/backend/executor/execUtils.c
Labels: version: 6X_STABLE, community

#14828 [6X_Backport] gpcheckperf: Fix memory calculation function
  gpMgmt/bin/gpcheckperf
  gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckperf.py
  gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
Labels: version: 6X_STABLE, backport, gpcm_in

#14233 docs - update sql ref pages for ALTER/CREATE/DROP EXTENSION
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_EXTENSION.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_EXTENSION.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_EXTENSION.html.md
Labels: area: server, 7X_Docs

#15218 ASSERT relation is AO in GetAppendOnlyEntryAuxOids/GetAppendOnlyEntry
  src/backend/catalog/pg_appendonly.c
Labels: version: 7X_ALPHA

#15136 Fixed the string comparison warning
  src/bin/pg_rewind/pg_rewind.c
Labels: gpcm_in

#15217 Disable GUC optimizer_penalize_broadcast_threshold when set to 0
  src/backend/gporca/data/dxl/minidump/DisableBroadcastThreshold.mdp
  src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/backend/utils/misc/guc_gp.c
Labels: area: gporca, version: 6X_STABLE

#15208 [6X Backport] gpexpand: Fix tables not copied to new segments
  gpMgmt/bin/gppylib/gpcatalog.py
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: version: 6X_STABLE, backport, gpcm_in

#15192 [6X] Fixing gpcheckperf error when ran with -f and -V option
  gpMgmt/bin/gpcheckperf
  gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in

#14185 Enhance logging for FTS time out
  src/backend/fts/ftsprobe.c
  src/include/postmaster/ftsprobe.h
Labels: area: server

#15184 bug fix: 'unrecognized node type: 145'
  src/backend/parser/parse_expr.c
  src/test/regress/expected/alter_table.out
  src/test/regress/sql/alter_table.sql
Labels: version: 7X_ALPHA, community

#15267 Do not force gp_dist_random in set_subquery_pathlist in utility mode
  src/backend/optimizer/path/allpaths.c
  src/test/isolation2/expected/misc.out
  src/test/isolation2/sql/misc.sql
Labels: version: 7X_ALPHA

#14477 docs - some system catalog updates for new partitioning ...
  gpdb-doc/markdown/admin_guide/ddl/ddl-partition.html.md
  gpdb-doc/markdown/admin_guide/ddl/ddl-table.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-html.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-tables.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/gp_partition_template.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_attribute.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_class.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_constraint.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_depend.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_inherits.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_opclass.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_partition_columns.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_partition_encoding.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_partition_rule.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_partition_templates.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_partitioned_table.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_stat_partition_operations.html.md
  gpdb-doc/markdown/ref_guide/toc.md
Labels: 7X_Docs

#14980 Implement Left Join Pruning
  src/backend/gporca/data/dxl/minidump/LeftJoinPruning.mdp
  src/backend/gporca/data/dxl/minidump/LeftJoinPruningInOuterInnerQuery.mdp
  src/backend/gporca/data/dxl/minidump/LeftJoinPruningInnerQuery.mdp
  src/backend/gporca/data/dxl/minidump/LeftJoinPruningOuterQuery.mdp
  src/backend/gporca/libgpopt/include/gpopt/operators/CLeftJoinPruningPreprocessor.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPredicateUtils.h
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/libgpopt/src/operators/CLeftJoinPruningPreprocessor.cpp
  src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
  src/backend/gporca/libgpopt/src/operators/Makefile
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/join_gp.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/expected/join_optimizer.out
  src/test/regress/sql/join_gp.sql
Labels: area: gporca, version: 7X_ALPHA

#15243 Collect I/O timing stats for AO/AOCO tables
  src/backend/cdb/cdbbufferedappend.c
  src/backend/cdb/cdbbufferedread.c
  src/test/isolation2/input/uao/collected_stats_views.source
  src/test/isolation2/output/uao/collected_stats_views.source
Labels: area: server

#15262 Collect vacuum stats for append-optimized tables
  src/backend/commands/vacuum_ao.c
  src/test/isolation2/expected/setup.out
  src/test/isolation2/expected/vacuum_progress_column.out
  src/test/isolation2/expected/vacuum_progress_row.out
  src/test/isolation2/sql/setup.sql
  src/test/isolation2/sql/vacuum_progress_column.sql
  src/test/isolation2/sql/vacuum_progress_row.sql
Labels: area: server, area: aoco

#15272 fix: typo of allocated
  src/backend/cdb/dispatcher/cdbconn.c
Labels: version: 7X_ALPHA, community
