Repository greenplum-db/gpdb, pull requests merged in 2023-10, with the labels that each got.

#16519 docs - new gpfdist --ssl_verify_peer option and changes
  gpdb-doc/markdown/admin_guide/external/g-gpfdists-protocol.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/utility_guide/ref/gpfdist.html.md
Labels: 7X_Docs, cla-not-required

#16518 docs - add topic for migrating partition maint scripts
  gpdb-doc/markdown/admin_guide/ddl/about-part-changes.html.md
  gpdb-doc/markdown/admin_guide/ddl/ddl-partition.html.md
  gpdb-doc/markdown/install_guide/migrate-classic-partitioning.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_partitioned_table.html.md
Labels: 7X_Docs, cla-not-required

#16531 (6x backport) print log message with write_stderr when reach vmem or resgroup limit.
  src/backend/utils/mmgr/memprot.c
Labels: cla-not-required

#16537 [gpcloud] Update respsonse size from https://www.bing.com/
  gpcontrib/gpcloud/test/s3restful_service_test.cpp
Labels: cla-not-required

#16538 [gpcloud] [6X] [backport] Update respsonse size from https://www.bing.com/
  gpcontrib/gpcloud/test/s3restful_service_test.cpp
Labels: cla-not-required

#16541 [5X][gpcloud] Backport: Update respsonse size from https://www.bing.com/
  gpAux/extensions/gpcloud/test/s3restful_service_test.cpp
Labels: cla-not-required

#16508 [6X Backport] gpexpand: Fix error when database has tablespaces
  gpMgmt/bin/gpexpand
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: version: 6X_STABLE, backport, gpcm_in, cla-not-required

#16535 docs - update query on pg_stat_all_indexes ref page to remove dup ind…
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_stat_indexes.html.md
Labels: cla-not-required

#16542 docs - add filepath column to gp_check_orphaned_files
  gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
Labels: cla-not-required

#16539 docs - add gp_check_functions module docs
  gpdb-doc/markdown/install_guide/install_modules.html.md
  gpdb-doc/markdown/ref_guide/modules/gp_check_functions.html.md
  gpdb-doc/markdown/ref_guide/modules/intro.html.md
  gpdb-doc/markdown/ref_guide/toc.md
Labels: cla-not-required

#16314 [6X] Abort rebalance if replay lag is big on mirror
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/bin/gppylib/operations/rebalanceSegments.py
  gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py
  gpMgmt/bin/gppylib/test/unit/test_unit_rebalance_segment.py
  gpMgmt/doc/gprecoverseg_help
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  gpdb-doc/markdown/utility_guide/ref/gprecoverseg.html.md
Labels: gpcm_in

#16549 docs - gp6 supports madlib 2.1.0
  gpdb-doc/markdown/analytics/madlib.html.md
  gpdb-doc/markdown/install_guide/platform-requirements-overview.md.hbs
Labels: cla-not-required

#16548 docs - gp7 supports madlib 2.1.0
  gpdb-doc/markdown/analytics/madlib.html.md
  gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
Labels: 7X_Docs, cla-not-required

#16388 Fix int overflow in printTableAddCell()
  src/fe_utils/Makefile
  src/fe_utils/print.c
  src/fe_utils/test/Makefile
  src/fe_utils/test/print_test.c
Labels: area: clients, version: 7X_ALPHA, needs: backport

#16458 Improve prune behavior for the read-only transaction
  src/backend/cdb/cdbvars.c
  src/backend/cdb/motion/ic_udpifc.c
  src/backend/utils/misc/guc_gp.c
  src/include/cdb/cdbvars.h
  src/include/utils/sync_guc_name.h
Labels: version: 7X_ALPHA, needs: backport, cla-not-required

#16438 Check peer listener failed in IC-PROXY mode
  src/backend/cdb/motion/ic_proxy_backend.c
  src/backend/cdb/motion/ic_proxy_backend.h
  src/backend/cdb/motion/ic_proxy_main.c
  src/backend/cdb/motion/ic_tcp.c
  src/test/isolation2/expected/ic_proxy_listen_failed.out
  src/test/isolation2/isolation2_ic_proxy_schedule
  src/test/isolation2/script/start_py_httpserver.sh
  src/test/isolation2/sql/ic_proxy_listen_failed.sql
Labels: version: 7X_ALPHA, needs: backport, area: inter-connect, cla-not-required

#16551 docs - note some partitioning ddl lock-related behaviours
  gpdb-doc/markdown/admin_guide/ddl/ddl-partition.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
Labels: 7X_Docs, cla-not-required

#16509 [6X backport] Fix ORCA nested SubLink processing during query normalization
  src/backend/gpopt/translate/CQueryMutators.cpp
  src/test/regress/expected/aggregates_optimizer.out
  src/test/regress/expected/bfv_olap.out
  src/test/regress/expected/bfv_olap_optimizer.out
  src/test/regress/expected/subselect.out
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/expected/subselect_optimizer.out
  src/test/regress/sql/bfv_olap.sql
  src/test/regress/sql/subselect.sql
  src/test/regress/sql/subselect_gp.sql
Labels: area: gporca, version: 6X_STABLE, cla-not-required, status: fully approved

#16543 Fix validation of too many arguments in gprecoverseg
  gpMgmt/bin/gppylib/mainUtils.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
Labels: gpcm_in, cla-not-required

#16560 resolve GPDB_96_MERGE_FIXME for SplitUpdate
  src/backend/cdb/cdbpath.c
Labels: cla-not-required

#16562 [DOC][GP7] Fix pgaudit document.
  gpdb-doc/markdown/ref_guide/modules/pgaudit.html.md
Labels: cla-not-required

#16557 add duration if the query is canceled when it needs to be logged
  src/backend/tcop/postgres.c
Labels: cla-not-required

#16525 [6x]: Cleanup orphaned directory of dropped database after differential recovery
  gpMgmt/sbin/gpsegrecovery.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
Labels: version: 6X_STABLE, gpcm_in, cla-not-required

#16547 Expose AO storage format checking functions for external use
  src/backend/cdb/cdbappendonlystorageformat.c
  src/include/cdb/cdbappendonlystorageformat.h
  src/include/cdb/cdbappendonlystorageformat_impl.h
Labels: refactor, cla-not-required, 7X_STABLE

#16565 docs - include built-in gp_array_agg functions in ref guide
  gpdb-doc/markdown/ref_guide/function-summary.html.md
Labels: 7X_Docs, cla-not-required

#16576 Add missing dep pyscopg2 for ubuntu readme
  README.Ubuntu.bash
Labels: cla-not-required

#16581 Docs: update the values for pg_resgroupcapability catalog table
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_resgroupcapability.html.md
Labels: 7X_Docs, cla-not-required

#16414 [7x] Use utility mode when connecting to DB with dbconn.Connect()
  gpMgmt/bin/gpstop
  gpMgmt/doc/gpstop_help
Labels: gpcm_in

#16582 Fix missing check return value of pg_strcasecmp.
  src/backend/access/common/reloptions_gp.c
  src/test/regress/expected/quicklz_fallback.out
  src/test/regress/sql/quicklz_fallback.sql
Labels: cla-not-required

#15563 Initial commit of the revamped GPDB utilities
  gpMgmt/bin/go-tools/Makefile
  gpMgmt/bin/go-tools/README.md
  gpMgmt/bin/go-tools/agent/server.go
  gpMgmt/bin/go-tools/agent/server_test.go
  gpMgmt/bin/go-tools/ci/pipelines/pipeline.yml
  gpMgmt/bin/go-tools/ci/scripts/generate_ssl_cert_multi_host.bash
  gpMgmt/bin/go-tools/ci/scripts/run_tests.bash
  gpMgmt/bin/go-tools/cli/agent.go
  gpMgmt/bin/go-tools/cli/commands.go
  gpMgmt/bin/go-tools/cli/commands_test.go
  gpMgmt/bin/go-tools/cli/hub.go
  gpMgmt/bin/go-tools/cli/hub_test.go
  gpMgmt/bin/go-tools/cli/start.go
  gpMgmt/bin/go-tools/cli/start_test.go
  gpMgmt/bin/go-tools/cli/status.go
  gpMgmt/bin/go-tools/cli/status_test.go
  gpMgmt/bin/go-tools/cli/stop.go
  gpMgmt/bin/go-tools/cli/stop_test.go
  gpMgmt/bin/go-tools/constants/constants.go
  gpMgmt/bin/go-tools/generate_test_tls_certificates.sh
  gpMgmt/bin/go-tools/go.mod
  gpMgmt/bin/go-tools/go.sum
  gpMgmt/bin/go-tools/hub/server.go
  gpMgmt/bin/go-tools/hub/server_test.go
  gpMgmt/bin/go-tools/idl/agent.pb.go
  gpMgmt/bin/go-tools/idl/agent.proto
  gpMgmt/bin/go-tools/idl/generate.go
  gpMgmt/bin/go-tools/idl/hub.pb.go
  gpMgmt/bin/go-tools/idl/hub.proto
  gpMgmt/bin/go-tools/idl/mock_idl/mock_agent.pb.go
  gpMgmt/bin/go-tools/idl/mock_idl/mock_hub.pb.go
  gpMgmt/bin/go-tools/main.go
  gpMgmt/bin/go-tools/testutils/exectest/command.go
  gpMgmt/bin/go-tools/testutils/exectest/command_test.go
  gpMgmt/bin/go-tools/testutils/exectest/mains.go
  gpMgmt/bin/go-tools/testutils/exectest/mains_test.go
  gpMgmt/bin/go-tools/testutils/testutils.go
  gpMgmt/bin/go-tools/utils/platform.go
  gpMgmt/bin/go-tools/utils/platform_test.go
  gpMgmt/bin/go-tools/utils/ssl.go
  gpMgmt/bin/go-tools/utils/ssl_test.go
Labels: topic: cluster mgmt, gpcm_in

#15203 Handle parallel retrieve cursor errors via timeout mechanism #15143
  src/backend/cdb/endpoint/cdbendpointutils.c
  src/backend/commands/portalcmds.c
  src/backend/tcop/postgres.c
  src/backend/utils/init/postinit.c
  src/backend/utils/mmgr/portalmem.c
  src/include/cdb/cdbendpoint.h
  src/include/utils/portal.h
  src/include/utils/timeout.h
  src/test/isolation2/input/parallel_retrieve_cursor/status_check.source
  src/test/isolation2/output/parallel_retrieve_cursor/status_check.source
Labels: version: 7X_ALPHA, community

#16586 Init ICProxy's SHM variable in CreateSharedMemoryAndSemaphores()
  src/backend/cdb/motion/ic_proxy_backend.c
  src/backend/cdb/motion/ic_proxy_backend.h
  src/backend/cdb/motion/ic_proxy_bgworker.c
  src/backend/cdb/motion/ic_proxy_main.c
  src/backend/cdb/motion/ic_tcp.c
  src/backend/postmaster/postmaster.c
  src/backend/storage/ipc/ipci.c
  src/include/cdb/ic_proxy_bgworker.h
Labels: type: bug, version: 7X_ALPHA, needs: backport, area: inter-connect, cla-not-required

#16575 [ORCA] Fix bug checking index_can_return()
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/test/regress/expected/gp_covering_index.out
  src/test/regress/expected/gp_covering_index_optimizer.out
  src/test/regress/sql/gp_covering_index.sql
Labels: area: gporca, cla-not-required, 7X_STABLE

#16589 fix missing cgroup v2 controllers caused by systemd management
  concourse/scripts/ic_gpdb_resgroup.bash
  concourse/scripts/ic_gpdb_resgroup_v2.bash
  concourse/scripts/ic_resgroup.bash
  gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
Labels: cla-not-required

#16578 Fix missing " in subpartition template name
  src/backend/utils/adt/ruleutils.c
  src/test/regress/expected/partition.out
  src/test/regress/expected/partition_optimizer.out
  src/test/regress/sql/partition.sql
Labels: cla-not-required

#16577 Update the statistic info of hash join temporary files
  src/backend/executor/nodeHash.c
  src/backend/executor/nodeHashjoin.c
  src/backend/utils/workfile_manager/workfile_mgr.c
  src/include/executor/hashjoin.h
  src/include/utils/workfile_mgr.h
  src/test/regress/expected/zlib.out
  src/test/regress/expected/zlib_optimizer.out
  src/test/regress/sql/zlib.sql
Labels: cla-not-required

#16600 Remove yum install from verify_gpdb_versions task
  concourse/scripts/verify_gpdb_versions.bash
Labels: cla-not-required

#16601 Remove yum install from verify_gpdb_versions task
  concourse/scripts/verify_gpdb_versions.bash
Labels: cla-not-required

#16507 Accommodate for AF_INET6 when doing a motion layer IPC teardown
  src/backend/cdb/motion/ic_udpifc.c
  src/backend/cdb/motion/test/Makefile
  src/backend/cdb/motion/test/cdbsenddummypacket_test.c
Labels: cla-not-required

#16546 Fix long running execution for bitmap index
  src/backend/access/bitmap/bitmaputil.c
  src/test/isolation2/expected/bitmap_index_concurrent.out
  src/test/isolation2/sql/bitmap_index_concurrent.sql
Labels: cla-not-required

#16494 (6X) Improve prune behavior for the read-only transaction
  src/backend/cdb/cdbvars.c
  src/backend/cdb/motion/ic_udpifc.c
  src/backend/utils/misc/guc_gp.c
  src/include/cdb/cdbvars.h
  src/include/utils/sync_guc_name.h
Labels: cla-not-required

#16529 [7X] gprecoverseg: Fix behaviour of -o flag
  gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
  gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
  gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment_triples.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in, cla-not-required

#16498 6X: Fix Insert Error with unknown type
  src/backend/parser/analyze.c
  src/test/regress/expected/strings.out
  src/test/regress/sql/strings.sql
Labels: cla-not-required

#16587 [6X] gprecoverseg rebalance: revert 10 GB default value for replay lag
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/bin/gppylib/operations/rebalanceSegments.py
  gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py
  gpMgmt/bin/gppylib/test/unit/test_unit_rebalance_segment.py
  gpMgmt/doc/gprecoverseg_help
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpdb-doc/markdown/utility_guide/ref/gprecoverseg.html.md
Labels: gpcm_in, cla-not-required

#16607 Update the verify_gpdb_versions task image
  concourse/tasks/verify_gpdb_versions.yml
Labels: cla-not-required

#16604 Fix the TimeoutId ABI breakage
  src/include/executor/hashjoin.h
  src/include/utils/timeout.h
  src/include/utils/workfile_mgr.h
Labels: cla-not-required

#16456 Extend usage of cache_mpentry_num for optimizing minipage entries lookup.
  src/backend/access/aocs/aocsam.c
  src/backend/access/appendonly/appendonlyam.c
  src/backend/access/appendonly/appendonlyblockdirectory.c
  src/include/cdb/cdbappendonlyblockdirectory.h
  src/test/isolation2/input/uao/fast_analyze.source
  src/test/isolation2/output/uao/fast_analyze.source
Labels: cla-not-required

#16580 docs - updated workload_mgmt_resgroups to support cgroup v1 on rhel9 (6X)
  gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
Labels: cla-not-required

#16613 fix testcase for broken CI
  contrib/postgres_fdw/expected/mpp_gp2pg_postgres_fdw.out
  src/test/regress/expected/bfv_aggregate_optimizer.out
Labels: cla-not-required

#16618 docs - clarify fillfactor valid for heap tables only (7x)
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
Labels: 7X_Docs, cla-not-required

#16617 docs - clarify fillfactor valid for heap tables only (6x)
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
Labels: cla-not-required

#16621 Fix the USER_TIMTOUTs allocation
  src/backend/utils/misc/timeout.c
Labels: cla-not-required

#16612 [Doc] Add missing dependency libyaml-devel for Rocky Linux.
  README.Rhel-Rocky.bash
Labels: cla-not-required

#16635 Fix segmentation fault caused by concurrent INSERT ON CONFLICT and DROP TABLE
  src/backend/access/table/table.c
  src/test/isolation2/expected/gdd/concurrent_insert_on_conflict.out
  src/test/isolation2/expected/gdd/concurrent_insert_on_conflict_optimizer.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/gdd/concurrent_insert_on_conflict.sql
Labels: community, Priority 1, 7X_only, 7X_STABLE

#16620 Remove the redundant comma in subpartition template.
  src/backend/utils/adt/ruleutils.c
  src/test/regress/expected/AOCO_Compression.out
  src/test/regress/expected/gp_partition_template.out
  src/test/regress/expected/partition.out
  src/test/regress/expected/partition_optimizer.out
Labels: cla-not-required

#16632 [Doc] Fix a typo in gpfdist doc
  gpdb-doc/markdown/admin_guide/external/g-using-the-greenplum-parallel-file-server--gpfdist-.html.md
Labels: cla-not-required

#16510 [6X] Add GUC gp_workfile_compression_overhead_limit for ZSTD buffer
  src/backend/cdb/cdbvars.c
  src/backend/executor/nodeHash.c
  src/backend/executor/nodeHashjoin.c
  src/backend/storage/file/buffile.c
  src/backend/utils/misc/guc_gp.c
  src/backend/utils/workfile_manager/workfile_mgr.c
  src/include/cdb/cdbvars.h
  src/include/executor/hashjoin.h
  src/include/utils/sync_guc_name.h
  src/include/utils/workfile_mgr.h
  src/test/regress/expected/zlib.out
  src/test/regress/sql/zlib.sql
Labels: version: 6X_STABLE, cla-not-required

#16496 6X: Handle parallel retrieve cursor errors via timeout mechanism
  src/backend/cdb/endpoint/cdbendpointutils.c
  src/backend/commands/portalcmds.c
  src/backend/utils/init/postinit.c
  src/backend/utils/misc/timeout.c
  src/backend/utils/mmgr/portalmem.c
  src/include/cdb/cdbendpoint.h
  src/include/utils/portal.h
  src/include/utils/timeout.h
  src/test/isolation2/input/parallel_retrieve_cursor/status_check.source
  src/test/isolation2/output/parallel_retrieve_cursor/status_check.source
Labels: version: 6X_STABLE, cla-not-required

#16606 [6X] Fix long running execution for bitmap index
  src/backend/access/bitmap/bitmaputil.c
  src/test/isolation2/expected/bitmap_index_concurrent.out
  src/test/isolation2/sql/bitmap_index_concurrent.sql
Labels: version: 6X_STABLE, cla-not-required

#16605 [6X] Remove `getaddrinfo` in `SendDummyPacket()` to address malloc deadlock
  src/backend/cdb/motion/ic_udpifc.c
  src/backend/cdb/motion/test/Makefile
  src/backend/cdb/motion/test/cdbsenddummypacket_test.c
Labels: version: 6X_STABLE, cla-not-required

#16602 [6X] Fix segmentation fault during dispatch interrupt
  src/backend/cdb/dispatcher/test/Makefile
  src/backend/cdb/dispatcher/test/cdbdisp_query_test.c
  src/backend/cdb/dispatcher/test/gpsegconfig_dump
  src/interfaces/libpq/fe-connect.c
  src/interfaces/libpq/fe-misc.c
Labels: version: 6X_STABLE, area: dispatch, cla-not-required

#16024 Remove return at the end of void functions
  src/backend/access/appendonly/appendonlywriter.c
Labels: version: 6X_STABLE, community

#16647 [6X] Backport ci pg upgrade
  concourse/pipelines/gpdb_6X_STABLE-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: version: 6X_STABLE, cla-not-required

#16625 Add a filedump job to main pipeline
  concourse/pipelines/gpdb_main-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
  concourse/scripts/filedump_gpdb.bash
  concourse/tasks/compile_gpdb_with_filedump.yml
Labels: area:ci, cla-not-required, 7X_STABLE

#16566 [6X_BACKPORT] Fix flaky basebackup tap test that relied on pg_current_xlog_location
  src/bin/pg_basebackup/t/010_pg_basebackup.pl
Labels: cla-not-required

#16596 Fix orphaned temp table on coordinator
  src/backend/cdb/cdbtm.c
  src/test/isolation2/expected/orphan_temp_table.out
  src/test/isolation2/sql/orphan_temp_table.sql
Labels: backport, community

#16649 fix GPDB_96_MERGE_FIXME in create_ctescan_path
  src/backend/optimizer/util/pathnode.c
Labels: type: fixme, cla-not-required

#16615 Fix ORCA producing incorrect plan when handling SEMI join with RANDOM distributed table
  src/backend/gporca/libgpopt/src/xforms/CXformJoin2IndexApplyGeneric.cpp
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/sql/subselect_gp.sql
Labels: area: gporca

#16651 [6X] Post fix for ABI checking pipeline.
  .abi-check/6.25.3/postgres.symbols.ignore
  .github/workflows/greenplum-abi-tests.yml
Labels: cla-not-required

#16480 Add support for min/max aggregates optimization
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gporca/data/dxl/minidump/IndexScan-IsNotNullPred.mdp
  src/backend/gporca/data/dxl/minidump/IndexScan-IsNullPred.mdp
  src/backend/gporca/data/dxl/minidump/Max-Aggregate-uses-IndexScan-and-Limit.mdp
  src/backend/gporca/data/dxl/minidump/Min-Aggregate-uses-IndexScan-and-Limit.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CScalarProjectElement.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXform.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXformMinMax2IndexGet.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/CXformUtils.h
  src/backend/gporca/libgpopt/include/gpopt/xforms/xforms.h
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libgpopt/src/metadata/CTableDescriptor.cpp
  src/backend/gporca/libgpopt/src/operators/CLogical.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalGbAgg.cpp
  src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformFactory.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformJoin2IndexApply.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformLimit2IndexGet.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformMinMax2IndexGet.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformSelect2DynamicIndexGet.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformSelect2IndexGet.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
  src/backend/gporca/libgpopt/src/xforms/Makefile
  src/backend/gporca/server/CMakeLists.txt
  src/include/gpopt/translate/CIndexQualInfo.h
  src/test/regress/expected/aggregates_optimizer.out
  src/test/regress/expected/dpe.out
  src/test/regress/expected/dpe_optimizer.out
  src/test/regress/expected/groupingsets_optimizer.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/expected/partition_prune_optimizer.out
  src/test/regress/expected/qp_indexscan.out
  src/test/regress/expected/qp_indexscan_optimizer.out
  src/test/regress/expected/select_parallel_optimizer.out
  src/test/regress/sql/dpe.sql
  src/test/regress/sql/qp_indexscan.sql
Labels: area: gporca, version: 7X_ALPHA, cla-not-required

#16652 Fix CColRefSet's DbgPrint
  src/backend/gporca/libgpopt/include/gpopt/base/CColRefSet.h
  src/backend/gporca/libgpopt/src/base/CColRefSet.cpp
  src/backend/gporca/libgpos/include/gpos/common/CBitSet.h
Labels: area: gporca, version: 7X_ALPHA, cla-not-required

#16659 [ORCA] Allow alias name to represent table name
  contrib/file_fdw/output/gp_file_fdw_optimizer.source
  contrib/postgres_fdw/expected/gp2pg_postgres_fdw_optimizer.out
  src/backend/gpopt/translate/CTranslatorUtils.cpp
Labels: area: gporca, cla-not-required, 7X_STABLE

#16595 Add help information for gpfdist
  gpMgmt/doc/gpfdist_help
Labels: cla-not-required

#16667 Only create the ext/python3.9 folder when vendoring python3.9
  gpAux/Makefile
Labels: cla-not-required

#16670 Remove FOR (RANK) and add two new syntaxes in the ALTER TABLE sgml file
  doc/src/sgml/ref/alter_table.sgml
Labels: 7X_Docs, cla-not-required

#16638 Docs: fixed an error with provided query
  gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
Labels: 7X_Docs, cla-not-required

#16637 Docs: new guc gp_interconnect_cursor_ic_table_size
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
Labels: cla-not-required

#16666 Fix bug: cannot use LOCALE flag with a str pattern
  gpMgmt/bin/gppylib/gpparseopts.py
Labels: cla-not-required

#16669 Add test case for PR-11946
  src/pl/plpython/expected/plpython_test.out
  src/pl/plpython/sql/plpython_test.sql
Labels: cla-not-required

#16572 [6X] add duration if the query is canceled when it needs to be logged
  src/backend/tcop/postgres.c
Labels: cla-not-required

#16399 Refactor function gp_decompress
  src/backend/storage/file/gp_compress.c
Labels: version: 7X_ALPHA, community, refactor

#16672 Remove the pass condition for icw_extensions_gpcloud job
  concourse/pipelines/gpdb_6X_STABLE-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: cla-not-required

#16673 7X: Remove the pass condition for icw_extensions_gpcloud job
  concourse/pipelines/gpdb_main-generated.yml
  concourse/pipelines/templates/gpdb-tpl.yml
Labels: cla-not-required

#16654 Fix ORCA producing incorrect plan when handling SEMI join with randomly distributed table
  src/backend/gporca/libgpopt/src/xforms/CXformJoin2IndexApplyGeneric.cpp
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/sql/subselect_gp.sql
Labels: area: gporca, version: 6X_STABLE, community
