Repository greenplum-db/gpdb, pull requests merged in 2023-05, with the labels that each got.

#15399 changed default value for guc vacuum_cost_page_miss
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
Labels: 7X_Docs

#15358 Wrong results by ORCA when NULL TEST on LOJ
  src/backend/gporca/data/dxl/minidump/LOJ-With-Single-Pred-On-Outer.mdp
  src/backend/gporca/data/dxl/minidump/LOJ_NULLTEST-On-SelfCheck-Pred.mdp
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionPreprocessor.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPredicateUtils.h
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/bfv_joins.out
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/sql/bfv_joins.sql
Labels: area: gporca

#15398 Added views to gp.toolkit
  gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
Labels: 7X_Docs

#15392 Added new autovacuum gucs to the documentation
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
Labels: 7X_Docs

#15410 Disallow dbconnlimit checking on segments
  src/backend/utils/init/postinit.c
  src/test/regress/expected/dboptions.out
  src/test/regress/sql/dboptions.sql
Labels: version: 7X_ALPHA

#15470 Fix 7X explain pipeline diff failure
  concourse/tasks/diff_explain_results_with_baseline.yml
Labels: area: gporca, version: 7X_ALPHA

#15414 Fix a wrong behavior of the DatabaseFrozenIds lock
  src/backend/commands/vacuum.c
Labels: version: 7X_ALPHA, merge_fixme

#15443 Remove non-default collation fixme
  src/test/regress/expected/select_parallel_optimizer.out
Labels: area: gporca, version: 7X_ALPHA

#15486 [7X] mem intensive agg should contains mixed type
  src/backend/utils/resource_manager/memquota.c
Labels: version: 7X_ALPHA, community

#15490 Turn on optimizer_force_multistage_agg by default for ORCA
  contrib/auto_explain/expected/bfv_preload_auto_explain_optimizer.out
  contrib/postgres_fdw/expected/gp2pg_postgres_fdw_optimizer.out
  src/backend/utils/misc/guc_gp.c
  src/test/isolation2/expected/spilling_hashagg_optimizer.out
  src/test/regress/expected/aggregates_optimizer.out
  src/test/regress/expected/bfv_aggregate.out
  src/test/regress/expected/bfv_aggregate_optimizer.out
  src/test/regress/expected/bfv_index_optimizer.out
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/expected/bfv_olap_optimizer.out
  src/test/regress/expected/bfv_planner_optimizer.out
  src/test/regress/expected/bitmap_index_optimizer.out
  src/test/regress/expected/bitmapops_optimizer.out
  src/test/regress/expected/create_index_optimizer.out
  src/test/regress/expected/direct_dispatch_optimizer.out
  src/test/regress/expected/dpe_optimizer.out
  src/test/regress/expected/eagerfree_optimizer.out
  src/test/regress/expected/gp_aggregates_costs_optimizer.out
  src/test/regress/expected/gp_dqa_optimizer.out
  src/test/regress/expected/gpdiffcheck_optimizer.out
  src/test/regress/expected/gpdist_legacy_opclasses_optimizer.out
  src/test/regress/expected/gpdist_optimizer.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/expected/groupingsets_optimizer.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/expected/limit_gp_optimizer.out
  src/test/regress/expected/matview_optimizer.out
  src/test/regress/expected/notin_optimizer.out
  src/test/regress/expected/olap_plans_optimizer.out
  src/test/regress/expected/partition_optimizer.out
  src/test/regress/expected/plancache_optimizer.out
  src/test/regress/expected/qp_correlated_query_optimizer.out
  src/test/regress/expected/qp_misc_jiras_optimizer.out
  src/test/regress/expected/qp_targeted_dispatch_optimizer.out
  src/test/regress/expected/rpt_optimizer.out
  src/test/regress/expected/select_distinct_optimizer.out
  src/test/regress/expected/select_parallel_optimizer.out
  src/test/regress/expected/sublink_optimizer.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/expected/subselect_optimizer.out
  src/test/regress/expected/union_gp_optimizer.out
  src/test/regress/expected/union_optimizer.out
  src/test/regress/expected/update_gp_optimizer.out
  src/test/regress/expected/with_clause_optimizer.out
  src/test/regress/sql/bfv_aggregate.sql
Labels: area: gporca, version: 7X_ALPHA

#15417 Fix some Valgrind markings in AllocSetRealloc
  src/backend/utils/mmgr/aset.c
Labels: valgrind

#15460 Fix wrong results by ORCA when NULL TEST on LOJ
  src/backend/gporca/data/dxl/minidump/LOJ-With-Single-Pred-On-Outer.mdp
  src/backend/gporca/data/dxl/minidump/LOJ_NULLTEST-On-SelfCheck-Pred.mdp
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionPreprocessor.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CPredicateUtils.h
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/bfv_joins.out
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/sql/bfv_joins.sql
Labels: area: gporca, version: 6X_STABLE

#15513 (backport to 6X) Fix bypass catalog unittest
  src/backend/utils/resgroup/test/resgroup_test.c
Labels: version: 6X_STABLE

#15506 Re-support Dynamic Partition Elimination with semi joins in Orca
  src/backend/gporca/data/dxl/minidump/EffectOfLocalPredOnJoin2.mdp
  src/backend/gporca/data/dxl/minidump/PartTbl-DPE-GroupBy.mdp
  src/backend/gporca/data/dxl/minidump/SemiJoinDPE.mdp
  src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftSemiHashJoin.h
  src/backend/gporca/libgpopt/src/operators/CPhysicalLeftSemiHashJoin.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/dpe_optimizer.out
Labels: area: gporca, version: 7X_ALPHA

#15362 added new pg_dump options
  gpdb-doc/markdown/utility_guide/ref/pg_dump.html.md
Labels: 7X_Docs

#15069 Added ao_aux_only option
  gpdb-doc/markdown/ref_guide/sql_commands/VACUUM.html.md
Labels: 7X_Docs

#15366 Modified table entry for alter column type and aoco tables
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
Labels: 7X_Docs

#15438 docs - updates to address changes to legacy partitioning syntax
  gpdb-doc/markdown/admin_guide/ddl/about-part-changes.html.md
  gpdb-doc/markdown/admin_guide/ddl/ddl-partition.html.md
  gpdb-doc/markdown/admin_guide/ddl/ddl.html.md
  gpdb-doc/markdown/admin_guide/query/topics/query-piv-uniform-part-tbl.html.md
  gpdb-doc/markdown/best_practices/analyze.html.md
  gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-html.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-tables.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_partition.html.md
  gpdb-doc/markdown/ref_guide/toc.md
  gpdb-doc/markdown/utility_guide/ref/gpcheckcat.html.md
Labels: 7X_Docs

#15527 resolve fixme, do not need to check forceDistRandom in set_cte_pathlist
  src/backend/optimizer/path/allpaths.c
  src/test/regress/expected/bfv_cte.out
  src/test/regress/sql/bfv_cte.sql
Labels: type: fixme

#15518 Fix up stale gp_default_storage_options comment
  src/backend/utils/misc/guc_gp.c
Labels: area: server, version: 7X_ALPHA

#15531 DOCS: Fix the default value of gp_interconnect_address_type in 7X
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
Labels: 7X_Docs, 7X_beta_testing

#15501 Marking the "PexprConvert2In" preprocessing step as "unsupported for now"
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 7X_ALPHA

#15445 [ORCA] Fix option to enable multi-distinct agg
  src/backend/gporca/data/dxl/minidump/MDQA-SameDQAColumn.mdp
  src/backend/gporca/data/dxl/minidump/MDQAs-Grouping-OrderBy.mdp
  src/backend/gporca/data/dxl/minidump/MDQAs-Grouping.mdp
  src/backend/gporca/data/dxl/minidump/MDQAs-Union.mdp
  src/backend/gporca/data/dxl/minidump/MDQAs1.mdp
  src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
  src/test/regress/expected/gp_dqa.out
  src/test/regress/expected/gp_dqa_optimizer.out
  src/test/regress/sql/gp_dqa.sql
Labels: area: gporca, version: 7X_ALPHA

#15548 Fix ORCA build break
  src/backend/gporca/data/dxl/minidump/MDQAs-Grouping-OrderBy.mdp
  src/backend/gporca/data/dxl/minidump/MDQAs-Grouping.mdp
  src/backend/gporca/data/dxl/minidump/MDQAs-Union.mdp
  src/backend/gporca/data/dxl/minidump/MDQAs1.mdp
  src/test/regress/expected/gp_dqa_optimizer.out
Labels: area: gporca

#15533 Mark additional Orca gucs to be shown in guc list
  src/backend/utils/misc/guc_gp.c
Labels: area: gporca, version: 7X_ALPHA

#15532 Allow role names started with 'gp_'
  src/backend/catalog/catalog.c
  src/backend/commands/schemacmds.c
  src/backend/commands/tablespace.c
  src/backend/replication/logical/origin.c
  src/include/catalog/catalog.h
  src/test/regress/expected/role.out
  src/test/regress/sql/role.sql
Labels: version: 7X_ALPHA

#15553 Remove dead function in src/backend/cdb (7X)
  src/backend/cdb/motion/cdbmotion.c
  src/backend/cdb/motion/ic_proxy_addr.c
  src/backend/cdb/motion/ic_proxy_addr.h
  src/backend/cdb/motion/ic_proxy_iobuf.c
  src/backend/cdb/motion/ic_proxy_iobuf.h
  src/backend/cdb/motion/ic_proxy_main.c
  src/backend/cdb/motion/ic_proxy_packet.c
  src/backend/cdb/motion/ic_proxy_packet.h
  src/include/cdb/cdbmotion.h
Labels: area: inter-connect

#15552 Fix several compile warnings.
  src/backend/commands/explain.c
Labels: version: 7X_ALPHA, community

#15560 Remove FIXME in partition_pruning that was already addressed
  src/test/regress/expected/partition_pruning.out
  src/test/regress/expected/partition_pruning_optimizer.out
  src/test/regress/sql/partition_pruning.sql
Labels: version: 7X_ALPHA

#15578 aofetch: Clarify early exit for inter-entry hole
  src/backend/access/appendonly/appendonlyblockdirectory.c
  src/test/isolation2/expected/ao_blkdir.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/ao_blkdir.sql
Labels: version: 7X_ALPHA, area: aoco

#15402 Add exclude of directory "db_analyze" to generate template to gpexpand
  gpMgmt/bin/gppylib/commands/pg.py
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: version: 7X_ALPHA, community

#15593 Track LLVM 15 changes.
  configure
  configure.in
  src/backend/jit/llvm/llvmjit.c
  src/backend/jit/llvm/llvmjit_inline.cpp
Labels: area: server

#15549 [ORCA] Fix option to enable multi-distinct agg (#15445)
  src/backend/gporca/data/dxl/minidump/MDQA-SameDQAColumn.mdp
  src/backend/gporca/data/dxl/minidump/MDQAs-Grouping-OrderBy.mdp
  src/backend/gporca/data/dxl/minidump/MDQAs-Grouping.mdp
  src/backend/gporca/data/dxl/minidump/MDQAs-Union.mdp
  src/backend/gporca/data/dxl/minidump/MDQAs1.mdp
  src/backend/gporca/data/dxl/minidump/Union-On-HJNs.mdp
  src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
  src/test/regress/expected/gp_dqa.out
  src/test/regress/expected/gp_dqa_optimizer.out
  src/test/regress/sql/gp_dqa.sql
Labels: area: gporca, version: 6X_STABLE, backport

#15230 DOCS: Document new --differential option to gprecoverseg
  gpdb-doc/markdown/admin_guide/highavail/topics/g-recovering-from-segment-failures.html.md
  gpdb-doc/markdown/admin_guide/highavail/topics/g-understanding-segment-recovery.html.md
  gpdb-doc/markdown/utility_guide/ref/gprecoverseg.html.md
Labels: 7X_Docs

#15583 Fix flaky test
  src/test/regress/expected/gp_dqa.out
  src/test/regress/expected/gp_dqa_optimizer.out
  src/test/regress/sql/gp_dqa.sql
Labels: area: gporca, version: 7X_ALPHA

#15530 Run analyzedb during ICW
  GNUmakefile.in
Labels: version: 7X_ALPHA

#15568 [6X]: ORCA Fallback to planner if table contains dropped partition key column
  src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
  src/test/regress/expected/qp_orca_fallback.out
  src/test/regress/expected/qp_orca_fallback_optimizer.out
  src/test/regress/sql/qp_orca_fallback.sql
Labels: area: gporca, version: 6X_STABLE

#15442 Remove some dead code in memtuple.c
  src/backend/access/common/memtuple.c
  src/include/access/memtup.h
Labels: version: 7X_ALPHA

#15528 Added test case for pr 15283
  gpMgmt/bin/gppylib/commands/base.py
  gpMgmt/bin/gppylib/commands/test/unit/test_unit_base.py
Labels: gpcm_in

#15380 Resolve a FIXME re AOCO column write functionality in tablecmds.c
  src/backend/access/aocs/aocsam.c
  src/backend/access/aocs/aocsam_handler.c
  src/backend/access/aocs/test/aocsam_test.c
  src/backend/access/appendonly/appendonlyam_handler.c
  src/backend/access/heap/heapam_handler.c
  src/backend/access/table/tableamapi.c
  src/backend/commands/tablecmds.c
  src/backend/commands/test/Makefile
  src/backend/commands/test/tablecmds_test.c
  src/include/access/tableam.h
  src/include/cdb/cdbaocsam.h
  src/include/commands/event_trigger.h
Labels: type: fixme, version: 7X_ALPHA, merge_fixme

#15594 DOCS: Add meat of MPP-ized system views and note which summary views the relevant views are summarized in
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
Labels: 7X_Docs

#14976 [7x] Fix url_curl.c headers handling
  src/backend/access/external/url_curl.c
  src/bin/gpfdist/regress/input/exttab1.source
  src/bin/gpfdist/regress/output/exttab1.source
Labels: version: 7X_ALPHA, community

#15430 Enabling JIT with Orca costing (7X)
  src/backend/jit/jit.c
  src/backend/optimizer/plan/planner.c
  src/backend/utils/misc/guc_gp.c
  src/include/jit/jit.h
  src/include/utils/guc.h
  src/include/utils/unsync_guc_name.h
  src/test/regress/expected/explain_format.out
  src/test/regress/expected/explain_format_optimizer.out
  src/test/regress/sql/explain_format.sql
Labels: area: gporca, version: 7X_ALPHA

#15420 Modifications to JIT documentation page
  gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
Labels: 7X_Docs

#15597 Ignore any local .psqlrc when running tests.
  src/test/regress/expected/async.out
  src/test/regress/expected/dboptions.out
  src/test/regress/expected/distributed_transactions.out
  src/test/regress/expected/gpsd.out
  src/test/regress/expected/minirepro.out
  src/test/regress/input/createdb.source
  src/test/regress/output/createdb.source
  src/test/regress/sql/async.sql
  src/test/regress/sql/dboptions.sql
  src/test/regress/sql/distributed_transactions.sql
  src/test/regress/sql/gpsd.sql
  src/test/regress/sql/minirepro.sql
Labels: version: 7X_ALPHA, community

#15616 [7X] new operator shouldn't return NULL
  src/backend/gpopt/utils/CMemoryPoolPalloc.cpp
Labels: area: gporca, version: 7X_ALPHA, community

#15404 Update VACUUM ANALYZE to correctly store relallvisible
  src/backend/commands/analyze.c
  src/backend/commands/vacuum.c
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/expected/vacuum_gp.out
  src/test/regress/sql/vacuum_gp.sql
Labels: area: server, version: 7X_ALPHA

#15582 DOCS: Document support for macaddr8 data type
  gpdb-doc/markdown/ref_guide/data_types.html.md
Labels: 7X_Docs

#15473 [typo] polish parameter name of _get_remove_cmd
  gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
Labels: version: 7X_ALPHA, community

#15537 Fix bug in ORCA of removing required redistribution motion when query uses GROUP BY over gp_segment_id
  src/backend/gporca/data/dxl/minidump/DistinctQueryWithMotions.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecHashed.h
  src/backend/gporca/libgpopt/src/base/CDistributionSpecHashed.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/bfv_aggregate.out
  src/test/regress/expected/bfv_aggregate_optimizer.out
  src/test/regress/expected/direct_dispatch_optimizer.out
  src/test/regress/sql/bfv_aggregate.sql
Labels: area: gporca, version: 7X_ALPHA

#15622 Do not check new relfilenodes against the preserved oid list for upgrade
  src/backend/catalog/catalog.c
  src/backend/utils/cache/relcache.c
Labels: needs: backport
