Repository greenplum-db/gpdb, pull requests merged in 2023-01, with the labels that each got.

#14448 Fix statistic counters for parent memory contexts when some child one…
  src/backend/utils/mmgr/mcxt.c
Labels: version: 6X_STABLE, community, Priority 1

#14699 dsnap: Remove dead function
  src/backend/utils/time/snapmgr.c
  src/include/utils/snapmgr.h
Labels: version: 7X_ALPHA

#14700 Fix locking clause on foreign table missing when ORCA is enabled
  contrib/file_fdw/output/file_fdw_optimizer.source
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
Labels: area: gporca, version: 7X_ALPHA, community

#14376 docs - update the sql ref pages for ALTER/CREATE/DROP SCHEMA
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_SCHEMA.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_SCHEMA.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_SCHEMA.html.md
Labels: 7X_Docs

#14703 Query executed using JDBC extend protocol is not controled by Resource Queue
  src/backend/executor/spi.c
  src/backend/tcop/postgres.c
  src/test/regress/.gitignore
  src/test/regress/GNUmakefile
  src/test/regress/expected/resource_queue.out
  src/test/regress/extended_protocol_resqueue.c
  src/test/regress/sql/resource_queue.sql
Labels: version: 7X_ALPHA, community

#14600 Enable postgres_fdw test for gpdb7 in pipeline
  GNUmakefile.in
  contrib/postgres_fdw/.gitignore
  contrib/postgres_fdw/Makefile
  contrib/postgres_fdw/deparse.c
  contrib/postgres_fdw/expected/gp2pg_postgres_fdw.out
  contrib/postgres_fdw/postgres_clean.bash
  contrib/postgres_fdw/postgres_fdw.c
  contrib/postgres_fdw/postgres_setup.bash
  contrib/postgres_fdw/sql/gp2pg_postgres_fdw.sql
  contrib/postgres_fdw/sql/postgres_sql/gp2pg_postgres_init.sql
Labels: version: 7X_ALPHA

#14695 Fix the flaky case truncate_gp
  src/test/regress/expected/truncate_gp.out
  src/test/regress/sql/truncate_gp.sql
Labels: flaky test

#14206 cdb: fix SEGFAULT for gpdb builded with cassert
  src/backend/cdb/cdbpartition.c
  src/test/regress/expected/partition.out
  src/test/regress/expected/partition_optimizer.out
  src/test/regress/sql/partition.sql
Labels: version: 6X_STABLE, community

#14677 Handling exception to call the hook in standard_ExecutorStart
  src/backend/executor/execMain.c
Labels: version: 6X_STABLE

#14492 Support for dumping extended statistics using gpsd and minirepro
  gpMgmt/bin/gpsd
  gpMgmt/bin/minirepro
  src/backend/statistics/Makefile
  src/backend/statistics/dependencies.c
  src/backend/statistics/mcv.c
  src/backend/statistics/mvdistinct.c
  src/backend/statistics/statistics_gram.y
  src/backend/statistics/statistics_scanner.l
  src/include/statistics/extended_stats_internal.h
  src/include/statistics/statistics.h
  src/test/regress/expected/gpsd.out
  src/test/regress/expected/minirepro.out
  src/test/regress/expected/stats_ext.out
  src/test/regress/expected/stats_ext_optimizer.out
  src/test/regress/sql/gpsd.sql
  src/test/regress/sql/minirepro.sql
  src/test/regress/sql/stats_ext.sql
Labels: area: gporca, version: 7X_ALPHA

#14648 Record pg_controldata output of failed segment
  gpMgmt/bin/gppylib/heapchecksum.py
  gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
Labels: gpcm_in

#14736 Fix resgroup init error when there is a lot of cores in cpuset.cpus
  src/backend/utils/resgroup/cgroup.c
  src/include/utils/cgroup.h
Labels: version: 7X_ALPHA, community

#14679 [6X] pg_dump: set check constraints
  src/bin/pg_dump/pg_dump.c
Labels: version: 6X_STABLE

#14756 Docs: Change /gpmaster to /gpcoordinator
  gpMgmt/doc/gpconfigs/gpinitsystem_singlenode
Labels: gpcm_in

#14674 [ORCA] Use extended stats to estimate correlated cardinality
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/gporca/data/dxl/minidump/Correlated-Stat-Function-Dependency-2.mdp
  src/backend/gporca/data/dxl/minidump/Correlated-Stat-Function-Dependency-3.mdp
  src/backend/gporca/data/dxl/minidump/Correlated-Stat-Function-Dependency.mdp
  src/backend/gporca/libgpopt/include/gpopt/mdcache/CMDAccessor.h
  src/backend/gporca/libgpopt/src/mdcache/CMDAccessor.cpp
  src/backend/gporca/libnaucrates/include/naucrates/dxl/operators/CDXLOperatorFactory.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerExtStats.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerExtStatsDependencies.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerExtStatsDependency.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerExtStatsInfo.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerFactory.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerRelationExtendedStats.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/parsehandlers.h
  src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
  src/backend/gporca/libnaucrates/include/naucrates/md/CDXLExtStats.h
  src/backend/gporca/libnaucrates/include/naucrates/md/CDXLExtStatsInfo.h
  src/backend/gporca/libnaucrates/include/naucrates/md/CMDDependency.h
  src/backend/gporca/libnaucrates/include/naucrates/md/CMDExtStatsInfo.h
  src/backend/gporca/libnaucrates/include/naucrates/md/IMDCacheObject.h
  src/backend/gporca/libnaucrates/include/naucrates/md/IMDExtStats.h
  src/backend/gporca/libnaucrates/include/naucrates/md/IMDExtStatsInfo.h
  src/backend/gporca/libnaucrates/include/naucrates/md/IMDId.h
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CExtendedStatsProcessor.h
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CFilterStatsProcessor.h
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatistics.h
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatsPred.h
  src/backend/gporca/libnaucrates/src/md/CDXLExtStats.cpp
  src/backend/gporca/libnaucrates/src/md/CDXLExtStatsInfo.cpp
  src/backend/gporca/libnaucrates/src/md/CMDExtStatsInfo.cpp
  src/backend/gporca/libnaucrates/src/md/CMDProviderMemory.cpp
  src/backend/gporca/libnaucrates/src/md/Makefile
  src/backend/gporca/libnaucrates/src/operators/CDXLOperatorFactory.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerExtStats.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerExtStatsDependencies.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerExtStatsDependency.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerExtStatsInfo.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerFactory.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerRelationExtendedStats.cpp
  src/backend/gporca/libnaucrates/src/parser/Makefile
  src/backend/gporca/libnaucrates/src/statistics/CExtendedStatsProcessor.cpp
  src/backend/gporca/libnaucrates/src/statistics/CFilterStatsProcessor.cpp
  src/backend/gporca/libnaucrates/src/statistics/CStatistics.cpp
  src/backend/gporca/libnaucrates/src/statistics/Makefile
  src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/backend/gporca/server/src/unittest/dxl/statistics/CStatisticsTest.cpp
  src/backend/optimizer/util/plancat.c
  src/include/gpopt/gpdbwrappers.h
  src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
  src/include/optimizer/plancat.h
  src/test/regress/expected/stats_ext_optimizer.out
Labels: area: gporca, version: 7X_ALPHA

#14737 [6X] psql: Ensure EXECUTE ON INITPLAN is in help text
  doc/src/sgml/ref/create_function.sgml
Labels: version: 6X_STABLE

#14646 Fix parallel retrieve cursor on select transient record types and ret…
  src/backend/cdb/endpoint/cdbendpointretrieve.c
  src/backend/utils/cache/typcache.c
  src/include/utils/typcache.h
  src/test/isolation2/input/parallel_retrieve_cursor/special_query.source
  src/test/isolation2/output/parallel_retrieve_cursor/special_query.source
Labels: version: 7X_ALPHA, community

#14525 Correct direct dispatch error in ORCA, if distribution column is of varchar type
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorExprToDXLUtils.h
  src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXLUtils.cpp
  src/include/gpopt/translate/CTranslatorDXLToPlStmt.h
  src/test/regress/expected/bfv_dd_types_optimizer.out
  src/test/regress/expected/direct_dispatch.out
  src/test/regress/expected/direct_dispatch_optimizer.out
  src/test/regress/expected/inherit_optimizer.out
  src/test/regress/expected/qp_targeted_dispatch_optimizer.out
  src/test/regress/expected/window_optimizer.out
  src/test/regress/sql/direct_dispatch.sql
Labels: area: gporca, version: 7X_ALPHA

#14750 Remove result tuple bound push down if qual
  src/backend/executor/execProcnode.c
  src/test/regress/expected/bfv_subquery.out
  src/test/regress/expected/bfv_subquery_optimizer.out
  src/test/regress/sql/bfv_subquery.sql
Labels: area: gporca, version: 7X_ALPHA

#14806 Add .gitignore entries for distributed_snapshot test
  src/test/isolation2/expected/.gitignore
  src/test/isolation2/sql/.gitignore
Labels: needs: backport

#14809 docs - sql ref page updates for LISTEN/NOTIFY/UNLISTEN
  gpdb-doc/markdown/ref_guide/sql_commands/LISTEN.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/NOTIFY.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/UNLISTEN.html.md
Labels: 7X_Docs

#14786 Remove compilation warnings from statistic grammar file
  src/backend/statistics/dependencies.c
  src/backend/statistics/mvdistinct.c
  src/backend/statistics/statistics_gram.y
  src/backend/statistics/statistics_scanner.l
  src/test/regress/expected/minirepro.out
  src/test/regress/expected/stats_ext.out
  src/test/regress/expected/stats_ext_optimizer.out
  src/test/regress/sql/stats_ext.sql
Labels: area: gporca

#14718 Ban reindexdb --concurrently
  src/bin/scripts/reindexdb.c
Labels: merge_fixme

#14793 (6x backport) Possible qual postponing past ANTI-JOIN/LASJ_NOTIN-JOIN
  src/backend/optimizer/plan/initsplan.c
  src/test/regress/expected/bfv_joins.out
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/sql/bfv_joins.sql
Labels: version: 6X_STABLE, backport

#13722 Possible qual postponing past ANTI-JOIN/LASJ_NOTIN-JOIN
  src/backend/optimizer/plan/initsplan.c
  src/test/regress/expected/bfv_joins.out
  src/test/regress/expected/bfv_joins_optimizer.out
  src/test/regress/sql/bfv_joins.sql
Labels: topic: planner, community

#12885 6X: Fix assert when inserting/updating table with trigger and returning ctid
  src/backend/executor/nodeModifyTable.c
  src/test/regress/expected/returning_gp.out
  src/test/regress/sql/returning_gp.sql
Labels: version: 6X_STABLE, Priority 2

#14748 docs - some new and updated reference info for statistics
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ALTER_STATISTICS.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/CREATE_STATISTICS.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/DROP_STATISTICS.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/sql_ref.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-html.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-tables.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_statistic.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_statistic_ext.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_statistic_ext_data.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_stats.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/pg_stats_ext.html.md
  gpdb-doc/markdown/ref_guide/toc.md
Labels: 7X_Docs

#14812 Fix flaky test 'partition'
  src/test/regress/expected/partition.out
  src/test/regress/expected/partition_optimizer.out
  src/test/regress/sql/partition.sql
Labels: version: 7X_ALPHA, flaky test

#14827 Adding Test cases for a bug (fixed now) which existed in ORCA 6X only
  src/test/regress/expected/partition.out
  src/test/regress/expected/partition_optimizer.out
  src/test/regress/sql/partition.sql
Labels: area: gporca, version: 7X_ALPHA

#14157 docs - update sql ref pages for ABORT/BEGIN/END/COMMIT/ROLLBACK/...
  gpdb-doc/markdown/admin_guide/dml.html.md
  gpdb-doc/markdown/ref_guide/feature_summary.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ABORT.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/BEGIN.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/COMMIT.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/END.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/ROLLBACK.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/SET_TRANSACTION.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/START_TRANSACTION.html.md
Labels: 7X_Docs

#14760 [6X] backport: Fix resgroup init error when there is a lot of cores in cpuset.cpus
  src/backend/utils/resgroup/resgroup-ops-linux.c
  src/include/utils/resgroup.h
Labels: version: 6X_STABLE, community

#14774 Fix high memory consumption for queries with SQL subqueries
  src/backend/executor/execMain.c
  src/backend/executor/functions.c
  src/backend/executor/spi.c
Labels: version: 6X_STABLE, community

#14831 Fix minirepro utility to create view dependencies for explain queries
  src/backend/utils/adt/gp_dump_oids.c
  src/test/regress/expected/gp_dump_query_oids.out
  src/test/regress/sql/gp_dump_query_oids.sql
Labels: area: gporca, version: 7X_ALPHA

#14801 docs - update transaction isolation level info
  gpdb-doc/markdown/admin_guide/intro/about_mvcc.html.md
Labels: 7X_Docs

#14864 Cleaning untracked files
  src/backend/Makefile
  src/backend/statistics/.gitignore
  src/backend/statistics/Makefile
Labels: area: gporca

#14771 6X: set ctid on inserting AO table
  src/backend/executor/nodeModifyTable.c
  src/test/regress/expected/returning_gp.out
  src/test/regress/input/uao_dml/uao_dml.source
  src/test/regress/output/uao_dml/uao_dml.source
  src/test/regress/sql/returning_gp.sql
Labels: version: 6X_STABLE

#14844 Add GUC optimizer_enable_foreign_table
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/include/utils/unsync_guc_name.h
Labels: area: gporca, version: 7X_ALPHA

#14795 [6X_STABLE] Ressurect the lost code for archiver auto restart
  src/backend/postmaster/postmaster.c
Labels: version: 6X_STABLE, community
