Repository greenplum-db/gpdb, pull requests merged in 2023-11, with the labels that each got.

#16619 [ORCA] Relax client/server CTYPE encoding requirement
  src/backend/gpopt/translate/CDXLTranslateContext.cpp
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gporca/libgpos/include/gpos/error/CException.h
  src/backend/gporca/libgpos/server/src/unittest/gpos/string/CWStringTest.cpp
  src/backend/gporca/libgpos/src/common/clibwrapper.cpp
  src/backend/gporca/libgpos/src/error/CMessage.cpp
  src/include/gpopt/translate/CDXLTranslateContext.h
  src/test/regress/expected/gp_locale.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/gp_locale.sql
Labels: area: gporca, version: 7X_ALPHA, needs: backport, cla-not-required, status: fully approved

#16685 Fix uninitialized-use warning in CTranslatorDXLToPlStmt.cpp
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
Labels: cla-not-required, 7X_STABLE

#16544 [6X Backport] Fix error seen in CM utilities when invalid argument is provided
  gpMgmt/bin/gppylib/mainUtils.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
Labels: version: 6X_STABLE, backport, gpcm_in, cla-not-required

#16677 Upgrade golang dependencies
  gpMgmt/bin/go-tools/go.mod
  gpMgmt/bin/go-tools/go.sum
Labels: cla-not-required

#16683 Docs: added two new diskquota gucs
  gpdb-doc/markdown/ref_guide/modules/diskquota.html.md
Labels: cla-not-required

#16661 [7x]: Fix gpstart issues for large segment host
  gpMgmt/bin/gppylib/operations/startSegments.py
  gpMgmt/test/behave/mgmt_utils/gpstart.feature
Labels: gpcm_in, cla-not-required, 7X_STABLE

#15422 Fix gpdiff.pl should ignore infomation when explain ignore costs.
  src/test/isolation2/input/parallel_retrieve_cursor/explain.source
  src/test/isolation2/output/parallel_retrieve_cursor/explain.source
  src/test/regress/atmsort.pm
Labels: version: 7X_ALPHA, community

#16676 Use finish_heap_swap to swap relation files and else in ALTER TABLE DISTRIBUTED BY
  src/backend/commands/tablecmds.c
  src/test/regress/expected/alter_distribution_policy.out
  src/test/regress/sql/alter_distribution_policy.sql
Labels: needs: backport, cla-not-required, 7X_STABLE

#16692 docs - gp_move_orphaned_files() UDF (6x)
  gpdb-doc/markdown/ref_guide/modules/gp_check_functions.html.md
  gpdb-doc/markdown/ref_guide/modules/intro.html.md
Labels: version: 6X_STABLE, cla-not-required

#16664 Improve cardinality estimation for projection of ndv-preserving columns
  src/backend/gporca/data/dxl/minidump/NdvPreservingExprProjectionEquiJoin.mdp
  src/backend/gporca/data/dxl/minidump/NdvPreservingExprProjectionNonEquiJoin.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CColRef.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalUnary.h
  src/backend/gporca/libgpopt/src/operators/CLogicalProject.cpp
  src/backend/gporca/libgpopt/src/operators/CLogicalUnary.cpp
  src/backend/gporca/libnaucrates/include/naucrates/statistics/CProjectStatsProcessor.h
  src/backend/gporca/libnaucrates/src/statistics/CProjectStatsProcessor.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/join_hash_optimizer.out
Labels: area: gporca, cla-not-required, status: fully approved, 7X_STABLE

#16674 Fix bug of very long UTF-8 encoded query string truncation [6X]
  src/backend/utils/error/elog.c
  src/pl/plpython/expected/plpython_test.out
  src/pl/plpython/sql/plpython_test.sql
Labels: cla-not-required

#16698 Fix subtemplate relstorage dump result.
  src/backend/utils/adt/ruleutils.c
  src/test/regress/expected/AOCO_Compression.out
  src/test/regress/expected/gp_partition_template.out
  src/test/regress/expected/partition.out
  src/test/regress/expected/partition_optimizer.out
  src/test/regress/sql/partition.sql
Labels: cla-not-required

#16412 [6X Backport] Fix Differential recovery tablespace issue (#16195)
  gpMgmt/bin/gppylib/commands/unix.py
  gpMgmt/bin/gppylib/operations/segment_tablespace_locations.py
  gpMgmt/bin/gppylib/operations/test/unit/test_unit_segment_tablespace_locations.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
  gpMgmt/sbin/gpsegrecovery.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/steps/tablespace_mgmt_utils.py
Labels: gpcm_in

#16663 DOCS: Update links to postgresml docs
  gpdb-doc/markdown/ref_guide/modules/postgresml.html.md
Labels: cla-not-required

#16706 Remove 'hack' from comments from commit 6e2c664e
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gporca/libgpos/src/common/clibwrapper.cpp
Labels: area: gporca, cla-not-required, 7X_STABLE

#16684 [ORCA] Relax client/server CTYPE encoding requirement
  src/backend/gpopt/translate/CDXLTranslateContext.cpp
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gpopt/utils/COptTasks.cpp
  src/backend/gporca/libgpos/include/gpos/error/CException.h
  src/backend/gporca/libgpos/server/src/unittest/gpos/string/CWStringTest.cpp
  src/backend/gporca/libgpos/src/common/clibwrapper.cpp
  src/backend/gporca/libgpos/src/error/CMessage.cpp
  src/include/gpopt/translate/CDXLTranslateContext.h
  src/include/gpopt/translate/CTranslatorDXLToPlStmt.h
  src/include/gpopt/utils/COptTasks.h
  src/test/regress/expected/gp_locale.out
  src/test/regress/greenplum_schedule
  src/test/regress/sql/gp_locale.sql
Labels: area: gporca, version: 6X_STABLE, backport, cla-not-required

#16699 Use finish_heap_swap to swap relation files and else in ALTER TABLE EXPAND TABLE
  src/backend/commands/tablecmds.c
  src/test/regress/expected/expand_table.out
  src/test/regress/sql/expand_table.sql
Labels: needs: backport, cla-not-required, 7X_STABLE

#16696 [DOC] Various fixes for plpython doc
  gpdb-doc/markdown/analytics/pl_python.html.md
Labels: cla-not-required

#16668 Fix ValueError exception if there is an empty lock directory
  gpMgmt/bin/gppylib/mainUtils.py
  gpMgmt/test/behave/mgmt_utils/gpstop.feature
  gpMgmt/test/behave/mgmt_utils/steps/gpstate_utils.py
Labels: needs: backport, gpcm_in, 7X_STABLE

#16639 [6x]: Added support for gpstate tracking for differential recovery
  gpMgmt/bin/gppylib/commands/test/unit/test_unit_unix.py
  gpMgmt/bin/gppylib/commands/unix.py
  gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
  gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
  gpMgmt/bin/gppylib/programs/clsSystemState.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gpstate.py
  gpMgmt/sbin/gpsegrecovery.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/gpstate.feature
  gpMgmt/test/behave/mgmt_utils/steps/gpstate_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/tablespace_mgmt_utils.py
Labels: gpcm_in, cla-not-required

#16714 Fix a flakiness in gpcontrib/gp_toolkit test
  gpcontrib/gp_toolkit/expected/gp_toolkit.out
  gpcontrib/gp_toolkit/expected/gp_toolkit_resgroup.out
  gpcontrib/gp_toolkit/sql/gp_toolkit.sql
Labels: flaky test, cla-not-required, 7X_STABLE

#16718 Fix some typos
  src/backend/postmaster/syslogger.c
  src/test/regress/expected/qp_indexscan.out
  src/test/regress/expected/qp_indexscan_optimizer.out
  src/test/regress/sql/qp_indexscan.sql
Labels: cla-not-required

#14780 support multi-dqa with normal agg
  src/backend/cdb/cdbgroupingpaths.c
  src/backend/executor/nodeTupleSplit.c
  src/backend/nodes/copyfuncs.c
  src/backend/nodes/equalfuncs.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfuncs.c
  src/backend/optimizer/plan/setrefs.c
  src/include/nodes/execnodes.h
  src/include/nodes/primnodes.h
  src/test/regress/expected/gp_dqa.out
  src/test/regress/expected/gp_dqa_optimizer.out
  src/test/regress/sql/gp_dqa.sql
Labels: version: 7X_ALPHA

#16717 Refined the peer listener failed message in IC-PROXY mode
  src/backend/cdb/motion/ic_tcp.c
  src/test/isolation2/expected/ic_proxy_listen_failed.out
  src/test/isolation2/sql/ic_proxy_listen_failed.sql
Labels: area: inter-connect, cla-not-required, 7X_STABLE

#16681 Docs: relax requirements for anti-virus
  gpdb-doc/markdown/admin_guide/perf_intro.html.md
  gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
  gpdb-doc/markdown/install_guide/prep_os.html.md
  gpdb-doc/markdown/security-guide/topics/preface.html.md
Labels: 7X_Docs, cla-not-required

#16682 Docs: updated 6.X documentation to include EL 9 requirements
  gpdb-doc/markdown/install_guide/platform-requirements-overview.md.hbs
  gpdb-doc/markdown/install_guide/prep_os.html.md
Labels: cla-not-required

#16711 Docs: edit the description for gpload option MAX_LINE_LENGHT
  gpdb-doc/markdown/utility_guide/ref/gpfdist.html.md
  gpdb-doc/markdown/utility_guide/ref/gpload.html.md
Labels: 7X_Docs, cla-not-required

#16713 Docs: edit MAX_LINE_LENGHT description for 6X
  gpdb-doc/markdown/utility_guide/ref/gpfdist.html.md
  gpdb-doc/markdown/utility_guide/ref/gpload.html.md
Labels: cla-not-required

#16701 [6X backport] Fix issue that segment index might be wrong in slice->segments
  src/backend/executor/execMain.c
Labels: cla-not-required

#16704 Fix issue that segment index might be wrong in slice->segments
  contrib/postgres_fdw/expected/gp_postgres_fdw.out
  contrib/postgres_fdw/expected/gp_postgres_fdw_optimizer.out
  contrib/postgres_fdw/sql/gp_postgres_fdw.sql
  src/backend/optimizer/plan/createplan.c
Labels: cla-not-required

#16690 Fix LeftJoinPruning pruns essential left join
  src/backend/gporca/libgpopt/src/operators/CLeftJoinPruningPreprocessor.cpp
  src/test/regress/expected/join_gp.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/sql/join_gp.sql
Labels: area: gporca, community

#16553 6X: Check peer listener failed in IC-PROXY mode
  src/backend/cdb/motion/ic_proxy_backend.c
  src/backend/cdb/motion/ic_proxy_backend.h
  src/backend/cdb/motion/ic_proxy_bgworker.c
  src/backend/cdb/motion/ic_proxy_main.c
  src/backend/cdb/motion/ic_tcp.c
  src/backend/postmaster/postmaster.c
  src/backend/storage/ipc/ipci.c
  src/include/cdb/ic_proxy_bgworker.h
  src/test/isolation2/expected/ic_proxy_listen_failed.out
  src/test/isolation2/isolation2_ic_proxy_schedule
  src/test/isolation2/script/start_py_httpserver.sh
  src/test/isolation2/sql/ic_proxy_listen_failed.sql
Labels: version: 6X_STABLE, area: inter-connect, cla-not-required

#16574 docs - remove statement from INSERT ref page; remove dup para
  gpdb-doc/markdown/ref_guide/sql_commands/INSERT.html.md
  gpdb-doc/markdown/ref_guide/sql_commands/UPDATE.html.md
Labels: 7X_Docs, cla-not-required

#16708 Improve NDV estimation when merging partition stats for skewed data
  src/backend/commands/analyze.c
  src/test/regress/expected/incremental_analyze.out
  src/test/regress/expected/incremental_analyze_optimizer.out
Labels: area: gporca, cla-not-required, 7X_STABLE

#16421 [DOC][GP7] Update diskquota doc
  gpdb-doc/markdown/ref_guide/modules/diskquota.html.md
Labels: cla-not-required

#14701 Fix autovacuum to drop leftover temporary tables
  src/backend/catalog/namespace.c
  src/backend/postmaster/autovacuum.c
  src/backend/storage/ipc/procarray.c
  src/include/catalog/namespace.h
  src/include/storage/procarray.h
  src/test/isolation2/expected/autovacuum-temp-table.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/autovacuum-temp-table.sql
Labels: version: 7X_ALPHA, community

#16693 Retry gang creation for non-recovery failures
  src/backend/cdb/dispatcher/cdbgang.c
  src/backend/cdb/dispatcher/cdbgang_async.c
  src/include/cdb/cdbgang.h
  src/test/regress/output/dispatch.source
Labels: needs: backport, area: dispatch, cla-not-required, 7X_STABLE

#16720 icw: Disable autovacuum for col_proj test
  src/test/regress/greenplum_schedule
Labels: flaky test, cla-not-required, 7X_STABLE

#16735 docs - pgbouncer supports encrypted ldap password
  gpdb-doc/markdown/admin_guide/access_db/topics/pgbouncer.html.md
  gpdb-doc/markdown/utility_guide/ref/pgbouncer-ini.html.md
Labels: version: 6X_STABLE, cla-not-required

#16739 Added rsync version requirement for gpstate -e
  gpdb-doc/markdown/utility_guide/ref/gpstate.html.md
Labels: cla-not-required

#16636 Docs: perform os upgrade from el7 to el8
  gpdb-doc/markdown/install_guide/migrate-linux.html.md
  gpdb-doc/markdown/install_guide/prep_os.html.md
Labels: cla-not-required

#16737 Add workload7 to explain pipeline
  concourse/scripts/build_gpdb.py
  concourse/scripts/builds/GpBuild.py
  concourse/tasks/run_explain_suite.yml
  src/backend/gporca/concourse/test_explain_pipeline.yml
Labels: area: gporca, cla-not-required

#16743 Fix flaky test function_extensions
  src/test/regress/expected/function_extensions.out
  src/test/regress/expected/function_extensions_optimizer.out
  src/test/regress/sql/function_extensions.sql
Labels: flaky test, cla-not-required, 7X_STABLE

#16552 Fix AT SETAM for ao_row tables with added columns
  src/backend/catalog/pg_appendonly.c
  src/backend/catalog/pg_attribute_encoding.c
  src/backend/commands/tablecmds.c
  src/include/catalog/pg_attribute_encoding.h
  src/test/regress/expected/alter_table_set_am.out
  src/test/regress/sql/alter_table_set_am.sql
Labels: cla-not-required

#15094 Fix pg_stat_statements node type unexpected warning
  contrib/pg_stat_statements/Makefile
  contrib/pg_stat_statements/expected/olap_group.out
  contrib/pg_stat_statements/expected/olap_setup.out
  contrib/pg_stat_statements/expected/pg_stat_statements.out
  contrib/pg_stat_statements/pg_stat_statements.c
  contrib/pg_stat_statements/sql/olap_group.sql
  contrib/pg_stat_statements/sql/olap_setup.sql
  contrib/pg_stat_statements/sql/pg_stat_statements.sql
Labels: version: 7X_ALPHA, community

#16757 Remove duplicated function definitions in builtins.h
  src/include/utils/builtins.h
Labels: community

#16756 Fix typos clause.
  gpcontrib/gp_exttable_fdw/gp_exttable_fdw.c
  src/test/regress/input/appendonly.source
  src/test/regress/output/appendonly.source
Labels: community

#16758 Fix typo timestamp
  gpcontrib/gp_toolkit/resgroup.c
Labels: cla-not-required

#16754 Remove quote_identifier in function list_join()
  src/backend/commands/exttablecmds.c
  src/bin/gpfdist/regress/input/gpfdist2.source
  src/bin/gpfdist/regress/output/gpfdist2.source
Labels: cla-not-required

#16726 [6X] Fix SET command that sends DTX protocol command when shouldn't
  src/backend/cdb/dispatcher/cdbdisp_query.c
  src/test/regress/expected/distributed_transactions.out
  src/test/regress/sql/distributed_transactions.sql
Labels: version: 6X_STABLE, backport, cla-not-required

#16766 Fix a test failure in distributed_transactions
  src/test/regress/expected/distributed_transactions.out
Labels: version: 6X_STABLE, test, cla-not-required

#16584 UDF to move orphaned files
  gpcontrib/gp_toolkit/Makefile
  gpcontrib/gp_toolkit/gp_toolkit--1.3--1.4.sql
  gpcontrib/gp_toolkit/gp_toolkit.control
  src/test/regress/input/gp_check_files.source
  src/test/regress/output/gp_check_files.source
Labels: backport, cla-not-required, 7X_STABLE

#16750 remove ereport()/elog() from signal handler
  src/backend/tcop/postgres.c
  src/backend/tcop/test/postgres_test.c
Labels: version: 6X_STABLE, cla-not-required

#16747 Don't emit critical error message when gppkg is missing.
  gpMgmt/bin/gppylib/commands/base.py
  gpMgmt/bin/gppylib/operations/package.py
Labels: cla-not-required

#16768 [CI] Post fix for ABI checking pipeline.
  .abi-check/6.26.0/postgres.symbols.ignore
  .github/workflows/greenplum-abi-tests.yml
Labels: cla-not-required

#16751 ao/co: Manage array type during AM changes
  src/backend/commands/cluster.c
  src/backend/commands/typecmds.c
  src/include/commands/typecmds.h
  src/test/regress/expected/alter_table_set_am.out
  src/test/regress/sql/alter_table_set_am.sql
Labels: area: aoco, cla-not-required, 7X_STABLE

#16709 Push down predicates into the subquery
  src/backend/optimizer/path/allpaths.c
  src/test/regress/expected/subselect_gp.out
  src/test/regress/expected/subselect_gp_optimizer.out
  src/test/regress/sql/subselect_gp.sql
Labels: cla-not-required

#16716 Add analyze functionality for mpp file fdw.
  contrib/file_fdw/file_fdw.c
  contrib/file_fdw/input/gp_file_fdw.source
  contrib/file_fdw/output/gp_file_fdw.source
  contrib/file_fdw/output/gp_file_fdw_optimizer.source
  contrib/postgres_fdw/expected/mpp_gp2pg_postgres_fdw.out
  contrib/postgres_fdw/sql/mpp_gp2pg_postgres_fdw.sql
  src/backend/commands/analyze.c
  src/include/commands/vacuum.h
Labels: cla-not-required

#16763 [main] Add support for checking ABI compatibility
  .abi-check/.images/download-report-from-gh-action.png
  .abi-check/7.0.0/postgres.symbols.ignore
  .abi-check/7.0.0/postgres.types.ignore
  .abi-check/README.md
  .github/workflows/greenplum-abi-tests.yml
Labels: cla-not-required

#16746 gp_toolkit: partition maintenance UDFs and views
  gpcontrib/gp_toolkit/Makefile
  gpcontrib/gp_toolkit/expected/gp_partition_maint.out
  gpcontrib/gp_toolkit/gp_partition_maint.c
  gpcontrib/gp_toolkit/gp_toolkit--1.3--1.4.sql
  gpcontrib/gp_toolkit/sql/gp_partition_maint.sql
  src/backend/catalog/partition.c
  src/include/catalog/partition.h
  src/include/partitioning/partbounds.h
Labels: topic: partitions, cla-not-required, 7X_STABLE

#16495 (6X) Fix ERROR: "Cannot add cell to table content: total cell count of XXX exceeded"
  src/bin/psql/print.c
Labels: area: clients, version: 6X_STABLE, cla-not-required

#16460 [7x]: Added support for gpstate tracking of differential recovery
  gpMgmt/bin/gppylib/commands/test/unit/test_unit_unix.py
  gpMgmt/bin/gppylib/commands/unix.py
  gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
  gpMgmt/bin/gppylib/operations/test/unit/test_unit_buildMirrorSegments.py
  gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
  gpMgmt/bin/gppylib/programs/clsSystemState.py
  gpMgmt/bin/gppylib/test/unit/test_unit_gpstate.py
  gpMgmt/sbin/gpsegrecovery.py
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
  gpMgmt/test/behave/mgmt_utils/gpstate.feature
  gpMgmt/test/behave/mgmt_utils/steps/gpstate_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
  gpMgmt/test/behave/mgmt_utils/steps/tablespace_mgmt_utils.py
Labels: gpcm_in, 7X_STABLE

#16725 Disable SET DISTRIBUTED REPLICATED for ALTER EXTERNAL TABLE
  src/backend/commands/tablecmds.c
  src/test/regress/input/external_table.source
  src/test/regress/output/external_table.source
  src/test/regress/output/external_table_optimizer.source
Labels: cla-not-required

#16585 gpexpand: skip expanded/broken tables when redistributing
  gpMgmt/bin/gpexpand
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
  gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Labels: gpcm_in, cla-not-required, 7X_STABLE

#16782 fix results wrong while using union for recursive_cte
  src/backend/optimizer/prep/prepunion.c
  src/test/regress/expected/gp_recursive_cte.out
  src/test/regress/sql/gp_recursive_cte.sql
Labels: cla-not-required
