Repository greenplum-db/gpdb, pull requests merged in 2024-02, with the labels that each got.

#17053 Fix query crash with minus memory_limit value in resgroup
  src/backend/commands/resgroupcmds.c
  src/test/isolation2/expected/resgroup/resgroup_memory_limit.out
  src/test/isolation2/sql/resgroup/resgroup_memory_limit.sql
Labels: cla-not-required

#17056 DOCS: Document pg_filedump utility
  gpdb-doc/markdown/utility_guide/ref/pg_filedump.html.md
  gpdb-doc/markdown/utility_guide/toc.md
  gpdb-doc/markdown/utility_guide/utility-programs.html.md
  gpdb-doc/markdown/utility_guide/utility_guide.html.md
Labels: cla-not-required

#16960 Fix for finding child output columns when parent is union while join pruning
  .abi-check/7.1.0/postgres.symbols.ignore
  .abi-check/7.1.0/postgres.types.ignore
  src/backend/gporca/libgpopt/src/operators/CLeftJoinPruningPreprocessor.cpp
  src/test/regress/expected/join_gp.out
  src/test/regress/expected/join_gp_optimizer.out
  src/test/regress/sql/join_gp.sql
Labels: area: gporca, cla-not-required, 7X_STABLE

#16862 Update Root Stats If A Partition Is Attached Or Detached
  src/backend/commands/analyzeutils.c
  src/backend/commands/tablecmds.c
  src/backend/postmaster/autovacuum.c
  src/include/commands/analyzeutils.h
  src/include/postmaster/autovacuum.h
  src/test/isolation2/expected/merge_root_stats.out
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/sql/merge_root_stats.sql
Labels: area: gporca, cla-not-required, 7X_STABLE

#17059 Docs: manual verification of EL 7 to EL 8 impacted data
  gpdb-doc/markdown/install_guide/migrate-linux.html.md
Labels: version: 6X_STABLE, cla-not-required

#17063 Remove AuxProcType from the abi ignore files for 7.1.0
  .abi-check/7.1.0/postgres.types.ignore
Labels: cla-not-required

#17017 fix gpload create staging table with wrong distribution key order
  gpMgmt/bin/gpload.py
  gpMgmt/bin/gpload_test/gpload2/TEST_local_data_format.py
  gpMgmt/bin/gpload_test/gpload2/query264.ans
  gpMgmt/bin/gpload_test/gpload2/setup.ans
  gpMgmt/bin/gpload_test/gpload2/setup.sql
Labels: version: 6X_STABLE, cla-not-required

#17068 Fix typo of statistics under gporca.
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerDynamicForeignScan.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerDynamicTableScan.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerGatherMotion.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerHashJoin.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerMaterialize.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerMergeJoin.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerNLJoin.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerPhysicalAbstractBitmapScan.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerRandomMotion.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerRedistributeMotion.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerResult.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerRoutedMotion.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerSort.cpp
  src/backend/gporca/libnaucrates/src/parser/CParseHandlerTableScan.cpp
Labels: area: gporca, 7X_STABLE

#16790 Keep partition child lock until end of select
  .abi-check/6.26.2/postgres.symbols.ignore
  src/backend/gpopt/config/CConfigParamMapping.cpp
  src/backend/gpopt/gpdbwrappers.cpp
  src/backend/gpopt/translate/CContextDXLToPlStmt.cpp
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/backend/gpopt/utils/COptTasks.cpp
  src/backend/gporca/libnaucrates/include/naucrates/traceflags/traceflags.h
  src/backend/optimizer/prep/prepunion.c
  src/backend/tcop/pquery.c
  src/backend/utils/misc/guc_gp.c
  src/include/gpopt/gpdbwrappers.h
  src/include/gpopt/translate/CContextDXLToPlStmt.h
  src/include/gpopt/translate/CTranslatorDXLToPlStmt.h
  src/include/utils/guc.h
  src/include/utils/unsync_guc_name.h
  src/test/isolation2/expected/concurrent_select_vacuum_ao_partitioned_table.out
  src/test/isolation2/expected/concurrent_select_vacuum_ao_partitioned_table_optimizer.out
  src/test/isolation2/input/uao/select_while_vacuum.source
  src/test/isolation2/isolation2_schedule
  src/test/isolation2/output/uao/select_while_vacuum.source
  src/test/isolation2/sql/concurrent_select_vacuum_ao_partitioned_table.sql
Labels: area: gporca, version: 6X_STABLE, area: aoco, cla-not-required

#17011 Docs: document guc debug_shareinput_xslice
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
Labels: 7X_Docs, cla-not-required

#16922 Added support to include datadir in gpsegconf_dump file
  src/backend/cdb/cdbutil.c
  src/backend/cdb/dispatcher/test/gpsegconfig_dump
Labels: gpcm_in, cla-not-required

#17071 fix flakyness in gpmovemirror demo cluster without-assert build
  gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
Labels: cla-not-required

#17076 Docs: Fixed typo where it was still referring to GPDB 6
  gpdb-doc/markdown/install_guide/install_guide.html.md
Labels: cla-not-required

#16911 [6X][backport] updated max range value in help file for gpexpand -n option
  gpMgmt/doc/gpexpand_help
Labels: gpcm_in, cla-not-required

#17057 Include distributed xid in transaction commit WAL in all dtx cases
  src/backend/access/transam/xact.c
Labels: cla-not-required, 7X_STABLE

#17047 [ORCA] Fix invalid colref using subquery exists
  src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
  src/test/regress/expected/qp_subquery.out
  src/test/regress/expected/qp_subquery_optimizer.out
  src/test/regress/sql/qp_subquery.sql
Labels: area: gporca, needs: backport, cla-not-required, 7X_STABLE

#17079 Capture Non default planner gucs in minirepro
  gpMgmt/bin/minirepro
  src/test/regress/expected/minirepro.out
  src/test/regress/sql/minirepro.sql
Labels: area: gporca, cla-not-required

#17087 Properly set function column count for table value functions in Orca
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, cla-not-required, 7X_STABLE

#17090 Ignore symbol ConfigureNamesBool_gp for base 6.26.3
  .abi-check/6.26.3/postgres.symbols.ignore
Labels: cla-not-required

#17092 Fix broken link
  gpdb-doc/markdown/install_guide/install_gpdb.html.md
Labels: cla-not-required

#16914 Add multi-thread compression for gpfdist in gpdb6
  gpMgmt/doc/gpfdist_help
  src/backend/access/external/url_curl.c
  src/backend/storage/file/buffile.c
  src/backend/utils/misc/fstream/gfile.c
  src/bin/gpfdist/gpfdist.c
  src/bin/gpfdist/regress/Makefile
  src/bin/gpfdist/regress/data/gpfdist2/one_column.txt
  src/bin/gpfdist/regress/input/gpfdist2.source
  src/bin/gpfdist/regress/input/gpfdist2_compress.source
  src/bin/gpfdist/regress/output/gpfdist2_compress.source
Labels: version: 6X_STABLE, cla-not-required

#17001 Add new option --gp_version to pg_config.
  src/bin/pg_config/pg_config.c
Labels: cla-not-required

#17101 Docs: add enable_network and roles to remote plc example
  gpdb-doc/markdown/analytics/pl_container_using.html.md
Labels: cla-not-required

#17106 [6X][Doc] Add an description entry for pg_config --gp_version.
  gpdb-doc/markdown/utility_guide/ref/pg_config.html.md
Labels: cla-not-required

#17107 [Doc] Add an description entry for pg_config --gp_version.
  gpdb-doc/markdown/utility_guide/ref/pg_config.html.md
Labels: cla-not-required

#17111 DOCS: some "Using plcontainer" updates for 6.27.0
  gpdb-doc/markdown/analytics/pl_container_using.html.md
Labels: cla-not-required

#17115 Fix join condition lost after pull up sublink to join
  src/backend/cdb/cdbsubselect.c
  src/test/regress/expected/subselect.out
  src/test/regress/expected/subselect_optimizer.out
  src/test/regress/sql/subselect.sql
Labels: cla-not-required

#16924 [6X]Add verbose option and improve the GUC check error display
  gpMgmt/bin/el8_migrate_locale/README.md
  gpMgmt/bin/el8_migrate_locale/el8_migrate_locale.py
Labels: cla-not-required

#17119 Remove fixme in nodeModifyTable.c.
  src/backend/executor/nodeModifyTable.c
  src/test/regress/expected/update_gp.out
  src/test/regress/expected/update_gp_optimizer.out
  src/test/regress/sql/update_gp.sql
Labels: cla-not-required

#17095 Fix no response when alter io_limit of resource group to '-1'
  src/backend/commands/resgroupcmds.c
  src/backend/utils/resgroup/resgroup.c
  src/test/isolation2/expected/resgroup/resgroup_auxiliary_tools_v2.out
  src/test/isolation2/input/resgroup/resgroup_io_limit.source
  src/test/isolation2/output/resgroup/resgroup_io_limit.source
  src/test/isolation2/sql/resgroup/resgroup_auxiliary_tools_v2.sql
Labels: cla-not-required

#17084 Fix Orca to not generate unnecessary slices for plans with Subplans
  src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
  src/test/regress/expected/explain_format_optimizer.out
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, version: 6X_STABLE, status: merge window, cla-not-required, status: fully approved

#17088 [ORCA] Fix ident to const predicate push down optimization
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/test/regress/expected/bfv_cte.out
  src/test/regress/expected/bfv_cte_optimizer.out
  src/test/regress/sql/bfv_cte.sql
Labels: area: gporca, needs: backport, cla-not-required, 7X_STABLE

#17123 Remove unused buf[MAXPGPATH] variable in mdcreate_ao()
  src/backend/storage/smgr/md.c
Labels: cla-not-required

#17114 [6X] Fix join condition lost after pull up sublink to join
  src/backend/cdb/cdbsubselect.c
  src/test/regress/expected/subselect.out
  src/test/regress/expected/subselect_optimizer.out
  src/test/regress/sql/subselect.sql
Labels: cla-not-required

#17116 [6x only]Introduce GUC `gp_enable_mdqa_shared_scan` for queries with multi-DQA
  src/backend/cdb/cdbgroup.c
  src/backend/utils/misc/guc_gp.c
  src/include/cdb/cdbvars.h
  src/include/utils/unsync_guc_name.h
  src/test/regress/expected/gp_aggregates.out
  src/test/regress/sql/gp_aggregates.sql
Labels: version: 6X_STABLE, cla-not-required

#17113 Re-support DISTINCT-qualified Window Aggregate in Orca
  src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-2.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-3.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-PartitionBy-DifferentColumn-2.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-PartitionBy-DifferentColumn.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-PartitionBy-SameColumn-2.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-PartitionBy-SameColumn.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-RowNumber-2.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-RowNumber-Distinct-Different-Columns.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-RowNumber-Distinct-ParitionBy-Different-Columns.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-RowNumber-Multiple-ParitionBy-Columns.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-RowNumber-OrderBy-PartitionBy-SameColumn-2.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-RowNumber-OrderBy-PartitionBy-SameColumn.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-RowNumber-PartitionBy-SameColumn-2.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-RowNumber-PartitionBy-SameColumn.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-RowNumber.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Single-DQA-Query.xml
  src/backend/gporca/data/dxl/minidump/WinFunc-Redistribute-Sort-CTE-Producer.mdp
  src/backend/gporca/libgpopt/include/gpopt/operators/CWindowPreprocessor.h
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/libgpopt/src/operators/CWindowPreprocessor.cpp
  src/backend/gporca/libgpopt/src/operators/Makefile
  src/backend/gporca/server/include/unittest/gpopt/operators/CExpressionPreprocessorTest.h
  src/backend/gporca/server/src/unittest/gpopt/operators/CExpressionPreprocessorTest.cpp
  src/test/regress/expected/olap_window_seq.out
  src/test/regress/expected/olap_window_seq_optimizer.out
  src/test/regress/sql/olap_window_seq.sql
Labels: area: gporca, cla-not-required, 7X_STABLE

#17127 6X: Re-support DISTINCT-qualified Window Aggregate in Orca
  src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-2.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-3.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-PartitionBy-DifferentColumn-2.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-PartitionBy-DifferentColumn.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-PartitionBy-SameColumn-2.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-PartitionBy-SameColumn.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-RowNumber-2.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-RowNumber-Distinct-Different-Columns.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-RowNumber-Distinct-ParitionBy-Different-Columns.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-RowNumber-Multiple-ParitionBy-Columns.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-RowNumber-OrderBy-PartitionBy-SameColumn-2.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-RowNumber-OrderBy-PartitionBy-SameColumn.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-RowNumber-PartitionBy-SameColumn-2.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-RowNumber-PartitionBy-SameColumn.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query-RowNumber.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Multiple-DQA-Query.xml
  src/backend/gporca/data/dxl/expressiontests/WinFunc-Single-DQA-Query.xml
  src/backend/gporca/data/dxl/minidump/WinFunc-Redistribute-Sort-CTE-Producer.mdp
  src/backend/gporca/libgpopt/include/gpopt/operators/CWindowPreprocessor.h
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/libgpopt/src/operators/CWindowPreprocessor.cpp
  src/backend/gporca/libgpopt/src/operators/Makefile
  src/backend/gporca/server/include/unittest/gpopt/operators/CExpressionPreprocessorTest.h
  src/backend/gporca/server/src/unittest/gpopt/operators/CExpressionPreprocessorTest.cpp
  src/test/regress/expected/olap_window_seq.out
  src/test/regress/expected/olap_window_seq_optimizer.out
  src/test/regress/sql/olap_window_seq.sql
Labels: area: gporca, version: 6X_STABLE, cla-not-required

#17097 Prevent overwriting of workers in ORCA
  src/backend/gpopt/CGPOptimizer.cpp
  src/backend/gporca/libgpos/include/gpos/error/CException.h
  src/backend/gporca/libgpos/src/_api.cpp
  src/backend/gporca/libgpos/src/error/CMessage.cpp
Labels: area: gporca, cla-not-required, 7X_STABLE
