Repository greenplum-db/gpdb, pull requests merged in 2024-05, with the labels that each got.

#17415 [6X Backport] Stream WAL archiving status from primaries to mirrors
  .abi-check/6.27.0/postgres.symbols.ignore
  src/backend/postmaster/pgstat.c
  src/backend/replication/walreceiver.c
  src/backend/replication/walsender.c
  src/backend/utils/misc/guc_gp.c
  src/backend/utils/misc/postgresql.conf.sample
  src/bin/pg_basebackup/receivelog.c
  src/include/access/xlog.h
  src/include/pgstat.h
  src/include/utils/guc.h
  src/include/utils/unsync_guc_name.h
  src/test/recovery/t/121_streaming_and_archiving.pl
Labels: version: 6X_STABLE, cla-not-required

#17416 Docs: Document wal_sender_archiving_status_interval GUC
  gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
  gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
Labels: cla-not-required

#17419 Fix gppylib/operations unit tests
  gpMgmt/bin/gppylib/operations/test/__init__.py
  gpMgmt/bin/gppylib/operations/test/unit/test_unit_buildMirrorSegments.py
  gpMgmt/bin/gppylib/operations/test/unit/test_unit_configurationImplGpdb.py
  gpMgmt/bin/gppylib/operations/test/unit/test_unit_segment_reconfigurer.py
  gpMgmt/bin/gppylib/operations/test/unit/test_unit_update_pg_hba_on_segments.py
Labels: gpcm_in, cla-not-required

#17425 uao covering index test: Fix minor plan diff flake
  src/test/regress/input/uao_dml/ao_covering_index.source
  src/test/regress/output/uao_dml/ao_covering_index.source
  src/test/regress/output/uao_dml/ao_covering_index_optimizer.source
Labels: area: aoco, flaky test, cla-not-required, 7X_STABLE

#16812 [7X] Skip ssh if segments are on the same host with coordinator.
  gpMgmt/bin/gppylib/commands/base.py
  gpMgmt/bin/gppylib/commands/gp.py
  gpMgmt/bin/gppylib/operations/detect_unreachable_hosts.py
Labels: cla-not-required

#17393 Inline CTEs in Orca that contain outer references
  src/backend/gporca/libgpopt/include/gpopt/base/CCTEInfo.h
  src/backend/gporca/libgpopt/src/base/CCTEInfo.cpp
  src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformCTEAnchor2Sequence.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformCTEAnchor2TrivialSelect.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformInlineCTEConsumer.cpp
  src/backend/gporca/libgpopt/src/xforms/CXformInlineCTEConsumerUnderSelect.cpp
  src/test/regress/expected/bfv_cte.out
  src/test/regress/expected/bfv_cte_optimizer.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/bfv_cte.sql
Labels: area: gporca, cla-not-required, 7X_STABLE

#17316 Add a new option for gpexpand to bypass checking the icproxy address
  gpMgmt/bin/gpexpand
  gpMgmt/doc/gpexpand_help
Labels: area: management utilities, needs: backport, 7X_STABLE

#17345 gpssh: Retry with TERM env variable set during failures
  gpMgmt/bin/gppylib/util/ssh_utils.py
  gpMgmt/bin/gppylib/util/test/unit/test_cluster_ssh_utils.py
Labels: needs: backport, gpcm_in, cla-not-required, 7X_STABLE

#17354 [6X Backport] gpssh: Retry with TERM env variable set during failures
  gpMgmt/bin/gppylib/util/ssh_utils.py
  gpMgmt/bin/gppylib/util/test/unit/test_cluster_ssh_utils.py
Labels: version: 6X_STABLE, backport, gpcm_in, cla-not-required

#17377 [6X] fix wrong result of MDQA in planner
  src/backend/cdb/cdbgroup.c
  src/backend/optimizer/plan/plangroupext.c
  src/test/regress/expected/bfv_dd.out
  src/test/regress/expected/bfv_dd_multicolumn.out
  src/test/regress/expected/gp_dqa.out
  src/test/regress/expected/gp_dqa_optimizer.out
  src/test/regress/sql/gp_dqa.sql
Labels: cla-not-required

#17435 Directory structure for storing state files
  gpMgmt/bin/go-tools/configs/README.md
  gpMgmt/bin/go-tools/configs/salt/common/.gitkeep
  gpMgmt/bin/go-tools/configs/salt/coordinator/.gitkeep
  gpMgmt/bin/go-tools/configs/salt/segments/.gitkeep
Labels: cla-not-required

#17436 Revert "Directory structure for storing state files"
  gpMgmt/bin/go-tools/configs/README.md
  gpMgmt/bin/go-tools/configs/salt/common/.gitkeep
  gpMgmt/bin/go-tools/configs/salt/coordinator/.gitkeep
  gpMgmt/bin/go-tools/configs/salt/segments/.gitkeep
Labels: cla-not-required

#17437 Directory structure for storing state files (#17435)
  gpMgmt/bin/go-tools/configs/README.md
  gpMgmt/bin/go-tools/configs/salt/common/.gitkeep
  gpMgmt/bin/go-tools/configs/salt/coordinator/.gitkeep
  gpMgmt/bin/go-tools/configs/salt/segments/.gitkeep
Labels: cla-not-required

#17408 Avoid replay dtx info in checkpoint for newly expanded segments
  gpMgmt/test/behave/mgmt_utils/gpexpand.feature
  src/backend/access/transam/xact.c
  src/backend/access/transam/xlog.c
Labels: cla-not-required

#17439 DOCS: Remove now supported items from items previously unsupported in GPORCA
  gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-limitations.html.md
Labels: cla-not-required

#17378 Rename the resource group parameter 'memory_limit' to 'memory_quota'
  .abi-check/7.1.0/postgres.types.ignore
  doc/src/sgml/ref/alter_resource_group.sgml
  doc/src/sgml/ref/create_resource_group.sgml
  gpcontrib/gp_toolkit/gp_toolkit--1.3.sql
  gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
  gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
  src/backend/commands/resgroupcmds.c
  src/backend/parser/gram.y
  src/backend/utils/resgroup/resgroup.c
  src/bin/psql/tab-complete.c
  src/include/catalog/pg_resgroup.h
  src/include/parser/kwlist.h
  src/include/utils/resgroup.h
  src/test/binary_swap/expected/resgroup_current_1_queue.out
  src/test/binary_swap/expected/resgroup_current_3_group.out
  src/test/binary_swap/expected/resgroup_current_3_queue.out
  src/test/binary_swap/expected/resgroup_other_2_group.out
  src/test/binary_swap/expected/resgroup_other_2_queue.out
  src/test/binary_swap/sql/resgroup_current_1_group.sql
  src/test/binary_swap/sql/resgroup_current_1_queue.sql
  src/test/binary_swap/sql/resgroup_current_3_group.sql
  src/test/binary_swap/sql/resgroup_current_3_queue.sql
  src/test/binary_swap/sql/resgroup_other_2_group.sql
  src/test/binary_swap/sql/resgroup_other_2_queue.sql
  src/test/isolation2/expected/resgroup/resgroup_auxiliary_tools_v1.out
  src/test/isolation2/expected/resgroup/resgroup_auxiliary_tools_v2.out
  src/test/isolation2/expected/resgroup/resgroup_memory_limit.out
  src/test/isolation2/expected/resgroup/resgroup_syntax.out
  src/test/isolation2/output/resgroup/resgroup_views.source
  src/test/isolation2/sql/resgroup/resgroup_memory_limit.sql
Labels: cla-not-required

#17444 Adding the user.sls file for user creation using salt
  gpMgmt/bin/go-tools/configs/salt/segments/.gitkeep
  gpMgmt/bin/go-tools/configs/saltstates/pillar/top.sls
  gpMgmt/bin/go-tools/configs/saltstates/pillar/user.sls
  gpMgmt/bin/go-tools/configs/saltstates/salt/common/user.sls
  gpMgmt/bin/go-tools/configs/saltstates/salt/coordinator/.gitkeep
  gpMgmt/bin/go-tools/configs/saltstates/salt/segments/.gitkeep
Labels: cla-not-required

#17422 Gpinitsystem2.0 - Bug-Fix Validate port in use by dialing connection
  gpMgmt/bin/go-tools/utils/sys_utils.go
Labels: cla-not-required

#17450 Added the cgroups.sls state file
  gpMgmt/bin/go-tools/configs/saltstates/pillar/cgroups.sls
  gpMgmt/bin/go-tools/configs/saltstates/pillar/top.sls
  gpMgmt/bin/go-tools/configs/saltstates/salt/common/cgroups.sls
  gpMgmt/bin/go-tools/configs/saltstates/salt/templates/cgconfig.conf.tpl
Labels: cla-not-required

#17380 Expose several functions for extensions
  src/backend/cdb/cdbgroupingpaths.c
  src/backend/cdb/cdbtargeteddispatch.c
  src/backend/optimizer/util/walkers.c
  src/include/cdb/cdbgroupingpaths.h
Labels: cla-not-required

#17412 Resolve Deadlock: Allow Concurrent Creation of Non-First Index on AO
  src/backend/commands/indexcmds.c
  src/test/isolation2/sql/concurrent_index_creation_should_not_deadlock.sql
Labels: cla-not-required

#17441 Fix crash caused by vacuum ao_aux_only on AO partitioned table.
  src/backend/commands/vacuum.c
  src/test/regress/expected/vacuum_ao_aux_only.out
  src/test/regress/sql/vacuum_ao_aux_only.sql
Labels: community

#17453 Fix missing discard_output variable in shared scan node's functions
  src/backend/nodes/copyfuncs.c
  src/backend/nodes/outfuncs.c
  src/backend/nodes/readfast.c
  src/test/regress/expected/gporca.out
  src/test/regress/expected/gporca_optimizer.out
  src/test/regress/sql/gporca.sql
Labels: area: gporca, cla-not-required, 7X_STABLE

#17465 Docs: add pg_cron reference page for GP 7
  gpdb-doc/markdown/ref_guide/modules/intro.html.md
  gpdb-doc/markdown/ref_guide/modules/pg_cron.html.md
Labels: cla-not-required

#17466 [DOC] Add PyXB-X for DSB Python GP7
  gpdb-doc/markdown/install_guide/install_python_dsmod.html.md
Labels: cla-not-required

#17458 Change deadlock_timeout GUC to sync
  src/include/utils/sync_guc_name.h
  src/include/utils/unsync_guc_name.h
Labels: needs: backport, cla-not-required, 7X_STABLE

#17463 Add trigger times for main rocky9 pipeline
  concourse/vars/common_prod.yml
Labels: cla-not-required

#17398 Add support for Planhints logging
  gpcontrib/pg_hint_plan/pg_hint_plan.c
  src/backend/gpopt/utils/COptTasks.cpp
  src/backend/gporca/libgpopt/include/gpopt/hints/CJoinTypeHint.h
  src/backend/gporca/libgpopt/include/gpopt/hints/CScanHint.h
  src/backend/gporca/libgpopt/include/gpopt/hints/IHint.h
  src/backend/gporca/libgpopt/src/hints/CHintUtils.cpp
  src/backend/gporca/libgpopt/src/hints/CJoinTypeHint.cpp
  src/backend/gporca/libgpopt/src/hints/CPlanHint.cpp
  src/backend/gporca/libgpopt/src/hints/CScanHint.cpp
  src/backend/gporca/libgpopt/src/optimizer/COptimizer.cpp
  src/backend/gporca/libnaucrates/include/naucrates/traceflags/traceflags.h
  src/include/optimizer/hints.h
  src/test/regress/expected/joinhints.out
  src/test/regress/expected/joinhints_optimizer.out
  src/test/regress/expected/planhints.out
  src/test/regress/expected/planhints_optimizer.out
  src/test/regress/expected/rowhints.out
  src/test/regress/expected/rowhints_optimizer.out
  src/test/regress/sql/joinhints.sql
  src/test/regress/sql/planhints.sql
  src/test/regress/sql/rowhints.sql
Labels: area: gporca, cla-not-required

#17464 Don't generate unique rowid path for DML on replicated table.
  src/backend/optimizer/path/joinrels.c
  src/test/regress/expected/rpt_joins.out
  src/test/regress/sql/rpt_joins.sql
Labels: cla-not-required

#17423 Fix orca preprocess step for query with Select-Project-NaryJoin pattern
  src/backend/gporca/data/dxl/minidump/JoinOnViewWithCastedColumnAndJoinWithCastedColumnInPredicate.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionPreprocessor.h
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/qp_subquery.out
  src/test/regress/expected/qp_subquery_optimizer.out
  src/test/regress/sql/qp_subquery.sql
Labels: area: gporca, needs: backport, cla-not-required

#17421 gp init cluster: support for mirror functional tests
  gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_config_validation_test.go
  gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_db_validation_test.go
  gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_env_validation_test.go
  gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_test.go
  gpMgmt/bin/go-tools/test/integration/testutils/db_utils.go
  gpMgmt/bin/go-tools/test/integration/testutils/locale_utils.go
  gpMgmt/bin/go-tools/test/integration/testutils/test_utils.go
Labels: gpcm_in, cla-not-required

#17431 [gpinitsystem2.0] Functional tests for expansion support
  gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_config_validation_test.go
  gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_db_validation_test.go
  gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_suite_test.go
  gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_test.go
Labels: cla-not-required

#17477 [Orca] Fallback to planner if a function in 'from' clause uses 'WITH …
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/test/regress/expected/qp_orca_fallback.out
  src/test/regress/expected/qp_orca_fallback_optimizer.out
  src/test/regress/sql/qp_orca_fallback.sql
Labels: area: gporca, cla-not-required, 7X_STABLE

#17468 [6X] Change deadlock_timeout GUC to sync
  src/include/utils/sync_guc_name.h
  src/include/utils/unsync_guc_name.h
Labels: version: 6X_STABLE, backport, cla-not-required

#17481 gpexpand: TRUNCATE coordinator-only tables for cleanup
  gpMgmt/bin/gpexpand
  gpMgmt/bin/gppylib/gpcatalog.py
Labels: topic: gpexpand, needs: backport, cla-not-required, 7X_STABLE

#17488 [7X] Removed redundant tests
  gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
Labels: gpcm_in, cla-not-required

#17487 mirrorless: Enable WAL optimization for COPY FROM
  src/backend/commands/copy.c
Labels: needs: backport, cla-not-required, 7X_STABLE, mirrorless

#17451 Bypass the ICProxy addresses check of gpexpand when disable ENABLE_IC_PROXY
  gpMgmt/bin/gpexpand
Labels: area: management utilities, needs: backport, cla-not-required, 7X_STABLE

#17336 pg_waldump: Added option --last-valid-walname
  doc/src/sgml/ref/pg_waldump.sgml
  src/bin/pg_waldump/pg_waldump.c
  src/bin/pg_waldump/t/001_basic.pl
Labels: cla-not-required

#17348 [7X][NFC] Fix mismatched types.
  src/backend/access/transam/gp_distributed_log.c
  src/backend/cdb/cdbdistributedxacts.c
  src/backend/cdb/cdbdistributedxid.c
  src/backend/commands/queue.c
Labels: cla-not-required

#17368 Fix issue 17333 for except over no columns.
  .abi-check/7.1.0/postgres.symbols.ignore
  src/backend/cdb/cdbsetop.c
  src/backend/optimizer/prep/prepunion.c
  src/include/cdb/cdbsetop.h
  src/test/regress/expected/qp_union_intersect.out
  src/test/regress/expected/qp_union_intersect_optimizer.out
  src/test/regress/sql/qp_union_intersect.sql
Labels: cla-not-required

#17485 [6X] gpexpand: TRUNCATE coordinator-only tables for cleanup
  gpMgmt/bin/gpexpand
  gpMgmt/bin/gppylib/gpcatalog.py
Labels: topic: gpexpand, version: 6X_STABLE, backport, cla-not-required

#17472 Introduce "gp init cluster --clean" command
  gpMgmt/bin/go-tools/agent/remove_directory.go
  gpMgmt/bin/go-tools/agent/remove_directory_test.go
  gpMgmt/bin/go-tools/cli/init.go
  gpMgmt/bin/go-tools/cli/init_test.go
  gpMgmt/bin/go-tools/constants/constants.go
  gpMgmt/bin/go-tools/hub/add_mirrors.go
  gpMgmt/bin/go-tools/hub/add_mirrors_test.go
  gpMgmt/bin/go-tools/hub/clean_init_cluster.go
  gpMgmt/bin/go-tools/hub/clean_init_cluster_test.go
  gpMgmt/bin/go-tools/hub/make_cluster.go
  gpMgmt/bin/go-tools/idl/agent.pb.go
  gpMgmt/bin/go-tools/idl/agent.proto
  gpMgmt/bin/go-tools/idl/hub.pb.go
  gpMgmt/bin/go-tools/idl/hub.proto
  gpMgmt/bin/go-tools/idl/mock_idl/mock_agent.pb.go
  gpMgmt/bin/go-tools/idl/mock_idl/mock_hub.pb.go
  gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_env_validation_test.go
  gpMgmt/bin/go-tools/testutils/testutils.go
  gpMgmt/bin/go-tools/utils/greenplum/gparray.go
  gpMgmt/bin/go-tools/utils/postgres/commands.go
  gpMgmt/bin/go-tools/utils/sys_utils.go
  gpMgmt/bin/go-tools/utils/sys_utils_test.go
  gpMgmt/bin/go-tools/utils/user_input.go
  gpMgmt/bin/go-tools/utils/user_input_test.go
Labels: gpcm_in, cla-not-required

#17476 [6X] Fix orca preprocess step for query with Select-Project-NaryJoin pattern
  src/backend/gporca/data/dxl/minidump/JoinOnViewWithCastedColumnAndJoinWithCastedColumnInPredicate.mdp
  src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
  src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionPreprocessor.h
  src/backend/gporca/libgpopt/src/base/CUtils.cpp
  src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
  src/backend/gporca/server/CMakeLists.txt
  src/test/regress/expected/qp_subquery.out
  src/test/regress/expected/qp_subquery_optimizer.out
  src/test/regress/sql/qp_subquery.sql
Labels: area: gporca, version: 6X_STABLE, backport, cla-not-required

#17480 [6X] Fallback to planner if a function in 'from' clause uses 'WITH ORDINALITY'
  src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
  src/test/regress/expected/qp_orca_fallback.out
  src/test/regress/expected/qp_orca_fallback_optimizer.out
  src/test/regress/sql/qp_orca_fallback.sql
Labels: area: gporca, version: 6X_STABLE, backport, cla-not-required

#17484 [Orca] Update doc about Fallback to planner for queries with 'WITH ORDINALITY'
  gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-limitations.html.md
Labels: area: gporca, area: documentation, 7X_Docs, cla-not-required

#17506 Revert "Fix mismatched types. (#17348)"
  src/backend/access/transam/gp_distributed_log.c
  src/backend/cdb/cdbdistributedxacts.c
  src/backend/cdb/cdbdistributedxid.c
  src/backend/commands/queue.c
Labels: cla-not-required

#17490 [6X] mirrorless: Enable WAL optimization for COPY FROM
  src/backend/commands/copy.c
Labels: version: 6X_STABLE, backport, cla-not-required, mirrorless

#17521 Add missing volatile qualifier.
  src/backend/executor/nodeSubplan.c
Labels: cla-not-required

#17511 Fix compiler warnings
  src/bin/pg_waldump/pg_waldump.c
  src/bin/pg_waldump/t/001_basic.pl
Labels: cla-not-required

#17522 [6X] analyze: Don't leak DatumHashTable
  src/backend/commands/analyzeutils.c
Labels: version: 6X_STABLE, backport, topic: analyze, cla-not-required

#17524 Fix Addmirror valid range port error
  gpMgmt/bin/gppylib/programs/clsAddMirrors.py
  gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
  gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
Labels: gpcm_in, cla-not-required

#17526 Detect integer overflow while computing new array dimensions.
  src/backend/utils/adt/arrayfuncs.c
  src/backend/utils/adt/arrayutils.c
  src/include/utils/array.h
  src/test/regress/expected/arrays.out
  src/test/regress/sql/arrays.sql
Labels: cla-not-required

#17525 Reject substituting extension schemas or owners matching ["$'\].
  src/backend/commands/extension.c
  src/test/modules/test_extensions/Makefile
  src/test/modules/test_extensions/expected/test_extensions.out
  src/test/modules/test_extensions/sql/test_extensions.sql
  src/test/modules/test_extensions/test_ext_extschema--1.0.sql
  src/test/modules/test_extensions/test_ext_extschema.control
Labels: cla-not-required

#17414 Introduce gp_appendonly_compaction_segfile_limit
  src/backend/access/appendonly/appendonlywriter.c
  src/backend/utils/misc/guc_gp.c
  src/include/utils/guc.h
  src/include/utils/sync_guc_name.h
  src/test/isolation2/input/uao/max_concurrency2.source
  src/test/isolation2/output/uao/max_concurrency2.source
Labels: needs: backport, area: aoco, cla-not-required, 7X_STABLE

#17538 Run REFRESH MATERIALIZED VIEW CONCURRENTLY in right security context
  src/backend/commands/matview.c
Labels: cla-not-required

#17499 Get the GUC gp_resgroup_print_operator_memory_limits back
  .abi-check/7.1.0/postgres.symbols.ignore
  gpdb-doc/markdown/ref_guide/guc-changes-6to7.html.md.erb
  src/backend/utils/misc/guc_gp.c
  src/backend/utils/resgroup/resgroup.c
  src/backend/utils/resource_manager/resource_manager.c
  src/include/utils/resgroup.h
  src/include/utils/sync_guc_name.h
  src/test/regress/expected/resource_group_gucs.out
  src/test/regress/sql/resource_group_gucs.sql
Labels: cla-not-required
